#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-08-10
# Version: dev003
# Function: Format and write SeRP peak-calling outputs for legacy and consensus methods.
# Input: SeRP peak results, enrichment profiles, sequence metadata, and output settings.
# Output: Peak logs, peak tables, BED files, peak sequences, and enrichment profiles.

"""Output helpers for selective ribosome profiling peak calling."""

from __future__ import annotations

from collections import OrderedDict
from pathlib import Path
from typing import TextIO

import numpy as np
import pandas as pd
from Bio.Seq import Seq


class SeRPOutput:
    """Format and write SeRP peak-calling results.

    Parameters
    ----------
    output_prefix : str
        Prefix used for all SeRP output files.
    sample_names : list[str]
        Ordered control and IP sample names.
    upstream : int
        Number of upstream codons retained for peak sequence output.
    downstream : int
        Number of downstream codons retained for peak sequence output.
    ratio_out : bool
        Whether to write method-specific replicate enrichment ratios.
    """

    def __init__(
        self,
        output_prefix: str,
        sample_names: list[str],
        upstream: int,
        downstream: int,
        ratio_out: bool,
    ) -> None:
        """Initialize output paths and the historical result schema."""
        self.output_prefix = output_prefix
        self.sample_names = list(sample_names)
        self.upstream = upstream
        self.downstream = downstream
        self.ratio_out = ratio_out

        self.peak_log_file = self.output_prefix + "_peaks.log"
        self.peak_txt_file = self.output_prefix + "_peaks.txt"
        self.peak_bed_file = self.output_prefix + "_peaks.bed"
        self.peak_sig_bed_file = self.output_prefix + "_sig_peaks.bed"
        self.peak_seq_file = self.output_prefix + "_peaks_sequence.txt"
        self.peak_ratio_file = self.output_prefix + "_peaks_ratio.txt"
        self.enrich_ratio_file = self.output_prefix + "_enrich_ratio.txt"

        self.result_columns = self._build_result_columns()

    def _build_result_columns(self) -> list[str]:
        """Build the historical SeRP peak result column order."""
        rpm_names = [sample + "_rpm" for sample in self.sample_names]
        result_names = [
            "min_corr_ck",
            "min_corr_ip",
            "comments",
            "peak_num",
            "peak_length",
            "gaps",
            "collision_start",
            "peak_start",
            "peak_end",
            "collision_end",
            "max_site",
            "max_fold",
            "mean_fold",
            "ck_peak_rpm",
            "ip_peak_rpm",
            "P_Value",
            "BHFDR",
            "Peak_loci",
        ]
        return ["transcripts", "gene_name"] + self.sample_names + rpm_names + result_names

    @staticmethod
    def _safe_to_numeric(series: pd.Series) -> pd.Series:
        """Convert a Series to numeric values when conversion is possible."""
        try:
            return pd.to_numeric(series)
        except (TypeError, ValueError):
            return series

    @staticmethod
    def _adjust_bh(pvalues: pd.Series) -> np.ndarray:
        """Calculate Benjamini-Hochberg adjusted p-values."""
        values = pvalues.astype(float).to_numpy()
        order = np.argsort(values, kind="stable")
        ranked = values[order]
        n = len(ranked)
        adjusted = ranked * n / np.arange(1, n + 1, dtype=float)
        adjusted = np.minimum.accumulate(adjusted[::-1])[::-1]
        adjusted = np.minimum(adjusted, 1.0)
        result = np.empty(n, dtype=float)
        result[order] = adjusted
        return result

    def prepare(self) -> None:
        """Remove output files that are regenerated by the current run."""
        output_files = [
            self.peak_log_file,
            self.peak_txt_file,
            self.peak_bed_file,
            self.peak_sig_bed_file,
            self.peak_seq_file,
            self.peak_ratio_file,
        ]
        if self.ratio_out:
            output_files.append(self.enrich_ratio_file)

        for file_name in output_files:
            path = Path(file_name)
            if path.exists():
                print(
                    "Warning: {file_name} exists and will be overwritten.".format(
                        file_name=file_name
                    ),
                    flush=True,
                )
                path.unlink()

    def open_peak_log(self) -> TextIO:
        """Open the per-transcript peak log and write its header."""
        handle = open(self.peak_log_file, "w", encoding="utf-8")
        handle.write("\t".join(self.result_columns) + "\n")
        return handle

    @staticmethod
    def write_log_row(handle: TextIO, row: list[str]) -> None:
        """Write one formatted row to the peak log."""
        handle.write("\t".join(row) + "\n")

    def build_status_row(
        self,
        transcript: str,
        gene_name: str,
        gene_rpf_sum: list[float],
        raw_gene_rpm_sum: list[float],
        ck_min_corr: str,
        ip_min_corr: str,
        comment: str,
        peak_num: str = "-",
    ) -> list[str]:
        """Build one non-peak result row using the historical output schema."""
        row = [
            transcript,
            gene_name,
            *[str(value) for value in gene_rpf_sum],
            *[str(round(value, 4)) for value in raw_gene_rpm_sum],
            ck_min_corr,
            ip_min_corr,
            comment,
            peak_num,
        ]
        row.extend(["-"] * 14)
        return row

    def build_peak_row(
        self,
        transcript: str,
        gene_name: str,
        gene_rpf_sum: list[float],
        raw_gene_rpm_sum: list[float],
        ck_min_corr: str,
        ip_min_corr: str,
        peak_num: int,
        peak_len: int,
        gaps: int,
        collision_start: int,
        peak_start: int,
        peak_end: int,
        collision_end: int,
        max_site: int,
        max_fold,
        mean_fold,
        ck_peak_rpm,
        ip_peak_rpm,
        pvalue,
        peak_loci: str,
    ) -> list[str]:
        """Build one called-peak row using the historical output schema."""
        return [
            transcript,
            gene_name,
            *[str(value) for value in gene_rpf_sum],
            *[str(round(value, 4)) for value in raw_gene_rpm_sum],
            ck_min_corr,
            ip_min_corr,
            "Qualified",
            str(peak_num + 1),
            str(peak_len),
            str(gaps),
            str(collision_start),
            str(peak_start),
            str(peak_end),
            str(collision_end),
            str(max_site),
            str(max_fold),
            mean_fold,
            str(ck_peak_rpm),
            str(ip_peak_rpm),
            pvalue,
            "-",
            peak_loci,
        ]

    def write_profile(
        self,
        gene_rpf: pd.DataFrame,
        gene_ratio_smooth: pd.DataFrame,
        peak: OrderedDict | None = None,
        peak_left_start: list[int] | None = None,
        peak_right_end: list[int] | None = None,
    ) -> None:
        """Append one transcript enrichment profile for later ``serp_plot`` use."""
        profile = pd.concat([gene_rpf, gene_ratio_smooth], axis=1).reset_index(drop=True)
        edge = pd.Series(np.nan, index=gene_ratio_smooth.index, name="edge", dtype=float)
        bound = pd.Series(np.nan, index=gene_ratio_smooth.index, name="bound", dtype=float)

        if peak and peak_left_start is not None and peak_right_end is not None:
            edge_positions: set[int] = set()
            bound_positions: set[int] = set()
            for peak_num, peak_dict in peak.items():
                peak_len = list(peak_dict.keys())[0]
                peak_positions = peak[peak_num][peak_len]
                peak_start = int(peak_positions[0])
                peak_end = int(peak_positions[-1])
                edge_positions.update(range(int(peak_left_start[peak_num]), peak_start + 1))
                edge_positions.update(range(peak_end, int(peak_right_end[peak_num]) + 1))
                bound_positions.update(range(peak_start, peak_end + 1))

            edge_index = gene_ratio_smooth.index.intersection(list(edge_positions))
            bound_index = gene_ratio_smooth.index.intersection(list(bound_positions))
            edge.loc[edge_index] = gene_ratio_smooth.loc[edge_index, "enrich"]
            bound.loc[bound_index] = gene_ratio_smooth.loc[bound_index, "enrich"]

        profile["edge"] = edge.reset_index(drop=True)
        profile["bound"] = bound.reset_index(drop=True)
        output_path = Path(self.peak_ratio_file)
        profile.to_csv(
            output_path,
            sep="\t",
            mode="a",
            header=not output_path.exists(),
            index=False,
        )

    def write_raw_ratio(self, transcript: str, ratio: pd.DataFrame) -> None:
        """Append one transcript's unsmoothed enrichment ratios when requested."""
        if not self.ratio_out:
            return

        output_path = Path(self.enrich_ratio_file)
        with open(output_path, "a", encoding="utf-8") as handle:
            handle.write("##############################################\n")
        ratio_out = ratio.copy()
        ratio_out.index.name = transcript
        ratio_out.to_csv(output_path, sep="\t", mode="a", header=True, index=True)

    def write_results(
        self,
        peak_merge: list[list[str]] | pd.DataFrame,
        rpf_seq: pd.DataFrame,
        gene_dict: OrderedDict[str, str],
    ) -> pd.DataFrame:
        """Write final peak tables, BED files, and peak sequence output."""
        if not isinstance(peak_merge, pd.DataFrame):
            peak_merge = pd.DataFrame(peak_merge, columns=self.result_columns)

        peak_number = pd.to_numeric(peak_merge["peak_num"], errors="coerce")
        peak_all = peak_merge.loc[peak_number > 0].copy()
        if peak_all.empty:
            peak_all.to_csv(self.peak_txt_file, sep="\t", header=True, index=False)
            self._write_empty_bed(self.peak_bed_file)
            self._write_empty_bed(self.peak_sig_bed_file)
            self._write_empty_peak_sequences()
            return peak_merge

        numeric_pvalue = pd.to_numeric(peak_all["P_Value"], errors="coerce")
        valid_pvalue = numeric_pvalue.notna()
        peak_all["rank"] = "-"
        peak_all["BHFDR"] = "-"
        if valid_pvalue.any():
            valid_values = numeric_pvalue.loc[valid_pvalue].astype(float)
            peak_all.loc[valid_pvalue, "P_Value"] = valid_values.astype(str)
            peak_all.loc[valid_pvalue, "rank"] = valid_values.rank(
                method="first"
            ).astype(str)
            peak_all.loc[valid_pvalue, "BHFDR"] = [
                str(value) for value in self._adjust_bh(valid_values)
            ]

        peak_all.to_csv(self.peak_txt_file, sep="\t", header=True, index=False)

        peak_bed = self._build_peak_bed(peak_all)
        self._write_bed(peak_bed, self.peak_bed_file)
        significant_peak = peak_bed.loc[
            peak_bed["P_Value"].notna() & (peak_bed["P_Value"] < 0.05)
        ].copy()
        self._write_bed(significant_peak, self.peak_sig_bed_file)
        self._write_peak_sequences(peak_all, rpf_seq, gene_dict)
        return peak_merge

    def _build_peak_bed(self, peak_all: pd.DataFrame) -> pd.DataFrame:
        """Convert peak coordinates to the historical BED-like representation."""
        peak_bed = peak_all.loc[
            :,
            [
                "transcripts",
                "peak_start",
                "peak_end",
                "peak_num",
                "mean_fold",
                "max_site",
                "P_Value",
            ],
        ].copy()
        peak_bed["name"] = (
            peak_bed["transcripts"].astype(str)
            + "_peak_"
            + peak_bed["peak_num"].astype(str)
        )
        peak_bed["strand"] = "+"
        for column in [
            "peak_start",
            "peak_end",
            "peak_num",
            "mean_fold",
            "max_site",
            "P_Value",
        ]:
            peak_bed[column] = pd.to_numeric(peak_bed[column], errors="coerce")
        peak_bed["peak_start"] = peak_bed["peak_start"] - 1
        peak_bed = peak_bed.loc[peak_bed["peak_start"] >= 0].copy()
        peak_bed["start"] = peak_bed["peak_start"] * 3
        peak_bed["end"] = peak_bed["peak_end"] * 3 + 2
        return peak_bed

    @staticmethod
    def _write_bed(peak_bed: pd.DataFrame, output_file: str) -> None:
        """Write a BED-like SeRP peak table."""
        bed_merge = peak_bed.loc[
            :, ["transcripts", "start", "end", "name", "mean_fold", "strand"]
        ].copy()
        bed_merge.columns = [
            "#transcripts",
            "start",
            "end",
            "name",
            "mean_fold",
            "strand",
        ]
        bed_merge.to_csv(output_file, sep="\t", header=True, index=False)

    @staticmethod
    def _write_empty_bed(output_file: str) -> None:
        """Write an empty BED-like table with the historical column names."""
        pd.DataFrame(
            columns=["#transcripts", "start", "end", "name", "mean_fold", "strand"]
        ).to_csv(output_file, sep="\t", index=False)

    def _write_empty_peak_sequences(self) -> None:
        """Write an empty peak-sequence table with the historical schema."""
        pd.DataFrame(columns=self._peak_sequence_columns()).to_csv(
            self.peak_seq_file,
            sep="\t",
            index=False,
        )

    @staticmethod
    def _peak_sequence_columns() -> list[str]:
        """Return the peak-sequence output column order."""
        return [
            "transcripts",
            "gene_name",
            "peak_name",
            "peak_start",
            "peak_end",
            "max_site",
            "upstream_nt",
            "peak_nt",
            "downstream_nt",
            "upstream_aa",
            "peak_aa",
            "downstream_aa",
        ]

    def _write_peak_sequences(
        self,
        peak_table: pd.DataFrame,
        rpf_seq: pd.DataFrame,
        gene_dict: OrderedDict[str, str],
    ) -> None:
        """Write nucleotide and translated amino-acid sequences around each peak.

        Peak sequences must use the original ``from_tis`` codon coordinates.
        BED conversion is intentionally kept separate because its start coordinate
        is transformed for the historical BED-like output representation.
        """
        if peak_table.empty:
            return

        peak_gene_names = peak_table["transcripts"].astype(str).unique().tolist()
        selected_rpf_seq = rpf_seq.loc[rpf_seq["name"].isin(peak_gene_names)].copy()
        rpf_seq_group = selected_rpf_seq.groupby("name", sort=False)
        peak_seq_list = []

        for _, row in peak_table.iterrows():
            transcript = str(row["transcripts"])
            if transcript not in rpf_seq_group.groups:
                continue

            peak_start = int(row["peak_start"])
            peak_end = int(row["peak_end"])
            up_start = peak_start - self.upstream
            down_end = peak_end + self.downstream
            gene_rpf = rpf_seq_group.get_group(transcript)

            upstream_seq = gene_rpf.loc[
                (gene_rpf["from_tis"] >= up_start)
                & (gene_rpf["from_tis"] < peak_start),
                "codon",
            ].astype(str).tolist()
            peak_seq = gene_rpf.loc[
                (gene_rpf["from_tis"] >= peak_start)
                & (gene_rpf["from_tis"] <= peak_end),
                "codon",
            ].astype(str).tolist()
            downstream_seq = gene_rpf.loc[
                (gene_rpf["from_tis"] > peak_end)
                & (gene_rpf["from_tis"] <= down_end),
                "codon",
            ].astype(str).tolist()

            upstream_nt = "".join(upstream_seq)
            peak_nt = "".join(peak_seq)
            downstream_nt = "".join(downstream_seq)
            peak_seq_list.append(
                [
                    transcript,
                    gene_dict.get(transcript, "-"),
                    "{0}_peak_{1}".format(transcript, int(row["peak_num"])),
                    peak_start,
                    peak_end,
                    int(row["max_site"]),
                    upstream_nt,
                    peak_nt,
                    downstream_nt,
                    str(Seq(upstream_nt).translate()) if upstream_nt else "",
                    str(Seq(peak_nt).translate()) if peak_nt else "",
                    str(Seq(downstream_nt).translate()) if downstream_nt else "",
                ]
            )

        peak_seq = pd.DataFrame(peak_seq_list, columns=self._peak_sequence_columns())
        peak_seq.to_csv(self.peak_seq_file, sep="\t", header=True, index=False)
