#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-06-12
# Version: 0.2.7
# Function: This script is used to calculate the GC content of fasta file.
# Input: Command-line arguments and input files specified by the user.
# Output: Analysis tables, figures, logs, or intermediate files generated by the command.


import pandas as pd
# import polars as pl
# import numpy as np
from collections import OrderedDict
from collections import Counter
# from Bio import SeqIO
import argparse


def fa_gc_args_parser():

    parser = argparse.ArgumentParser(description='This script is used to calculate the GC content of fasta file.')

    require_group = parser.add_argument_group('Required arguments')
    require_group.add_argument(
        '-i', dest='input', required=True, type=str, 
        help='input fasta file name.'
    )
    require_group.add_argument(
        '-o', dest='output', required=True, type=str, 
        help='output txt file name.'
    )

    args = parser.parse_args()

    return args


def input_fa(args):
    """Import the fasta file.

    Parameters
    ----------
    args : object
        Packed arguments used by this function.

    Returns
    -------
    object
        fasta dict.

    Notes
    -----
    Legacy input information:
    - ``fasta``: input file.
    """

    fa_dict = OrderedDict()
    seq_name = None

    with open(args.input, 'r') as fa_in:
        for line in fa_in:
            
            if line.startswith('>'):
                seq_name = line.strip()
                if seq_name in fa_dict:
                    fa_dict[seq_name + 'rep2'] = []
                else:
                    fa_dict[seq_name] = ['', 0, 0, 0, 0]
            else:
                fa_dict[seq_name][0] += line.strip()
    
    return fa_dict


def calc_gc(args, fa_dict):
    """Calculate the GC content of fasta file.

    Parameters
    ----------
    args : object
        Input argument used by this function.
    fa_dict : object
        Input argument used by this function.

    Returns
    -------
    None
        The function updates internal state or writes output files in place.

    Notes
    -----
    Legacy input information:
    - ``fasta``: input file.

    Legacy return information:
    - ``output``: GC content of fasta file.
    """

    gc_dict = OrderedDict()

    for seq_name, seq_info in fa_dict.items():
        gc_dict[seq_name] = [seq_name,
                             seq_info[0].count('A'), 
                             seq_info[0].count('T'), 
                             seq_info[0].count('C'), 
                             seq_info[0].count('G')]

    gc_df = pd.DataFrame.from_dict(gc_dict, orient='index', columns=['name', 'A', 'T', 'C', 'G'])

    gc_df.to_csv(args.output, sep='\t', index=False)

    sum_gc = gc_df.iloc[:, 1:5].sum(axis=0)
    print(sum_gc)


def main():
    args = fa_gc_args_parser()
    fa_dict = input_fa(args)
    calc_gc(args, fa_dict)


if __name__ == '__main__':
    main()
