#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-06-12
# Version: 0.2.7
# Function: This script is used to convert multiple lines to one line.
# Input: Command-line arguments and input files specified by the user.
# Output: Analysis tables, figures, logs, or intermediate files generated by the command.


# from Bio import SeqIO
import argparse


def line_feed_args_parser():
    
    parser = argparse.ArgumentParser(description='This script is used to convert multiple lines to one line.')

    # needed arguments
    input_group = parser.add_argument_group('Required arguments')
    input_group.add_argument(
        '-i', dest='input', required=True, type=str, help='input fasta file name.'
    )
    input_group.add_argument(
        '-o', dest='output', required=True, type=str, help='output fasta file name.'
    )

    args = parser.parse_args()
    args_dict = vars(args)
    for k, v in args_dict.items():
        print('{:<12}:  {:<}'.format(k, str(v)), flush=True)

    return args


def line_feed(args):
    """Convert multiple lines to one line.

    Parameters
    ----------
    args : object
        Packed arguments used by this function.

    Returns
    -------
    None
        The function updates internal state or writes output files in place.

    Notes
    -----
    Legacy input information:
    - ``fasta``: input file.

    Legacy return information:
    - ``output``: fasta file.
    """

    with open(args.input, 'r') as fa_in:
        with open(args.output, 'w') as fa_out:
            seq_id = ''
            seq_mess = ''

            for line in fa_in:
                if line.startswith('>') and seq_mess == '':
                    seq_id = line.strip()

                elif line.startswith('>') and seq_mess != '':
                    fa_out.writelines(seq_id + '\n')
                    fa_out.writelines(seq_mess + '\n')

                    seq_id = line.strip()
                    seq_mess = ''
                else:
                    seq_mess += line.strip()
                
            fa_out.writelines(seq_id + '\n')
            fa_out.writelines(seq_mess + '\n')


def main():
    args = line_feed_args_parser()
    line_feed(args)


if __name__ == '__main__':
    main()
