#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-07-09
# Version: 0.2.8-dev.013
# Function: Calculate and plot normalized metagene coverage profiles.
# Input: RPF density file in JSONL or TXT format and optional transcript filter.
# Output: Metagene coverage tables, outlier tables, line plots, heatmaps, and summary JSON.

"""Metagene coverage analysis utilities for RiboParser.

This module calculates normalized 5'UTR-CDS-3'UTR coverage profiles from the
updated RiboParser density format. The RPF import layer is delegated to
``utils.ribo.RPFs.RPFData`` so compact JSONL density files generated by the
updated ``rpf_Density`` / ``rpf_Merge`` workflow and legacy TXT files are both
supported.
"""

from __future__ import annotations

import json
import os
import re
from collections import OrderedDict
from collections.abc import Iterable
from typing import Any

from . import RPFs

import matplotlib

matplotlib.use("AGG")

import matplotlib.patches as patches
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


BASE_COLUMNS = ["name", "now_nt", "from_tis", "from_tts", "region", "codon"]
REGION_ORDER = ["5utr", "cds", "3utr"]
REGION_LABELS = {
    "5utr": "5-UTR",
    "cds": "CDS",
    "3utr": "3-UTR",
}
REGION_STRUCTURE_LABELS = {
    "5utr": "5' UTR",
    "cds": "CDS",
    "3utr": "3' UTR",
}
REGION_COLORS = {
    "5utr": "#BDBDBD",
    "cds": "#4C78A8",
    "3utr": "#BDBDBD",
}
BOUNDARY_COLOR = "#222222"
HEATMAP_CMAP = "Blues"
RPM_SCALE = 1_000_000.0
PLOT_TRANSFORM_LABELS = {
    "none": "",
    "sqrt": "sqrt",
    "log": "log1p",
    "log1p": "log1p",
    "log2": "log2(x + 1)",
    "log10": "log10(x + 1)",
}


class Coverage(object):
    """Calculate and plot metagene coverage profiles.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed command-line arguments from ``rpf_Coverage``.
    """

    def __init__(self, args):
        # Input and output.
        self.transcript = args.transcript
        self.rpf = args.rpf
        self.output = args.output

        # Density and filtering parameters.
        self.frame = args.frame
        self.site = getattr(args, "site", "P")
        self.rpf_num = int(args.min)
        self.utr5_bin, self.cds_bin, self.utr3_bin = self._parse_bins(args.bin)
        self.norm = bool(args.normal)
        self.normal_scale = RPM_SCALE
        self.set = args.set
        self.thread = max(1, int(getattr(args, "thread", 1)))

        # Plot transformation and heatmap scaling parameters.
        self.plot_transform = args.plot_transform
        self.scale = args.scale

        # Outlier filtering parameters.
        self.remove_outlier = bool(args.remove_outlier)
        self.outlier_iqr = float(args.outlier_iqr)
        self.outlier_window = int(args.outlier_window)
        self.outlier_local_fold = float(args.outlier_local_fold)

        # Imported RPF data.
        self.rpf_data = None
        self.raw_rpf = None
        self.raw_density_table = None
        self.density_table = None
        self.sample_name = []
        self.sample_num = 0
        self.total_rpf_num = None
        self.file_format = None

        # Coverage results.
        self.coverage = None
        self.outliers = pd.DataFrame()
        self.sample_summary = pd.DataFrame()
        self.sample_dict = OrderedDict()
        self.output_files = OrderedDict()

    # ------------------------------------------------------------------
    # Import and validation
    # ------------------------------------------------------------------

    @staticmethod
    def _parse_bins(bin_arg: str | Iterable[int]) -> tuple[int, int, int]:
        """Parse metagene bin settings."""
        if isinstance(bin_arg, str):
            values = [item.strip() for item in bin_arg.split(",")]
        else:
            values = list(bin_arg)

        if len(values) != 3:
            raise ValueError("-b/--bin must contain three comma-separated integers, such as 30,100,30.")

        utr5_bin, cds_bin, utr3_bin = [int(value) for value in values]
        if utr5_bin < 0:
            raise ValueError("5'UTR bin number must be >= 0.")
        if cds_bin <= 0:
            raise ValueError("CDS bin number must be > 0.")
        if utr3_bin < 0:
            raise ValueError("3'UTR bin number must be >= 0.")
        return utr5_bin, cds_bin, utr3_bin

    def import_rpf(self) -> None:
        """Import RPF density data through the updated ``RPFs`` module."""
        self.rpf_data = RPFs.RPFData.from_file(
            rpf_file=self.rpf,
            sample_name=None,
            gene=self.transcript,
            tis=None,
            tts=None,
        )

        self.raw_rpf = self.rpf_data.raw_rpf.to_pandas()
        self.sample_name = list(self.rpf_data.sample_name)
        self.sample_num = int(self.rpf_data.sample_num)
        self.total_rpf_num = self.rpf_data.total_rpf_num
        self.file_format = self.rpf_data.file_format

        self.raw_density_table = self.rpf_data.shifted_frame(sites=self.site, frame=self.frame)
        self.density_table = self.raw_density_table.copy()

        self._validate_density_table(self.raw_density_table)
        self._normalize_density_table()

        print(
            "Imported RPF density for {sample_num} sample(s), format={fmt}, rows={rows:,}.".format(
                sample_num=self.sample_num,
                fmt=self.file_format,
                rows=len(self.density_table),
            ),
            flush=True,
        )

    def read_rpf(self) -> None:
        """Backward-compatible alias of :meth:`import_rpf`."""
        self.import_rpf()

    def _validate_density_table(self, density_table: pd.DataFrame) -> None:
        """Validate required columns in the imported density table."""
        if density_table is None or density_table.empty:
            raise ValueError("RPF density table is empty after import.")

        missing_base = [column for column in BASE_COLUMNS if column not in density_table.columns]
        if missing_base:
            raise ValueError(
                "RPF density table is missing required base column(s): {columns}".format(
                    columns=", ".join(missing_base)
                )
            )

        missing_samples = [sample for sample in self.sample_name if sample not in density_table.columns]
        if missing_samples:
            raise ValueError(
                "RPF density table is missing sample column(s): {columns}".format(
                    columns=", ".join(missing_samples)
                )
            )

    def _sample_total(self, sample: str) -> float:
        """Return total raw RPF count for one sample."""
        if self.total_rpf_num is not None and sample in self.total_rpf_num.index:
            total = float(self.total_rpf_num.loc[sample])
        elif self.raw_density_table is not None and sample in self.raw_density_table.columns:
            total = float(self.raw_density_table[sample].sum())
        else:
            total = 0.0
        return total

    def _normalize_density_table(self) -> None:
        """Convert sample density columns to RPM when requested.

        Notes
        -----
        Pandas 2.x does not allow assigning floating-point RPM values back into
        integer columns through ``.loc`` without explicit dtype conversion. The
        sample columns are therefore converted to ``float64`` before in-place
        normalization.
        """
        sample_columns = list(self.sample_name)

        if not sample_columns:
            return

        for sample in sample_columns:
            self.density_table[sample] = (
                pd.to_numeric(self.density_table[sample], errors="coerce")
                .fillna(0.0)
                .astype("float64")
            )

        if not self.norm:
            return

        for sample in sample_columns:
            total = self._sample_total(sample)
            if total > 0:
                self.density_table[sample] = self.density_table[sample] * self.normal_scale / total
            else:
                self.density_table[sample] = 0.0

    # ------------------------------------------------------------------
    # Calculation helpers
    # ------------------------------------------------------------------

    def _region_bins(self) -> OrderedDict[str, int]:
        """Return bin number for each metagene region."""
        return OrderedDict(
            [
                ("5utr", self.utr5_bin),
                ("cds", self.cds_bin),
                ("3utr", self.utr3_bin),
            ]
        )

    def _region_offset(self, region: str) -> int:
        """Return metagene position offset for one region."""
        if region == "5utr":
            return -int(self.utr5_bin)
        if region == "cds":
            return 0
        if region == "3utr":
            return int(self.cds_bin)
        raise ValueError("Unsupported region: {region}".format(region=region))

    def _region_capacity(self) -> pd.DataFrame:
        """Return per-transcript region codon counts."""
        region_count = (
            self.raw_density_table.groupby(["name", "region"], sort=False)
            .size()
            .unstack(fill_value=0)
        )
        for region in REGION_ORDER:
            if region not in region_count.columns:
                region_count[region] = 0
        region_count = region_count.loc[:, REGION_ORDER].astype(int)
        return region_count

    def _get_high_expression_genes(self, sample: str) -> pd.Index:
        """Return sample-specific high-expression transcripts."""
        cds_rpf = self.raw_density_table.loc[
            self.raw_density_table["region"] == "cds",
            ["name", sample],
        ].copy()
        gene_count = cds_rpf.groupby("name", sort=False)[sample].sum()
        high_gene = gene_count.loc[gene_count >= self.rpf_num].index

        if self.set == "intersect":
            capacity = self._region_capacity()
            required_regions = [region for region, bins in self._region_bins().items() if bins > 0]
            if required_regions:
                valid_region_gene = capacity.index[(capacity.loc[:, required_regions] > 0).all(axis=1)]
                high_gene = high_gene.intersection(valid_region_gene)

        return high_gene

    @staticmethod
    def _assign_normalized_bins(region_df: pd.DataFrame, bins: int) -> pd.DataFrame:
        """Assign local normalized bins within each transcript region."""
        if region_df.empty or bins <= 0:
            return region_df.assign(Bin=pd.Series(dtype="int64"))

        region_df = region_df.sort_values(["name", "now_nt"], kind="mergesort").copy()
        region_df["RegionIndex"] = region_df.groupby("name", sort=False).cumcount()
        region_df["RegionLength"] = region_df.groupby("name", sort=False)["name"].transform("size")
        region_df["Bin"] = np.floor(
            region_df["RegionIndex"].astype(float) * float(bins) / region_df["RegionLength"].astype(float)
        ).astype(int)
        region_df["Bin"] = region_df["Bin"].clip(lower=0, upper=bins - 1)
        return region_df

    def _build_binned_region_table(self, sample: str, region: str, genes: pd.Index) -> pd.DataFrame:
        """Return per-transcript normalized-bin coverage for one sample and region."""
        bins = self._region_bins()[region]
        columns = ["name", "now_nt", "region", sample]

        if bins <= 0 or len(genes) == 0:
            return pd.DataFrame(
                columns=["Sample", "Region", "Transcript", "Bin", "MetaPosition", "RawDensity", "Density"]
            )

        density_df = self.density_table.loc[
            self.density_table["name"].isin(genes) & (self.density_table["region"] == region),
            columns,
        ].copy()
        raw_df = self.raw_density_table.loc[
            self.raw_density_table["name"].isin(genes) & (self.raw_density_table["region"] == region),
            columns,
        ].copy()

        density_df = self._assign_normalized_bins(density_df, bins)
        raw_df = self._assign_normalized_bins(raw_df, bins)

        if density_df.empty:
            value_df = pd.DataFrame(columns=["Transcript", "Bin", "Density", "RawDensity"])
        else:
            density_bin = (
                density_df.groupby(["name", "Bin"], sort=False)[sample]
                .mean()
                .rename("Density")
                .reset_index()
                .rename(columns={"name": "Transcript"})
            )
            raw_bin = (
                raw_df.groupby(["name", "Bin"], sort=False)[sample]
                .mean()
                .rename("RawDensity")
                .reset_index()
                .rename(columns={"name": "Transcript"})
            )
            value_df = density_bin.merge(raw_bin, on=["Transcript", "Bin"], how="outer")

        full_index = pd.MultiIndex.from_product(
            [pd.Index(genes, name="Transcript"), range(bins)],
            names=["Transcript", "Bin"],
        )
        value_df = value_df.set_index(["Transcript", "Bin"]).reindex(full_index).reset_index()
        value_df["Density"] = value_df["Density"].fillna(0.0).astype(float)
        value_df["RawDensity"] = value_df["RawDensity"].fillna(0.0).astype(float)
        value_df["Sample"] = sample
        value_df["Region"] = REGION_LABELS[region]
        value_df["MetaPosition"] = value_df["Bin"].astype(int) + self._region_offset(region)

        return value_df[
            ["Sample", "Region", "Transcript", "Bin", "MetaPosition", "RawDensity", "Density"]
        ]

    @staticmethod
    def _robust_upper_cutoff(values: pd.Series, multiplier: float) -> float:
        """Return a dynamic robust upper cutoff on the log1p scale."""
        positive = values.loc[values > 0].astype(float)
        if positive.size < 4:
            return float("inf")

        log_values = np.log1p(positive.to_numpy(dtype=float))
        q1 = float(np.percentile(log_values, 25))
        q3 = float(np.percentile(log_values, 75))
        iqr = q3 - q1

        median = float(np.median(log_values))
        mad = float(np.median(np.abs(log_values - median)))
        mad_sigma = 1.4826 * mad

        cutoffs = []
        if iqr > 0:
            cutoffs.append(q3 + multiplier * iqr)
        if mad_sigma > 0:
            cutoffs.append(median + multiplier * mad_sigma)

        if not cutoffs:
            return float("inf")

        return float(np.expm1(max(cutoffs)))

    def _candidate_local_background(
        self,
        binned_df: pd.DataFrame,
        candidate_df: pd.DataFrame,
    ) -> pd.DataFrame:
        """Add local-background metrics only for global outlier candidates."""
        if candidate_df.empty:
            candidate_df = candidate_df.copy()
            candidate_df["LocalBackground"] = []
            candidate_df["LocalFold"] = []
            return candidate_df

        window = max(1, int(self.outlier_window))
        density_lookup = (
            binned_df.loc[:, ["Transcript", "Bin", "RawDensity"]]
            .set_index(["Transcript", "Bin"])["RawDensity"]
            .astype(float)
        )

        local_backgrounds = []
        local_folds = []

        for row in candidate_df.itertuples(index=False):
            transcript = getattr(row, "Transcript")
            bin_id = int(getattr(row, "Bin"))
            raw_density = float(getattr(row, "RawDensity"))

            neighbor_values = []
            for offset in range(1, window + 1):
                left_value = density_lookup.get((transcript, bin_id - offset), np.nan)
                right_value = density_lookup.get((transcript, bin_id + offset), np.nan)

                if pd.notna(left_value):
                    neighbor_values.append(float(left_value))
                if pd.notna(right_value):
                    neighbor_values.append(float(right_value))

            if neighbor_values:
                local_background = float(np.median(neighbor_values))
            else:
                local_background = 0.0

            local_backgrounds.append(local_background)
            local_folds.append((raw_density + 1.0) / (local_background + 1.0))

        candidate_df = candidate_df.copy()
        candidate_df["LocalBackground"] = local_backgrounds
        candidate_df["LocalFold"] = local_folds
        return candidate_df

    def _remove_outlier_points(self, binned_df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
        """Remove dynamic, locally isolated extreme gene-bin pileups."""
        outlier_columns = list(binned_df.columns) + [
            "LocalBackground",
            "LocalFold",
            "OutlierCutoff",
            "OutlierMethod",
            "OutlierReason",
        ]

        if not self.remove_outlier or binned_df.empty:
            return binned_df, pd.DataFrame(columns=outlier_columns)

        raw_density = binned_df["RawDensity"].astype(float)
        cutoff = self._robust_upper_cutoff(raw_density, float(self.outlier_iqr))

        if not np.isfinite(cutoff):
            return binned_df, pd.DataFrame(columns=outlier_columns)

        candidate_mask = raw_density > cutoff
        if not bool(candidate_mask.any()):
            return binned_df, pd.DataFrame(columns=outlier_columns)

        candidate_df = binned_df.loc[candidate_mask, :].copy()
        candidate_df = self._candidate_local_background(binned_df, candidate_df)

        local_fold = (
            candidate_df["LocalFold"]
            .astype(float)
            .replace([np.inf, -np.inf], np.nan)
            .fillna(0.0)
        )
        keep_candidate_mask = local_fold >= float(self.outlier_local_fold)
        outlier_df = candidate_df.loc[keep_candidate_mask, :].copy()

        if outlier_df.empty:
            return binned_df, pd.DataFrame(columns=outlier_columns)

        outlier_df["OutlierCutoff"] = cutoff
        outlier_df["OutlierMethod"] = "fast_log1p_robust_cutoff_and_candidate_local_peak"
        outlier_df["OutlierReason"] = (
            "RawDensity > dynamic robust cutoff and LocalFold >= "
            + str(float(self.outlier_local_fold))
        )

        clean_df = binned_df.drop(index=outlier_df.index).copy()
        outlier_df = outlier_df.reindex(columns=outlier_columns)
        return clean_df, outlier_df

    def _aggregate_region_profile(
        self,
        clean_df: pd.DataFrame,
        sample: str,
        region: str,
        bins: int,
        gene_count: int,
        outlier_count: int,
    ) -> pd.DataFrame:
        """Aggregate transcript-bin coverage into one sample-level region profile."""
        grid = pd.DataFrame(
            {
                "Sample": sample,
                "Region": REGION_LABELS[region],
                "Bin": list(range(bins)),
                "MetaPosition": [self._region_offset(region) + bin_id for bin_id in range(bins)],
            }
        )

        if clean_df.empty:
            aggregated = grid.copy()
            aggregated["Density"] = 0.0
            aggregated["RawDensity"] = 0.0
            aggregated["ObservedGeneCount"] = 0
        else:
            aggregated = (
                clean_df.groupby(["Sample", "Region", "Bin", "MetaPosition"], sort=False)
                .agg(
                    Density=("Density", "mean"),
                    RawDensity=("RawDensity", "mean"),
                    ObservedGeneCount=("Transcript", "nunique"),
                )
                .reset_index()
            )
            aggregated = grid.merge(
                aggregated,
                on=["Sample", "Region", "Bin", "MetaPosition"],
                how="left",
            )
            aggregated["Density"] = aggregated["Density"].fillna(0.0)
            aggregated["RawDensity"] = aggregated["RawDensity"].fillna(0.0)
            aggregated["ObservedGeneCount"] = aggregated["ObservedGeneCount"].fillna(0).astype(int)

        aggregated["TotalGeneCount"] = int(gene_count)
        aggregated["OutlierCount"] = int(outlier_count)
        return aggregated[
            [
                "Sample",
                "Region",
                "Bin",
                "MetaPosition",
                "Density",
                "RawDensity",
                "ObservedGeneCount",
                "TotalGeneCount",
                "OutlierCount",
            ]
        ]

    # ------------------------------------------------------------------
    # Public calculation workflow
    # ------------------------------------------------------------------

    def calc_coverage(self) -> None:
        """Calculate metagene coverage profiles for all samples."""
        if self.density_table is None:
            raise ValueError("RPF density data has not been imported yet.")

        coverage_tables = []
        outlier_tables = []
        summary_records = []

        for sample in self.sample_name:
            high_gene = self._get_high_expression_genes(sample)
            gene_count = int(len(high_gene))

            if gene_count == 0:
                print(
                    "Warning: sample {sample} has no transcript after expression filtering.".format(
                        sample=sample
                    ),
                    flush=True,
                )

            sample_tables = []
            sample_outlier_count = 0
            region_gene_counts: dict[str, int] = {}

            for region, bins in self._region_bins().items():
                if bins <= 0:
                    continue

                binned_df = self._build_binned_region_table(sample, region, high_gene)
                region_gene_counts[region] = int(
                    binned_df.loc[binned_df["RawDensity"] > 0, "Transcript"].nunique()
                )
                clean_df, outlier_df = self._remove_outlier_points(binned_df)
                outlier_count = int(len(outlier_df))
                sample_outlier_count += outlier_count

                aggregated = self._aggregate_region_profile(
                    clean_df=clean_df,
                    sample=sample,
                    region=region,
                    bins=bins,
                    gene_count=gene_count,
                    outlier_count=outlier_count,
                )
                coverage_tables.append(aggregated)
                sample_tables.append(aggregated)

                if not outlier_df.empty:
                    outlier_tables.append(outlier_df)

            self.sample_dict[sample] = {
                "gene_count": gene_count,
                "outlier_count": int(sample_outlier_count),
                "coverage": pd.concat(sample_tables, axis=0, ignore_index=True) if sample_tables else pd.DataFrame(),
            }
            summary_records.append(
                {
                    "Sample": sample,
                    "HighGeneCount": gene_count,
                    "UTR5GeneCount": region_gene_counts.get("5utr", 0),
                    "CDSGeneCount": region_gene_counts.get("cds", 0),
                    "UTR3GeneCount": region_gene_counts.get("3utr", 0),
                    "OutlierCount": int(sample_outlier_count),
                }
            )
            print(
                "Sample {sample}: high genes={genes:,}, removed outlier points={outliers:,}.".format(
                    sample=sample,
                    genes=gene_count,
                    outliers=sample_outlier_count,
                ),
                flush=True,
            )

        if not coverage_tables:
            raise ValueError("No coverage result was generated.")

        self.coverage = pd.concat(coverage_tables, axis=0, ignore_index=True)
        self.coverage.sort_values(["Sample", "MetaPosition"], inplace=True)
        self.sample_summary = pd.DataFrame.from_records(summary_records)

        if outlier_tables:
            self.outliers = pd.concat(outlier_tables, axis=0, ignore_index=True)
        else:
            self.outliers = pd.DataFrame(
                columns=[
                    "Sample",
                    "Region",
                    "Transcript",
                    "Bin",
                    "MetaPosition",
                    "RawDensity",
                    "Density",
                    "LocalBackground",
                    "LocalFold",
                    "OutlierCutoff",
                    "OutlierMethod",
                    "OutlierReason",
                ]
            )

    # ------------------------------------------------------------------
    # Output tables and summary
    # ------------------------------------------------------------------

    def output_coverage(self) -> None:
        """Write coverage summary tables."""
        if self.coverage is None:
            raise ValueError("Coverage has not been calculated yet.")

        out_txt = self.output + "_metagene_coverage.txt"
        self.coverage.to_csv(out_txt, sep="\t", index=False)
        self.output_files["coverage_table"] = out_txt

        summary_txt = self.output + "_coverage.sample_summary.txt"
        self.sample_summary.to_csv(summary_txt, sep="\t", index=False)
        self.output_files["sample_summary"] = summary_txt

        if self.remove_outlier:
            outlier_txt = self.output + "_coverage.outliers.txt"
            self.outliers.to_csv(outlier_txt, sep="\t", index=False)
            self.output_files["outlier_table"] = outlier_txt
            print(
                "Outlier table written: {file} (removed points={count:,}).".format(
                    file=outlier_txt,
                    count=len(self.outliers),
                ),
                flush=True,
            )

    def output_meta_gene(self) -> None:
        """Backward-compatible alias of :meth:`output_coverage`."""
        self.output_coverage()

    def write_summary(self) -> None:
        """Write a machine-readable coverage summary JSON."""
        summary_json = self.output + "_coverage.summary.json"
        self.output_files["summary_json"] = summary_json
        summary = OrderedDict(
            [
                ("tool", "rpf_Coverage"),
                ("version", "0.2.8-dev.013"),
                ("input_rpf", os.path.abspath(self.rpf)),
                ("input_format", self.file_format),
                ("transcript_filter", os.path.abspath(self.transcript) if self.transcript else None),
                ("sample_count", self.sample_num),
                ("samples", self.sample_name),
                (
                    "parameters",
                    OrderedDict(
                        [
                            ("min", self.rpf_num),
                            ("frame", self.frame),
                            ("site", self.site),
                            ("bin", [self.utr5_bin, self.cds_bin, self.utr3_bin]),
                            ("set", self.set),
                            ("normal", self.norm),
                            ("rpm_scale", RPM_SCALE),
                            ("plot_transform", self.plot_transform),
                            ("heatmap_scale", self.scale),
                            ("remove_outlier", self.remove_outlier),
                            ("outlier_iqr", self.outlier_iqr),
                            ("outlier_window", self.outlier_window),
                            ("outlier_local_fold", self.outlier_local_fold),
                        ]
                    ),
                ),
                ("sample_summary", self.sample_summary.to_dict(orient="records")),
                ("output_files", self.output_files),
            ]
        )
        with open(summary_json, "w", encoding="utf-8") as out:
            json.dump(summary, out, ensure_ascii=False, indent=2)
            out.write("\n")

    # ------------------------------------------------------------------
    # Plot helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _safe_name(name: str) -> str:
        """Return a safe sample name for output file names."""
        return re.sub(r"[^0-9A-Za-z._-]+", "_", str(name)).strip("_") or "sample"

    @staticmethod
    def _nice_tick_step(span: float, max_ticks: int = 8) -> int:
        """Return a regular tick interval for the normalized metagene axis."""
        span = abs(float(span))
        if span <= 0:
            return 1

        raw_step = span / max(1, max_ticks - 1)
        preferred_steps = [1, 2, 5, 10, 15, 20, 25, 30, 50, 75, 100, 150, 200, 300, 500]
        for step in preferred_steps:
            if step >= raw_step:
                return step

        exponent = int(np.ceil(np.log10(raw_step)))
        return int(10 ** exponent)

    @staticmethod
    def _regular_ticks(x_min: int, x_max: int, step: int, max_ticks: int = 10) -> list[int]:
        """Return regular integer ticks and preserve TIS/TTS boundaries."""
        if x_min > x_max:
            x_min, x_max = x_max, x_min

        step = max(1, int(step))
        start = int(np.ceil(x_min / step) * step)
        end = int(np.floor(x_max / step) * step)
        ticks = list(range(start, end + step, step)) if start <= end else []

        if x_min not in ticks:
            ticks.append(x_min)
        if x_max not in ticks:
            ticks.append(x_max)
        ticks = sorted(set(int(tick) for tick in ticks))

        while len(ticks) > max_ticks:
            ticks = ticks[::2]
            if x_min not in ticks:
                ticks.insert(0, x_min)
            if x_max not in ticks:
                ticks.append(x_max)
            ticks = sorted(set(ticks))
            if len(ticks) <= 3:
                break

        return ticks

    def _axis_range(self) -> tuple[int, int]:
        """Return x-axis range of the normalized metagene profile."""
        x_min = -int(self.utr5_bin) if self.utr5_bin > 0 else 0
        x_max = int(self.cds_bin + self.utr3_bin - 1) if self.utr3_bin > 0 else int(self.cds_bin - 1)
        return x_min, x_max

    def _transform_density_values(self, values: Any) -> pd.Series:
        """Transform density values for plotting only."""
        transformed = pd.Series(values, dtype="float64").replace([np.inf, -np.inf], np.nan).fillna(0.0)
        transformed = transformed.clip(lower=0.0)

        if self.plot_transform == "none":
            return transformed
        if self.plot_transform == "sqrt":
            return np.sqrt(transformed)
        if self.plot_transform in {"log", "log1p"}:
            return np.log1p(transformed)
        if self.plot_transform == "log2":
            return np.log2(transformed + 1.0)
        if self.plot_transform == "log10":
            return np.log10(transformed + 1.0)

        raise ValueError("Unsupported plot transform: {transform}".format(transform=self.plot_transform))

    def _density_axis_label(self) -> str:
        """Return y-axis or colorbar label for plotted density values."""
        base = "Mean RPF coverage"
        if self.norm:
            base = "Mean RPF coverage (RPM)"

        label = PLOT_TRANSFORM_LABELS.get(self.plot_transform, "")
        if label:
            return "{base}, {label} transformed".format(base=base, label=label)
        return base

    @staticmethod
    def _row_minmax_scale(matrix: pd.DataFrame) -> pd.DataFrame:
        """Scale each heatmap row to the [0, 1] range."""
        scaled = matrix.astype(float).copy()
        row_min = scaled.min(axis=1)
        row_max = scaled.max(axis=1)
        row_range = (row_max - row_min).replace(0, np.nan)
        scaled = scaled.sub(row_min, axis=0).div(row_range, axis=0).fillna(0.0)
        return scaled

    def _set_common_axis_style(self, ax) -> None:
        """Apply common axis style to a coverage panel."""
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.grid(axis="y", linewidth=0.4, alpha=0.25)
        ax.axvline(0, color=BOUNDARY_COLOR, linewidth=0.8, linestyle="--", alpha=0.75)
        ax.axvline(self.cds_bin, color=BOUNDARY_COLOR, linewidth=0.8, linestyle="--", alpha=0.75)

    def _set_coverage_xticks(self, ax, max_ticks: int = 10) -> None:
        """Set normalized metagene x-axis without numeric tick labels."""
        x_min, x_max = self._axis_range()
        ax.set_xlim(x_min - 0.5, x_max + 0.5)
        ax.set_xticks([])
        ax.set_xticklabels([])

    def _draw_gene_structure(self, ax) -> None:
        """Draw a compact 5'UTR-CDS-3'UTR structure aligned to the metagene axis."""
        x_min, x_max = self._axis_range()
        ax.set_xlim(x_min - 0.5, x_max + 0.5)
        ax.set_ylim(0, 1)
        ax.set_yticks([])
        ax.set_xticks([])
        ax.set_xticklabels([])
        ax.tick_params(axis="x", length=0)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.spines["left"].set_visible(False)
        ax.spines["bottom"].set_visible(False)

        y_mid = 0.52
        utr_height = 0.18
        cds_height = 0.38

        if self.utr5_bin > 0:
            ax.add_patch(
                patches.Rectangle(
                    (-self.utr5_bin, y_mid - utr_height / 2),
                    self.utr5_bin,
                    utr_height,
                    facecolor=REGION_COLORS["5utr"],
                    edgecolor="none",
                    linewidth=0,
                )
            )
            ax.text(
                -self.utr5_bin / 2,
                0.86,
                REGION_STRUCTURE_LABELS["5utr"],
                ha="center",
                va="center",
                fontsize=9,
            )

        ax.add_patch(
            patches.Rectangle(
                (0, y_mid - cds_height / 2),
                self.cds_bin,
                cds_height,
                facecolor=REGION_COLORS["cds"],
                edgecolor="none",
                linewidth=0,
            )
        )
        ax.text(self.cds_bin / 2, 0.86, REGION_STRUCTURE_LABELS["cds"], ha="center", va="center", fontsize=9)

        if self.utr3_bin > 0:
            ax.add_patch(
                patches.Rectangle(
                    (self.cds_bin, y_mid - utr_height / 2),
                    self.utr3_bin,
                    utr_height,
                    facecolor=REGION_COLORS["3utr"],
                    edgecolor="none",
                    linewidth=0,
                )
            )
            ax.text(
                self.cds_bin + self.utr3_bin / 2,
                0.86,
                REGION_STRUCTURE_LABELS["3utr"],
                ha="center",
                va="center",
                fontsize=9,
            )

        ax.axvline(0, color=BOUNDARY_COLOR, linewidth=0.8, linestyle="--", alpha=0.75)
        ax.axvline(self.cds_bin, color=BOUNDARY_COLOR, linewidth=0.8, linestyle="--", alpha=0.75)
        ax.text(0, 0.12, "TIS", ha="center", va="center", fontsize=8)
        ax.text(self.cds_bin, 0.12, "TTS", ha="center", va="center", fontsize=8)

    def _profile_matrix(self) -> pd.DataFrame:
        """Return sample-by-position matrix for combined heatmap plotting."""
        if self.coverage is None:
            raise ValueError("Coverage has not been calculated yet.")

        data = self.coverage.loc[:, ["Sample", "MetaPosition", "Density"]].copy()
        data["PlotDensity"] = self._transform_density_values(data["Density"]).to_numpy(dtype=float)
        matrix = data.pivot_table(
            index="Sample",
            columns="MetaPosition",
            values="PlotDensity",
            aggfunc="mean",
            fill_value=0,
        )
        matrix = matrix.reindex(index=self.sample_name)
        matrix = matrix.reindex(columns=sorted(matrix.columns))

        if self.scale == "row":
            matrix = self._row_minmax_scale(matrix)

        return matrix

    def _set_heatmap_xticks(self, ax, positions: list[int], max_ticks: int = 10) -> None:
        """Hide numeric heatmap x-axis ticks and keep labeling in the structure track only."""
        ax.set_xticks([])
        ax.set_xticklabels([])

    # ------------------------------------------------------------------
    # Plotting workflow
    # ------------------------------------------------------------------

    def draw_meta_gene_line(self) -> None:
        """Draw per-sample metagene coverage line plots."""
        if self.coverage is None:
            raise ValueError("Coverage has not been calculated yet.")

        for sample, message in self.sample_dict.items():
            sample_coverage = message["coverage"].sort_values("MetaPosition").copy()
            if sample_coverage.empty:
                continue

            sample_coverage["PlotDensity"] = self._transform_density_values(sample_coverage["Density"]).to_numpy(dtype=float)
            safe_sample = self._safe_name(sample)
            out_pdf = f"{self.output}_{safe_sample}_coverage_line_plot.pdf"
            out_png = f"{self.output}_{safe_sample}_coverage_line_plot.png"

            print("Draw {sample} coverage line plot.".format(sample=sample), flush=True)

            fig = plt.figure(figsize=(9.5, 5.6))
            grid = fig.add_gridspec(nrows=2, ncols=1, height_ratios=[4.2, 0.95], hspace=0.05)
            ax = fig.add_subplot(grid[0, 0])
            gene_ax = fig.add_subplot(grid[1, 0], sharex=ax)

            ax.plot(sample_coverage["MetaPosition"], sample_coverage["PlotDensity"], linewidth=1.5, label=sample)
            ax.set_title(
                "Metagene coverage of {sample} ({genes:,} genes)".format(
                    sample=sample,
                    genes=int(message["gene_count"]),
                ),
                fontsize=12,
            )
            ax.set_ylabel(self._density_axis_label())
            self._set_common_axis_style(ax)
            self._set_coverage_xticks(ax, max_ticks=10)
            ax.legend(frameon=False, fontsize=8, loc="upper right")
            plt.setp(ax.get_xticklabels(), visible=False)

            self._draw_gene_structure(gene_ax)

            fig.savefig(out_pdf, bbox_inches="tight")
            fig.savefig(out_png, dpi=300, bbox_inches="tight")
            plt.close(fig)

            self.output_files[f"{sample}_coverage_line_pdf"] = out_pdf
            self.output_files[f"{sample}_coverage_line_png"] = out_png

    def draw_combined_line(self) -> None:
        """Draw one combined line plot for all samples."""
        if self.coverage is None:
            raise ValueError("Coverage has not been calculated yet.")

        out_pdf = self.output + "_coverage_line_plot.pdf"
        out_png = self.output + "_coverage_line_plot.png"

        fig = plt.figure(figsize=(10.5, 5.8))
        grid = fig.add_gridspec(nrows=2, ncols=1, height_ratios=[4.2, 0.95], hspace=0.05)
        ax = fig.add_subplot(grid[0, 0])
        gene_ax = fig.add_subplot(grid[1, 0], sharex=ax)

        for sample in self.sample_name:
            sample_coverage = self.coverage.loc[self.coverage["Sample"] == sample, :].sort_values("MetaPosition")
            if sample_coverage.empty:
                continue
            plot_density = self._transform_density_values(sample_coverage["Density"]).to_numpy(dtype=float)
            ax.plot(sample_coverage["MetaPosition"], plot_density, linewidth=1.1, alpha=0.85, label=sample)

        ax.set_title("Metagene coverage profiles", fontsize=12)
        ax.set_ylabel(self._density_axis_label())
        self._set_common_axis_style(ax)
        self._set_coverage_xticks(ax, max_ticks=10)
        if len(self.sample_name) <= 12:
            ax.legend(frameon=False, fontsize=7, ncol=min(3, max(1, len(self.sample_name))), loc="upper right")
        plt.setp(ax.get_xticklabels(), visible=False)

        self._draw_gene_structure(gene_ax)

        fig.savefig(out_pdf, bbox_inches="tight")
        fig.savefig(out_png, dpi=300, bbox_inches="tight")
        plt.close(fig)

        self.output_files["combined_line_pdf"] = out_pdf
        self.output_files["combined_line_png"] = out_png

    def draw_heatmap(self) -> None:
        """Draw the combined sample-by-position coverage heatmap."""
        matrix = self._profile_matrix()
        sample_count = max(1, len(matrix.index))
        figure_height = min(max(5.2, sample_count * 0.25 + 2.2), 18.0)

        out_pdf = self.output + "_coverage_heatmap.pdf"
        out_png = self.output + "_coverage_heatmap.png"

        fig = plt.figure(figsize=(11.0, figure_height + 0.45))
        grid = fig.add_gridspec(
            nrows=3,
            ncols=1,
            height_ratios=[max(3.5, figure_height - 1.4), 0.90, 0.28],
            hspace=0.06,
        )
        ax = fig.add_subplot(grid[0, 0])
        gene_ax = fig.add_subplot(grid[1, 0], sharex=ax)
        cbar_ax = fig.add_subplot(grid[2, 0])

        x_min, x_max = self._axis_range()
        image = ax.imshow(
            matrix.to_numpy(dtype=float),
            aspect="auto",
            interpolation="nearest",
            cmap=HEATMAP_CMAP,
            extent=(x_min - 0.5, x_max + 0.5, len(matrix.index) - 0.5, -0.5),
        )
        ax.set_title("Metagene coverage heatmap", fontsize=12)
        ax.set_ylabel("Sample")
        ax.set_xlabel("")

        if len(matrix.index) <= 60:
            ax.set_yticks(range(len(matrix.index)))
            ax.set_yticklabels(matrix.index.tolist(), fontsize=7)
        else:
            tick_indices = np.linspace(0, len(matrix.index) - 1, 20, dtype=int)
            ax.set_yticks(tick_indices)
            ax.set_yticklabels([matrix.index[idx] for idx in tick_indices], fontsize=6)

        positions = [int(value) for value in matrix.columns.tolist()]
        self._set_heatmap_xticks(ax, positions, max_ticks=10)
        ax.axvline(0, color=BOUNDARY_COLOR, linewidth=0.8, linestyle="--", alpha=0.75)
        ax.axvline(self.cds_bin, color=BOUNDARY_COLOR, linewidth=0.8, linestyle="--", alpha=0.75)

        max_value = float(np.nanmax(matrix.to_numpy(dtype=float))) if matrix.size else 0.0
        image.set_clim(0, max_value if max_value > 0 else 1)
        heatmap_label = "Row-scaled " + self._density_axis_label() if self.scale == "row" else self._density_axis_label()
        cbar = fig.colorbar(image, cax=cbar_ax, orientation="horizontal")
        cbar.set_label(heatmap_label)

        self._draw_gene_structure(gene_ax)

        fig.savefig(out_pdf, bbox_inches="tight")
        fig.savefig(out_png, dpi=300, bbox_inches="tight")
        plt.close(fig)

        self.output_files["heatmap_pdf"] = out_pdf
        self.output_files["heatmap_png"] = out_png

    def draw_meta_gene_bar(self) -> None:
        """Draw per-sample percentage barplots of covered transcript bins."""
        if self.coverage is None:
            raise ValueError("Coverage has not been calculated yet.")

        percentage_tables = []

        for sample in self.sample_name:
            high_gene = self._get_high_expression_genes(sample)
            sample_percentage = []

            for region, bins in self._region_bins().items():
                if bins <= 0:
                    continue

                binned_df = self._build_binned_region_table(sample, region, high_gene)
                binned_df["Present"] = (binned_df["RawDensity"] > 0).astype(float)
                percentage = (
                    binned_df.groupby(["Sample", "Region", "Bin", "MetaPosition"], sort=False)["Present"]
                    .mean()
                    .mul(100.0)
                    .rename("Percentage")
                    .reset_index()
                )
                sample_percentage.append(percentage)
                percentage_tables.append(percentage)

            if not sample_percentage:
                continue

            sample_df = pd.concat(sample_percentage, axis=0, ignore_index=True).sort_values("MetaPosition")
            safe_sample = self._safe_name(sample)
            out_pdf = f"{self.output}_{safe_sample}_coverage_bar_plot.pdf"
            out_png = f"{self.output}_{safe_sample}_coverage_bar_plot.png"

            fig = plt.figure(figsize=(9.5, 5.6))
            grid = fig.add_gridspec(nrows=2, ncols=1, height_ratios=[4.2, 0.95], hspace=0.05)
            ax = fig.add_subplot(grid[0, 0])
            gene_ax = fig.add_subplot(grid[1, 0], sharex=ax)

            ax.bar(sample_df["MetaPosition"], sample_df["Percentage"], width=0.9, edgecolor="none")
            ax.set_title("Covered transcript percentage of {sample}".format(sample=sample), fontsize=12)
            ax.set_ylabel("Covered transcripts (%)")
            ax.set_ylim(0, 100)
            self._set_common_axis_style(ax)
            self._set_coverage_xticks(ax, max_ticks=10)
            plt.setp(ax.get_xticklabels(), visible=False)

            self._draw_gene_structure(gene_ax)

            fig.savefig(out_pdf, bbox_inches="tight")
            fig.savefig(out_png, dpi=300, bbox_inches="tight")
            plt.close(fig)

            self.output_files[f"{sample}_coverage_bar_pdf"] = out_pdf
            self.output_files[f"{sample}_coverage_bar_png"] = out_png

        if percentage_tables:
            percentage_df = pd.concat(percentage_tables, axis=0, ignore_index=True)
            out_txt = self.output + "_metagene_coverage_percentage.txt"
            percentage_df.to_csv(out_txt, sep="\t", index=False)
            self.output_files["coverage_percentage"] = out_txt

    def draw_gene_heatmap(self) -> None:
        """Draw optional per-sample transcript-by-position heatmaps."""
        for sample in self.sample_name:
            high_gene = self._get_high_expression_genes(sample)
            if len(high_gene) == 0:
                continue

            region_tables = []
            for region, bins in self._region_bins().items():
                if bins <= 0:
                    continue
                region_tables.append(self._build_binned_region_table(sample, region, high_gene))

            if not region_tables:
                continue

            gene_df = pd.concat(region_tables, axis=0, ignore_index=True)
            gene_df["PlotDensity"] = self._transform_density_values(gene_df["Density"]).to_numpy(dtype=float)
            matrix = gene_df.pivot_table(
                index="Transcript",
                columns="MetaPosition",
                values="PlotDensity",
                aggfunc="mean",
                fill_value=0,
            )
            matrix = matrix.reindex(columns=sorted(matrix.columns))

            # Transcript-level heatmaps are much easier to interpret after
            # row scaling and ordering by peak-position pattern.
            plot_matrix = self._row_minmax_scale(matrix)
            order_df = pd.DataFrame(
                {
                    "PeakPosition": plot_matrix.idxmax(axis=1),
                    "MeanSignal": plot_matrix.mean(axis=1),
                    "MaxSignal": plot_matrix.max(axis=1),
                },
                index=plot_matrix.index,
            ).sort_values(["PeakPosition", "MeanSignal", "MaxSignal"], ascending=[True, False, False])
            plot_matrix = plot_matrix.reindex(order_df.index)

            safe_sample = self._safe_name(sample)
            out_txt = f"{self.output}_{safe_sample}_gene_coverage_matrix.txt"
            out_pdf = f"{self.output}_{safe_sample}_gene_coverage_heatmap.pdf"
            out_png = f"{self.output}_{safe_sample}_gene_coverage_heatmap.png"
            matrix.to_csv(out_txt, sep="	", index=True)

            figure_height = min(max(5.8, len(plot_matrix.index) * 0.005 + 2.4), 18.0)
            fig = plt.figure(figsize=(10.8, figure_height))
            grid = fig.add_gridspec(
                nrows=2,
                ncols=1,
                height_ratios=[max(3.8, figure_height - 1.4), 0.95],
                hspace=0.04,
            )
            ax = fig.add_subplot(grid[0, 0])
            gene_ax = fig.add_subplot(grid[1, 0], sharex=ax)

            x_min, x_max = self._axis_range()
            image = ax.imshow(
                plot_matrix.to_numpy(dtype=float),
                aspect="auto",
                interpolation="nearest",
                cmap=HEATMAP_CMAP,
                vmin=0.0,
                vmax=1.0,
                extent=(x_min - 0.5, x_max + 0.5, len(plot_matrix.index) - 0.5, -0.5),
            )
            ax.set_title(
                "Transcript-level coverage heatmap: {sample} ({count:,} transcripts)".format(
                    sample=sample,
                    count=len(plot_matrix.index),
                ),
                fontsize=12,
            )
            ax.set_ylabel("Transcript")
            ax.set_yticks([])
            positions = [int(value) for value in plot_matrix.columns.tolist()]
            self._set_heatmap_xticks(ax, positions, max_ticks=10)
            ax.axvline(0, color=BOUNDARY_COLOR, linewidth=0.8, linestyle="--", alpha=0.75)
            ax.axvline(self.cds_bin, color=BOUNDARY_COLOR, linewidth=0.8, linestyle="--", alpha=0.75)
            fig.colorbar(image, ax=ax, shrink=0.72, pad=0.015).set_label(
                "Row-scaled " + self._density_axis_label()
            )

            self._draw_gene_structure(gene_ax)

            fig.savefig(out_pdf, bbox_inches="tight")
            fig.savefig(out_png, dpi=300, bbox_inches="tight")
            plt.close(fig)

            self.output_files[f"{sample}_gene_heatmap_table"] = out_txt
            self.output_files[f"{sample}_gene_heatmap_pdf"] = out_pdf
            self.output_files[f"{sample}_gene_heatmap_png"] = out_png

    def run(self, mode: str = "both", draw_barplot: bool = False, draw_gene_heatmap: bool = False) -> None:
        """Run the full coverage workflow."""
        self.import_rpf()
        self.calc_coverage()
        self.output_coverage()

        if mode in {"line", "both", "all"}:
            self.draw_meta_gene_line()
            self.draw_combined_line()
        if mode in {"heatmap", "both", "all"}:
            self.draw_heatmap()
        if draw_barplot or mode == "all":
            self.draw_meta_gene_bar()
        if draw_gene_heatmap:
            print("Warning: --gene-heatmap/--heat is deprecated and no transcript-level heatmap will be drawn.", flush=True)

        self.write_summary()
