#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Author: Rensc
# Date: 2026-06-24
# Version: 0.2.7.2
# Function: Provide RiboParser core functions for Digestion analysis.
# Input: Function parameters and intermediate RiboParser data objects.
# Output: Processed data objects or output files generated by module functions.

"""Digestion-site analysis utilities for RiboParser.

This module is used by ``rpf_Digest`` to inspect the codon-frame distribution
of read 5'-ends and 3'-ends and to summarize the nucleotide context around
digestion sites.

Main workflow
-------------
1. Import transcript annotation and transcript FASTA generated by
   ``rpf_Reference``.
2. Read BAM/SAM alignments.
3. Count read 5'-end and 3'-end frame distribution by RPF length.
4. Count A/C/G/T frequency around 5'-end and 3'-end digestion sites.
5. Output digestion-site frame table, heatmap, nucleotide counts, PWM, and
   sequence-logo figures.

"""

from __future__ import annotations

import os
import re
import sys
from collections import OrderedDict
from itertools import islice

import numpy as np
import pandas as pd
import pysam
from Bio import SeqIO

from .Ribo import Mrna


MOTIF_BASES = ("A", "C", "G", "T")
MOTIF_WINDOW = 16


class Ribo:
    """Core class for digestion-site analysis.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed arguments from ``rpf_Digest``.

    Attributes
    ----------
    mrna_file : str
        Transcript annotation file generated by ``rpf_Reference``.
    mrna_seq : str
        Transcript FASTA file generated by ``rpf_Reference``.
    mrna_dict : OrderedDict
        Transcript annotation dictionary.
    longest : bool
        Whether to retain representative transcripts only.
    bam : str
        BAM or SAM alignment file.
    min_length : int
        Minimum RPF length used for frame counting.
    max_length : int
        Maximum RPF length used for frame counting.
    motif_5end_counts : numpy.ndarray
        A/C/G/T counts around read 5'-end digestion sites.
    motif_3end_counts : numpy.ndarray
        A/C/G/T counts around read 3'-end digestion sites.
    """

    def __init__(self, args):
        self.mrna_file = args.transcript
        self.mrna_seq = args.sequence
        self.mrna_dict = OrderedDict()

        # Important bug fix:
        # Do not convert bool to string. ``str(False)`` is "False", and
        # non-empty strings are truthy in Python.
        self.longest = args.longest

        self.bam = args.bam
        self.sample_format = os.path.splitext(args.bam)[1]
        self.pysam_input = None

        self.min_length = args.min
        self.max_length = args.max

        self.profile = None
        self.rpf_start = None
        self.rpf_end = None

        # Kept for backward compatibility, but no longer used for large lists.
        self.align_left = []
        self.align_right = []

        self.motif_bases = MOTIF_BASES
        self.motif_window = MOTIF_WINDOW
        self.motif_base_index = {
            base: index for index, base in enumerate(self.motif_bases)
        }

        # Relative positions corresponding to the 16-nt motif windows.
        self.motif_5end_positions = list(range(-5, 11))
        self.motif_3end_positions = list(range(-10, 6))

        self.motif_5end_ticks = [-5, 0, 5, 10]
        self.motif_3end_ticks = [-10, -5, 0, 5]

        # Count matrices:
        # rows = A/C/G/T, columns = positions in the 16-nt window.
        self.motif_5end_counts = np.zeros(
            (len(self.motif_bases), self.motif_window),
            dtype=np.int64,
        )
        self.motif_3end_counts = np.zeros(
            (len(self.motif_bases), self.motif_window),
            dtype=np.int64,
        )

        # Position probability matrices:
        # rows = motif positions, columns = A/C/G/T.
        self.seqlogo_5end = None
        self.seqlogo_3end = None
        self.seqlogo_5end_pwm = None
        self.seqlogo_3end_pwm = None

        self.scaled = args.scale
        self.output = args.output

    # ------------------------------------------------------------------
    # Input readers
    # ------------------------------------------------------------------

    def read_transcript(self) -> None:
        """Import transcript sequences and transcript annotation.

        Returns
        -------
        None
            The function updates ``self.mrna_dict`` in place.

        Notes
        -----
        Legacy input information:

        - ``self.mrna_seq``: transcript FASTA generated by ``rpf_Reference``.
        - ``self.mrna_file``: transcript annotation generated by
          ``rpf_Reference``.

        Legacy return information:

        - ``self.mrna_dict``: transcript annotation dictionary.

        Workflow
        --------
        1. Import transcript sequences.
        2. Skip sequences containing characters outside A/T/G/C.
        3. Import transcript annotation.
        4. Optionally retain representative transcripts only.
        5. Match transcript IDs between annotation and FASTA.
        """
        record = SeqIO.parse(self.mrna_seq, "fasta")
        mrna_sequence = OrderedDict()

        for line in record:
            now_sequence = line.seq.upper()

            if re.search(r"[^ATGC]", str(now_sequence)):
                print(line.id, flush=True)
                print(now_sequence, flush=True)
                continue

            mrna_sequence[line.id] = now_sequence

        with open(self.mrna_file, "r", encoding="utf-8") as trans_file_in:
            for line in islice(trans_file_in, 1, None):
                line = line.strip()

                if not line:
                    continue

                transcript_record = line.split("\t")

                if self.longest and transcript_record[9] != "True":
                    continue

                self._add_transcript_record(
                    transcript_record=transcript_record,
                    mrna_sequence=mrna_sequence,
                )

    def _add_transcript_record(
        self,
        transcript_record: list[str],
        mrna_sequence: OrderedDict,
    ) -> None:
        """Add one transcript record to ``self.mrna_dict``.

        Parameters
        ----------
        transcript_record : list[str]
            One line from the normalized transcript TXT file.
        mrna_sequence : OrderedDict
            Dictionary of transcript sequences.

        Returns
        -------
        None
            The function updates ``self.mrna_dict`` in place.
        """
        now_mrna = Mrna(transcript_record)
        now_mrna.length = (
            now_mrna.utr5_length + now_mrna.utr3_length + now_mrna.cds_length
        )

        try:
            now_mrna.seq = mrna_sequence[now_mrna.transcript_id]
        except KeyError:
            return

        now_mrna.rpf = [0] * len(now_mrna.seq)
        self.mrna_dict[now_mrna.transcript_id] = now_mrna

    # ------------------------------------------------------------------
    # BAM/SAM parsing and digestion-site detection
    # ------------------------------------------------------------------

    def _get_alignment_mode(self) -> str:
        """Return pysam open mode according to input file suffix."""
        sample_format = self.sample_format.lower()

        if sample_format == ".bam":
            return "rb"

        if sample_format == ".sam":
            return "r"

        print("Unknown file format, please input the correct BAM or SAM file.", flush=True)
        sys.exit(1)

    def _init_rpf_frame_counts(self) -> tuple[dict[int, list[int]], dict[int, list[int]]]:
        """Initialize RPF frame count dictionaries.

        Returns
        -------
        tuple[dict[int, list[int]], dict[int, list[int]]]
            Empty frame count dictionaries for 5'-end and 3'-end.

        Notes
        -----
        The original implementation always kept the default display range
        ``20..100`` unless the user-specified range exceeded it. This behavior
        is preserved for output compatibility.
        """
        if self.min_length < 20 and self.max_length > 100:
            length_start = self.min_length
            length_end = self.max_length
        elif self.min_length < 20:
            length_start = self.min_length
            length_end = 100
        elif self.max_length > 100:
            length_start = 20
            length_end = self.max_length
        else:
            length_start = 20
            length_end = 100

        rpf_start = {
            read_length: [0, 0, 0]
            for read_length in range(length_start, length_end + 1)
        }
        rpf_end = {
            read_length: [0, 0, 0]
            for read_length in range(length_start, length_end + 1)
        }

        return rpf_start, rpf_end

    @staticmethod
    def _skip_alignment(read) -> bool:
        """Return whether one alignment record should be skipped."""
        if read.is_unmapped:
            return True

        if read.is_reverse:
            return True

        if read.is_secondary or read.is_supplementary:
            return True

        return False

    def get_digest_sites(self) -> None:
        """Detect digestion sites from the BAM/SAM alignment file.

        Returns
        -------
        None
            The function updates ``self.rpf_start``, ``self.rpf_end``,
            ``self.motif_5end_counts``, and ``self.motif_3end_counts``.

        Notes
        -----
        Speed optimization:

        1. Skip invalid alignments before calling expensive methods.
        2. Count motif windows directly instead of storing every sequence.
        3. Preserve frame-count output range behavior from the legacy code.
        """
        read_mode = self._get_alignment_mode()
        rpf_start, rpf_end = self._init_rpf_frame_counts()

        with pysam.AlignmentFile(self.bam, read_mode) as bam_in:
            self.pysam_input = bam_in

            for read in bam_in.fetch(until_eof=True):
                if self._skip_alignment(read):
                    continue

                transcript_id = read.reference_name
                mrna = self.mrna_dict.get(transcript_id)

                if mrna is None:
                    continue

                read_length = read.infer_read_length()

                if read_length is None:
                    continue

                blocks = read.get_blocks()

                if not blocks:
                    continue

                map_start, map_end = blocks[0]

                # Preserve the legacy behavior:
                # motif windows are counted for all retained transcript-mapped
                # reads, while frame distribution is restricted by min/max.
                self._count_motif_windows(
                    mrna=mrna,
                    map_start=map_start,
                    map_end=map_end,
                )

                if not (self.min_length <= read_length <= self.max_length):
                    continue

                if read_length not in rpf_start:
                    continue

                frame_start = (map_start - mrna.utr5_length) % 3
                frame_end = (map_end - 1 - mrna.utr5_length) % 3

                rpf_start[read_length][frame_start] += 1
                rpf_end[read_length][frame_end] += 1

        self.pysam_input = None
        self.rpf_start = pd.DataFrame(rpf_start).T
        self.rpf_end = pd.DataFrame(rpf_end).T

    def _count_motif_windows(self, mrna: Mrna, map_start: int, map_end: int) -> None:
        """Count 5'-end and 3'-end motif windows for one read.

        Parameters
        ----------
        mrna : Mrna
            Transcript annotation object.
        map_start : int
            Read alignment start in transcript coordinates.
        map_end : int
            Read alignment end in transcript coordinates.

        Returns
        -------
        None
            The function updates motif count matrices in place.

        Notes
        -----
        Window definitions preserve the legacy slicing logic:

        - 5'-end window: ``[map_start - 5, map_start + 11)``
        - 3'-end window: ``[map_end - 10, map_end + 6)``
        """
        mrna_length = mrna.length
        mrna_seq = mrna.seq

        left_start = map_start - 5
        left_end = map_start + 11

        if left_start >= 0 and left_end <= mrna_length:
            self._add_motif_window(
                window=mrna_seq[left_start:left_end],
                counts=self.motif_5end_counts,
            )

        right_start = map_end - 10
        right_end = map_end + 6

        if right_start >= 0 and right_end <= mrna_length:
            self._add_motif_window(
                window=mrna_seq[right_start:right_end],
                counts=self.motif_3end_counts,
            )

    def _add_motif_window(self, window, counts: np.ndarray) -> None:
        """Add one 16-nt motif window to an A/C/G/T count matrix.

        Parameters
        ----------
        window : Bio.Seq.Seq or str
            Motif window sequence.
        counts : numpy.ndarray
            Motif count matrix to update.

        Returns
        -------
        None
            The function updates ``counts`` in place.

        Notes
        -----
        If the window contains characters outside A/C/G/T, the whole window is
        skipped. This is consistent with the transcript-level sequence filter.
        """
        window = str(window).upper()

        if len(window) != self.motif_window:
            return

        for position, base in enumerate(window):
            base_index = self.motif_base_index.get(base)

            if base_index is None:
                return

            counts[base_index, position] += 1

    # ------------------------------------------------------------------
    # Output digestion-site frame table
    # ------------------------------------------------------------------

    def output_digest_sites(self) -> None:
        """Output 5'-end and 3'-end frame counts by RPF length."""
        psite_merge = pd.concat([self.rpf_start, self.rpf_end], join="outer", axis=1)
        psite_merge.fillna(0, inplace=True)

        psite_merge.columns = [
            "5end_frame1",
            "5end_frame2",
            "5end_frame3",
            "3end_frame1",
            "3end_frame2",
            "3end_frame3",
        ]
        psite_merge.index.name = "length"

        psite_merge.to_csv(
            self.output + "_digestion_sites.txt",
            sep="\t",
            index=True,
        )

    # ------------------------------------------------------------------
    # Plot digestion-site heatmap
    # ------------------------------------------------------------------

    def digestion_plot(self) -> None:
        """Draw the heatmap of digestion-site frame distribution.

        Returns
        -------
        None
            The function writes a PDF figure.

        Notes
        -----
        ``matplotlib.use("Agg")`` is called before importing pyplot so the
        function works on servers without a graphical display.
        """
        import matplotlib

        matplotlib.use("Agg")

        import matplotlib.pyplot as plt
        import seaborn as sns

        if self.scaled:
            out_pdf = self.output + "_scaled_digestion_sites_plot.pdf"

            psite_start_norm = self.rpf_start.sub(self.rpf_start.mean(axis=1), axis=0)
            psite_start_norm_row = psite_start_norm.div(
                psite_start_norm.std(axis=1),
                axis=0,
            )
            psite_start_norm_row.fillna(0, inplace=True)

            psite_end_norm = self.rpf_end.sub(self.rpf_end.mean(axis=1), axis=0)
            psite_end_norm_row = psite_end_norm.div(
                psite_end_norm.std(axis=1),
                axis=0,
            )
            psite_end_norm_row.fillna(0, inplace=True)

            now_cmap = "Blues"

        else:
            out_pdf = self.output + "_digestion_sites_plot.pdf"
            psite_start_norm_row = self.rpf_start.copy()
            psite_end_norm_row = self.rpf_end.copy()
            now_cmap = "RdYlBu_r"

        codon_frame_5end = pd.DataFrame(
            self.rpf_start.loc[self.min_length : self.max_length].sum(axis=0)
        ).T
        codon_frame_3end = pd.DataFrame(
            self.rpf_end.loc[self.min_length : self.max_length].sum(axis=0)
        ).T

        rpfs_count_5end = (
            pd.DataFrame(self.rpf_start.sum(axis=1))
            .loc[self.min_length : self.max_length]
            .T
        )
        rpfs_count_3end = (
            pd.DataFrame(self.rpf_end.sum(axis=1))
            .loc[self.min_length : self.max_length]
            .T
        )

        fig = plt.figure(figsize=(12, 10), dpi=300)

        ax1 = plt.subplot2grid((5, 6), (0, 0), rowspan=1, colspan=2)
        sns.barplot(data=codon_frame_5end, color="#388e70", alpha=0.6, ax=ax1)
        ax1.tick_params(labelbottom=False)
        ax1.yaxis.set_ticks_position("right")
        ax1.set_ylabel("RPFs counts")
        ax1.set_title("5'-end")

        cbar_ax1 = fig.add_axes([0.43, 0.75, 0.01, 0.12])

        ax2 = plt.subplot2grid((5, 6), (1, 0), rowspan=4, colspan=2)
        sns.heatmap(
            data=psite_start_norm_row.loc[self.min_length : self.max_length],
            annot=None,
            linewidths=0.5,
            ax=ax2,
            cmap=now_cmap,
            cbar_ax=cbar_ax1,
        )
        label_y = ax2.get_yticklabels()
        plt.setp(label_y, rotation=0, horizontalalignment="right")
        ax2.set_ylabel("RPF length")
        ax2.set_xlabel("Codon frame")

        ax3 = plt.subplot2grid((5, 6), (1, 2), rowspan=4, colspan=1)
        sns.barplot(
            data=rpfs_count_5end,
            color="#388e70",
            alpha=0.6,
            ax=ax3,
            orient="h",
        )
        ax3.tick_params(bottom=True, top=False, left=False, right=False)
        ax3.set_yticklabels([])
        plt.xticks(rotation=60)
        ax3.set_xlabel("RPFs count")

        ax4 = plt.subplot2grid((5, 6), (0, 3), rowspan=1, colspan=2)
        sns.barplot(data=codon_frame_3end, color="#388e70", alpha=0.6, ax=ax4)
        ax4.tick_params(labelbottom=False)
        ax4.yaxis.set_ticks_position("right")
        ax4.set_title("3'-end")

        cbar_ax2 = fig.add_axes([0.83, 0.75, 0.01, 0.12])

        ax5 = plt.subplot2grid((5, 6), (1, 3), rowspan=4, colspan=2)
        sns.heatmap(
            data=psite_end_norm_row.loc[self.min_length : self.max_length],
            annot=None,
            linewidths=0.5,
            ax=ax5,
            cmap=now_cmap,
            cbar_ax=cbar_ax2,
        )
        ax5.set_yticklabels([])
        ax5.set_xlabel("Codon frame")

        ax6 = plt.subplot2grid((5, 6), (1, 5), rowspan=4, colspan=1)
        sns.barplot(
            data=rpfs_count_3end,
            color="#388e70",
            alpha=0.6,
            ax=ax6,
            orient="h",
        )
        ax6.yaxis.set_ticks_position("right")
        plt.xticks(rotation=60)
        ax6.set_xlabel("RPFs count")

        fig.savefig(fname=out_pdf)
        plt.close(fig)

    # ------------------------------------------------------------------
    # Output motif count and PWM tables
    # ------------------------------------------------------------------

    def output_counts(self) -> None:
        """Output nucleotide counts and PWM for digestion-site motif windows.

        Returns
        -------
        None
            The function writes four TXT files:

            - ``*_5end_counts.txt``
            - ``*_5end_pwm.txt``
            - ``*_3end_counts.txt``
            - ``*_3end_pwm.txt``

        Notes
        -----
        The output table index uses real relative positions instead of
        ``0..15``:

        - 5'-end: ``-5..10``
        - 3'-end: ``-10..5``
        """
        counts_5end = self._counts_to_dataframe(
            counts=self.motif_5end_counts,
            position_labels=self.motif_5end_positions,
        )
        pwm_5end = self._counts_to_pwm_dataframe(
            counts=self.motif_5end_counts,
            position_labels=self.motif_5end_positions,
        )

        counts_5end.to_csv(
            self.output + "_5end_counts.txt",
            sep="\t",
            index=True,
        )
        pwm_5end.to_csv(
            self.output + "_5end_pwm.txt",
            sep="\t",
            index=True,
        )

        counts_3end = self._counts_to_dataframe(
            counts=self.motif_3end_counts,
            position_labels=self.motif_3end_positions,
        )
        pwm_3end = self._counts_to_pwm_dataframe(
            counts=self.motif_3end_counts,
            position_labels=self.motif_3end_positions,
        )

        counts_3end.to_csv(
            self.output + "_3end_counts.txt",
            sep="\t",
            index=True,
        )
        pwm_3end.to_csv(
            self.output + "_3end_pwm.txt",
            sep="\t",
            index=True,
        )

        # Matrix shape for logo:
        # rows = motif positions, columns = A/C/G/T.
        self.seqlogo_5end_pwm = pwm_5end.to_numpy()
        self.seqlogo_3end_pwm = pwm_3end.to_numpy()

        # Backward-compatible aliases.
        self.seqlogo_5end = self.seqlogo_5end_pwm
        self.seqlogo_3end = self.seqlogo_3end_pwm

    def _counts_to_dataframe(
        self,
        counts: np.ndarray,
        position_labels: list[int],
    ) -> pd.DataFrame:
        """Convert A/C/G/T count matrix to a dataframe.

        Parameters
        ----------
        counts : numpy.ndarray
            Count matrix with shape ``4 x motif_window``.
        position_labels : list[int]
            Relative motif positions shown as dataframe index.

        Returns
        -------
        pandas.DataFrame
            Rows are motif positions and columns are A/C/G/T.
        """
        return pd.DataFrame(
            counts.T,
            columns=self.motif_bases,
            index=position_labels,
        )

    def _counts_to_pwm_dataframe(
        self,
        counts: np.ndarray,
        position_labels: list[int],
    ) -> pd.DataFrame:
        """Convert A/C/G/T counts to a position probability matrix.

        Parameters
        ----------
        counts : numpy.ndarray
            Count matrix with shape ``4 x motif_window``.
        position_labels : list[int]
            Relative motif positions shown as dataframe index.

        Returns
        -------
        pandas.DataFrame
            Position probability matrix. Rows are motif positions and columns
            are A/C/G/T.
        """
        column_sums = counts.sum(axis=0)

        pwm = np.divide(
            counts,
            column_sums,
            out=np.zeros_like(counts, dtype=float),
            where=column_sums != 0,
        )

        return pd.DataFrame(
            pwm.T,
            columns=self.motif_bases,
            index=position_labels,
        )

    # ------------------------------------------------------------------
    # Sequence logo drawing without seqlogo dependency
    # ------------------------------------------------------------------

    def _ensure_pwm_matrices(self) -> None:
        """Ensure PWM matrices are available before drawing sequence logos."""
        if self.seqlogo_5end_pwm is None or self.seqlogo_3end_pwm is None:
            self.output_counts()

    @staticmethod
    def _get_logo_base_colors() -> dict[str, str]:
        """Return nucleotide colors used in sequence-logo figures.

        Returns
        -------
        dict[str, str]
            Mapping from nucleotide base to color.
        """
        return {
            "A": "#4daf4a",
            "C": "#377eb8",
            "G": "#ff7f00",
            "T": "#e41a1c",
        }

    def _draw_logo_letter(
        self,
        ax,
        letter: str,
        x_position: int,
        y_position: float,
        height: float,
        color: str,
    ) -> None:
        """Draw one nucleotide letter in a sequence logo.

        Parameters
        ----------
        ax : matplotlib.axes.Axes
            Target matplotlib axis.
        letter : str
            Nucleotide letter.
        x_position : int
            Position index on the x-axis.
        y_position : float
            Bottom y-position of the letter.
        height : float
            Letter height.
        color : str
            Letter color.

        Returns
        -------
        None
            The function adds one patch to the axis.
        """
        if height <= 0:
            return

        from matplotlib import transforms
        from matplotlib.font_manager import FontProperties
        from matplotlib.patches import PathPatch
        from matplotlib.textpath import TextPath

        font_property = FontProperties(family="DejaVu Sans", weight="bold")
        text_path = TextPath((0, 0), letter, size=1, prop=font_property)
        text_box = text_path.get_extents()

        if text_box.width == 0 or text_box.height == 0:
            return

        scale_x = 0.85 / text_box.width
        scale_y = height / text_box.height

        transform = (
            transforms.Affine2D()
            .scale(scale_x, scale_y)
            .translate(x_position - 0.425, y_position)
        )

        patch = PathPatch(
            text_path,
            transform=transform + ax.transData,
            facecolor=color,
            edgecolor="none",
        )
        ax.add_patch(patch)

    def _write_seqlogo(
        self,
        pwm: np.ndarray,
        filename: str,
        position_labels: list[int],
        tick_labels: list[int],
        title: str,
    ) -> None:
        """Write one sequence-logo PDF using matplotlib only.

        Parameters
        ----------
        pwm : numpy.ndarray
            Position probability matrix. Rows are positions and columns are
            A/C/G/T.
        filename : str
            Output PDF filename.
        position_labels : list[int]
            Relative position labels for every motif position.
        tick_labels : list[int]
            Relative positions shown on x-axis.
        title : str
            Plot title.

        Returns
        -------
        None
            The function writes one PDF file.
        """
        import matplotlib

        matplotlib.use("Agg")

        import matplotlib.pyplot as plt

        base_colors = self._get_logo_base_colors()

        fig, ax = plt.subplots(figsize=(6, 2.8), dpi=300)

        for x_index, row in enumerate(pwm):
            y_position = 0.0

            # Draw smaller letters first and larger letters later, so the
            # larger letters are stacked above smaller letters.
            base_heights = sorted(
                zip(self.motif_bases, row),
                key=lambda item: item[1],
            )

            for base, height in base_heights:
                self._draw_logo_letter(
                    ax=ax,
                    letter=base,
                    x_position=x_index,
                    y_position=y_position,
                    height=float(height),
                    color=base_colors.get(base, "black"),
                )
                y_position += float(height)

        tick_positions = [
            position_labels.index(tick)
            for tick in tick_labels
            if tick in position_labels
        ]

        ax.set_xlim(-0.5, len(position_labels) - 0.5)
        ax.set_ylim(0, 1.05)

        ax.set_xticks(tick_positions)
        ax.set_xticklabels([str(position_labels[pos]) for pos in tick_positions])

        ax.set_xlabel("Position relative to digestion site")
        ax.set_ylabel("Probability")
        ax.set_title(title)

        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)

        fig.tight_layout()
        fig.savefig(filename)
        plt.close(fig)

    def seq_logo_plot(self) -> None:
        """Draw sequence logos with legacy output filenames.

        Returns
        -------
        None
            The function writes two PDF files:

            - ``*_5end_seqlogo.pdf``
            - ``*_3end_seqlogo.pdf``

        Notes
        -----
        The method name is preserved for compatibility, but this function no
        longer uses the external ``seqlogo`` package.
        """
        self._ensure_pwm_matrices()

        self._write_seqlogo(
            pwm=self.seqlogo_5end_pwm,
            filename=self.output + "_5end_seqlogo.pdf",
            position_labels=self.motif_5end_positions,
            tick_labels=self.motif_5end_ticks,
            title="5'-end digestion motif",
        )
        self._write_seqlogo(
            pwm=self.seqlogo_3end_pwm,
            filename=self.output + "_3end_seqlogo.pdf",
            position_labels=self.motif_3end_positions,
            tick_labels=self.motif_3end_ticks,
            title="3'-end digestion motif",
        )

    def seq_logo_plot2(self) -> None:
        """Draw sequence logos with current output filenames.

        Returns
        -------
        None
            The function writes two PDF files:

            - ``*_5end_seqlogo2.pdf``
            - ``*_3end_seqlogo2.pdf``

        Notes
        -----
        The original code called ``seqlogo.seqlogo`` twice for the same 5'-end
        logo and twice for the same 3'-end logo. This version writes each logo
        once and does not require the external ``seqlogo`` package.
        """
        self._ensure_pwm_matrices()

        self._write_seqlogo(
            pwm=self.seqlogo_5end_pwm,
            filename=self.output + "_5end_seqlogo2.pdf",
            position_labels=self.motif_5end_positions,
            tick_labels=self.motif_5end_ticks,
            title="5'-end digestion motif",
        )
        self._write_seqlogo(
            pwm=self.seqlogo_3end_pwm,
            filename=self.output + "_3end_seqlogo2.pdf",
            position_labels=self.motif_3end_positions,
            tick_labels=self.motif_3end_ticks,
            title="3'-end digestion motif",
        )
