#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-06-12
# Version: 0.2.7
# Function: Provide RiboParser core functions for GenePred analysis.
# Input: Function parameters and intermediate RiboParser data objects.
# Output: Processed data objects or output files generated by module functions.


import os
import subprocess
import sys
from collections import OrderedDict

import numpy as np
import pandas as pd
from Bio import SeqIO
from Bio import Seq


class Chrom(object):

    def __init__(self, line):
        self.attr = line.description
        self.chromosome = str(line.id)
        self.start = 1
        self.end = len(line.seq)
        self.seq = line.seq


class GenePred(object):
    def __init__(self, args):
        self.gene = OrderedDict()
        self.gtf = args.gtf
        self.gtf_format = os.path.splitext(self.gtf)[-1]
        self.gp_df = None
        self.columns = ['name', 'chrom', 'strand', 'txStart', 'txEnd', 'cdsStart', 'cdsEnd', 'exonCount',
                        'exonStarts', 'exonEnds', 'score', 'name2', 'cdsStartStat', 'cdsEndStat',
                        'exonFrames']
        self.coding = args.coding
        self.longest = args.longest
        self.utr = args.utr

        # genome file
        self.fasta = args.genome
        self.chroms_dict = OrderedDict()
        self.mrna_seq = OrderedDict()
        self.cds_seq = OrderedDict()

        # output file
        self.out_prefix = args.output
        self.whole = args.whole
        self.gp_file = self.out_prefix + '.genepred'
        self.gtf_new = self.out_prefix + '.norm.gtf'
        self.whole_file = self.out_prefix + '.whole.txt'
        self.txt_file = self.out_prefix + '.norm.txt'
        self.rna_file = self.out_prefix + '.norm.rna.fa'
        self.cds_file = self.out_prefix + '.norm.cds.fa'

    def gtf2gp(self):
        """Function to convert the gtf to genepred.

        Returns
        -------
        None
            The function updates internal state or writes output files in place.

        Notes
        -----
        Legacy input information:
        - ``self.gtf_format``: format of the gtf file.
        - ``self.gtf``: gtf file.
        - ``self.gp_file``: genepred file.

        Legacy return information:
        - ``output``: description.

        Workflow
        --------
        1. Check the gff3ToGenePred and gtfToGenePred in the current environment.
        2. Convert the gtf or gff to genepred.
        """
        
        script_path = os.path.split((os.path.abspath(sys.argv[0])))[0]
        nowpath = os.path.dirname(script_path)
        if self.gtf_format in ['.gff', '.gff3']:
            gff3ToGenePred = subprocess.run(['which', 'gff3ToGenePred'], capture_output=True, text=True)
            if gff3ToGenePred.returncode == 0:
                run_tmp = subprocess.run(['gff3ToGenePred', '-warnAndContinue', '-rnaNameAttr=attr',
                                        '-geneNameAttr=attr', self.gtf, self.gp_file])
            else:
                print('{0} not found in current environment.\n'.format('gff3ToGenePred'), flush=True)
                sys.exit(1)

        elif self.gtf_format == '.gtf':
            gtfToGenePred = subprocess.run(['which', 'gtfToGenePred'], capture_output=True, text=True)
            if gtfToGenePred.returncode == 0:
                run_tmp = subprocess.run(['gtfToGenePred', '-allErrors', '-genePredExt',
                                        '-ignoreGroupsWithoutExons', self.gtf, self.gp_file])
            else:
                print('{0} not found in current environment.\n'.format('gtfToGenePred'), flush=True)
                sys.exit(1)
        else:
            print('Unknown file format {0}.\n'.format(self.gtf_format),)
            print('Please input annotation file in GTF or GFF format.\n', flush=True)
            sys.exit(1)

    def gp2gtf(self):
        """Function to convert the genepred to gtf file.

        Returns
        -------
        None
            The function updates internal state or writes output files in place.

        Notes
        -----
        Legacy input information:
        - ``self.gp_file``: genepred file.
        - ``self.gtf_new``: new gtf file.

        Legacy return information:
        - ``output``: genePred file.

        Workflow
        --------
        1. Check the genePredToGtf in the current environment.
        2. Convert the genepred to gtf.
        """
        
        # script_path = os.path.split((os.path.abspath(sys.argv[0])))[0]
        # nowpath = os.path.dirname(script_path)

        genePredToGtf = subprocess.run(['which', 'genePredToGtf'], capture_output=True, text=True)

        if genePredToGtf.returncode == 0:
            run_tmp = subprocess.run(['genePredToGtf', 'file', '-utr', '-honorCdsStat',
                                      '-source=ribo', self.gp_file, self.gtf_new])
        else:
            print('{0} not found in current environment.\n'.format('genePredToGtf'), flush=True)
            sys.exit(1)
        # os.remove(self.gp_file)

    def read_genepred(self):
        """Function import the parser the genepred file.

        Returns
        -------
        None
            The function updates internal state or writes output files in place.

        Notes
        -----
        Legacy input information:
        - ``self.gp_file``: gene pred file derived from gtf file.

        Legacy return information:
        - ``self.gp_df``: dataframe of the genepred file.

        Workflow
        --------
        1. Read the genepred file and rename the columns.
        2. Calculate the utr5, cds and utr3 length.
        """

        self.gp_df = pd.read_csv(self.gp_file, sep="\t", header=None)
        os.remove(self.gp_file)

        self.gp_df.columns = self.columns
        
        utr5_list = []
        cds_list = []
        utr3_list = []

        print("Import gtf annotation.", flush=True)

        for idx, row in self.gp_df.iterrows():

            if idx % 1000 == 0:
                print(f"rows: {idx}", flush=True)

            if row.cdsStartStat == "none" or row.cdsEndStat == "none":
                utr5_list.append(0)
                cds_list.append(0)
                utr3_list.append(0)
                continue

            exon_starts = np.fromstring(row.exonStarts, sep=",", dtype=int)
            exon_ends   = np.fromstring(row.exonEnds, sep=",", dtype=int)

            cds_start = row.cdsStart
            cds_end   = row.cdsEnd

            utr5_length = 0
            cds_length = 0
            utr3_length = 0

            for exon_start, exon_end in zip(exon_starts, exon_ends):
                utr5_length += max(0, min(exon_end, cds_start) - exon_start)
                cds_length += max(0, min(exon_end, cds_end) - max(exon_start, cds_start))
                utr3_length += max(0, exon_end - max(exon_start, cds_end))

            if row.strand == "-":
                utr5_length, utr3_length = utr3_length, utr5_length

            utr5_list.append(utr5_length)
            cds_list.append(cds_length)
            utr3_list.append(utr3_length)

        print('rows: ' + str(idx), flush=True)

        self.gp_df["utr5_length"] = utr5_list
        self.gp_df["cds_length"] = cds_list
        self.gp_df["utr3_length"] = utr3_list


    def get_rep_transcript_bak(self):
        """Function to filter the representative transcripts.

        Returns
        -------
        object
            dataframe of the genepred file with annotated column [rep_transcript].

        Notes
        -----
        Legacy input information:
        - ``self.gp_df``: dataframe of the genepred file.

        Workflow
        --------
        1. Group the dataframe by gene name.
        2. Label the max cds length.
        3. Label the max utr5 + cds + utr3 length.
        4. Label the first transcript.
        5. Add the flag of representative transcript.
        - @Note     : low efficiency of this mothod to label the representative
        transcript.
        """
        
        print('Filter representative transcripts.', flush=True)

        counter = 0
        def add_true_flag(group):

            nonlocal counter
            counter += 1
            if counter % 500 == 0:
                print('Representative gene: ' + str(counter), flush=True)

            if len(group) == 1:
                group['rep_transcript'] = True
                return group
            
            else:
                max_cds_length = group['cds_length'].max()
                max_utr5_cds_utr3 = group.loc[group['cds_length'] == max_cds_length, ['utr5_length', 'cds_length', 'utr3_length']].sum(axis=1).max()

                max_cds_index = group.loc[group['cds_length'] == max_cds_length].index
                max_utr5_cds_utr3_index = group.loc[group['utr5_length'] + group['cds_length'] + group['utr3_length'] == max_utr5_cds_utr3].index

                if len(max_cds_index) == 1:
                    group.loc[max_cds_index, 'rep_transcript'] = True
                elif len(max_utr5_cds_utr3_index) == 1:
                    group.loc[max_utr5_cds_utr3_index, 'rep_transcript'] = True
                else:
                    group.loc[max_cds_index[0], 'rep_transcript'] = True
                return group

        self.gp_df['rep_transcript'] = False
        self.gp_df = self.gp_df.groupby('name2').apply(add_true_flag)
        print('Representative gene: ' + str(counter), flush=True)

        # print(self.gp_df)

    def get_rep_transcript(self):
        """Function to filter the representative transcripts.

        Returns
        -------
        None
            The function updates internal state or writes output files in place.

        Notes
        -----
        Legacy input information:
        - ``self.gp_df``: dataframe of the genepred file.

        Legacy return information:
        - ``self.gp_df``: dataframe of the genepred file with annotated column
        [rep_transcript].

        Workflow
        --------
        1. Calculate the gene length, length = cds_length + utr5_length + utr3_length.
        2. Sort the dataframe by gene name, cds length, gene length, utr5 length and
        utr3 length.
        3. Reset the index of the dataframe.
        4. Group the dataframe by gene name and label the max cds length and max gene
        length.
        5. Label the first transcript.
        6. Reset the index of the dataframe.
        """

        print('Filter representative transcripts.', flush=True)

        self.gp_df['gene_length'] = self.gp_df['cds_length'] + self.gp_df['utr5_length'] + self.gp_df['utr3_length']
        self.gp_df = self.gp_df.sort_values(by=['name2', 'cds_length', 'gene_length', 'utr5_length', 'utr3_length'], 
                                            ascending=[False, False, False, False, False])

        self.gp_df.reset_index(drop=True, inplace=True)
        self.gp_df['rep_transcript'] = False
        self.gp_df.loc[self.gp_df.groupby('name2').head(1).index, 'rep_transcript'] = True
        self.gp_df.sort_values(by=['chrom', 'txStart', 'name2', 'rep_transcript'], 
                               ascending=[True, True, True, False],
                               inplace=True)
        self.gp_df.reset_index(drop=True, inplace=True)

    def add_utr(self):
        """Function to add the pseudo utr.

        Returns
        -------
        None
            The function updates internal state or writes output files in place.

        Notes
        -----
        Legacy input information:
        - ``self.gp_df``: dataframe of the genepred file.

        Legacy return information:
        - ``self.gp_df``: dataframe of the genepred file with annotated column
        [modified].

        Workflow
        --------
        1. Create the list to store the new exon starts and ends.
        2. Skip the transcript without cds.
        3. Calculate the new exon start site to extend the utr5.
        4. Calculate the new exon end site to extend the utr3.
        5. Add the pseudo utr to the transcript.
        """
        
        exonStarts_list, exonEnds_list = [], []
        txStart_list, txEnd_list = [], []
        utr5_list, utr3_list = [], []

        self.gp_df.loc[:, 'modified'] = 'False'

        # add pseudo utr
        if self.utr == 0:
            pass

        else:
            print('Add pseudo UTR.', flush=True)

            for idx, rows in self.gp_df.iterrows():
                if idx % 1000 == 0:
                    print('rows: ' + str(idx), flush=True)

                # skip the transcript without cds
                if rows['cdsStartStat'] == 'none' or rows['cdsEndStat'] == 'none':
                    exonStarts_list.append(rows.exonStarts)
                    exonEnds_list.append(rows.exonEnds)
                    txStart_list.append(rows.txStart)
                    txEnd_list.append(rows.txEnd)
                    utr5_list.append(rows.utr5_length)
                    utr3_list.append(rows.utr3_length)
                    continue

                # check exon starts for each genes
                exonStarts = rows['exonStarts'].split(',')[:-1]
                
                if int(rows['utr5_length']) >= self.utr:
                    # skip the transcript with utr5 length >= self.utr
                    exonStarts_list.append(rows.exonStarts)
                    txStart_list.append(rows.txStart)
                    utr5_list.append(rows.utr5_length)

                else:
                    # calculate the new exon start site to extend the utr5
                    new_start = int(exonStarts[0]) - self.utr

                    if new_start < 0:
                        # set the negative new start site to 0, since the chromosome start site can not be negative
                        exonStarts[0] = '0'
                        exonStarts_list.append(','.join(exonStarts) + ',')
                        txStart_list.append(0)
                        utr5_list.append(rows['cdsStart'])
                        self.gp_df.loc[idx, 'modified'] = 'True'
                    else:
                        # set the new start site to new_start
                        exonStarts[0] = str(new_start)
                        exonStarts_list.append(','.join(exonStarts) + ',')
                        txStart_list.append(rows.txStart - self.utr)
                        utr5_list.append(rows.utr5_length + self.utr)
                        self.gp_df.loc[idx, 'modified'] = 'True'

                # check exon ends for each genes
                exonEnds = rows['exonEnds'].split(',')[:-1]

                if int(rows['utr3_length']) >= self.utr:
                    # skip the transcript with utr3 length >= self.utr
                    exonEnds_list.append(rows.exonEnds)
                    txEnd_list.append(rows.txEnd)
                    utr3_list.append(rows.utr3_length)
                else:
                    # calculate the new exon end site to extend the utr3
                    new_end = int(exonEnds[-1]) + self.utr

                    if new_end > self.chroms_dict[str(rows['chrom'])].end:
                        # set the new end site to chromosome end site, since the chromosome end site can not be larger than the chromosome end site
                        exonEnds[-1] = str(self.chroms_dict[str(rows['chrom'])].end)
                        exonEnds_list.append(','.join(exonEnds) + ',')
                        txEnd_list.append(self.chroms_dict[str(rows['chrom'])].end)
                        utr3_list.append(rows.utr3_length + self.chroms_dict[str(rows['chrom'])].end - rows['cdsEnd'])
                        self.gp_df.loc[idx, 'modified'] = 'True'
                    else:
                        # set the new end site to new_end
                        exonEnds[-1] = str(new_end)
                        exonEnds_list.append(','.join(exonEnds) + ',')
                        txEnd_list.append(new_end)
                        utr3_list.append(rows.utr3_length + self.utr)
                        self.gp_df.loc[idx, 'modified'] = 'True'

            self.gp_df['exonStarts'] = exonStarts_list
            self.gp_df['exonEnds'] = exonEnds_list
            self.gp_df['txStart'] = txStart_list
            self.gp_df['txEnd'] = txEnd_list
            self.gp_df['utr5_length'] = utr5_list
            self.gp_df['utr3_length'] = utr3_list


    def remove_duplicate(self):
        """Function to remove the duplicate transcripts.

        Returns
        -------
        None
            The function updates internal state or writes output files in place.

        Notes
        -----
        Legacy input information:
        - ``self.gp_df``: dataframe of the genepred file.

        Legacy return information:
        - ``self.gp_df``: dataframe of the genepred file with removed duplicate
        transcripts.

        Workflow
        --------
        1. Drop the duplicate transcripts by name2 and strand.
        """
        
        print('Remove duplicate transcripts.', flush=True)
        self.gp_df.drop_duplicates(subset=['transcript_id'], inplace=True)
        self.gp_df.reset_index(drop=True, inplace=True)


    def read_genome(self):
        """Function import the genome sequences.

        Returns
        -------
        None
            The function updates internal state or writes output files in place.

        Notes
        -----
        Legacy input information:
        - ``self.fasta``: genome file.

        Legacy return information:
        - ``self.chroms_dict``: dictionary of the chromosome sequences.

        Workflow
        --------
        1. Read the genome file with SeqIO.
        2. Store the chromosome sequences in the dictionary.
        """
        
        record = SeqIO.parse(self.fasta, "fasta")

        for line in record:
            print("import chromosome: {chrom}".format(chrom=line.id), flush=True)
            self.chroms_dict[str(line.id)] = Chrom(line)


    def get_seq(self):
        """Function to retrieve the mRNA sequences.

        Returns
        -------
        None
            The function updates internal state or writes output files in place.

        Notes
        -----
        Legacy input information:
        - ``self.gp_df``: dataframe of the genepred file.

        Legacy return information:
        - ``self.mrna_seq``: dictionary of the mRNA sequences.

        Workflow
        --------
        1. Iterate the dataframe to get the mRNA sequences.
        2. Store the mRNA sequences in the dictionary.
        3. Store the cds sequences in the dictionary.
        """

        for idx, rows in self.gp_df.iterrows():

            # skip the transcript without cds
            if rows['cds_length'] == 0:
                continue

            chromesome = str(rows['chrom'])
            rna = list(zip(rows.exonStarts.split(',')[:-1], rows.exonEnds.split(',')[:-1]))
            tmp_rna_seq = Seq.Seq('')

            if rows['strand'] == "-":
                for exon in rna:
                    exon_start, exon_end = int(exon[0]), int(exon[1])
                    tmp_rna_seq += self.chroms_dict[chromesome].seq[exon_start: exon_end]
                tmp_rna_seq = tmp_rna_seq.reverse_complement()

            else:
                for exon in rna:
                    exon_start, exon_end = int(exon[0]), int(exon[1])
                    tmp_rna_seq += self.chroms_dict[chromesome].seq[exon_start: exon_end]

            self.mrna_seq[rows['name']] = tmp_rna_seq
        
            self.cds_seq[rows['name']] = tmp_rna_seq[rows['utr5_length']: rows['utr5_length'] + rows['cds_length']]

    def write_txt(self):
        """Function to output the txt file.

        Returns
        -------
        None
            The function updates internal state or writes output files in place.

        Notes
        -----
        Legacy input information:
        - ``self.gp_df``: dataframe of the genepred file.

        Legacy return information:
        - ``gp_df_new``: dataframe of the genepred file.
        - ``txt_df``: dataframe of the txt file.

        Workflow
        --------
        1. Output the whole genepred file.
        2. Filter the coding transcript.
        3. Filter the longest transcript.
        4. Output the genePred file.
        5. Format the genePred file to txt file.
        """
        
        if self.whole:
            self.gp_df.to_csv(self.whole_file, sep='\t', header=True, index=None)

        if self.coding:
            self.gp_df = self.gp_df.loc[self.gp_df['cds_length'] != 0, ]

        if self.longest:
            self.gp_df = self.gp_df.loc[self.gp_df['rep_transcript'] == 'True', ]

        self.gp_df.loc[:, 'name'] = self.gp_df.loc[:, 'name'].str.replace('cds-', '').str.replace('rna-', '')
        self.gp_df.loc[:, 'name2'] = self.gp_df.loc[:, 'name2'].str.replace('gene-', '')

        # output the genePred file
        gp_df_new = self.gp_df.loc[:, self.columns].copy()
        gp_df_new.to_csv(self.gp_file, sep='\t', header=None, index=None)

        # output the txt file
        txt_columns = ['chrom', 'name2', 'name', 'txStart', 'txEnd', 'utr5_length', 'cds_length', 'utr3_length',
                       'strand', 'rep_transcript', 'modified']
        txt_df = self.gp_df.loc[:, txt_columns].copy()

        txt_df.columns = ['chromosome', 'gene_id', 'transcript_id', 'start', 'end', 'utr5_length',
                          'cds_length', 'utr3_length', 'strand', 'rep_transcript', 'modified']
        
        txt_df.loc[:, ['utr5_length', 'cds_length', 'utr3_length']] = txt_df.loc[:, ['utr5_length', 'cds_length', 'utr3_length']].astype(int)
        txt_df = txt_df.loc[txt_df['cds_length'] != 0, ]
        txt_df.to_csv(self.txt_file, sep='\t', header=True, index=None)

    def write_seq(self):
        """Function to output the mRNA and cds sequences.

        Notes
        -----
        Legacy input information:
        - ``self.rna_file``: mrna sequences file.
        - ``self.cds_file``: cds sequences file.
        """
        
        with open(self.rna_file, 'w') as seq_out:
            for rna, mess in self.mrna_seq.items():
                seq_out.writelines('\n'.join(['>' + rna, str(mess)]) + '\n')

        with open(self.cds_file, 'w') as cds_out:
            for cds, mess in self.cds_seq.items():
                cds_out.writelines('\n'.join(['>' + cds, str(mess)]) + '\n')
