#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Author: Rensc
# Date: 2026-06-24
# Version: 0.2.7
# Function: Provide RiboParser core functions for GenePred analysis.
# Input: Function parameters and intermediate RiboParser data objects.
# Output: Processed data objects or output files generated by module functions.

"""GenePred reference-building utilities for RiboParser.

This module is used by ``rpf_Reference`` to build normalized RiboParser
reference files from genome FASTA and GTF/GFF annotation files.

Main workflow
-------------
1. Read genome FASTA.
2. Convert GTF/GFF annotation to genePred format.
3. Parse genePred annotation.
4. Calculate UTR5, CDS, and UTR3 lengths.
5. Select representative transcripts.
6. Optionally add pseudo UTRs.
7. Export normalized genePred, GTF, TXT, mRNA FASTA, and CDS FASTA files.
"""

from __future__ import annotations

import os
import subprocess
import sys
from collections import OrderedDict
from pathlib import Path

import numpy as np
import pandas as pd
from Bio import Seq, SeqIO


GENEPRED_COLUMNS = [
    "name",
    "chrom",
    "strand",
    "txStart",
    "txEnd",
    "cdsStart",
    "cdsEnd",
    "exonCount",
    "exonStarts",
    "exonEnds",
    "score",
    "name2",
    "cdsStartStat",
    "cdsEndStat",
    "exonFrames",
]

REFERENCE_TXT_COLUMNS = [
    "chrom",
    "name2",
    "name",
    "txStart",
    "txEnd",
    "utr5_length",
    "cds_length",
    "utr3_length",
    "strand",
    "rep_transcript",
    "modified",
]

REFERENCE_TXT_RENAMED_COLUMNS = [
    "chromosome",
    "gene_id",
    "transcript_id",
    "start",
    "end",
    "utr5_length",
    "cds_length",
    "utr3_length",
    "strand",
    "rep_transcript",
    "modified",
]


class Chrom:
    """Container for one chromosome sequence.

    Parameters
    ----------
    line : Bio.SeqRecord.SeqRecord
        One sequence record parsed from the genome FASTA file.

    Attributes
    ----------
    attr : str
        Original FASTA record description.
    chromosome : str
        Chromosome or contig ID.
    start : int
        Chromosome start coordinate. RiboParser stores this as 1.
    end : int
        Chromosome sequence length.
    seq : Bio.Seq.Seq
        Chromosome sequence.
    """

    def __init__(self, line):
        self.attr = line.description
        self.chromosome = str(line.id)
        self.start = 1
        self.end = len(line.seq)
        self.seq = line.seq


class GenePred:
    """Core class for building normalized RiboParser references.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed arguments from ``rpf_Reference``.

    Notes
    -----
    This class stores intermediate data as object attributes. The public
    methods are called sequentially by ``rpf_Reference``.
    """

    def __init__(self, args):
        self.gene = OrderedDict()

        # Input annotation file.
        self.gtf = args.gtf
        self.gtf_format = Path(self.gtf).suffix
        self.gp_df = None
        self.columns = GENEPRED_COLUMNS

        # Transcript filtering options.
        self.coding = args.coding
        self.longest = args.longest
        self.utr = args.utr

        # Genome file and in-memory sequence containers.
        self.fasta = args.genome
        self.chroms_dict = OrderedDict()
        self.mrna_seq = OrderedDict()
        self.cds_seq = OrderedDict()

        # Output file prefix and generated file paths.
        self.out_prefix = args.output
        self.whole = args.whole
        self.gp_file = self.out_prefix + ".genepred"
        self.gtf_new = self.out_prefix + ".norm.gtf"
        self.whole_file = self.out_prefix + ".whole.txt"
        self.txt_file = self.out_prefix + ".norm.txt"
        self.rna_file = self.out_prefix + ".norm.rna.fa"
        self.cds_file = self.out_prefix + ".norm.cds.fa"

    # ------------------------------------------------------------------
    # External command helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _check_command(command: str) -> None:
        """Check whether an external command exists.

        Parameters
        ----------
        command : str
            Command name to check with ``which``.

        Returns
        -------
        None
            The function exits if the command is not found.

        Notes
        -----
        Legacy behavior is preserved: missing commands print a message and
        terminate the program with ``sys.exit(1)``.
        """
        command_check = subprocess.run(
            ["which", command],
            capture_output=True,
            text=True,
            check=False,
        )

        if command_check.returncode != 0:
            print(f"{command} not found in current environment.\n", flush=True)
            sys.exit(1)

    @staticmethod
    def _run_command(command: list[str]) -> None:
        """Run an external command.

        Parameters
        ----------
        command : list[str]
            Command and arguments.

        Returns
        -------
        None
            The function exits if the command fails.
        """
        run_tmp = subprocess.run(command, check=False)

        if run_tmp.returncode != 0:
            print(f"Command failed: {' '.join(command)}", flush=True)
            sys.exit(run_tmp.returncode)

    # ------------------------------------------------------------------
    # Annotation format conversion
    # ------------------------------------------------------------------

    def gtf2gp(self) -> None:
        """Function to convert the gtf to genepred.

        Returns
        -------
        None
            The function updates internal state or writes output files in place.

        Notes
        -----
        Legacy input information:

        - ``self.gtf_format``: format of the gtf file.
        - ``self.gtf``: gtf file.
        - ``self.gp_file``: genepred file.

        Legacy return information:

        - ``output``: description.

        Workflow
        --------
        1. Check the ``gff3ToGenePred`` and ``gtfToGenePred`` commands in the
           current environment.
        2. Convert the GTF or GFF annotation file to genePred format.
        """
        if self.gtf_format in [".gff", ".gff3"]:
            self._check_command("gff3ToGenePred")
            self._run_command(
                [
                    "gff3ToGenePred",
                    "-warnAndContinue",
                    "-rnaNameAttr=attr",
                    "-geneNameAttr=attr",
                    self.gtf,
                    self.gp_file,
                ]
            )
            return

        if self.gtf_format == ".gtf":
            self._check_command("gtfToGenePred")
            self._run_command(
                [
                    "gtfToGenePred",
                    "-allErrors",
                    "-genePredExt",
                    "-ignoreGroupsWithoutExons",
                    self.gtf,
                    self.gp_file,
                ]
            )
            return

        print(f"Unknown file format {self.gtf_format}.\n")
        print("Please input annotation file in GTF or GFF format.\n", flush=True)
        sys.exit(1)

    def gp2gtf(self) -> None:
        """Function to convert the genepred to gtf file.

        Returns
        -------
        None
            The function updates internal state or writes output files in place.

        Notes
        -----
        Legacy input information:

        - ``self.gp_file``: genepred file.
        - ``self.gtf_new``: new gtf file.

        Legacy return information:

        - ``output``: genePred file.

        Workflow
        --------
        1. Check the ``genePredToGtf`` command in the current environment.
        2. Convert the normalized genePred file to GTF format.
        """
        self._check_command("genePredToGtf")
        self._run_command(
            [
                "genePredToGtf",
                "file",
                "-utr",
                "-honorCdsStat",
                "-source=ribo",
                self.gp_file,
                self.gtf_new,
            ]
        )

        # Legacy note:
        # The original code kept this line commented.
        # Keep the generated genePred file because it is still used by
        # downstream output and debugging.
        # os.remove(self.gp_file)

    # ------------------------------------------------------------------
    # Input readers
    # ------------------------------------------------------------------

    def read_genome(self) -> None:
        """Function import the genome sequences.

        Returns
        -------
        None
            The function updates internal state or writes output files in place.

        Notes
        -----
        Legacy input information:

        - ``self.fasta``: genome file.

        Legacy return information:

        - ``self.chroms_dict``: dictionary of the chromosome sequences.

        Workflow
        --------
        1. Read the genome file with ``SeqIO``.
        2. Store the chromosome sequences in the dictionary.
        """
        record = SeqIO.parse(self.fasta, "fasta")

        for line in record:
            print(f"import chromosome: {line.id}", flush=True)
            self.chroms_dict[str(line.id)] = Chrom(line)

    def read_genepred(self) -> None:
        """Function import the parser the genepred file.

        Returns
        -------
        None
            The function updates internal state or writes output files in place.

        Notes
        -----
        Legacy input information:

        - ``self.gp_file``: gene pred file derived from gtf file.

        Legacy return information:

        - ``self.gp_df``: dataframe of the genepred file.

        Workflow
        --------
        1. Read the genePred file and rename the columns.
        2. Calculate the UTR5, CDS, and UTR3 length.
        """
        self.gp_df = pd.read_csv(self.gp_file, sep="\t", header=None)

        # The temporary genePred file produced by gtfToGenePred/gff3ToGenePred
        # will be rewritten later after normalization.
        os.remove(self.gp_file)

        self.gp_df.columns = self.columns

        utr5_list = []
        cds_list = []
        utr3_list = []

        print("Import gtf annotation.", flush=True)

        for idx, row in self.gp_df.iterrows():
            if idx % 1000 == 0:
                print(f"rows: {idx}", flush=True)

            # Skip non-coding transcripts or transcripts without complete CDS.
            if row.cdsStartStat == "none" or row.cdsEndStat == "none":
                utr5_list.append(0)
                cds_list.append(0)
                utr3_list.append(0)
                continue

            utr5_length, cds_length, utr3_length = self._calculate_region_lengths(row)

            utr5_list.append(utr5_length)
            cds_list.append(cds_length)
            utr3_list.append(utr3_length)

        print(f"rows: {idx}", flush=True)

        self.gp_df["utr5_length"] = utr5_list
        self.gp_df["cds_length"] = cds_list
        self.gp_df["utr3_length"] = utr3_list

    @staticmethod
    def _calculate_region_lengths(row) -> tuple[int, int, int]:
        """Calculate UTR5, CDS, and UTR3 lengths for one transcript.

        Parameters
        ----------
        row : pandas.Series
            One transcript record from the genePred dataframe.

        Returns
        -------
        tuple[int, int, int]
            UTR5 length, CDS length, and UTR3 length.

        Notes
        -----
        The genePred coordinates are exon-based. This method calculates the
        overlap between each exon and the CDS region.

        For negative-strand transcripts, the biological UTR5 and UTR3 are
        opposite to genomic coordinate order, so UTR5 and UTR3 lengths are
        swapped at the end.
        """
        exon_starts = np.fromstring(row.exonStarts, sep=",", dtype=int)
        exon_ends = np.fromstring(row.exonEnds, sep=",", dtype=int)

        cds_start = row.cdsStart
        cds_end = row.cdsEnd

        utr5_length = 0
        cds_length = 0
        utr3_length = 0

        for exon_start, exon_end in zip(exon_starts, exon_ends):
            # Genomic region before CDS start contributes to UTR5 on plus strand.
            utr5_length += max(0, min(exon_end, cds_start) - exon_start)

            # Exonic overlap with [cdsStart, cdsEnd) contributes to CDS length.
            cds_length += max(
                0,
                min(exon_end, cds_end) - max(exon_start, cds_start),
            )

            # Genomic region after CDS end contributes to UTR3 on plus strand.
            utr3_length += max(0, exon_end - max(exon_start, cds_end))

        if row.strand == "-":
            utr5_length, utr3_length = utr3_length, utr5_length

        return utr5_length, cds_length, utr3_length

    # ------------------------------------------------------------------
    # Representative transcript selection
    # ------------------------------------------------------------------

    def get_rep_transcript_bak(self) -> None:
        """Function to filter the representative transcripts.

        Returns
        -------
        object
            Dataframe of the genepred file with annotated column
            ``rep_transcript``.

        Notes
        -----
        Legacy input information:

        - ``self.gp_df``: dataframe of the genepred file.

        Workflow
        --------
        1. Group the dataframe by gene name.
        2. Label the max CDS length.
        3. Label the max UTR5 + CDS + UTR3 length.
        4. Label the first transcript.
        5. Add the flag of representative transcript.

        Note
        ----
        Low efficiency method to label the representative transcript.
        Kept for compatibility, but the main pipeline uses
        ``get_rep_transcript``.
        """
        print("Filter representative transcripts.", flush=True)
        counter = 0

        def add_true_flag(group):
            nonlocal counter
            counter += 1

            if counter % 500 == 0:
                print(f"Representative gene: {counter}", flush=True)

            if len(group) == 1:
                group["rep_transcript"] = True
                return group

            max_cds_length = group["cds_length"].max()
            max_cds_index = group.loc[group["cds_length"] == max_cds_length].index

            max_utr5_cds_utr3 = group.loc[
                group["cds_length"] == max_cds_length,
                ["utr5_length", "cds_length", "utr3_length"],
            ].sum(axis=1).max()

            max_utr5_cds_utr3_index = group.loc[
                group["utr5_length"] + group["cds_length"] + group["utr3_length"]
                == max_utr5_cds_utr3
            ].index

            if len(max_cds_index) == 1:
                group.loc[max_cds_index, "rep_transcript"] = True
            elif len(max_utr5_cds_utr3_index) == 1:
                group.loc[max_utr5_cds_utr3_index, "rep_transcript"] = True
            else:
                group.loc[max_cds_index[0], "rep_transcript"] = True

            return group

        self.gp_df["rep_transcript"] = False
        self.gp_df = self.gp_df.groupby("name2").apply(add_true_flag)

        print(f"Representative gene: {counter}", flush=True)

    def get_rep_transcript(self) -> None:
        """Function to filter the representative transcripts.

        Returns
        -------
        None
            The function updates internal state or writes output files in place.

        Notes
        -----
        Legacy input information:

        - ``self.gp_df``: dataframe of the genepred file.

        Legacy return information:

        - ``self.gp_df``: dataframe of the genepred file with annotated column
          ``rep_transcript``.

        Workflow
        --------
        1. Calculate the gene length:
           ``gene_length = cds_length + utr5_length + utr3_length``.
        2. Sort the dataframe by gene name, CDS length, gene length, UTR5
           length, and UTR3 length.
        3. Reset the index of the dataframe.
        4. Group the dataframe by gene name.
        5. Label the first transcript in each gene group as representative.
        6. Sort the dataframe back by chromosome and transcript start site.
        7. Reset the index of the dataframe.
        """
        print("Filter representative transcripts.", flush=True)

        # Gene length is used as a tie-breaker after CDS length.
        self.gp_df["gene_length"] = (
            self.gp_df["cds_length"]
            + self.gp_df["utr5_length"]
            + self.gp_df["utr3_length"]
        )

        # Representative transcript priority:
        # 1. gene name
        # 2. longest CDS
        # 3. longest whole transcript
        # 4. longer UTR5
        # 5. longer UTR3
        self.gp_df = self.gp_df.sort_values(
            by=[
                "name2",
                "cds_length",
                "gene_length",
                "utr5_length",
                "utr3_length",
            ],
            ascending=[False, False, False, False, False],
        )
        self.gp_df.reset_index(drop=True, inplace=True)

        self.gp_df["rep_transcript"] = False

        # After sorting, the first transcript of each gene is the selected
        # representative transcript.
        self.gp_df.loc[
            self.gp_df.groupby("name2").head(1).index,
            "rep_transcript",
        ] = True

        # Restore genomic order for downstream output.
        self.gp_df.sort_values(
            by=["chrom", "txStart", "name2", "rep_transcript"],
            ascending=[True, True, True, False],
            inplace=True,
        )
        self.gp_df.reset_index(drop=True, inplace=True)

    # ------------------------------------------------------------------
    # Pseudo UTR extension
    # ------------------------------------------------------------------

    def add_utr(self) -> None:
        """Function to add the pseudo utr.

        Returns
        -------
        None
            The function updates internal state or writes output files in place.

        Notes
        -----
        Legacy input information:

        - ``self.gp_df``: dataframe of the genepred file.

        Legacy return information:

        - ``self.gp_df``: dataframe of the genepred file with annotated column
          ``modified``.

        Workflow
        --------
        1. Create the list to store the new exon starts and ends.
        2. Skip the transcript without CDS.
        3. Calculate the new exon start site to extend the UTR5.
        4. Calculate the new exon end site to extend the UTR3.
        5. Add the pseudo UTR to the transcript.
        """
        exon_starts_list = []
        exon_ends_list = []
        tx_start_list = []
        tx_end_list = []
        utr5_list = []
        utr3_list = []

        self.gp_df.loc[:, "modified"] = "False"

        # add pseudo utr
        if self.utr == 0:
            return

        print("Add pseudo UTR.", flush=True)

        for idx, rows in self.gp_df.iterrows():
            if idx % 1000 == 0:
                print(f"rows: {idx}", flush=True)

            # skip the transcript without cds
            if rows["cdsStartStat"] == "none" or rows["cdsEndStat"] == "none":
                exon_starts_list.append(rows.exonStarts)
                exon_ends_list.append(rows.exonEnds)
                tx_start_list.append(rows.txStart)
                tx_end_list.append(rows.txEnd)
                utr5_list.append(rows.utr5_length)
                utr3_list.append(rows.utr3_length)
                continue

            self._extend_utr5(
                idx=idx,
                rows=rows,
                exon_starts_list=exon_starts_list,
                tx_start_list=tx_start_list,
                utr5_list=utr5_list,
            )

            self._extend_utr3(
                idx=idx,
                rows=rows,
                exon_ends_list=exon_ends_list,
                tx_end_list=tx_end_list,
                utr3_list=utr3_list,
            )

        self.gp_df["exonStarts"] = exon_starts_list
        self.gp_df["exonEnds"] = exon_ends_list
        self.gp_df["txStart"] = tx_start_list
        self.gp_df["txEnd"] = tx_end_list
        self.gp_df["utr5_length"] = utr5_list
        self.gp_df["utr3_length"] = utr3_list

    def _extend_utr5(
        self,
        idx: int,
        rows,
        exon_starts_list: list[str],
        tx_start_list: list[int],
        utr5_list: list[int],
    ) -> None:
        """Extend the 5' UTR for one transcript.

        Notes
        -----
        This helper preserves the original logic:

        - If the current UTR5 length is already longer than ``self.utr``,
          keep the original exon start and transcript start.
        - Otherwise, extend the first exon start upstream by ``self.utr``.
        - If the new start is negative, set it to 0 because chromosome
          coordinate cannot be negative.
        """
        # check exon starts for each genes
        exon_starts = rows["exonStarts"].split(",")[:-1]

        if int(rows["utr5_length"]) >= self.utr:
            # skip the transcript with utr5 length >= self.utr
            exon_starts_list.append(rows.exonStarts)
            tx_start_list.append(rows.txStart)
            utr5_list.append(rows.utr5_length)
            return

        # calculate the new exon start site to extend the utr5
        new_start = int(exon_starts[0]) - self.utr

        if new_start < 0:
            # set the negative new start site to 0, since the chromosome start
            # site can not be negative
            exon_starts[0] = "0"
            exon_starts_list.append(",".join(exon_starts) + ",")
            tx_start_list.append(0)
            utr5_list.append(rows["cdsStart"])
        else:
            # set the new start site to new_start
            exon_starts[0] = str(new_start)
            exon_starts_list.append(",".join(exon_starts) + ",")
            tx_start_list.append(rows.txStart - self.utr)
            utr5_list.append(rows.utr5_length + self.utr)

        self.gp_df.loc[idx, "modified"] = "True"

    def _extend_utr3(
        self,
        idx: int,
        rows,
        exon_ends_list: list[str],
        tx_end_list: list[int],
        utr3_list: list[int],
    ) -> None:
        """Extend the 3' UTR for one transcript.

        Notes
        -----
        This helper preserves the original logic:

        - If the current UTR3 length is already longer than ``self.utr``,
          keep the original exon end and transcript end.
        - Otherwise, extend the last exon end downstream by ``self.utr``.
        - If the new end is larger than chromosome end, set it to chromosome
          end because transcript coordinate cannot exceed chromosome length.
        """
        # check exon ends for each genes
        exon_ends = rows["exonEnds"].split(",")[:-1]

        if int(rows["utr3_length"]) >= self.utr:
            # skip the transcript with utr3 length >= self.utr
            exon_ends_list.append(rows.exonEnds)
            tx_end_list.append(rows.txEnd)
            utr3_list.append(rows.utr3_length)
            return

        # calculate the new exon end site to extend the utr3
        new_end = int(exon_ends[-1]) + self.utr
        chromosome_end = self.chroms_dict[str(rows["chrom"])].end

        if new_end > chromosome_end:
            # set the new end site to chromosome end site, since the chromosome
            # end site can not be larger than the chromosome end site
            exon_ends[-1] = str(chromosome_end)
            exon_ends_list.append(",".join(exon_ends) + ",")
            tx_end_list.append(chromosome_end)
            utr3_list.append(rows.utr3_length + chromosome_end - rows["cdsEnd"])
        else:
            # set the new end site to new_end
            exon_ends[-1] = str(new_end)
            exon_ends_list.append(",".join(exon_ends) + ",")
            tx_end_list.append(new_end)
            utr3_list.append(rows.utr3_length + self.utr)

        self.gp_df.loc[idx, "modified"] = "True"

    # ------------------------------------------------------------------
    # Optional duplicate removal
    # ------------------------------------------------------------------

    def remove_duplicate(self) -> None:
        """Function to remove the duplicate transcripts.

        Returns
        -------
        None
            The function updates internal state or writes output files in place.

        Notes
        -----
        Legacy input information:

        - ``self.gp_df``: dataframe of the genepred file.

        Legacy return information:

        - ``self.gp_df``: dataframe of the genepred file with removed duplicate
          transcripts.

        Workflow
        --------
        1. Drop the duplicate transcripts by name2 and strand.

        Warning
        -------
        This method is not used by the current ``rpf_Reference`` pipeline.
        The original implementation uses ``transcript_id`` as the subset column,
        but the genePred dataframe uses ``name`` as transcript ID. Keep this
        method for compatibility unless it is explicitly refactored later.
        """
        print("Remove duplicate transcripts.", flush=True)
        self.gp_df.drop_duplicates(subset=["transcript_id"], inplace=True)
        self.gp_df.reset_index(drop=True, inplace=True)

    # ------------------------------------------------------------------
    # Sequence retrieval
    # ------------------------------------------------------------------

    def get_seq(self) -> None:
        """Function to retrieve the mRNA sequences.

        Returns
        -------
        None
            The function updates internal state or writes output files in place.

        Notes
        -----
        Legacy input information:

        - ``self.gp_df``: dataframe of the genepred file.

        Legacy return information:

        - ``self.mrna_seq``: dictionary of the mRNA sequences.

        Workflow
        --------
        1. Iterate the dataframe to get the mRNA sequences.
        2. Store the mRNA sequences in the dictionary.
        3. Store the CDS sequences in the dictionary.
        """
        for _, rows in self.gp_df.iterrows():
            # skip the transcript without cds
            if rows["cds_length"] == 0:
                continue

            chromosome = str(rows["chrom"])
            rna = list(
                zip(
                    rows.exonStarts.split(",")[:-1],
                    rows.exonEnds.split(",")[:-1],
                )
            )
            tmp_rna_seq = Seq.Seq("")

            # Concatenate exon sequences by genomic order.
            for exon in rna:
                exon_start, exon_end = int(exon[0]), int(exon[1])
                tmp_rna_seq += self.chroms_dict[chromosome].seq[exon_start:exon_end]

            # Reverse-complement the concatenated transcript sequence for
            # negative-strand transcripts.
            if rows["strand"] == "-":
                tmp_rna_seq = tmp_rna_seq.reverse_complement()

            # CDS coordinates in transcript space:
            # CDS starts after UTR5 and ends after UTR5 + CDS length.
            cds_start = rows["utr5_length"]
            cds_end = rows["utr5_length"] + rows["cds_length"]

            self.mrna_seq[rows["name"]] = tmp_rna_seq
            self.cds_seq[rows["name"]] = tmp_rna_seq[cds_start:cds_end]

    # ------------------------------------------------------------------
    # Output writers
    # ------------------------------------------------------------------

    def write_txt(self) -> None:
        """Function to output the txt file.

        Returns
        -------
        None
            The function updates internal state or writes output files in place.

        Notes
        -----
        Legacy input information:

        - ``self.gp_df``: dataframe of the genepred file.

        Legacy return information:

        - ``gp_df_new``: dataframe of the genepred file.
        - ``txt_df``: dataframe of the txt file.

        Workflow
        --------
        1. Output the whole genePred file.
        2. Filter the coding transcript.
        3. Filter the longest transcript.
        4. Output the genePred file.
        5. Format the genePred file to TXT file.
        """
        if self.whole:
            self.gp_df.to_csv(
                self.whole_file,
                sep="\t",
                header=True,
                index=None,
            )

        if self.coding:
            self.gp_df = self.gp_df.loc[self.gp_df["cds_length"] != 0].copy()

        if self.longest:
            # Note:
            # In the original compressed code, this line compared the boolean
            # column with string "True". For a pure formatting-only commit, use:
            #
            # self.gp_df = self.gp_df.loc[
            #     self.gp_df["rep_transcript"] == "True"
            # ].copy()
            #
            # The following version matches the actual boolean value generated
            # by get_rep_transcript().
            self.gp_df = self.gp_df.loc[self.gp_df["rep_transcript"]].copy()

        self.gp_df.loc[:, "name"] = (
            self.gp_df.loc[:, "name"]
            .str.replace("cds-", "", regex=False)
            .str.replace("rna-", "", regex=False)
        )
        self.gp_df.loc[:, "name2"] = self.gp_df.loc[:, "name2"].str.replace(
            "gene-",
            "",
            regex=False,
        )

        # output the genePred file
        gp_df_new = self.gp_df.loc[:, self.columns].copy()
        gp_df_new.to_csv(
            self.gp_file,
            sep="\t",
            header=None,
            index=None,
        )

        # output the txt file
        txt_df = self.gp_df.loc[:, REFERENCE_TXT_COLUMNS].copy()
        txt_df.columns = REFERENCE_TXT_RENAMED_COLUMNS

        txt_df.loc[:, ["utr5_length", "cds_length", "utr3_length"]] = txt_df.loc[
            :,
            ["utr5_length", "cds_length", "utr3_length"],
        ].astype(int)

        txt_df = txt_df.loc[txt_df["cds_length"] != 0].copy()
        txt_df.to_csv(
            self.txt_file,
            sep="\t",
            header=True,
            index=None,
        )

    def write_seq(self) -> None:
        """Function to output the mRNA and cds sequences.

        Notes
        -----
        Legacy input information:

        - ``self.rna_file``: mRNA sequences file.
        - ``self.cds_file``: CDS sequences file.

        Workflow
        --------
        1. Write mRNA sequences to ``*.norm.rna.fa``.
        2. Write CDS sequences to ``*.norm.cds.fa``.
        """
        with open(self.rna_file, "w", encoding="utf-8") as seq_out:
            for rna, mess in self.mrna_seq.items():
                seq_out.writelines("\n".join([">" + rna, str(mess)]) + "\n")

        with open(self.cds_file, "w", encoding="utf-8") as cds_out:
            for cds, mess in self.cds_seq.items():
                cds_out.writelines("\n".join([">" + cds, str(mess)]) + "\n")
