#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-07-09
# Version: 0.2.8-dev.006
# Function: Provide compact JSON-based RPF density generation and conversion utilities.
# Input: RiboParser transcript annotation, transcript FASTA, BAM/SAM alignment, and P-site offset table.
# Output: Gzip-compressed compact RPF density JSONL, summary JSON, and optional legacy codon-level TXT table.

"""Core RPF density utilities for RiboParser.

This module converts transcriptome-aligned Ribo-seq BAM/SAM records into
P-site density. The default output is a compact JSONL file with one transcript
record per line. A compatibility converter is provided to expand the JSONL file
back into the legacy codon-level TXT table when downstream modules still require
that format.

Main workflow
-------------
1. Import P-site offsets generated by ``rpf_Offset``.
2. Import transcript annotation and transcript FASTA generated by
   ``rpf_Reference``.
3. Scan BAM/SAM alignments and accumulate single-base P-site density arrays.
4. Write one compact JSON record per transcript.
5. Optionally expand JSON records to the legacy TXT table.
"""

from __future__ import annotations

import csv
import gzip
import json
import os
import sys
import time
import multiprocessing as mp
from collections import Counter, OrderedDict
from itertools import islice
from math import ceil
from typing import Dict, Iterable, Iterator, List, Optional, Tuple

import numpy as np
import pandas as pd
import pysam
from Bio import SeqIO


SPARSE_ENCODING = "sparse_codon_frame"
DENSE_ENCODING = "dense_codon_frame"
DEFAULT_PROGRESS_EVERY = 1000000


class Mrna(object):
    """Transcript annotation and RPF density container.

    Parameters
    ----------
    record : list[str]
        Transcript annotation row generated by ``rpf_Reference``.
    """

    def __init__(self, record):
        self.chromosome = record[0]
        self.gene_id = record[1]
        self.transcript_id = record[2]
        self.start = record[3]
        self.end = record[4]
        self.utr5_length = int(record[5])
        self.cds_length = int(record[6])
        self.utr3_length = int(record[7])
        self.strand = record[8]
        self.rep_transcript = record[9]
        self.modified = record[10]
        self.length = self.utr5_length + self.cds_length + self.utr3_length
        self.bam = []
        self.rpf = []
        self.seq = None


class Ribo(object):
    """RPF density engine.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed arguments from ``rpf_Density``.
    """

    def __init__(self, args):
        self.mrna_file = args.transcript
        self.mrna_seq = args.sequence
        self.mrna_dict = OrderedDict()
        self.longest = args.longest
        self.silence = args.silence

        self.bam = args.bam
        self.sample_format = os.path.splitext(args.bam)[1]
        self.pysam_input = None

        self.psite = args.psite
        self.periodicity = args.periodicity
        self.min_confidence = args.min_confidence
        self.drop_warning = args.drop_warning
        self.min_length = args.min
        self.max_length = args.max
        self.offset = {}
        self.profile = None

        self.thread = max(1, int(args.thread))
        self.output = args.output
        self.sample_name = os.path.basename(args.output)
        self.output_format = getattr(args, "output_format", "json")
        self.density_encoding = getattr(args, "density_encoding", "sparse")

        self.total_rpf_df = None
        self.json_path = None
        self.txt_path = None
        self.summary_path = None
        self.scan_stats = Counter()
        self.progress_every = int(getattr(args, "progress_every", DEFAULT_PROGRESS_EVERY))
        if self.progress_every <= 0:
            self.progress_every = DEFAULT_PROGRESS_EVERY
        self.scan_start_time = None

    @staticmethod
    def _new_rpf_array(length: int) -> np.ndarray:
        """Create an integer RPF density array."""
        return np.zeros(length, dtype=np.uint32)

    @staticmethod
    def _open_text(path: str, mode: str = "rt"):
        """Open plain text or gzip-compressed text by filename suffix."""
        if path.endswith(".gz"):
            return gzip.open(path, mode, encoding="utf-8")
        return open(path, mode, encoding="utf-8")

    def _make_mrna(self, record: List[str], mrna_sequence: OrderedDict) -> Optional[Mrna]:
        """Create a transcript object and attach sequence/RPF arrays."""
        now_mrna = Mrna(record)
        try:
            now_mrna.seq = mrna_sequence[now_mrna.transcript_id]
        except KeyError:
            if not self.silence:
                print(
                    "Warning: {gene} KeyError, check the gene name.".format(gene=record[2]),
                    flush=True,
                )
            return None

        now_mrna.rpf = self._new_rpf_array(len(now_mrna.seq))
        return now_mrna

    def _insert_mrna(self, record: List[str], mrna_sequence: OrderedDict) -> None:
        """Insert transcript while retaining the longest duplicated transcript."""
        transcript_id = record[2]
        now_mrna = self._make_mrna(record, mrna_sequence)
        if now_mrna is None:
            return

        if transcript_id in self.mrna_dict:
            if not self.silence:
                print(
                    "Warning: {gene} is duplicated in gene message file, check the input file.".format(
                        gene=transcript_id
                    ),
                    flush=True,
                )
            if now_mrna.length > self.mrna_dict[transcript_id].length:
                self.mrna_dict[transcript_id] = now_mrna
            return

        self.mrna_dict[transcript_id] = now_mrna

    def read_transcript(self):
        """Import transcript sequences and transcript annotation.

        Returns
        -------
        None
            The function updates ``self.mrna_dict`` in place.

        Workflow
        --------
        1. Read transcript FASTA sequences into an ordered dictionary.
        2. Read transcript annotation generated by ``rpf_Reference``.
        3. Optionally retain representative transcripts only.
        4. Initialize each transcript RPF density array as ``uint32``.
        """
        mrna_sequence = OrderedDict()
        for line in SeqIO.parse(self.mrna_seq, "fasta"):
            if line.id in mrna_sequence:
                if not self.silence:
                    print(
                        "Warning: {gene} is duplicated in gene sequence file, check the input file.".format(
                            gene=line.id
                        ),
                        flush=True,
                    )
                continue
            mrna_sequence[line.id] = line.seq

        with open(self.mrna_file, "r", encoding="utf-8") as trans_file_in:
            for line in islice(trans_file_in, 1, None):
                record = line.rstrip("\n").split("\t")
                if len(record) < 11:
                    if not self.silence:
                        print("Warning: malformed transcript annotation row skipped.", flush=True)
                    continue

                if int(record[6]) % 3 != 0 and not self.silence:
                    print("{gene} CDS length is not a multiple of 3.".format(gene=record[2]), flush=True)

                if self.longest and record[9] != "True":
                    continue

                self._insert_mrna(record, mrna_sequence)

    def check_transcript(self):
        """Check whether transcript annotation length matches FASTA sequence length."""
        for gene in list(self.mrna_dict.keys()):
            if len(self.mrna_dict[gene].seq) != self.mrna_dict[gene].length:
                print(
                    "Warning: {gene} transcript length not equal to sequence length, check the input file.".format(
                        gene=gene
                    ),
                    flush=True,
                )
                del self.mrna_dict[gene]

        print("{number} gene retained.".format(number=len(self.mrna_dict.keys())), flush=True)

    def read_offset(self):
        """Import P-site offset and determine the Ribo-seq profile type."""
        offset = pd.read_csv(self.psite, sep="\t", header=0, names=None)
        offset.dropna(axis=0, inplace=True)
        offset["p_site"] = offset["p_site"].astype(int) - 1

        raw_offset = offset[["length", "p_site"]].groupby(offset["length"])["p_site"].apply(list).T.to_dict()
        print("The import offset table: ", flush=True)
        print(raw_offset, flush=True)

        if "confidence" in offset.columns:
            offset["confidence"] = pd.to_numeric(offset["confidence"], errors="coerce").fillna(0)
            offset = offset[offset["confidence"] >= self.min_confidence]
        if self.drop_warning and "warning" in offset.columns:
            offset["warning"] = offset["warning"].fillna("PASS").astype(str)
            offset = offset[offset["warning"].isin(["PASS", "", "nan"])]

        offset = offset[offset["periodicity"] >= self.periodicity]
        offset = offset[(offset["length"] >= self.min_length) & (offset["length"] <= self.max_length)]

        if offset.empty:
            sys.stdout.writelines(
                "No offset data retained, please check the input offset file or adjust the periodicity parameters!\n"
            )
            sys.exit(1)

        ave_periodicity = round(np.mean(offset["periodicity"]), 2)
        print(
            "The average periodicity of the imported offset table is {periodicity}.".format(
                periodicity=ave_periodicity
            ),
            flush=True,
        )

        self.offset = offset[["length", "p_site"]].groupby(offset["length"])["p_site"].apply(list).T.to_dict()
        print("Filtered RPFs offset table: ", flush=True)
        print(self.offset, flush=True)

        if "third" in offset["ribo"].unique():
            self.profile = "trisome"
        elif "second" in offset["ribo"].unique():
            self.profile = "disome"
        elif "first" in offset["ribo"].unique():
            self.profile = "monosome"
        else:
            sys.stdout.writelines("Unknown type of sequence profile, please re-check the offset file!\n")
            sys.exit(1)

    def _alignment_reader_mode(self) -> str:
        """Return pysam open mode for BAM/SAM input."""
        if self.sample_format.lower() == ".bam":
            return "rb"
        if self.sample_format.lower() == ".sam":
            return "r"
        sys.stdout.writelines("Unknown file format, please input the correct BAM or SAM file.\n")
        sys.exit(1)

    @staticmethod
    def _read_length(read) -> Optional[int]:
        """Return read length with fallback for records where infer_read_length is None."""
        read_length = read.infer_read_length()
        if read_length is None:
            read_length = read.query_length
        return read_length

    def _p_sites_from_read(self, read) -> Tuple[Optional[str], List[int]]:
        """Return transcript name and valid P-site positions for one alignment."""
        self.scan_stats["total_records_scanned"] += 1

        if read.is_unmapped:
            self.scan_stats["skipped_unmapped"] += 1
            return None, []

        reference_name = read.reference_name
        if reference_name not in self.mrna_dict:
            self.scan_stats["skipped_reference"] += 1
            return None, []

        read_length = self._read_length(read)
        if read_length is None:
            self.scan_stats["skipped_missing_length"] += 1
            return None, []

        if read_length < self.min_length or read_length > self.max_length:
            self.scan_stats["skipped_length"] += 1
            return None, []

        offset_sites = self.offset.get(read_length)
        if not offset_sites:
            self.scan_stats["skipped_no_offset"] += 1
            return None, []

        if offset_sites[0] == -1:
            positions = read.get_reference_positions(full_length=False)
        else:
            map_start = read.reference_start
            if map_start is None or map_start < 0:
                self.scan_stats["skipped_empty_blocks"] += 1
                return None, []
            positions = [map_start + int(site) for site in offset_sites]

        transcript_length = self.mrna_dict[reference_name].length
        valid_positions = [site for site in positions if 0 <= int(site) < transcript_length]
        if len(valid_positions) < len(positions):
            self.scan_stats["skipped_out_of_bounds_site"] += len(positions) - len(valid_positions)

        if not valid_positions:
            self.scan_stats["skipped_no_valid_site"] += 1
            return None, []

        self.scan_stats["passed_reads"] += 1
        self.scan_stats["counted_sites"] += len(valid_positions)
        return reference_name, valid_positions

    def _print_scan_progress(self, force: bool = False) -> None:
        """Print BAM/SAM scan progress based on the number of scanned records."""
        scanned = int(self.scan_stats.get("total_records_scanned", 0))
        if scanned == 0:
            return
        if not force and scanned % self.progress_every != 0:
            return

        elapsed = 0.0
        if self.scan_start_time is not None:
            elapsed = max(time.time() - self.scan_start_time, 1e-6)
        speed = scanned / elapsed if elapsed > 0 else 0.0

        message = (
            "scanned={scanned:,} reads, passed={passed:,}, "
            "counted_sites={sites:,}, skipped={skipped:,}, speed={speed:,.0f} reads/s"
        ).format(
            scanned=scanned,
            passed=int(self.scan_stats.get("passed_reads", 0)),
            sites=int(self.scan_stats.get("counted_sites", 0)),
            skipped=scanned - int(self.scan_stats.get("passed_reads", 0)),
            speed=speed,
        )
        print(message, flush=True)

    def _scan_bam_stream(self) -> None:
        """Scan BAM/SAM sequentially and accumulate P-site counts."""
        read_format = self._alignment_reader_mode()
        sys.stdout.writelines("import file: {bam}.\n".format(bam=self.bam))
        print("Start scanning alignments.", flush=True)

        self.scan_start_time = time.time()
        with pysam.AlignmentFile(self.bam, read_format) as bam_in:
            for read in bam_in.fetch(until_eof=True):
                reference_name, p_sites = self._p_sites_from_read(read)
                if self.scan_stats["total_records_scanned"] % self.progress_every == 0:
                    self._print_scan_progress(force=True)
                if reference_name is None:
                    continue
                self.mrna_dict[reference_name].rpf[p_sites] += 1

        self._print_scan_progress(force=True)

    @staticmethod
    def _read_length_from_worker(read) -> Optional[int]:
        """Return read length in a multiprocessing worker."""
        read_length = read.infer_read_length()
        if read_length is None:
            read_length = read.query_length
        return read_length

    @staticmethod
    def _p_sites_from_worker(
        read,
        transcript_lengths: Dict[str, int],
        min_length: int,
        max_length: int,
        offset: Dict[int, List[int]],
        stats: Counter,
    ) -> Tuple[Optional[str], List[int]]:
        """Return valid P-site positions for one alignment in a worker."""
        stats["total_records_scanned"] += 1

        if read.is_unmapped:
            stats["skipped_unmapped"] += 1
            return None, []

        reference_name = read.reference_name
        if reference_name not in transcript_lengths:
            stats["skipped_reference"] += 1
            return None, []

        read_length = Ribo._read_length_from_worker(read)
        if read_length is None:
            stats["skipped_missing_length"] += 1
            return None, []

        if read_length < min_length or read_length > max_length:
            stats["skipped_length"] += 1
            return None, []

        offset_sites = offset.get(read_length)
        if not offset_sites:
            stats["skipped_no_offset"] += 1
            return None, []

        if offset_sites[0] == -1:
            positions = read.get_reference_positions(full_length=False)
        else:
            map_start = read.reference_start
            if map_start is None or map_start < 0:
                stats["skipped_empty_blocks"] += 1
                return None, []
            positions = [map_start + int(site) for site in offset_sites]

        transcript_length = transcript_lengths[reference_name]
        valid_positions = [site for site in positions if 0 <= int(site) < transcript_length]
        if len(valid_positions) < len(positions):
            stats["skipped_out_of_bounds_site"] += len(positions) - len(valid_positions)

        if not valid_positions:
            stats["skipped_no_valid_site"] += 1
            return None, []

        stats["passed_reads"] += 1
        stats["counted_sites"] += len(valid_positions)
        return reference_name, valid_positions

    @staticmethod
    def _scan_bam_fetch_worker(args) -> Tuple[Counter, Dict[str, Tuple[np.ndarray, np.ndarray]]]:
        """Scan a subset of indexed BAM references in a multiprocessing worker."""
        (
            bam_file,
            read_format,
            gene_list,
            transcript_lengths,
            min_length,
            max_length,
            offset,
        ) = args

        stats = Counter()
        position_dict = {}

        with pysam.AlignmentFile(bam_file, read_format) as bam_in:
            for gene in gene_list:
                if gene not in transcript_lengths:
                    continue
                try:
                    gene_reads = bam_in.fetch(gene)
                except (ValueError, KeyError):
                    stats["skipped_missing_reference_in_bam"] += 1
                    continue

                for read in gene_reads:
                    reference_name, p_sites = Ribo._p_sites_from_worker(
                        read=read,
                        transcript_lengths=transcript_lengths,
                        min_length=min_length,
                        max_length=max_length,
                        offset=offset,
                        stats=stats,
                    )
                    if reference_name is None:
                        continue
                    position_dict.setdefault(reference_name, []).extend(int(site) for site in p_sites)

        updates = {}
        for gene, positions in position_dict.items():
            if not positions:
                continue
            position_array = np.asarray(positions, dtype=np.int64)
            unique_positions, counts = np.unique(position_array, return_counts=True)
            updates[gene] = (
                unique_positions.astype(np.int64, copy=False),
                counts.astype(np.uint32, copy=False),
            )

        return stats, updates

    def _can_use_indexed_parallel_scan(self) -> bool:
        """Return whether indexed BAM parallel scanning is available."""
        if self.thread <= 1:
            return False
        if self.sample_format.lower() != ".bam":
            return False

        try:
            with pysam.AlignmentFile(self.bam, "rb") as bam_in:
                return bool(bam_in.has_index())
        except (OSError, ValueError):
            return False

    def _split_gene_chunks(self) -> List[List[str]]:
        """Split transcript IDs into balanced chunks for indexed BAM parallel scanning."""
        gene_list = list(self.mrna_dict.keys())
        if not gene_list:
            return []

        # Too many chunks repeatedly open the same BAM file and increase random I/O.
        # Four chunks per worker usually keeps enough load balance while limiting BAM-open overhead.
        chunk_count = min(len(gene_list), max(self.thread * 4, self.thread))
        chunk_size = int(ceil(len(gene_list) / chunk_count))
        return [gene_list[i : i + chunk_size] for i in range(0, len(gene_list), chunk_size)]

    def _merge_density_updates(self, updates: Dict[str, Tuple[np.ndarray, np.ndarray]]) -> None:
        """Merge sparse worker density updates into transcript RPF arrays."""
        for gene, (positions, counts) in updates.items():
            if gene not in self.mrna_dict:
                continue
            if positions is None or len(positions) == 0:
                continue
            position_array = np.asarray(positions, dtype=np.int64)
            count_array = np.asarray(counts, dtype=self.mrna_dict[gene].rpf.dtype)
            self.mrna_dict[gene].rpf[position_array] += count_array

    @staticmethod
    def _parallel_context() -> mp.context.BaseContext:
        """Return a process context that is safer than the default fork mode for pysam."""
        for method in ("forkserver", "spawn"):
            try:
                return mp.get_context(method)
            except ValueError:
                continue
        return mp.get_context()

    def _scan_bam_parallel(self) -> None:
        """Scan indexed BAM references with process workers and accumulate P-site counts.

        The default Linux fork backend can be fast but may trigger a pysam/htslib
        segmentation fault during interpreter shutdown. This function therefore uses
        forkserver when available and falls back to spawn. Both backends keep process-level
        parallelism while avoiding unsafe fork-after-htslib state.
        """
        read_format = "rb"
        sys.stdout.writelines("import file: {bam}.\n".format(bam=self.bam))

        ctx = self._parallel_context()
        print(
            "Start scanning alignments with {threads} workers ({backend}).".format(
                threads=self.thread, backend=ctx.get_start_method()
            ),
            flush=True,
        )

        gene_chunks = self._split_gene_chunks()
        if not gene_chunks:
            return

        transcript_lengths = {gene: int(mrna.length) for gene, mrna in self.mrna_dict.items()}
        worker_args = [
            (
                self.bam,
                read_format,
                chunk,
                transcript_lengths,
                int(self.min_length),
                int(self.max_length),
                self.offset,
            )
            for chunk in gene_chunks
        ]

        self.scan_start_time = time.time()
        last_reported = 0

        with ctx.Pool(processes=self.thread) as pool:
            for stats, updates in pool.imap_unordered(Ribo._scan_bam_fetch_worker, worker_args, chunksize=1):
                self.scan_stats.update(stats)
                self._merge_density_updates(updates)

                scanned = int(self.scan_stats.get("total_records_scanned", 0))
                if scanned - last_reported >= self.progress_every:
                    self._print_scan_progress(force=True)
                    last_reported = scanned

        if int(self.scan_stats.get("total_records_scanned", 0)) != last_reported:
            self._print_scan_progress(force=True)

    def read_bam(self):
        """Import BAM/SAM alignments and accumulate transcript P-site density."""
        if self._can_use_indexed_parallel_scan():
            self._scan_bam_parallel()
            return

        if self.thread > 1:
            print(
                "Thread > 1 was requested, but indexed BAM parallel scanning is unavailable; fallback to stream mode.",
                flush=True,
            )
        self._scan_bam_stream()

    @staticmethod
    def _trim_info_from_isoform(isoform: Mrna) -> OrderedDict:
        """Return trimmed transcript metadata without mutating the source object."""
        utr5_length = int(isoform.utr5_length)
        cds_length = int(isoform.cds_length)
        utr3_length = int(isoform.utr3_length)

        if cds_length % 3 != 0:
            shift_cds = cds_length % 3
            cds_length -= shift_cds
            utr3_length += shift_cds

        shift_5 = utr5_length % 3
        shift_3 = utr3_length % 3

        trimmed_utr5_nt = utr5_length - shift_5
        trimmed_utr3_nt = utr3_length - shift_3
        trim_length_nt = isoform.length - shift_5 - shift_3
        codon_count = trim_length_nt // 3

        return OrderedDict(
            [
                ("shift5_nt", int(shift_5)),
                ("shift3_nt", int(shift_3)),
                ("start_nt0", int(shift_5)),
                ("end_nt0", int(isoform.length - shift_3)),
                ("trim_length_nt", int(trim_length_nt)),
                ("codon_count", int(codon_count)),
                ("utr5_nt", int(trimmed_utr5_nt)),
                ("cds_nt", int(cds_length)),
                ("utr3_nt", int(trimmed_utr3_nt)),
                ("utr5_codons", int(trimmed_utr5_nt // 3)),
                ("cds_codons", int(cds_length // 3)),
                ("utr3_codons", int(trimmed_utr3_nt // 3)),
            ]
        )

    @staticmethod
    def _trim_array(values: np.ndarray, shift5: int, shift3: int) -> np.ndarray:
        """Trim a one-dimensional array using 5' and 3' nucleotide shifts."""
        if shift3:
            return values[shift5:-shift3]
        return values[shift5:]

    @staticmethod
    def _trim_sequence(seq, shift5: int, shift3: int) -> str:
        """Trim transcript sequence using 5' and 3' nucleotide shifts."""
        if shift3:
            return str(seq[shift5:-shift3])
        return str(seq[shift5:])

    @staticmethod
    def _dense_density(trim_rpf: np.ndarray) -> OrderedDict:
        """Return dense codon-frame density arrays."""
        return OrderedDict(
            [
                ("encoding", DENSE_ENCODING),
                ("index_base", 0),
                ("f0", [int(x) for x in trim_rpf[0::3]]),
                ("f1", [int(x) for x in trim_rpf[1::3]]),
                ("f2", [int(x) for x in trim_rpf[2::3]]),
            ]
        )

    @staticmethod
    def _sparse_density(trim_rpf: np.ndarray) -> OrderedDict:
        """Return sparse codon-frame density arrays."""
        nonzero_nt = np.flatnonzero(trim_rpf)
        codon_index = (nonzero_nt // 3).astype(int)
        frame = (nonzero_nt % 3).astype(int)
        count = trim_rpf[nonzero_nt].astype(int)

        return OrderedDict(
            [
                ("encoding", SPARSE_ENCODING),
                ("index_base", 0),
                ("codon_index", codon_index.tolist()),
                ("frame", frame.tolist()),
                ("count", count.tolist()),
            ]
        )

    def _density_from_trimmed_rpf(self, trim_rpf: np.ndarray) -> OrderedDict:
        """Encode trimmed RPF density using the selected encoding."""
        if self.density_encoding == "dense":
            return self._dense_density(trim_rpf)
        return self._sparse_density(trim_rpf)

    def _record_from_isoform(self, name: str, isoform: Mrna) -> OrderedDict:
        """Build one compact JSON-serializable transcript density record."""
        trim_info = self._trim_info_from_isoform(isoform)
        shift5 = trim_info["shift5_nt"]
        shift3 = trim_info["shift3_nt"]

        trim_seq = self._trim_sequence(isoform.seq, shift5, shift3)
        trim_rpf = self._trim_array(isoform.rpf, shift5, shift3)
        density = self._density_from_trimmed_rpf(trim_rpf)

        return OrderedDict(
            [
                ("record_type", "transcript"),
                ("sample", self.sample_name),
                ("transcript_id", str(isoform.transcript_id)),
                ("gene_id", str(isoform.gene_id)),
                ("name", str(name)),
                ("chromosome", str(isoform.chromosome)),
                ("strand", str(isoform.strand)),
                ("profile", str(self.profile)),
                ("length_nt", int(isoform.length)),
                ("utr5_nt", int(isoform.utr5_length)),
                ("cds_nt", int(isoform.cds_length)),
                ("utr3_nt", int(isoform.utr3_length)),
                ("trim", trim_info),
                ("sequence", trim_seq),
                ("density", density),
            ]
        )

    def iter_density_records(self) -> Iterator[OrderedDict]:
        """Yield compact density records one transcript at a time."""
        for name, isoform in self.mrna_dict.items():
            yield self._record_from_isoform(name, isoform)

    def _json_output_path(self) -> str:
        """Return default gzip-compressed compact JSONL output path."""
        return self.output + "_rpf.jsonl.gz"

    def write_density_json(self) -> str:
        """Write compact RPF density records as JSONL."""
        out_json = self._json_output_path()
        record_count = 0
        with gzip.open(out_json, "wt", encoding="utf-8") as out:
            for record in self.iter_density_records():
                out.write(json.dumps(record, ensure_ascii=False, separators=(",", ":")))
                out.write("\n")
                record_count += 1

        self.json_path = out_json
        print("Compact RPF density JSONL written: {path}".format(path=out_json), flush=True)
        print("Transcript records written: {count}".format(count=record_count), flush=True)
        return out_json

    @staticmethod
    def _legacy_header(sample_name: str) -> List[str]:
        """Return legacy codon-level TXT header."""
        return [
            "name",
            "now_nt",
            "from_tis",
            "from_tts",
            "region",
            "codon",
            sample_name + "_f0",
            sample_name + "_f1",
            sample_name + "_f2",
        ]

    @staticmethod
    def _density_to_dense_frames(record: Dict) -> Tuple[List[int], List[int], List[int]]:
        """Return dense frame arrays from sparse or dense density encoding."""
        trim = record["trim"]
        codon_count = int(trim["codon_count"])
        density = record["density"]
        encoding = density.get("encoding", SPARSE_ENCODING)

        if encoding == DENSE_ENCODING:
            return (
                [int(x) for x in density.get("f0", [])],
                [int(x) for x in density.get("f1", [])],
                [int(x) for x in density.get("f2", [])],
            )

        f0 = [0] * codon_count
        f1 = [0] * codon_count
        f2 = [0] * codon_count
        frames = (f0, f1, f2)

        for codon_index, frame, count in zip(
            density.get("codon_index", []), density.get("frame", []), density.get("count", [])
        ):
            codon_index = int(codon_index)
            frame = int(frame)
            if 0 <= codon_index < codon_count and frame in (0, 1, 2):
                frames[frame][codon_index] += int(count)

        return f0, f1, f2

    @staticmethod
    def _legacy_rows_from_record(record: Dict, nonzero_only: bool = False) -> Iterator[List]:
        """Yield legacy codon-level TXT rows from one compact JSON record."""
        trim = record["trim"]
        sequence = record.get("sequence", "")
        name = record.get("name", record.get("transcript_id", "NA"))

        codon_count = int(trim["codon_count"])
        start_nt0 = int(trim["start_nt0"])
        trim_length_nt = int(trim["trim_length_nt"])
        utr5_codons = int(trim["utr5_codons"])
        cds_codons = int(trim["cds_codons"])
        utr3_nt = int(trim["utr3_nt"])

        from_tts_start = (utr3_nt - trim_length_nt) // 3 + 1
        f0, f1, f2 = Ribo._density_to_dense_frames(record)

        for codon_index in range(codon_count):
            value0 = int(f0[codon_index])
            value1 = int(f1[codon_index])
            value2 = int(f2[codon_index])

            if nonzero_only and value0 == 0 and value1 == 0 and value2 == 0:
                continue

            if codon_index < utr5_codons:
                region = "5utr"
            elif codon_index < utr5_codons + cds_codons:
                region = "cds"
            else:
                region = "3utr"

            codon_start = codon_index * 3
            codon = sequence[codon_start : codon_start + 3]
            now_nt = start_nt0 + 1 + codon_index * 3
            from_tis = codon_index - utr5_codons
            from_tts = from_tts_start + codon_index

            yield [name, now_nt, from_tis, from_tts, region, codon, value0, value1, value2]

    def write_density_txt(self, out_txt: Optional[str] = None) -> str:
        """Write complete legacy TXT directly from in-memory density records."""
        if out_txt is None:
            out_txt = self.output + "_rpf.txt"

        with open(out_txt, "w", encoding="utf-8", newline="") as out:
            writer = csv.writer(out, delimiter="\t", lineterminator="\n")
            writer.writerow(self._legacy_header(self.sample_name))
            for record in self.iter_density_records():
                writer.writerows(self._legacy_rows_from_record(record, nonzero_only=False))

        self.txt_path = out_txt
        print("Legacy RPF density TXT written: {path}".format(path=out_txt), flush=True)
        return out_txt

    @staticmethod
    def json_to_txt(
        json_file: str,
        output_txt: str,
    ) -> str:
        """Convert compact RPF density JSONL to the legacy codon-level TXT table.

        Parameters
        ----------
        json_file : str
            Input ``*_rpf.jsonl`` or ``*_rpf.jsonl.gz`` file.
        output_txt : str
            Output legacy TXT file.
        Returns
        -------
        str
            Path of the generated TXT file.
        """
        in_handle = Ribo._open_text(json_file, "rt")
        with in_handle as inp, open(output_txt, "w", encoding="utf-8", newline="") as out:
            writer = csv.writer(out, delimiter="\t", lineterminator="\n")
            header_written = False
            record_count = 0
            row_count = 0

            for line in inp:
                line = line.strip()
                if not line:
                    continue
                record = json.loads(line)
                if record.get("record_type") != "transcript":
                    continue

                current_sample = record.get("sample", "sample")
                if not header_written:
                    writer.writerow(Ribo._legacy_header(current_sample))
                    header_written = True

                for row in Ribo._legacy_rows_from_record(record, nonzero_only=False):
                    writer.writerow(row)
                    row_count += 1
                record_count += 1

            if not header_written:
                writer.writerow(Ribo._legacy_header("sample"))

        print(
            "JSONL to TXT conversion done: {records} records, {rows} rows.".format(
                records=record_count, rows=row_count
            ),
            flush=True,
        )
        return output_txt

    def write_summary(self) -> str:
        """Write RPF density generation summary as JSON."""
        summary = OrderedDict(
            [
                ("sample", self.sample_name),
                ("input_bam_or_sam", self.bam),
                ("transcript_file", self.mrna_file),
                ("sequence_file", self.mrna_seq),
                ("offset_file", self.psite),
                ("output_prefix", self.output),
                ("output_format", self.output_format),
                ("density_encoding", self.density_encoding),
                ("profile", self.profile),
                ("min_length", int(self.min_length)),
                ("max_length", int(self.max_length)),
                ("periodicity", float(self.periodicity)),
                ("min_confidence", float(self.min_confidence)),
                ("drop_warning", bool(self.drop_warning)),
                ("longest", bool(self.longest)),
                ("thread", int(self.thread)),
                ("transcripts_retained", int(len(self.mrna_dict))),
                ("json_output", self.json_path or "NA"),
                ("txt_output", self.txt_path or "NA"),
                ("scan_stats", OrderedDict((key, int(value)) for key, value in sorted(self.scan_stats.items()))),
            ]
        )

        out_json = self.output + "_rpf.summary.json"
        with open(out_json, "w", encoding="utf-8") as out:
            json.dump(summary, out, indent=2, ensure_ascii=False)
            out.write("\n")

        self.summary_path = out_json
        print("RPF density summary written: {path}".format(path=out_json), flush=True)
        return out_json

    def output_density(self):
        """Write RPF density output according to selected format."""
        output_format = str(self.output_format).lower()

        if output_format in ("json", "both"):
            self.write_density_json()
        if output_format in ("txt", "both"):
            self.write_density_txt()

        if output_format not in ("json", "txt", "both"):
            raise ValueError("Unsupported output format: {fmt}".format(fmt=self.output_format))

        self.write_summary()

    # Backward-compatible method names retained for old callers.
    def run_format_rpf_with_multi_thread(self):
        """Deprecated compatibility wrapper.

        The new implementation writes compact records directly in
        ``output_density`` and no longer expands all genes into one large
        in-memory pandas DataFrame.
        """
        print(
            "run_format_rpf_with_multi_thread is deprecated; compact records are generated during output_density.",
            flush=True,
        )

    @staticmethod
    def format_rpf_density(args):
        """Deprecated compatibility method for legacy callers.

        This method is intentionally kept minimal. New code should use JSONL
        records and ``json_to_txt`` for compatibility conversion.
        """
        gene_list, mrna_dict, out_prefix = args
        rpf_list = []
        fake_args = type("Args", (), {})()
        fake_args.transcript = "NA"
        fake_args.sequence = "NA"
        fake_args.bam = "NA.bam"
        fake_args.psite = "NA"
        fake_args.periodicity = 0
        fake_args.min_confidence = 0
        fake_args.drop_warning = False
        fake_args.min = 0
        fake_args.max = 999
        fake_args.thread = 1
        fake_args.output = out_prefix
        fake_args.output_format = "txt"
        fake_args.density_encoding = "sparse"
        fake_args.longest = False
        fake_args.silence = True
        ribo = Ribo(fake_args)
        ribo.mrna_dict = OrderedDict((name, mrna_dict[name]) for name in gene_list)
        ribo.profile = "unknown"

        for record in ribo.iter_density_records():
            header = Ribo._legacy_header(ribo.sample_name)
            rows = list(Ribo._legacy_rows_from_record(record))
            if rows:
                rpf_list.append(pd.DataFrame(rows, columns=header))

        if not rpf_list:
            return pd.DataFrame(columns=Ribo._legacy_header(os.path.basename(out_prefix)))
        return pd.concat(rpf_list, ignore_index=True)
