#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-08-04
# Version: 0.2.8-dev.009
# Function: Provide multi-sample-compatible JSON-based RNA-seq read density generation and conversion utilities.
# Input: RiboParser norm TXT or genePred annotation, transcript FASTA, BAM/SAM alignment, and RNA-seq read offset table.
# Output: Gzip-compressed compact RNA-seq density JSONL, summary JSON, and optional legacy codon-level TXT table.

"""Core RNA-seq read density utilities for RiboParser.

This module converts transcriptome-aligned RNA-seq BAM/SAM records into
single-base read density. The default output is a compact JSONL file with one
transcript record per line. Each record stores one or more samples under the
``samples`` field. A compatibility converter is provided to expand the JSONL
file back into the legacy codon-level TXT table when downstream modules still
require that format.

Main workflow
-------------
1. Import read offsets generated by ``rna_Offset``.
2. Import transcript annotation from old norm TXT, enhanced norm TXT, or genePred plus transcript FASTA generated by
   ``rpf_Reference``.
3. Scan BAM/SAM alignments and accumulate single-base read density arrays.
4. Write one compact JSON record per transcript.
5. Optionally expand JSON records to the legacy TXT table.
"""

from __future__ import annotations

import csv
import gzip
import json
import os
import sys
import time
import multiprocessing as mp
from collections import Counter, OrderedDict
from itertools import islice
from math import ceil
from typing import Dict, Iterable, Iterator, List, Optional, Tuple

import numpy as np
import pandas as pd
import pysam
from Bio import SeqIO


SPARSE_ENCODING = "sparse_codon_frame"
DENSE_ENCODING = "dense_codon_frame"
DEFAULT_PROGRESS_EVERY = 1000000


class Mrna(object):
    """Transcript annotation and read density container.

    Parameters
    ----------
    record : list[str]
        Core transcript annotation row with the first 11 RiboParser norm fields.
    """

    @staticmethod
    def _to_int(value, default: int = 0) -> int:
        """Safely convert a value to integer."""
        try:
            return int(value)
        except (TypeError, ValueError):
            try:
                return int(float(value))
            except (TypeError, ValueError):
                return default

    def __init__(self, record):
        self.chromosome = record[0]
        self.gene_id = record[1]
        self.transcript_id = record[2]
        self.start = self._to_int(record[3])
        self.end = self._to_int(record[4])
        self.utr5_length = self._to_int(record[5])
        self.cds_length = self._to_int(record[6])
        self.utr3_length = self._to_int(record[7])
        self.strand = record[8]
        self.rep_transcript = record[9]
        self.modified = record[10]
        self.length = self.utr5_length + self.cds_length + self.utr3_length

        # Extended annotation fields. Old norm TXT files leave these fields empty.
        self.annotation_source = "norm"
        self.coordinate_system = "0-based-half-open"
        self.tx_start = self.start
        self.tx_end = self.end
        self.cds_start = None
        self.cds_end = None
        self.exon_count = None
        self.exon_starts = []
        self.exon_ends = []
        self.exon_frames = []
        self.cds_start_stat = None
        self.cds_end_stat = None
        self.cds_tx_start = None
        self.cds_tx_end = None
        self.genome_mapping = None
        self.representative = str(self.rep_transcript).strip().lower() == "true"
        self.is_modified = str(self.modified).strip().lower() == "true"

        self.bam = []
        self.reads = []
        self.seq = None


class RNA(object):
    """RNA-seq read density engine.

    Parameters
    ----------
    args : argparse.Namespace
        Parsed arguments from ``rna_Density``.
    """

    def __init__(self, args):
        self.mrna_file = args.transcript
        self.mrna_seq = args.sequence
        self.mrna_dict = OrderedDict()
        self.gene_transcript_index = {}
        self.transcript_annotation_format = None
        self.longest = getattr(args, "longest", False)
        self.silence = getattr(args, "silence", False)

        self.bam = args.bam
        self.sample_format = os.path.splitext(args.bam)[1]
        self.pysam_input = None

        self.psite = args.psite
        self.drop_warning = getattr(args, "drop_warning", False)
        self.min_length = args.min
        self.max_length = args.max
        self.offset = {}
        self.profile = None

        self.rolling = getattr(args, "rolling", False)
        self.pair_end = getattr(args, "pair_end", False)

        self.thread = max(1, int(args.thread))
        self.output = args.output
        self.sample_name = os.path.basename(args.output)
        self.output_format = getattr(args, "output_format", "json")
        self.density_encoding = getattr(args, "density_encoding", "sparse")

        self.total_reads_df = None
        self.json_path = None
        self.txt_path = None
        self.summary_path = None
        self.scan_stats = Counter()
        self.progress_every = int(getattr(args, "progress_every", DEFAULT_PROGRESS_EVERY))
        if self.progress_every <= 0:
            self.progress_every = DEFAULT_PROGRESS_EVERY
        self.scan_start_time = None

    @staticmethod
    def _new_reads_array(length: int) -> np.ndarray:
        """Create an integer read density array."""
        return np.zeros(length, dtype=np.uint32)

    @staticmethod
    def _open_text(path: str, mode: str = "rt"):
        """Open plain text or gzip-compressed text by filename suffix."""
        if path.endswith(".gz"):
            return gzip.open(path, mode, encoding="utf-8")
        return open(path, mode, encoding="utf-8")

    @staticmethod
    def _parse_bool(value, default: bool = False) -> bool:
        """Parse common textual boolean values."""
        if value is None:
            return default
        if isinstance(value, bool):
            return value
        text = str(value).strip().lower()
        if text in {"true", "t", "1", "yes", "y"}:
            return True
        if text in {"false", "f", "0", "no", "n"}:
            return False
        return default

    @staticmethod
    def _parse_int(value, default: Optional[int] = None) -> Optional[int]:
        """Safely parse an integer value."""
        try:
            return int(value)
        except (TypeError, ValueError):
            try:
                return int(float(value))
            except (TypeError, ValueError):
                return default

    @staticmethod
    def _parse_int_list(value) -> List[int]:
        """Parse comma-separated integer lists used by genePred."""
        if value is None:
            return []
        if isinstance(value, (list, tuple, np.ndarray)):
            return [int(x) for x in value]
        text = str(value).strip()
        if not text or text in {"NA", "None", "nan"}:
            return []
        return [int(x) for x in text.split(",") if str(x).strip() != ""]

    @staticmethod
    def _is_int(value) -> bool:
        """Return whether a value can be parsed as integer."""
        try:
            int(value)
            return True
        except (TypeError, ValueError):
            return False

    @staticmethod
    def _dict_get(row: Dict[str, str], names: Iterable[str], default=None):
        """Get the first available key from a row dictionary."""
        for name in names:
            if name in row and row[name] not in (None, ""):
                return row[name]
        return default

    def _detect_transcript_format(self) -> str:
        """Automatically detect transcript annotation format."""
        with open(self.mrna_file, "r", encoding="utf-8") as handle:
            for line in handle:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                fields = line.split("\t")
                lower_fields = [field.strip().lower() for field in fields]

                if {"chromosome", "gene_id", "transcript_id"}.issubset(set(lower_fields)):
                    return "norm"

                if len(fields) >= 15 and self._is_int(fields[3]) and self._is_int(fields[4]) and self._is_int(fields[7]):
                    return "genepred"

                if len(fields) >= 11 and self._is_int(fields[5]) and self._is_int(fields[6]) and self._is_int(fields[7]):
                    return "norm_no_header"

                break

        raise ValueError(
            "Unable to detect transcript annotation format. Please provide RiboParser norm TXT or genePred input."
        )

    def _read_transcript_sequences(self) -> OrderedDict:
        """Read transcript FASTA sequences into an ordered dictionary."""
        mrna_sequence = OrderedDict()
        for line in SeqIO.parse(self.mrna_seq, "fasta"):
            if line.id in mrna_sequence:
                if not self.silence:
                    print(
                        "Warning: {gene} is duplicated in gene sequence file, check the input file.".format(
                            gene=line.id
                        ),
                        flush=True,
                    )
                continue
            mrna_sequence[line.id] = line.seq
        return mrna_sequence

    @staticmethod
    def _build_genome_mapping(
        strand: str,
        exon_starts: List[int],
        exon_ends: List[int],
        cds_start: Optional[int],
        cds_end: Optional[int],
        coordinate_system: str = "0-based-half-open",
    ) -> Tuple[Optional[OrderedDict], Optional[int], Optional[int], int]:
        """Build transcript-to-genome mapping in transcript 5'->3' order.

        Returns
        -------
        tuple
            ``(genome_mapping, cds_tx_start, cds_tx_end, transcript_length)``.
        """
        if not exon_starts or not exon_ends or len(exon_starts) != len(exon_ends):
            return None, None, None, 0

        genomic_exons = [
            (idx + 1, int(start), int(end))
            for idx, (start, end) in enumerate(zip(exon_starts, exon_ends))
            if int(end) > int(start)
        ]
        if not genomic_exons:
            return None, None, None, 0

        ordered_exons = genomic_exons if strand == "+" else list(reversed(genomic_exons))
        segments = []
        transcript_cursor = 0
        cds_ranges = []

        for exon_id, genome_start, genome_end in ordered_exons:
            exon_length = genome_end - genome_start
            transcript_start = transcript_cursor
            transcript_end = transcript_start + exon_length
            segments.append(
                OrderedDict(
                    [
                        ("exon_id", int(exon_id)),
                        ("transcript_start", int(transcript_start)),
                        ("transcript_end", int(transcript_end)),
                        ("genome_start", int(genome_start)),
                        ("genome_end", int(genome_end)),
                    ]
                )
            )

            if cds_start is not None and cds_end is not None and int(cds_end) > int(cds_start):
                overlap_start = max(genome_start, int(cds_start))
                overlap_end = min(genome_end, int(cds_end))
                if overlap_end > overlap_start:
                    if strand == "+":
                        cds_tx_start = transcript_start + (overlap_start - genome_start)
                        cds_tx_end = transcript_start + (overlap_end - genome_start)
                    else:
                        cds_tx_start = transcript_start + (genome_end - overlap_end)
                        cds_tx_end = transcript_start + (genome_end - overlap_start)
                    cds_ranges.append((int(cds_tx_start), int(cds_tx_end)))

            transcript_cursor = transcript_end

        genome_mapping = OrderedDict(
            [
                ("coordinate_system", coordinate_system),
                ("transcript_order", "5_to_3"),
                ("segments", segments),
            ]
        )

        if cds_ranges:
            cds_tx_start = min(start for start, _ in cds_ranges)
            cds_tx_end = max(end for _, end in cds_ranges)
        else:
            cds_tx_start = None
            cds_tx_end = None

        return genome_mapping, cds_tx_start, cds_tx_end, int(transcript_cursor)

    def _attach_sequence_and_density(self, isoform: Mrna, mrna_sequence: OrderedDict) -> Optional[Mrna]:
        """Attach transcript sequence and initialize read density array."""
        try:
            isoform.seq = mrna_sequence[isoform.transcript_id]
        except KeyError:
            if not self.silence:
                print(
                    "Warning: {gene} KeyError, check the gene name.".format(gene=isoform.transcript_id),
                    flush=True,
                )
            return None

        isoform.reads = self._new_reads_array(len(isoform.seq))
        return isoform

    def _make_mrna(self, record: List[str], mrna_sequence: OrderedDict) -> Optional[Mrna]:
        """Create a transcript object from a core norm-style record."""
        return self._attach_sequence_and_density(Mrna(record), mrna_sequence)

    def _insert_mrna_object(self, isoform: Mrna) -> None:
        """Insert transcript while retaining the longest duplicated transcript ID."""
        transcript_id = isoform.transcript_id
        if transcript_id in self.mrna_dict:
            if not self.silence:
                print(
                    "Warning: {gene} is duplicated in transcript annotation file, check the input file.".format(
                        gene=transcript_id
                    ),
                    flush=True,
                )
            if isoform.length > self.mrna_dict[transcript_id].length:
                self.mrna_dict[transcript_id] = isoform
            return
        self.mrna_dict[transcript_id] = isoform

    def _insert_mrna_by_gene(self, isoform: Mrna) -> None:
        """Insert transcript while retaining the longest CDS transcript per gene."""
        gene_id = isoform.gene_id
        transcript_id = isoform.transcript_id
        old_transcript = self.gene_transcript_index.get(gene_id)
        if old_transcript is None:
            self.gene_transcript_index[gene_id] = transcript_id
            self.mrna_dict[transcript_id] = isoform
            return

        old_isoform = self.mrna_dict.get(old_transcript)
        if old_isoform is None or isoform.cds_length > old_isoform.cds_length:
            if old_transcript in self.mrna_dict:
                del self.mrna_dict[old_transcript]
            self.gene_transcript_index[gene_id] = transcript_id
            self.mrna_dict[transcript_id] = isoform

    def _insert_mrna(self, record: List[str], mrna_sequence: OrderedDict) -> None:
        """Backward-compatible insert method for old callers."""
        now_mrna = self._make_mrna(record, mrna_sequence)
        if now_mrna is not None:
            self._insert_mrna_object(now_mrna)

    def _warn_cds_length(self, isoform: Mrna) -> None:
        """Print a warning when CDS length is not a multiple of three."""
        if int(isoform.cds_length) % 3 != 0 and not self.silence:
            print(
                "{gene} CDS length is not a multiple of 3.".format(gene=isoform.transcript_id),
                flush=True,
            )

    def _build_mrna_from_norm_row(self, row: Dict[str, str], mrna_sequence: OrderedDict) -> Optional[Mrna]:
        """Build transcript object from old or enhanced RiboParser norm TXT row."""
        chromosome = self._dict_get(row, ["chromosome", "chrom", "chromosome_name"])
        gene_id = self._dict_get(row, ["gene_id", "gene", "name2"])
        transcript_id = self._dict_get(row, ["transcript_id", "transcript", "name"])
        start = self._dict_get(row, ["start", "tx_start", "txStart"])
        end = self._dict_get(row, ["end", "tx_end", "txEnd"])
        utr5_length = self._dict_get(row, ["utr5_length", "utr5_nt"])
        cds_length = self._dict_get(row, ["cds_length", "cds_nt"])
        utr3_length = self._dict_get(row, ["utr3_length", "utr3_nt"])
        strand = self._dict_get(row, ["strand"])
        rep_transcript = self._dict_get(row, ["rep_transcript", "representative"], "True")
        modified = self._dict_get(row, ["modified"], "False")

        core_record = [
            chromosome,
            gene_id,
            transcript_id,
            start,
            end,
            utr5_length,
            cds_length,
            utr3_length,
            strand,
            rep_transcript,
            modified,
        ]
        isoform = Mrna(core_record)
        isoform.annotation_source = str(self._dict_get(row, ["annotation_source", "source"], "norm"))
        isoform.coordinate_system = str(self._dict_get(row, ["coordinate_system"], "0-based-half-open"))
        isoform.tx_start = self._parse_int(self._dict_get(row, ["tx_start", "txStart", "start"], isoform.start), isoform.start)
        isoform.tx_end = self._parse_int(self._dict_get(row, ["tx_end", "txEnd", "end"], isoform.end), isoform.end)
        isoform.cds_start = self._parse_int(self._dict_get(row, ["cds_start", "cdsStart"], None), None)
        isoform.cds_end = self._parse_int(self._dict_get(row, ["cds_end", "cdsEnd"], None), None)
        isoform.exon_starts = self._parse_int_list(self._dict_get(row, ["exon_starts", "exonStarts"], None))
        isoform.exon_ends = self._parse_int_list(self._dict_get(row, ["exon_ends", "exonEnds"], None))
        isoform.exon_count = self._parse_int(self._dict_get(row, ["exon_count", "exonCount"], None), None)
        isoform.exon_frames = self._parse_int_list(self._dict_get(row, ["exon_frames", "exonFrames"], None))
        isoform.cds_start_stat = self._dict_get(row, ["cds_start_stat", "cdsStartStat"], None)
        isoform.cds_end_stat = self._dict_get(row, ["cds_end_stat", "cdsEndStat"], None)
        isoform.representative = self._parse_bool(rep_transcript, default=True)
        isoform.is_modified = self._parse_bool(modified, default=False)

        if isoform.exon_starts and isoform.exon_ends:
            mapping, cds_tx_start, cds_tx_end, transcript_length = self._build_genome_mapping(
                strand=isoform.strand,
                exon_starts=isoform.exon_starts,
                exon_ends=isoform.exon_ends,
                cds_start=isoform.cds_start,
                cds_end=isoform.cds_end,
                coordinate_system=isoform.coordinate_system,
            )
            isoform.genome_mapping = mapping
            isoform.cds_tx_start = cds_tx_start
            isoform.cds_tx_end = cds_tx_end
            if isoform.exon_count is None:
                isoform.exon_count = len(isoform.exon_starts)
            if transcript_length and transcript_length != isoform.length and not self.silence:
                print(
                    "Warning: {gene} exon length does not match transcript length in norm annotation.".format(
                        gene=isoform.transcript_id
                    ),
                    flush=True,
                )

        return self._attach_sequence_and_density(isoform, mrna_sequence)

    def _build_mrna_from_genepred_fields(self, fields: List[str], mrna_sequence: OrderedDict) -> Optional[Mrna]:
        """Build transcript object from a genePred/genePredExt row."""
        transcript_id = fields[0]
        chromosome = fields[1]
        strand = fields[2]
        tx_start = self._parse_int(fields[3], 0)
        tx_end = self._parse_int(fields[4], 0)
        cds_start = self._parse_int(fields[5], None)
        cds_end = self._parse_int(fields[6], None)
        exon_count = self._parse_int(fields[7], 0)
        exon_starts = self._parse_int_list(fields[8])
        exon_ends = self._parse_int_list(fields[9])
        gene_id = fields[11] if len(fields) > 11 and fields[11] else transcript_id
        cds_start_stat = fields[12] if len(fields) > 12 else None
        cds_end_stat = fields[13] if len(fields) > 13 else None
        exon_frames = self._parse_int_list(fields[14]) if len(fields) > 14 else []

        mapping, cds_tx_start, cds_tx_end, transcript_length = self._build_genome_mapping(
            strand=strand,
            exon_starts=exon_starts,
            exon_ends=exon_ends,
            cds_start=cds_start,
            cds_end=cds_end,
            coordinate_system="0-based-half-open",
        )

        if cds_tx_start is None or cds_tx_end is None:
            utr5_length = 0
            cds_length = 0
            utr3_length = transcript_length
        else:
            utr5_length = int(cds_tx_start)
            cds_length = int(cds_tx_end - cds_tx_start)
            utr3_length = int(transcript_length - cds_tx_end)

        core_record = [
            chromosome,
            gene_id,
            transcript_id,
            tx_start,
            tx_end,
            utr5_length,
            cds_length,
            utr3_length,
            strand,
            "True",
            "False",
        ]
        isoform = Mrna(core_record)
        isoform.annotation_source = "genepred"
        isoform.coordinate_system = "0-based-half-open"
        isoform.tx_start = tx_start
        isoform.tx_end = tx_end
        isoform.cds_start = cds_start
        isoform.cds_end = cds_end
        isoform.exon_count = exon_count
        isoform.exon_starts = exon_starts
        isoform.exon_ends = exon_ends
        isoform.exon_frames = exon_frames
        isoform.cds_start_stat = cds_start_stat
        isoform.cds_end_stat = cds_end_stat
        isoform.cds_tx_start = cds_tx_start
        isoform.cds_tx_end = cds_tx_end
        isoform.genome_mapping = mapping
        isoform.representative = True
        isoform.is_modified = False

        return self._attach_sequence_and_density(isoform, mrna_sequence)

    def _read_norm_transcript(self, mrna_sequence: OrderedDict, has_header: bool = True) -> None:
        """Read old or enhanced RiboParser norm TXT annotation."""
        default_columns = [
            "chromosome",
            "gene_id",
            "transcript_id",
            "start",
            "end",
            "utr5_length",
            "cds_length",
            "utr3_length",
            "strand",
            "rep_transcript",
            "modified",
        ]

        with open(self.mrna_file, "r", encoding="utf-8") as handle:
            if has_header:
                header = handle.readline().rstrip("\n").split("\t")
                rows = (dict(zip(header, line.rstrip("\n").split("\t"))) for line in handle if line.strip())
            else:
                rows = (dict(zip(default_columns, line.rstrip("\n").split("\t"))) for line in handle if line.strip())

            for row in rows:
                isoform = self._build_mrna_from_norm_row(row, mrna_sequence)
                if isoform is None:
                    continue
                self._warn_cds_length(isoform)
                if self.longest and not isoform.representative:
                    continue
                self._insert_mrna_object(isoform)

    def _read_genepred_transcript(self, mrna_sequence: OrderedDict) -> None:
        """Read genePred/genePredExt transcript annotation."""
        with open(self.mrna_file, "r", encoding="utf-8") as handle:
            for line in handle:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                fields = line.split("\t")
                if len(fields) < 15:
                    if not self.silence:
                        print("Warning: malformed genePred row skipped.", flush=True)
                    continue
                isoform = self._build_mrna_from_genepred_fields(fields, mrna_sequence)
                if isoform is None:
                    continue
                self._warn_cds_length(isoform)
                if self.longest:
                    self._insert_mrna_by_gene(isoform)
                else:
                    self._insert_mrna_object(isoform)

    def read_transcript(self):
        """Import transcript sequences and transcript annotation.

        Returns
        -------
        None
            The function updates ``self.mrna_dict`` in place.

        Workflow
        --------
        1. Read transcript FASTA sequences into an ordered dictionary.
        2. Automatically detect old norm TXT, enhanced norm TXT, or genePred annotation.
        3. Optionally retain representative transcripts or the longest CDS transcript per gene.
        4. Initialize each transcript read density array as ``uint32``.
        """
        mrna_sequence = self._read_transcript_sequences()
        annotation_format = self._detect_transcript_format()
        self.transcript_annotation_format = annotation_format
        print("Detected transcript annotation format: {fmt}.".format(fmt=annotation_format), flush=True)

        if annotation_format == "genepred":
            self._read_genepred_transcript(mrna_sequence)
        elif annotation_format == "norm":
            self._read_norm_transcript(mrna_sequence, has_header=True)
        elif annotation_format == "norm_no_header":
            self._read_norm_transcript(mrna_sequence, has_header=False)
        else:
            raise ValueError("Unsupported transcript annotation format: {fmt}".format(fmt=annotation_format))

    def check_transcript(self):
        """Check whether transcript annotation length matches FASTA sequence length."""
        for gene in list(self.mrna_dict.keys()):
            if len(self.mrna_dict[gene].seq) != self.mrna_dict[gene].length:
                print(
                    "Warning: {gene} transcript length not equal to sequence length, check the input file.".format(
                        gene=gene
                    ),
                    flush=True,
                )
                del self.mrna_dict[gene]

        print("{number} gene retained.".format(number=len(self.mrna_dict.keys())), flush=True)

    def read_offset(self):
        """Import read offset and determine the sequencing profile type."""
        offset = pd.read_csv(self.psite, sep="\t", header=0, names=None)
        offset.dropna(axis=0, inplace=True)
        offset["p_site"] = offset["p_site"].astype(int) - 1

        raw_offset = offset[["length", "p_site"]].groupby(offset["length"])["p_site"].apply(list).T.to_dict()
        print("The import offset table: ", flush=True)
        print(raw_offset, flush=True)

        if self.drop_warning and "warning" in offset.columns:
            offset["warning"] = offset["warning"].fillna("PASS").astype(str)
            offset = offset[offset["warning"].isin(["PASS", "", "nan"])]

        offset = offset[(offset["length"] >= self.min_length) & (offset["length"] <= self.max_length)]

        if offset.empty:
            sys.stdout.writelines(
                "No offset data retained, please check the input offset file or adjust the filter parameters!\n"
            )
            sys.exit(1)

        self.offset = offset[["length", "p_site"]].groupby(offset["length"])["p_site"].apply(list).T.to_dict()
        print("Filtered RNA-seq offset table: ", flush=True)
        print(self.offset, flush=True)

        if "ribo" not in offset.columns:
            self.profile = "monosome"
        elif "third" in offset["ribo"].unique():
            self.profile = "trisome"
        elif "second" in offset["ribo"].unique():
            self.profile = "disome"
        elif "first" in offset["ribo"].unique():
            self.profile = "monosome"
        else:
            sys.stdout.writelines("Unknown type of sequence profile, please re-check the offset file!\n")
            sys.exit(1)

    def _alignment_reader_mode(self) -> str:
        """Return pysam open mode for BAM/SAM input."""
        if self.sample_format.lower() == ".bam":
            return "rb"
        if self.sample_format.lower() == ".sam":
            return "r"
        sys.stdout.writelines("Unknown file format, please input the correct BAM or SAM file.\n")
        sys.exit(1)

    @staticmethod
    def _read_length(read) -> Optional[int]:
        """Return read length with fallback for records where infer_read_length is None."""
        read_length = read.infer_read_length()
        if read_length is None:
            read_length = read.query_length
        return read_length

    def _p_sites_from_read(self, read) -> Tuple[Optional[str], List[int]]:
        """Return transcript name and valid read positions for one alignment."""
        self.scan_stats["total_records_scanned"] += 1

        if read.is_unmapped:
            self.scan_stats["skipped_unmapped"] += 1
            return None, []

        if read.is_reverse and not self.pair_end:
            self.scan_stats["skipped_reverse"] += 1
            return None, []

        reference_name = read.reference_name
        if reference_name not in self.mrna_dict:
            self.scan_stats["skipped_reference"] += 1
            return None, []

        read_length = self._read_length(read)
        if read_length is None:
            self.scan_stats["skipped_missing_length"] += 1
            return None, []

        if read_length < self.min_length or read_length > self.max_length:
            self.scan_stats["skipped_length"] += 1
            return None, []

        offset_sites = self.offset.get(read_length)
        if not offset_sites:
            self.scan_stats["skipped_no_offset"] += 1
            return None, []

        if offset_sites[0] == -1:
            positions = read.get_reference_positions(full_length=False)
        elif self.rolling:
            blocks = read.get_blocks()
            if not blocks:
                self.scan_stats["skipped_empty_blocks"] += 1
                return None, []
            map_start, map_end = blocks[0]
            positions = list(np.arange(map_start, map_end, 32))
        else:
            map_start = read.reference_start
            if map_start is None or map_start < 0:
                self.scan_stats["skipped_empty_blocks"] += 1
                return None, []
            positions = [map_start + int(site) for site in offset_sites]

        transcript_length = self.mrna_dict[reference_name].length
        valid_positions = [site for site in positions if 0 <= int(site) < transcript_length]
        if len(valid_positions) < len(positions):
            self.scan_stats["skipped_out_of_bounds_site"] += len(positions) - len(valid_positions)

        if not valid_positions:
            self.scan_stats["skipped_no_valid_site"] += 1
            return None, []

        self.scan_stats["passed_reads"] += 1
        self.scan_stats["counted_sites"] += len(valid_positions)
        return reference_name, valid_positions

    def _print_scan_progress(self, force: bool = False) -> None:
        """Print BAM/SAM scan progress based on the number of scanned records."""
        scanned = int(self.scan_stats.get("total_records_scanned", 0))
        if scanned == 0:
            return
        if not force and scanned % self.progress_every != 0:
            return

        elapsed = 0.0
        if self.scan_start_time is not None:
            elapsed = max(time.time() - self.scan_start_time, 1e-6)
        speed = scanned / elapsed if elapsed > 0 else 0.0

        message = (
            "scanned={scanned:,} reads, passed={passed:,}, "
            "counted_sites={sites:,}, skipped={skipped:,}, speed={speed:,.0f} reads/s"
        ).format(
            scanned=scanned,
            passed=int(self.scan_stats.get("passed_reads", 0)),
            sites=int(self.scan_stats.get("counted_sites", 0)),
            skipped=scanned - int(self.scan_stats.get("passed_reads", 0)),
            speed=speed,
        )
        print(message, flush=True)

    def _scan_bam_stream(self) -> None:
        """Scan BAM/SAM sequentially and accumulate read counts."""
        read_format = self._alignment_reader_mode()
        sys.stdout.writelines("import file: {bam}.\n".format(bam=self.bam))
        print("Start scanning alignments.", flush=True)

        self.scan_start_time = time.time()
        with pysam.AlignmentFile(self.bam, read_format) as bam_in:
            for read in bam_in.fetch(until_eof=True):
                reference_name, p_sites = self._p_sites_from_read(read)
                if self.scan_stats["total_records_scanned"] % self.progress_every == 0:
                    self._print_scan_progress(force=True)
                if reference_name is None:
                    continue
                self.mrna_dict[reference_name].reads[p_sites] += 1

        self._print_scan_progress(force=True)

    @staticmethod
    def _read_length_from_worker(read) -> Optional[int]:
        """Return read length in a multiprocessing worker."""
        read_length = read.infer_read_length()
        if read_length is None:
            read_length = read.query_length
        return read_length

    @staticmethod
    def _p_sites_from_worker(
        read,
        transcript_lengths: Dict[str, int],
        min_length: int,
        max_length: int,
        offset: Dict[int, List[int]],
        pair_end: bool,
        rolling: bool,
        stats: Counter,
    ) -> Tuple[Optional[str], List[int]]:
        """Return valid read positions for one alignment in a worker."""
        stats["total_records_scanned"] += 1

        if read.is_unmapped:
            stats["skipped_unmapped"] += 1
            return None, []

        if read.is_reverse and not pair_end:
            stats["skipped_reverse"] += 1
            return None, []

        reference_name = read.reference_name
        if reference_name not in transcript_lengths:
            stats["skipped_reference"] += 1
            return None, []

        read_length = RNA._read_length_from_worker(read)
        if read_length is None:
            stats["skipped_missing_length"] += 1
            return None, []

        if read_length < min_length or read_length > max_length:
            stats["skipped_length"] += 1
            return None, []

        offset_sites = offset.get(read_length)
        if not offset_sites:
            stats["skipped_no_offset"] += 1
            return None, []

        if offset_sites[0] == -1:
            positions = read.get_reference_positions(full_length=False)
        elif rolling:
            blocks = read.get_blocks()
            if not blocks:
                stats["skipped_empty_blocks"] += 1
                return None, []
            map_start, map_end = blocks[0]
            positions = list(np.arange(map_start, map_end, 32))
        else:
            map_start = read.reference_start
            if map_start is None or map_start < 0:
                stats["skipped_empty_blocks"] += 1
                return None, []
            positions = [map_start + int(site) for site in offset_sites]

        transcript_length = transcript_lengths[reference_name]
        valid_positions = [site for site in positions if 0 <= int(site) < transcript_length]
        if len(valid_positions) < len(positions):
            stats["skipped_out_of_bounds_site"] += len(positions) - len(valid_positions)

        if not valid_positions:
            stats["skipped_no_valid_site"] += 1
            return None, []

        stats["passed_reads"] += 1
        stats["counted_sites"] += len(valid_positions)
        return reference_name, valid_positions

    @staticmethod
    def _scan_bam_fetch_worker(args) -> Tuple[Counter, Dict[str, Tuple[np.ndarray, np.ndarray]]]:
        """Scan a subset of indexed BAM references in a multiprocessing worker."""
        (
            bam_file,
            read_format,
            gene_list,
            transcript_lengths,
            min_length,
            max_length,
            offset,
            pair_end,
            rolling,
        ) = args

        stats = Counter()
        position_dict = {}

        with pysam.AlignmentFile(bam_file, read_format) as bam_in:
            for gene in gene_list:
                if gene not in transcript_lengths:
                    continue
                try:
                    gene_reads = bam_in.fetch(gene)
                except (ValueError, KeyError):
                    stats["skipped_missing_reference_in_bam"] += 1
                    continue

                for read in gene_reads:
                    reference_name, p_sites = RNA._p_sites_from_worker(
                        read=read,
                        transcript_lengths=transcript_lengths,
                        min_length=min_length,
                        max_length=max_length,
                        offset=offset,
                        pair_end=pair_end,
                        rolling=rolling,
                        stats=stats,
                    )
                    if reference_name is None:
                        continue
                    position_dict.setdefault(reference_name, []).extend(int(site) for site in p_sites)

        updates = {}
        for gene, positions in position_dict.items():
            if not positions:
                continue
            position_array = np.asarray(positions, dtype=np.int64)
            unique_positions, counts = np.unique(position_array, return_counts=True)
            updates[gene] = (
                unique_positions.astype(np.int64, copy=False),
                counts.astype(np.uint32, copy=False),
            )

        return stats, updates

    def _can_use_indexed_parallel_scan(self) -> bool:
        """Return whether indexed BAM parallel scanning is available."""
        if self.thread <= 1:
            return False
        if self.sample_format.lower() != ".bam":
            return False

        try:
            with pysam.AlignmentFile(self.bam, "rb") as bam_in:
                return bool(bam_in.has_index())
        except (OSError, ValueError):
            return False

    def _split_gene_chunks(self) -> List[List[str]]:
        """Split transcript IDs into balanced chunks for indexed BAM parallel scanning."""
        gene_list = list(self.mrna_dict.keys())
        if not gene_list:
            return []

        # Too many chunks repeatedly open the same BAM file and increase random I/O.
        # Four chunks per worker usually keeps enough load balance while limiting BAM-open overhead.
        chunk_count = min(len(gene_list), max(self.thread * 4, self.thread))
        chunk_size = int(ceil(len(gene_list) / chunk_count))
        return [gene_list[i : i + chunk_size] for i in range(0, len(gene_list), chunk_size)]

    def _merge_density_updates(self, updates: Dict[str, Tuple[np.ndarray, np.ndarray]]) -> None:
        """Merge sparse worker density updates into transcript read arrays."""
        for gene, (positions, counts) in updates.items():
            if gene not in self.mrna_dict:
                continue
            if positions is None or len(positions) == 0:
                continue
            position_array = np.asarray(positions, dtype=np.int64)
            count_array = np.asarray(counts, dtype=self.mrna_dict[gene].reads.dtype)
            self.mrna_dict[gene].reads[position_array] += count_array

    @staticmethod
    def _parallel_context() -> mp.context.BaseContext:
        """Return a process context that is safer than the default fork mode for pysam."""
        for method in ("forkserver", "spawn"):
            try:
                return mp.get_context(method)
            except ValueError:
                continue
        return mp.get_context()

    def _scan_bam_parallel(self) -> None:
        """Scan indexed BAM references with process workers and accumulate read counts.

        The default Linux fork backend can be fast but may trigger a pysam/htslib
        segmentation fault during interpreter shutdown. This function therefore uses
        forkserver when available and falls back to spawn. Both backends keep process-level
        parallelism while avoiding unsafe fork-after-htslib state.
        """
        read_format = "rb"
        sys.stdout.writelines("import file: {bam}.\n".format(bam=self.bam))

        ctx = self._parallel_context()
        print(
            "Start scanning alignments with {threads} workers ({backend}).".format(
                threads=self.thread, backend=ctx.get_start_method()
            ),
            flush=True,
        )

        gene_chunks = self._split_gene_chunks()
        if not gene_chunks:
            return

        transcript_lengths = {gene: int(mrna.length) for gene, mrna in self.mrna_dict.items()}
        worker_args = [
            (
                self.bam,
                read_format,
                chunk,
                transcript_lengths,
                int(self.min_length),
                int(self.max_length),
                self.offset,
                self.pair_end,
                self.rolling,
            )
            for chunk in gene_chunks
        ]

        self.scan_start_time = time.time()
        last_reported = 0

        with ctx.Pool(processes=self.thread) as pool:
            for stats, updates in pool.imap_unordered(RNA._scan_bam_fetch_worker, worker_args, chunksize=1):
                self.scan_stats.update(stats)
                self._merge_density_updates(updates)

                scanned = int(self.scan_stats.get("total_records_scanned", 0))
                if scanned - last_reported >= self.progress_every:
                    self._print_scan_progress(force=True)
                    last_reported = scanned

        if int(self.scan_stats.get("total_records_scanned", 0)) != last_reported:
            self._print_scan_progress(force=True)

    def read_bam(self):
        """Import BAM/SAM alignments and accumulate transcript read density."""
        if self._can_use_indexed_parallel_scan():
            self._scan_bam_parallel()
            return

        if self.thread > 1:
            print(
                "Thread > 1 was requested, but indexed BAM parallel scanning is unavailable; fallback to stream mode.",
                flush=True,
            )
        self._scan_bam_stream()

    @staticmethod
    def _trim_info_from_isoform(isoform: Mrna) -> OrderedDict:
        """Return trimmed transcript metadata without mutating the source object."""
        utr5_length = int(isoform.utr5_length)
        cds_length = int(isoform.cds_length)
        utr3_length = int(isoform.utr3_length)

        if cds_length % 3 != 0:
            shift_cds = cds_length % 3
            cds_length -= shift_cds
            utr3_length += shift_cds

        shift_5 = utr5_length % 3
        shift_3 = utr3_length % 3

        trimmed_utr5_nt = utr5_length - shift_5
        trimmed_utr3_nt = utr3_length - shift_3
        trim_length_nt = isoform.length - shift_5 - shift_3
        codon_count = trim_length_nt // 3

        return OrderedDict(
            [
                ("shift5_nt", int(shift_5)),
                ("shift3_nt", int(shift_3)),
                ("start_nt0", int(shift_5)),
                ("end_nt0", int(isoform.length - shift_3)),
                ("trim_length_nt", int(trim_length_nt)),
                ("codon_count", int(codon_count)),
                ("utr5_nt", int(trimmed_utr5_nt)),
                ("cds_nt", int(cds_length)),
                ("utr3_nt", int(trimmed_utr3_nt)),
                ("utr5_codons", int(trimmed_utr5_nt // 3)),
                ("cds_codons", int(cds_length // 3)),
                ("utr3_codons", int(trimmed_utr3_nt // 3)),
            ]
        )

    @staticmethod
    def _trim_array(values: np.ndarray, shift5: int, shift3: int) -> np.ndarray:
        """Trim a one-dimensional array using 5' and 3' nucleotide shifts."""
        if shift3:
            return values[shift5:-shift3]
        return values[shift5:]

    @staticmethod
    def _trim_sequence(seq, shift5: int, shift3: int) -> str:
        """Trim transcript sequence using 5' and 3' nucleotide shifts."""
        if shift3:
            return str(seq[shift5:-shift3])
        return str(seq[shift5:])

    @staticmethod
    def _dense_density(trim_reads: np.ndarray) -> OrderedDict:
        """Return dense codon-frame density arrays."""
        return OrderedDict(
            [
                ("encoding", DENSE_ENCODING),
                ("index_base", 0),
                ("f0", [int(x) for x in trim_reads[0::3]]),
                ("f1", [int(x) for x in trim_reads[1::3]]),
                ("f2", [int(x) for x in trim_reads[2::3]]),
            ]
        )

    @staticmethod
    def _sparse_density(trim_reads: np.ndarray) -> OrderedDict:
        """Return sparse codon-frame density arrays."""
        nonzero_nt = np.flatnonzero(trim_reads)
        codon_index = (nonzero_nt // 3).astype(int)
        frame = (nonzero_nt % 3).astype(int)
        count = trim_reads[nonzero_nt].astype(int)

        return OrderedDict(
            [
                ("encoding", SPARSE_ENCODING),
                ("index_base", 0),
                ("codon_index", codon_index.tolist()),
                ("frame", frame.tolist()),
                ("count", count.tolist()),
            ]
        )

    def _density_from_trimmed_reads(self, trim_reads: np.ndarray) -> OrderedDict:
        """Encode trimmed read density using the selected encoding."""
        if self.density_encoding == "dense":
            return self._dense_density(trim_reads)
        return self._sparse_density(trim_reads)

    @staticmethod
    def _annotation_from_isoform(isoform: Mrna) -> OrderedDict:
        """Build JSON-serializable annotation metadata from an isoform."""
        return OrderedDict(
            [
                ("source", isoform.annotation_source),
                ("coordinate_system", isoform.coordinate_system),
                ("chromosome", str(isoform.chromosome)),
                ("gene_id", str(isoform.gene_id)),
                ("transcript_id", str(isoform.transcript_id)),
                ("strand", str(isoform.strand)),
                ("tx_start", None if isoform.tx_start is None else int(isoform.tx_start)),
                ("tx_end", None if isoform.tx_end is None else int(isoform.tx_end)),
                ("cds_start", None if isoform.cds_start is None else int(isoform.cds_start)),
                ("cds_end", None if isoform.cds_end is None else int(isoform.cds_end)),
                ("cds_tx_start", None if isoform.cds_tx_start is None else int(isoform.cds_tx_start)),
                ("cds_tx_end", None if isoform.cds_tx_end is None else int(isoform.cds_tx_end)),
                ("utr5_length", int(isoform.utr5_length)),
                ("cds_length", int(isoform.cds_length)),
                ("utr3_length", int(isoform.utr3_length)),
                ("transcript_length", int(isoform.length)),
                ("exon_count", None if isoform.exon_count is None else int(isoform.exon_count)),
                ("exon_starts", [int(x) for x in isoform.exon_starts]),
                ("exon_ends", [int(x) for x in isoform.exon_ends]),
                ("exon_frames", [int(x) for x in isoform.exon_frames]),
                ("cds_start_stat", isoform.cds_start_stat),
                ("cds_end_stat", isoform.cds_end_stat),
                ("representative", bool(isoform.representative)),
                ("modified", bool(isoform.is_modified)),
            ]
        )

    def _record_from_isoform(self, name: str, isoform: Mrna) -> OrderedDict:
        """Build one compact JSON-serializable transcript density record.

        Notes
        -----
        The JSON schema is multi-sample compatible by design. A single-sample
        ``rna_Density`` output stores its density under ``samples[sample_name]``.
        ``rpf_Merge`` can then merge multiple JSONL files by adding more sample
        entries without duplicating annotation, sequence, or genome mapping data.
        """
        trim_info = self._trim_info_from_isoform(isoform)
        shift5 = trim_info["shift5_nt"]
        shift3 = trim_info["shift3_nt"]

        trim_seq = self._trim_sequence(isoform.seq, shift5, shift3)
        trim_reads = self._trim_array(isoform.reads, shift5, shift3)
        density = self._density_from_trimmed_reads(trim_reads)

        sample_record = OrderedDict(
            [
                ("profile", str(self.profile)),
                ("density", density),
            ]
        )

        return OrderedDict(
            [
                ("record_type", "transcript"),
                ("transcript_id", str(isoform.transcript_id)),
                ("gene_id", str(isoform.gene_id)),
                ("name", str(name)),
                ("chromosome", str(isoform.chromosome)),
                ("strand", str(isoform.strand)),
                ("length_nt", int(isoform.length)),
                ("utr5_nt", int(isoform.utr5_length)),
                ("cds_nt", int(isoform.cds_length)),
                ("utr3_nt", int(isoform.utr3_length)),
                ("annotation", self._annotation_from_isoform(isoform)),
                ("genome_mapping", isoform.genome_mapping),
                ("trim", trim_info),
                ("sequence", trim_seq),
                ("samples", OrderedDict([(self.sample_name, sample_record)])),
            ]
        )

    def iter_density_records(self) -> Iterator[OrderedDict]:
        """Yield compact density records one transcript at a time."""
        for name, isoform in self.mrna_dict.items():
            yield self._record_from_isoform(name, isoform)

    def _json_output_path(self) -> str:
        """Return default gzip-compressed compact JSONL output path."""
        return self.output + "_rna.jsonl.gz"

    def write_density_json(self) -> str:
        """Write compact RNA-seq density records as JSONL."""
        out_json = self._json_output_path()
        record_count = 0
        with gzip.open(out_json, "wt", encoding="utf-8") as out:
            for record in self.iter_density_records():
                out.write(json.dumps(record, ensure_ascii=False, separators=(",", ":")))
                out.write("\n")
                record_count += 1

        self.json_path = out_json
        print("Compact RNA-seq density JSONL written: {path}".format(path=out_json), flush=True)
        print("Transcript records written: {count}".format(count=record_count), flush=True)
        return out_json

    @staticmethod
    def _legacy_header(sample_name: str) -> List[str]:
        """Return legacy codon-level TXT header for one sample."""
        return RNA._legacy_header_from_samples([sample_name])

    @staticmethod
    def _legacy_header_from_samples(sample_names: List[str]) -> List[str]:
        """Return legacy codon-level TXT header for one or more samples."""
        header = ["name", "now_nt", "from_tis", "from_tts", "region", "codon"]
        for sample_name in sample_names:
            header.extend([sample_name + "_f0", sample_name + "_f1", sample_name + "_f2"])
        return header

    @staticmethod
    def _sample_names_from_record(record: Dict) -> List[str]:
        """Return sample names stored in a compact density record."""
        samples = record.get("samples")
        if isinstance(samples, dict) and samples:
            return [str(sample) for sample in samples.keys()]
        return [str(record.get("sample", "sample"))]

    @staticmethod
    def _density_for_sample(record: Dict, sample_name: Optional[str] = None) -> Dict:
        """Return the density object for one sample from new or legacy JSON records."""
        samples = record.get("samples")
        if isinstance(samples, dict) and samples:
            if sample_name is None:
                sample_name = next(iter(samples.keys()))
            sample_entry = samples.get(sample_name)
            if sample_entry is None:
                return {}
            if isinstance(sample_entry, dict) and "density" in sample_entry:
                return sample_entry.get("density") or {}
            # Defensive fallback for records that store sample -> density directly.
            if isinstance(sample_entry, dict):
                return sample_entry
            return {}

        # Backward compatibility for rna_Density.001-.007 JSON records.
        return record.get("density") or {}

    @staticmethod
    def _density_to_dense_frames(record: Dict, sample_name: Optional[str] = None) -> Tuple[List[int], List[int], List[int]]:
        """Return dense frame arrays from sparse or dense density encoding."""
        trim = record["trim"]
        codon_count = int(trim["codon_count"])
        density = RNA._density_for_sample(record, sample_name=sample_name)
        encoding = density.get("encoding", SPARSE_ENCODING)

        if encoding == DENSE_ENCODING:
            f0 = [int(x) for x in density.get("f0", [])]
            f1 = [int(x) for x in density.get("f1", [])]
            f2 = [int(x) for x in density.get("f2", [])]
            # Fill missing trailing positions defensively.
            if len(f0) < codon_count:
                f0.extend([0] * (codon_count - len(f0)))
            if len(f1) < codon_count:
                f1.extend([0] * (codon_count - len(f1)))
            if len(f2) < codon_count:
                f2.extend([0] * (codon_count - len(f2)))
            return f0[:codon_count], f1[:codon_count], f2[:codon_count]

        f0 = [0] * codon_count
        f1 = [0] * codon_count
        f2 = [0] * codon_count
        frames = (f0, f1, f2)

        for codon_index, frame, count in zip(
            density.get("codon_index", []), density.get("frame", []), density.get("count", [])
        ):
            codon_index = int(codon_index)
            frame = int(frame)
            if 0 <= codon_index < codon_count and frame in (0, 1, 2):
                frames[frame][codon_index] += int(count)

        return f0, f1, f2

    @staticmethod
    def _legacy_rows_from_record(
        record: Dict,
        sample_names: Optional[List[str]] = None,
        nonzero_only: bool = False,
    ) -> Iterator[List]:
        """Yield legacy codon-level TXT rows from one compact JSON record."""
        trim = record["trim"]
        sequence = record.get("sequence", "")
        name = record.get("name", record.get("transcript_id", "NA"))

        if sample_names is None:
            sample_names = RNA._sample_names_from_record(record)

        codon_count = int(trim["codon_count"])
        start_nt0 = int(trim["start_nt0"])
        trim_length_nt = int(trim["trim_length_nt"])
        utr5_codons = int(trim["utr5_codons"])
        cds_codons = int(trim["cds_codons"])
        utr3_nt = int(trim["utr3_nt"])

        from_tts_start = (utr3_nt - trim_length_nt) // 3 + 1
        frame_arrays = [RNA._density_to_dense_frames(record, sample_name=sample_name) for sample_name in sample_names]

        for codon_index in range(codon_count):
            sample_values = []
            total_value = 0
            for f0, f1, f2 in frame_arrays:
                value0 = int(f0[codon_index])
                value1 = int(f1[codon_index])
                value2 = int(f2[codon_index])
                sample_values.extend([value0, value1, value2])
                total_value += value0 + value1 + value2

            if nonzero_only and total_value == 0:
                continue

            if codon_index < utr5_codons:
                region = "5utr"
            elif codon_index < utr5_codons + cds_codons:
                region = "cds"
            else:
                region = "3utr"

            codon_start = codon_index * 3
            codon = sequence[codon_start : codon_start + 3]
            now_nt = start_nt0 + 1 + codon_index * 3
            from_tis = codon_index - utr5_codons
            from_tts = from_tts_start + codon_index

            yield [name, now_nt, from_tis, from_tts, region, codon] + sample_values

    def write_density_txt(self, out_txt: Optional[str] = None) -> str:
        """Write complete legacy TXT directly from in-memory density records."""
        if out_txt is None:
            out_txt = self.output + "_rna.txt"

        sample_names = [self.sample_name]
        with open(out_txt, "w", encoding="utf-8", newline="") as out:
            writer = csv.writer(out, delimiter="\t", lineterminator="\n")
            writer.writerow(self._legacy_header_from_samples(sample_names))
            for record in self.iter_density_records():
                writer.writerows(self._legacy_rows_from_record(record, sample_names=sample_names, nonzero_only=False))

        self.txt_path = out_txt
        print("Legacy RNA-seq density TXT written: {path}".format(path=out_txt), flush=True)
        return out_txt

    @staticmethod
    def json_to_txt(
        json_file: str,
        output_txt: str,
    ) -> str:
        """Convert compact RNA-seq density JSONL to the legacy codon-level TXT table.

        Parameters
        ----------
        json_file : str
            Input ``*_rna.jsonl`` or ``*_rna.jsonl.gz`` file. Both single-sample
            and merged multi-sample JSONL files are supported.
        output_txt : str
            Output legacy TXT file.
        Returns
        -------
        str
            Path of the generated TXT file.
        """
        in_handle = RNA._open_text(json_file, "rt")
        with in_handle as inp, open(output_txt, "w", encoding="utf-8", newline="") as out:
            writer = csv.writer(out, delimiter="\t", lineterminator="\n")
            header_written = False
            sample_names = None
            record_count = 0
            row_count = 0

            for line in inp:
                line = line.strip()
                if not line:
                    continue
                record = json.loads(line)
                if record.get("record_type") != "transcript":
                    continue

                if sample_names is None:
                    sample_names = RNA._sample_names_from_record(record)
                    writer.writerow(RNA._legacy_header_from_samples(sample_names))
                    header_written = True

                for row in RNA._legacy_rows_from_record(record, sample_names=sample_names, nonzero_only=False):
                    writer.writerow(row)
                    row_count += 1
                record_count += 1

            if not header_written:
                writer.writerow(RNA._legacy_header_from_samples(["sample"]))

        print(
            "JSONL to TXT conversion done: {records} records, {rows} rows.".format(
                records=record_count, rows=row_count
            ),
            flush=True,
        )
        return output_txt

    def write_summary(self) -> str:
        """Write RNA-seq read density generation summary as JSON."""
        summary = OrderedDict(
            [
                ("sample", self.sample_name),
                ("input_bam_or_sam", self.bam),
                ("transcript_file", self.mrna_file),
                ("sequence_file", self.mrna_seq),
                ("transcript_annotation_format", self.transcript_annotation_format or "NA"),
                ("offset_file", self.psite),
                ("output_prefix", self.output),
                ("output_format", self.output_format),
                ("density_encoding", self.density_encoding),
                ("profile", self.profile),
                ("min_length", int(self.min_length)),
                ("max_length", int(self.max_length)),
                ("drop_warning", bool(self.drop_warning)),
                ("longest", bool(self.longest)),
                ("rolling", bool(self.rolling)),
                ("pair_end", bool(self.pair_end)),
                ("thread", int(self.thread)),
                ("transcripts_retained", int(len(self.mrna_dict))),
                ("json_output", self.json_path or "NA"),
                ("txt_output", self.txt_path or "NA"),
                ("scan_stats", OrderedDict((key, int(value)) for key, value in sorted(self.scan_stats.items()))),
            ]
        )

        out_json = self.output + "_rna.summary.json"
        with open(out_json, "w", encoding="utf-8") as out:
            json.dump(summary, out, indent=2, ensure_ascii=False)
            out.write("\n")

        self.summary_path = out_json
        print("RNA-seq density summary written: {path}".format(path=out_json), flush=True)
        return out_json

    def output_density(self):
        """Write RNA-seq read density output according to selected format."""
        output_format = str(self.output_format).lower()

        if output_format in ("json", "both"):
            self.write_density_json()
        if output_format in ("txt", "both"):
            self.write_density_txt()

        if output_format not in ("json", "txt", "both"):
            raise ValueError("Unsupported output format: {fmt}".format(fmt=self.output_format))

        self.write_summary()

    # Backward-compatible method names retained for old callers.
    def run_format_reads_with_multi_thread(self):
        """Deprecated compatibility wrapper.

        The new implementation writes compact records directly in
        ``output_density`` and no longer expands all genes into one large
        in-memory pandas DataFrame.
        """
        print(
            "run_format_reads_with_multi_thread is deprecated; compact records are generated during output_density.",
            flush=True,
        )

    @staticmethod
    def format_reads(args):
        """Deprecated compatibility method for legacy callers.

        This method is intentionally kept minimal. New code should use JSONL
        records and ``json_to_txt`` for compatibility conversion.
        """
        gene_list, mrna_dict, out_prefix = args
        reads_list = []
        fake_args = type("Args", (), {})()
        fake_args.transcript = "NA"
        fake_args.sequence = "NA"
        fake_args.bam = "NA.bam"
        fake_args.psite = "NA"
        fake_args.drop_warning = False
        fake_args.min = 0
        fake_args.max = 999
        fake_args.thread = 1
        fake_args.output = out_prefix
        fake_args.output_format = "txt"
        fake_args.density_encoding = "sparse"
        fake_args.longest = False
        fake_args.silence = True
        fake_args.rolling = False
        fake_args.pair_end = False
        rna = RNA(fake_args)
        rna.mrna_dict = OrderedDict((name, mrna_dict[name]) for name in gene_list)
        rna.profile = "unknown"

        for record in rna.iter_density_records():
            header = RNA._legacy_header(rna.sample_name)
            rows = list(RNA._legacy_rows_from_record(record))
            if rows:
                reads_list.append(pd.DataFrame(rows, columns=header))

        if not reads_list:
            return pd.DataFrame(columns=RNA._legacy_header(os.path.basename(out_prefix)))
        return pd.concat(reads_list, ignore_index=True)
