#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-07-09
# Version: 0.2.8-dev.002
# Function: Provide RiboParser core functions for RPF density data import and analysis.
# Input: RiboParser compact JSONL density files or legacy codon-level TXT density files.
# Output: Polars/Pandas RPF density objects and summary tables for downstream modules.

"""RPF density import and transformation utilities for RiboParser.

This module provides a compatibility layer for downstream RiboParser analysis
steps. The public ``import_rpf`` function keeps the historical return structure,
while the internal reader now supports both current compact JSONL density files
and legacy codon-level TXT density files.

Current JSONL records are expected to use the ``samples`` structure generated by
updated ``rpf_Density`` and ``rpf_Merge`` workflows.
"""

from __future__ import annotations

import gzip
import json
import os
import re
import sys
from collections.abc import Iterable, Iterator, Sequence
from dataclasses import dataclass, field
from typing import Any

import pandas as pd
import polars as pl


BASE_COLUMNS = ["name", "now_nt", "from_tis", "from_tts", "region", "codon"]
FRAME_SUFFIXES = ("_f0", "_f1", "_f2")
SPARSE_ENCODING = "sparse_codon_frame"
DENSE_ENCODING = "dense_codon_frame"
PROGRESS_EVERY = 1000


# -----------------------------------------------------------------------------
# Low-level file and type helpers
# -----------------------------------------------------------------------------


def _open_text(path: str, mode: str = "rt"):
    """Open plain text or gzip-compressed text files."""
    if path.endswith(".gz"):
        return gzip.open(path, mode, encoding="utf-8", newline="")
    return open(path, mode, encoding="utf-8", newline="")


def _to_int(value: Any, default: int = 0) -> int:
    """Safely convert one value to integer."""
    try:
        return int(value)
    except (TypeError, ValueError):
        try:
            return int(float(value))
        except (TypeError, ValueError):
            return default


def _detect_rpf_format(rpf_file: str) -> str:
    """Detect RPF density file format as ``json`` or ``txt``."""
    lower_name = rpf_file.lower()

    if lower_name.endswith((".jsonl.gz", ".jsonl", ".json.gz", ".json")):
        return "json"

    if lower_name.endswith((".txt", ".tsv", ".tab")):
        return "txt"

    with _open_text(rpf_file, "rt") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            if line.startswith("{"):
                return "json"
            return "txt"

    raise ValueError(f"Cannot detect density file format from empty file: {rpf_file}")


def _normalize_sample_name(sample_name: str | Sequence[str] | None) -> list[str] | None:
    """Normalize a user-provided sample name argument."""
    if sample_name is None:
        return None
    if isinstance(sample_name, str):
        if not sample_name:
            return None
        return [sample_name]
    return [str(item) for item in sample_name]


def _frame_columns(sample_name: str) -> list[str]:
    """Return three frame column names for one sample."""
    return [f"{sample_name}_f0", f"{sample_name}_f1", f"{sample_name}_f2"]


def _sample_from_frame_column(column: str) -> str:
    """Return sample name from a frame column name."""
    if column.endswith(FRAME_SUFFIXES):
        return column[:-3]
    return column


def _is_frame_column(column: str) -> bool:
    """Return whether one column is a frame density column."""
    return column.endswith(FRAME_SUFFIXES)


# -----------------------------------------------------------------------------
# Gene list and filtering helpers
# -----------------------------------------------------------------------------


def _read_gene_filter(gene: str | None) -> set[str] | None:
    """Read transcript IDs from a gene list file."""
    if not gene:
        return None

    gene_csv = pd.read_csv(gene, header=0, index_col=None, sep="\t")
    if "transcript_id" in gene_csv.columns:
        gene_name = gene_csv["transcript_id"].astype(str).tolist()
    else:
        gene_name = gene_csv.iloc[:, 0].astype(str).tolist()

    return set(gene_name)


def _row_pass_filter(
    name: str,
    codon: str,
    from_tis: int,
    from_tts: int,
    gene_filter: set[str] | None = None,
    tis: int | None = None,
    tts: int | None = None,
) -> bool:
    """Check whether one codon-level row passes common filters."""
    if gene_filter is not None and name not in gene_filter:
        return False

    if tis is not None and from_tis < tis:
        return False

    if tts is not None and from_tts > -tts:
        return False

    if "N" in codon.upper():
        return False

    return True


# -----------------------------------------------------------------------------
# JSONL reader
# -----------------------------------------------------------------------------


def iter_json_records(json_file: str) -> Iterator[dict[str, Any]]:
    """Yield current RPF density transcript records from JSONL."""
    with _open_text(json_file, "rt") as handle:
        for line_number, line in enumerate(handle, start=1):
            line = line.strip()
            if not line:
                continue

            record = json.loads(line)
            if record.get("record_type") != "transcript":
                continue

            samples = record.get("samples")
            if not isinstance(samples, dict) or not samples:
                raise ValueError(
                    "Invalid RPF density JSON record at line {line}: "
                    "missing non-empty 'samples' dictionary.".format(line=line_number)
                )

            yield record


def get_json_sample_names(json_file: str) -> list[str]:
    """Collect sample names from the first current JSONL transcript record."""
    for record in iter_json_records(json_file):
        return [str(sample) for sample in record["samples"].keys()]
    raise ValueError(f"No transcript records were found in JSON density file: {json_file}")


def _density_for_sample(record: dict[str, Any], sample_name: str) -> dict[str, Any]:
    """Return the density object for one sample from a current JSON record."""
    sample_entry = record["samples"].get(sample_name)
    if not isinstance(sample_entry, dict):
        return {}

    density = sample_entry.get("density")
    if not isinstance(density, dict):
        return {}

    return density


def density_to_frame_arrays(
    record: dict[str, Any],
    sample_name: str,
    codon_count: int | None = None,
) -> tuple[list[int], list[int], list[int]]:
    """Convert sparse or dense JSON density to three dense frame arrays."""
    if codon_count is None:
        codon_count = _to_int(record.get("trim", {}).get("codon_count"), 0)

    density = _density_for_sample(record, sample_name)
    encoding = str(density.get("encoding", SPARSE_ENCODING))

    if encoding in {DENSE_ENCODING, "dense"}:
        f0 = [_to_int(x) for x in density.get("f0", density.get("frame0", []))]
        f1 = [_to_int(x) for x in density.get("f1", density.get("frame1", []))]
        f2 = [_to_int(x) for x in density.get("f2", density.get("frame2", []))]

        if len(f0) < codon_count:
            f0.extend([0] * (codon_count - len(f0)))
        if len(f1) < codon_count:
            f1.extend([0] * (codon_count - len(f1)))
        if len(f2) < codon_count:
            f2.extend([0] * (codon_count - len(f2)))

        return f0[:codon_count], f1[:codon_count], f2[:codon_count]

    if encoding not in {SPARSE_ENCODING, "sparse"}:
        raise ValueError(
            "Unsupported density encoding '{encoding}' in transcript '{transcript}' sample '{sample}'.".format(
                encoding=encoding,
                transcript=record.get("transcript_id", "NA"),
                sample=sample_name,
            )
        )

    f0 = [0] * codon_count
    f1 = [0] * codon_count
    f2 = [0] * codon_count
    frames = (f0, f1, f2)

    for codon_index, frame, count in zip(
        density.get("codon_index", []),
        density.get("frame", []),
        density.get("count", []),
    ):
        codon_index = _to_int(codon_index, -1)
        frame = _to_int(frame, -1)
        if 0 <= codon_index < codon_count and frame in (0, 1, 2):
            frames[frame][codon_index] += _to_int(count)

    return f0, f1, f2


def _region_from_codon_index(codon_index: int, utr5_codons: int, cds_codons: int) -> str:
    """Return transcript region name for one codon index."""
    if codon_index < utr5_codons:
        return "5utr"
    if codon_index < utr5_codons + cds_codons:
        return "cds"
    return "3utr"


def _init_column_store(sample_names: Sequence[str]) -> dict[str, list[Any]]:
    """Initialize a column-oriented codon-level table store."""
    store: dict[str, list[Any]] = {column: [] for column in BASE_COLUMNS}
    for sample in sample_names:
        for column in _frame_columns(str(sample)):
            store[column] = []
    return store


def _append_record_to_store(
    store: dict[str, list[Any]],
    record: dict[str, Any],
    sample_names: Sequence[str],
    gene_filter: set[str] | None = None,
    tis: int | None = None,
    tts: int | None = None,
) -> int:
    """Append one JSON transcript record to a column-oriented table store."""
    trim = record.get("trim")
    if not isinstance(trim, dict):
        raise ValueError(
            "Transcript '{transcript}' has no valid 'trim' dictionary.".format(
                transcript=record.get("transcript_id", "NA")
            )
        )

    name = str(record.get("name") or record.get("transcript_id") or "NA")
    codon_count = _to_int(trim.get("codon_count"), 0)
    if codon_count <= 0:
        return 0

    start_nt0 = _to_int(trim.get("start_nt0"), 0)
    trim_length_nt = _to_int(trim.get("trim_length_nt"), codon_count * 3)
    utr5_codons = _to_int(trim.get("utr5_codons"), 0)
    cds_codons = _to_int(trim.get("cds_codons"), 0)
    utr3_nt = _to_int(trim.get("utr3_nt"), 0)
    from_tts_start = (utr3_nt - trim_length_nt) // 3 + 1

    sequence = str(record.get("sequence", "")).upper()
    frame_arrays = [density_to_frame_arrays(record, str(sample), codon_count) for sample in sample_names]

    appended_rows = 0

    for codon_index in range(codon_count):
        codon_start = codon_index * 3
        codon = sequence[codon_start : codon_start + 3].upper()
        from_tis = codon_index - utr5_codons
        from_tts = from_tts_start + codon_index

        if not _row_pass_filter(
            name=name,
            codon=codon,
            from_tis=from_tis,
            from_tts=from_tts,
            gene_filter=gene_filter,
            tis=tis,
            tts=tts,
        ):
            continue

        store["name"].append(name)
        store["now_nt"].append(start_nt0 + 1 + codon_index * 3)
        store["from_tis"].append(from_tis)
        store["from_tts"].append(from_tts)
        store["region"].append(_region_from_codon_index(codon_index, utr5_codons, cds_codons))
        store["codon"].append(codon)

        for sample_name, (f0, f1, f2) in zip(sample_names, frame_arrays):
            store[f"{sample_name}_f0"].append(int(f0[codon_index]))
            store[f"{sample_name}_f1"].append(int(f1[codon_index]))
            store[f"{sample_name}_f2"].append(int(f2[codon_index]))

        appended_rows += 1

    return appended_rows


def read_json_rpf_file(
    rpf_file: str,
    gene: str | None = None,
    tis: int | None = None,
    tts: int | None = None,
    sample_name: str | Sequence[str] | None = None,
) -> pl.DataFrame:
    """Read current compact JSONL RPF density as a codon-level Polars table."""
    all_sample_names = get_json_sample_names(rpf_file)
    requested_samples = _normalize_sample_name(sample_name)
    if requested_samples is None:
        selected_samples = all_sample_names
    else:
        missing = sorted(set(requested_samples) - set(all_sample_names))
        if missing:
            raise ValueError(
                "Requested sample(s) not found in JSON density file: {samples}".format(
                    samples=", ".join(missing)
                )
            )
        selected_samples = requested_samples

    gene_filter = _read_gene_filter(gene)
    store = _init_column_store(selected_samples)
    record_count = 0
    row_count = 0

    for record in iter_json_records(rpf_file):
        current_samples = [str(sample) for sample in record["samples"].keys()]
        if current_samples != all_sample_names:
            raise ValueError(
                "Inconsistent sample order in transcript '{transcript}'.".format(
                    transcript=record.get("transcript_id", "NA")
                )
            )

        row_count += _append_record_to_store(
            store=store,
            record=record,
            sample_names=selected_samples,
            gene_filter=gene_filter,
            tis=tis,
            tts=tts,
        )
        record_count += 1

        if record_count % PROGRESS_EVERY == 0:
            print(f"records={record_count:,}, rows={row_count:,}", flush=True)

    print(
        "Imported JSON RPF density: records={records:,}, rows={rows:,}.".format(
            records=record_count,
            rows=row_count,
        ),
        flush=True,
    )

    return pl.DataFrame(store)


# -----------------------------------------------------------------------------
# TXT reader
# -----------------------------------------------------------------------------


def read_txt_rpf_file(
    rpf_file: str,
    gene: str | None = None,
    tis: int | None = None,
    tts: int | None = None,
    sample_name: str | Sequence[str] | None = None,
) -> pl.DataFrame:
    """Read legacy codon-level TXT RPF density as a Polars table."""
    raw_rpf = pl.read_csv(rpf_file, has_header=True, separator="\t")

    raw_rpf = raw_rpf.with_columns(pl.col("codon").cast(pl.Utf8).str.to_uppercase())
    raw_rpf = raw_rpf.filter(~pl.col("codon").str.contains("N"))

    if gene:
        gene_filter = _read_gene_filter(gene) or set()
        raw_rpf = raw_rpf.filter(pl.col("name").cast(pl.Utf8).is_in(list(gene_filter)))

    raw_rpf = filter_tis_tts(raw_rpf, tis, tts)

    requested_samples = _normalize_sample_name(sample_name)
    if requested_samples is not None:
        keep_columns = BASE_COLUMNS.copy()
        for sample in requested_samples:
            keep_columns.extend(_frame_columns(sample))
        missing_columns = [column for column in keep_columns if column not in raw_rpf.columns]
        if missing_columns:
            raise ValueError(
                "Requested sample frame column(s) not found in TXT density file: {columns}".format(
                    columns=", ".join(missing_columns)
                )
            )
        raw_rpf = raw_rpf.select(keep_columns)

    return raw_rpf


# -----------------------------------------------------------------------------
# Public compatibility functions
# -----------------------------------------------------------------------------


def read_rpf_file(rpf_file: str) -> pl.DataFrame:
    """Import an RPF density file as a codon-level Polars table.

    Parameters
    ----------
    rpf_file : str
        RPF density file generated by ``rpf_Density`` or ``rpf_Merge``. Both
        current JSONL and legacy TXT formats are supported.

    Returns
    -------
    polars.DataFrame
        Codon-level table with base columns and sample frame columns.
    """
    file_format = _detect_rpf_format(rpf_file)
    if file_format == "json":
        return read_json_rpf_file(rpf_file)
    return read_txt_rpf_file(rpf_file)


def get_frame_rpf(raw_rpf: pl.DataFrame, sample_name: Sequence[str], frame: str) -> pd.DataFrame:
    """Merge all frame density or retrieve one frame as a Pandas table.

    Notes
    -----
    Polars expressions in ``with_columns`` can only reference columns that are
    already present in the dataframe being modified. Therefore this function
    builds the final table directly from the full ``raw_rpf`` dataframe instead
    of first selecting only the six metadata columns.
    """
    frame = str(frame)

    missing_base = [column for column in BASE_COLUMNS if column not in raw_rpf.columns]
    if missing_base:
        raise ValueError(
            "RPF density table is missing required base column(s): {columns}".format(
                columns=", ".join(missing_base)
            )
        )

    select_exprs = [pl.col(column) for column in BASE_COLUMNS]

    if frame == "all":
        for now_sp in sample_name:
            print("Import the density file {file_name}.".format(file_name=now_sp), flush=True)
            f0, f1, f2 = _frame_columns(now_sp)
            missing_frame = [column for column in (f0, f1, f2) if column not in raw_rpf.columns]
            if missing_frame:
                raise ValueError(
                    "RPF density table is missing frame column(s) for sample {sample}: {columns}".format(
                        sample=now_sp,
                        columns=", ".join(missing_frame),
                    )
                )
            select_exprs.append(
                pl.sum_horizontal([pl.col(f0), pl.col(f1), pl.col(f2)]).alias(now_sp)
            )
    elif frame in {"0", "1", "2"}:
        for now_sp in sample_name:
            print("Import the density file {file_name}.".format(file_name=now_sp), flush=True)
            now_sp_index = f"{now_sp}_f{frame}"
            if now_sp_index not in raw_rpf.columns:
                raise ValueError(
                    "RPF density table is missing frame column for sample {sample}: {column}".format(
                        sample=now_sp,
                        column=now_sp_index,
                    )
                )
            select_exprs.append(pl.col(now_sp_index).alias(now_sp))
    else:
        raise ValueError("frame must be one of '0', '1', '2', or 'all'.")

    merged_rpf = raw_rpf.select(select_exprs)
    return merged_rpf.to_pandas()


def set_codon_shift(sites: str) -> int:
    """Set codon shift by E/P/A site."""
    if sites == "E":
        return -1
    if sites == "P":
        return 0
    if sites == "A":
        return 1
    return 0


def shift_site(merged_rpf: pd.DataFrame, sample_name: Sequence[str], shift_num: int) -> pd.DataFrame:
    """Shift codon-level density from P-site to E-site or A-site."""
    if shift_num == 0:
        return merged_rpf

    merged_rpf.loc[:, list(sample_name)] = (
        merged_rpf.groupby("name", sort=False)[list(sample_name)]
        .shift(shift_num)
        .fillna(0)
        .values
    )

    return merged_rpf


def sum_total_rpf(raw_rpf: pl.DataFrame) -> pd.Series:
    """Calculate total RPF count for each sample across all three frames."""
    frame_columns = [column for column in raw_rpf.columns if _is_frame_column(column)]
    if not frame_columns:
        return pd.Series(dtype="int64", name="total_rpf")

    total_rpf_num = raw_rpf.select(frame_columns).sum().to_pandas().T.reset_index()
    total_rpf_num.columns = ["sample_frame", "total_rpf"]
    total_rpf_num["sample"] = total_rpf_num["sample_frame"].map(_sample_from_frame_column)
    total_rpf_num = total_rpf_num.groupby("sample", sort=False)["total_rpf"].sum()

    return total_rpf_num


def high_expression(
    merged_rpf: pd.DataFrame,
    total_rpf_num: pd.Series,
    sample_name: Sequence[str],
    rpf_num: int,
) -> tuple[pd.DataFrame, pd.Index, pd.DataFrame]:
    """Filter high-expression genes using the mean RPF count across samples."""
    gene_rpf_sum = merged_rpf.groupby("name", sort=False)[list(sample_name)].sum()
    high_gene = gene_rpf_sum.loc[gene_rpf_sum.mean(axis=1) >= rpf_num, :].index
    high_rpf = merged_rpf.loc[merged_rpf["name"].isin(high_gene), :]

    return gene_rpf_sum, high_gene, high_rpf


def sum_sample_number(raw_rpf: pl.DataFrame, sample_num: int | None) -> int:
    """Return the number of samples in an RPF table."""
    if sample_num:
        return int(sample_num)

    sample_names = retrieve_sample_name(raw_rpf, None)
    return len(sample_names)


def retrieve_sample_name(
    raw_rpf: pl.DataFrame,
    sample_name: str | Sequence[str] | None,
) -> list[str]:
    """Retrieve sample names from frame density columns."""
    normalized = _normalize_sample_name(sample_name)
    if normalized is not None:
        return normalized

    sample_names = []
    seen = set()
    for column in raw_rpf.columns:
        if not _is_frame_column(column):
            continue
        sample = _sample_from_frame_column(column)
        if sample not in seen:
            sample_names.append(sample)
            seen.add(sample)

    return sample_names


def filter_tis_tts(raw_rpf: pl.DataFrame, tis: int | None, tts: int | None) -> pl.DataFrame:
    """Trim the RPF table by TIS/TTS codon offsets."""
    if tis is not None:
        raw_rpf = raw_rpf.filter(pl.col("from_tis") >= tis)

    if tts is not None:
        raw_rpf = raw_rpf.filter(pl.col("from_tts") <= -tts)

    return raw_rpf


def retrieve_gene_rpf(raw_rpf: pl.DataFrame, gene: str | None) -> pl.DataFrame:
    """Retrieve RPF rows for specific transcript IDs."""
    gene_filter = _read_gene_filter(gene)
    if gene_filter is None:
        return raw_rpf

    return raw_rpf.filter(pl.col("name").cast(pl.Utf8).is_in(list(gene_filter)))


def check_merged_rpf_results(merged_rpf: pd.DataFrame) -> None:
    """Exit if the merged density table is empty."""
    if merged_rpf.empty:
        print("Filtered density table is empty! Please recheck the parameters and data quality.", flush=True)
        sys.exit(1)


def check_high_rpf_results(high_rpf: pd.DataFrame) -> None:
    """Exit if the high-expression density table is empty."""
    if high_rpf.empty:
        print("Filtered density table is empty! Please recheck the parameters and data quality.", flush=True)
        sys.exit(1)


def rpf_to_rpm(raw_rpf: pd.DataFrame | pl.DataFrame, norm: bool):
    """Convert frame density columns to RPM values."""
    if not norm:
        return raw_rpf

    if isinstance(raw_rpf, pl.DataFrame):
        frame_columns = [column for column in raw_rpf.columns if _is_frame_column(column)]
        total_exprs = []
        totals = raw_rpf.select(frame_columns).sum().row(0, named=True)
        for column in frame_columns:
            total = totals.get(column, 0) or 0
            if total > 0:
                total_exprs.append((pl.col(column) * 1_000_000 / total).alias(column))
        return raw_rpf.with_columns(total_exprs)

    frame_columns = [column for column in raw_rpf.columns if _is_frame_column(column)]
    totals = raw_rpf.loc[:, frame_columns].sum(axis=0)
    for column in frame_columns:
        if totals[column] > 0:
            raw_rpf.loc[:, column] = raw_rpf.loc[:, column] * 1_000_000 / totals[column]
    return raw_rpf


@dataclass
class RPFData:
    """Container for codon-level RPF density tables and derived metadata."""

    raw_rpf: pl.DataFrame
    sample_name: list[str]
    sample_num: int
    total_rpf_num: pd.Series
    file_format: str
    source_file: str
    metadata: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_file(
        cls,
        rpf_file: str,
        sample_name: str | Sequence[str] | None = None,
        gene: str | None = None,
        tis: int | None = None,
        tts: int | None = None,
    ) -> "RPFData":
        """Create an ``RPFData`` object from JSONL or TXT density input."""
        file_format = _detect_rpf_format(rpf_file)

        if file_format == "json":
            raw_rpf = read_json_rpf_file(
                rpf_file=rpf_file,
                gene=gene,
                tis=tis,
                tts=tts,
                sample_name=sample_name,
            )
        else:
            raw_rpf = read_txt_rpf_file(
                rpf_file=rpf_file,
                gene=gene,
                tis=tis,
                tts=tts,
                sample_name=sample_name,
            )

        samples = retrieve_sample_name(raw_rpf, sample_name)
        totals = sum_total_rpf(raw_rpf)

        return cls(
            raw_rpf=raw_rpf,
            sample_name=samples,
            sample_num=len(samples),
            total_rpf_num=totals,
            file_format=file_format,
            source_file=os.path.abspath(rpf_file),
            metadata={"rows": raw_rpf.height, "columns": raw_rpf.width},
        )

    def get_frame(self, frame: str = "all") -> pd.DataFrame:
        """Return a sample-level codon density table for one or all frames."""
        return get_frame_rpf(self.raw_rpf, self.sample_name, frame)

    def shifted_frame(self, sites: str = "P", frame: str = "all") -> pd.DataFrame:
        """Return frame density shifted to E/P/A site."""
        merged_rpf = self.get_frame(frame=frame)
        shift_num = set_codon_shift(sites)
        return shift_site(merged_rpf, self.sample_name, shift_num)

    def high_expression(
        self,
        rpf_num: int,
        sites: str = "P",
        frame: str = "all",
    ) -> tuple[pd.DataFrame, pd.Index, pd.DataFrame]:
        """Return high-expression transcript summary and table."""
        merged_rpf = self.shifted_frame(sites=sites, frame=frame)
        return high_expression(merged_rpf, self.total_rpf_num, self.sample_name, rpf_num)


def import_rpf(
    rpf_file: str,
    sample_num: int | None,
    sample_name: str | Sequence[str] | None,
    sites: str,
    frame: str,
    gene: str | None,
    rpf_num: int,
    tis: int | None = None,
    tts: int | None = None,
):
    """Import RPF density data using the historical RiboParser return structure.

    Returns
    -------
    tuple
        ``raw_rpf, sample_name, sample_num, merged_rpf, total_rpf_num, gene_rpf_sum, high_gene, high_rpf``.
    """
    # Import and filter the RPF file. JSON input is filtered during expansion to
    # reduce memory use; TXT input is filtered after table import.
    rpf_data = RPFData.from_file(
        rpf_file=rpf_file,
        sample_name=sample_name,
        gene=gene,
        tis=tis,
        tts=tts,
    )

    raw_rpf = rpf_data.raw_rpf
    sample_name = rpf_data.sample_name
    sample_num = int(sample_num) if sample_num else rpf_data.sample_num
    total_rpf_num = rpf_data.total_rpf_num

    # Merge the RPFs of nucleotide frames to codon-level values or retrieve a
    # specific frame.
    merged_rpf = get_frame_rpf(raw_rpf, sample_name, frame)

    # Shift P-site codon density to E-site or A-site when requested.
    shift_num = set_codon_shift(sites)
    merged_rpf = shift_site(merged_rpf, sample_name, shift_num)

    # Filter high-expression genes using the historical mean-count criterion.
    gene_rpf_sum, high_gene, high_rpf = high_expression(
        merged_rpf=merged_rpf,
        total_rpf_num=total_rpf_num,
        sample_name=sample_name,
        rpf_num=rpf_num,
    )

    check_merged_rpf_results(merged_rpf)
    check_high_rpf_results(high_rpf)

    return raw_rpf, sample_name, sample_num, merged_rpf, total_rpf_num, gene_rpf_sum, high_gene, high_rpf


# -----------------------------------------------------------------------------
# Codon annotation helper
# -----------------------------------------------------------------------------


def codon_table():
    """Return codon annotation dictionaries and tables."""
    codon_anno = {
        "AAA": ["Lys", "K"], "AAC": ["Asn", "N"], "AAG": ["Lys", "K"], "AAT": ["Asn", "N"],
        "ACA": ["Thr", "T"], "ACC": ["Thr", "T"], "ACG": ["Thr", "T"], "ACT": ["Thr", "T"],
        "AGA": ["Arg", "R"], "AGC": ["Ser", "S"], "AGG": ["Arg", "R"], "AGT": ["Ser", "S"],
        "ATA": ["Ile", "I"], "ATC": ["Ile", "I"], "ATG": ["Met", "M"], "ATT": ["Ile", "I"],
        "CAA": ["Gln", "Q"], "CAC": ["His", "H"], "CAG": ["Gln", "Q"], "CAT": ["His", "H"],
        "CCA": ["Pro", "P"], "CCC": ["Pro", "P"], "CCG": ["Pro", "P"], "CCT": ["Pro", "P"],
        "CGA": ["Arg", "R"], "CGC": ["Arg", "R"], "CGG": ["Arg", "R"], "CGT": ["Arg", "R"],
        "CTA": ["Leu", "L"], "CTC": ["Leu", "L"], "CTG": ["Leu", "L"], "CTT": ["Leu", "L"],
        "GAA": ["Glu", "E"], "GAC": ["Asp", "D"], "GAG": ["Glu", "E"], "GAT": ["Asp", "D"],
        "GCA": ["Ala", "A"], "GCC": ["Ala", "A"], "GCG": ["Ala", "A"], "GCT": ["Ala", "A"],
        "GGA": ["Gly", "G"], "GGC": ["Gly", "G"], "GGG": ["Gly", "G"], "GGT": ["Gly", "G"],
        "GTA": ["Val", "V"], "GTC": ["Val", "V"], "GTG": ["Val", "V"], "GTT": ["Val", "V"],
        "TAC": ["Tyr", "Y"], "TAT": ["Tyr", "Y"], "TCA": ["Ser", "S"], "TCC": ["Ser", "S"],
        "TCG": ["Ser", "S"], "TCT": ["Ser", "S"], "TGC": ["Cys", "C"], "TGG": ["Trp", "W"],
        "TGT": ["Cys", "C"], "TTA": ["Leu", "L"], "TTC": ["Phe", "F"], "TTG": ["Leu", "L"],
        "TTT": ["Phe", "F"], "TAA": ["Stop", "*"], "TAG": ["Stop", "*"], "TGA": ["Stop", "*"],
    }

    codon_df = pd.DataFrame(codon_anno, index=["AA", "Abbr"]).T.sort_values("Abbr")
    codon_df.index.name = "codon"

    return codon_anno, codon_df
