#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-07-13
# Version: 0.2.8-dev.011
# Function: Provide RiboParser core functions for RPF density data import and analysis.
# Input: RiboParser compact JSONL density files or legacy codon-level TXT density files.
# Output: Polars/Pandas RPF density objects and summary tables for downstream modules.

"""RPF density import and transformation utilities for RiboParser.

This module provides a compatibility layer for downstream RiboParser analysis
steps. The public ``import_rpf`` function keeps the historical return structure,
while the internal reader now supports both current compact JSONL density files
and legacy codon-level TXT density files.

Current JSONL records are expected to use the ``samples`` structure generated by
updated ``rpf_Density`` and ``rpf_Merge`` workflows.
"""

from __future__ import annotations

import gzip
import io
import json
import os
import itertools
import re
import sys
from collections.abc import Iterable, Iterator, Sequence
from dataclasses import dataclass, field
from typing import Any

import numpy as np
import pandas as pd
import polars as pl


BASE_COLUMNS = ["name", "now_nt", "from_tis", "from_tts", "region", "codon"]
FRAME_SUFFIXES = ("_f0", "_f1", "_f2")
SPARSE_ENCODING = "sparse_codon_frame"
DENSE_ENCODING = "dense_codon_frame"
PROGRESS_EVERY = 1000
JSON_CHUNK_RECORDS = 512
JSON_BUFFER_SIZE = 8 * 1024 * 1024
RPF_READER_VERSION = "0.2.8-dev.011"


def _json_loads(line: bytes | str) -> dict[str, Any]:
    """Decode one JSON line with the Python standard-library parser."""
    return json.loads(line)


# -----------------------------------------------------------------------------
# Low-level file and type helpers
# -----------------------------------------------------------------------------


def _open_text(path: str, mode: str = "rt"):
    """Open plain text or gzip-compressed text files."""
    if path.endswith(".gz"):
        return gzip.open(path, mode, encoding="utf-8", newline="")
    return open(path, mode, encoding="utf-8", newline="")


def _open_binary(path: str):
    """Open plain or gzip-compressed input with a large buffered reader."""
    raw = open(path, "rb", buffering=0)
    if path.endswith(".gz"):
        stream = gzip.GzipFile(fileobj=raw, mode="rb")
    else:
        stream = raw
    return io.BufferedReader(stream, buffer_size=JSON_BUFFER_SIZE)


def _to_int(value: Any, default: int = 0) -> int:
    """Safely convert one value to integer."""
    try:
        return int(value)
    except (TypeError, ValueError):
        try:
            return int(float(value))
        except (TypeError, ValueError):
            return default


def _detect_rpf_format(rpf_file: str) -> str:
    """Detect RPF density file format as ``json`` or ``txt``."""
    lower_name = rpf_file.lower()

    if lower_name.endswith((".jsonl.gz", ".jsonl", ".json.gz", ".json")):
        return "json"

    if lower_name.endswith((".txt", ".tsv", ".tab")):
        return "txt"

    with _open_text(rpf_file, "rt") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            if line.startswith("{"):
                return "json"
            return "txt"

    raise ValueError(f"Cannot detect density file format from empty file: {rpf_file}")


def _normalize_sample_name(sample_name: str | Sequence[str] | None) -> list[str] | None:
    """Normalize a user-provided sample name argument."""
    if sample_name is None:
        return None
    if isinstance(sample_name, str):
        if not sample_name:
            return None
        return [sample_name]
    return [str(item) for item in sample_name]


def _frame_columns(sample_name: str) -> list[str]:
    """Return three frame column names for one sample."""
    return [f"{sample_name}_f0", f"{sample_name}_f1", f"{sample_name}_f2"]


def _sample_from_frame_column(column: str) -> str:
    """Return sample name from a frame column name."""
    if column.endswith(FRAME_SUFFIXES):
        return column[:-3]
    return column


def _is_frame_column(column: str) -> bool:
    """Return whether one column is a frame density column."""
    return column.endswith(FRAME_SUFFIXES)


# -----------------------------------------------------------------------------
# Gene list and filtering helpers
# -----------------------------------------------------------------------------


def _read_gene_filter(gene: str | None) -> set[str] | None:
    """Read transcript IDs from a gene list file."""
    if not gene:
        return None

    gene_csv = pd.read_csv(gene, header=0, index_col=None, sep="\t")
    if "transcript_id" in gene_csv.columns:
        gene_name = gene_csv["transcript_id"].astype(str).tolist()
    else:
        gene_name = gene_csv.iloc[:, 0].astype(str).tolist()

    return set(gene_name)


def _row_pass_filter(
    name: str,
    codon: str,
    from_tis: int,
    from_tts: int,
    gene_filter: set[str] | None = None,
    tis: int | None = None,
    tts: int | None = None,
) -> bool:
    """Check whether one codon-level row passes common filters."""
    if gene_filter is not None and name not in gene_filter:
        return False

    if tis is not None and from_tis < tis:
        return False

    if tts is not None and from_tts > -tts:
        return False

    if "N" in codon.upper():
        return False

    return True


# -----------------------------------------------------------------------------
# JSONL reader
# -----------------------------------------------------------------------------


def iter_json_records(json_file: str) -> Iterator[dict[str, Any]]:
    """Yield current RPF density transcript records from JSONL."""
    with _open_binary(json_file) as handle:
        for line_number, line in enumerate(handle, start=1):
            line = line.strip()
            if not line:
                continue

            record = _json_loads(line)
            if record.get("record_type") != "transcript":
                continue

            samples = record.get("samples")
            if not isinstance(samples, dict) or not samples:
                raise ValueError(
                    "Invalid RPF density JSON record at line {line}: "
                    "missing non-empty 'samples' dictionary.".format(line=line_number)
                )

            yield record


def get_json_sample_names(json_file: str) -> list[str]:
    """Collect sample names from the first current JSONL transcript record."""
    for record in iter_json_records(json_file):
        return [str(sample) for sample in record["samples"].keys()]
    raise ValueError(f"No transcript records were found in JSON density file: {json_file}")


def _density_for_sample(record: dict[str, Any], sample_name: str) -> dict[str, Any]:
    """Return the density object for one sample from a current JSON record."""
    sample_entry = record["samples"].get(sample_name)
    if not isinstance(sample_entry, dict):
        return {}

    density = sample_entry.get("density")
    if not isinstance(density, dict):
        return {}

    return density


def density_to_frame_matrix(
    record: dict[str, Any],
    sample_name: str,
    codon_count: int | None = None,
) -> np.ndarray:
    """Convert sparse or dense JSON density to a dense ``codon x frame`` matrix."""
    if codon_count is None:
        codon_count = _to_int(record.get("trim", {}).get("codon_count"), 0)
    codon_count = max(0, int(codon_count))
    matrix = np.zeros((codon_count, 3), dtype=np.int64)
    if codon_count == 0:
        return matrix

    density = _density_for_sample(record, sample_name)
    encoding = str(density.get("encoding", SPARSE_ENCODING))

    if encoding in {DENSE_ENCODING, "dense"}:
        for frame, keys in enumerate((("f0", "frame0"), ("f1", "frame1"), ("f2", "frame2"))):
            values = density.get(keys[0], density.get(keys[1], []))
            if not values:
                continue
            array = np.asarray(values, dtype=np.int64).reshape(-1)
            length = min(codon_count, array.size)
            matrix[:length, frame] = array[:length]
        return matrix

    if encoding not in {SPARSE_ENCODING, "sparse"}:
        raise ValueError(
            "Unsupported density encoding '{encoding}' in transcript '{transcript}' "
            "sample '{sample}'.".format(
                encoding=encoding,
                transcript=record.get("transcript_id", "NA"),
                sample=sample_name,
            )
        )

    codon_index = np.asarray(density.get("codon_index", []), dtype=np.int64)
    frame = np.asarray(density.get("frame", []), dtype=np.int64)
    count = np.asarray(density.get("count", []), dtype=np.int64)
    length = min(codon_index.size, frame.size, count.size)
    if length == 0:
        return matrix
    codon_index = codon_index[:length]
    frame = frame[:length]
    count = count[:length]
    valid = (codon_index >= 0) & (codon_index < codon_count) & (frame >= 0) & (frame < 3)
    if valid.any():
        np.add.at(matrix, (codon_index[valid], frame[valid]), count[valid])
    return matrix


def _density_to_selected_matrix(
    record: dict[str, Any],
    sample_name: str,
    codon_count: int,
    selected: np.ndarray,
    selected_lookup: np.ndarray,
) -> np.ndarray:
    """Decode only retained codons into a compact ``selected x 3`` matrix."""
    result = np.zeros((selected.size, 3), dtype=np.int64)
    if selected.size == 0:
        return result

    density = _density_for_sample(record, sample_name)
    encoding = str(density.get("encoding", SPARSE_ENCODING))
    if encoding in {DENSE_ENCODING, "dense"}:
        for frame_id, keys in enumerate((("f0", "frame0"), ("f1", "frame1"), ("f2", "frame2"))):
            values = density.get(keys[0], density.get(keys[1], []))
            if not values:
                continue
            array = np.asarray(values, dtype=np.int64).reshape(-1)
            valid_selected = selected[selected < array.size]
            if valid_selected.size:
                output_index = selected_lookup[valid_selected]
                result[output_index, frame_id] = array[valid_selected]
        return result

    if encoding not in {SPARSE_ENCODING, "sparse"}:
        raise ValueError(
            "Unsupported density encoding '{encoding}' in transcript '{transcript}' "
            "sample '{sample}'.".format(
                encoding=encoding,
                transcript=record.get("transcript_id", "NA"),
                sample=sample_name,
            )
        )

    codon_index = np.asarray(density.get("codon_index", []), dtype=np.int64)
    frame = np.asarray(density.get("frame", []), dtype=np.int64)
    count = np.asarray(density.get("count", []), dtype=np.int64)
    length = min(codon_index.size, frame.size, count.size)
    if length == 0:
        return result
    codon_index = codon_index[:length]
    frame = frame[:length]
    count = count[:length]
    valid = (codon_index >= 0) & (codon_index < codon_count) & (frame >= 0) & (frame < 3)
    if not valid.any():
        return result
    codon_index = codon_index[valid]
    frame = frame[valid]
    count = count[valid]
    output_index = selected_lookup[codon_index]
    retained = output_index >= 0
    if retained.any():
        np.add.at(result, (output_index[retained], frame[retained]), count[retained])
    return result


def density_to_frame_arrays(
    record: dict[str, Any],
    sample_name: str,
    codon_count: int | None = None,
) -> tuple[list[int], list[int], list[int]]:
    """Convert JSON density to three frame arrays; retained for compatibility."""
    matrix = density_to_frame_matrix(record, sample_name, codon_count)
    return (
        matrix[:, 0].tolist(),
        matrix[:, 1].tolist(),
        matrix[:, 2].tolist(),
    )


def _region_from_codon_index(codon_index: int, utr5_codons: int, cds_codons: int) -> str:
    """Return transcript region name for one codon index."""
    if codon_index < utr5_codons:
        return "5utr"
    if codon_index < utr5_codons + cds_codons:
        return "cds"
    return "3utr"



def _prepare_record_metadata(
    record: dict[str, Any],
    gene_filter: set[str] | None = None,
    tis: int | None = None,
    tts: int | None = None,
) -> dict[str, Any] | None:
    """Prepare retained transcript coordinates once for batch construction."""
    trim = record.get("trim")
    if not isinstance(trim, dict):
        raise ValueError(
            "Transcript '{transcript}' has no valid 'trim' dictionary.".format(
                transcript=record.get("transcript_id", "NA")
            )
        )

    name = str(record.get("name") or record.get("transcript_id") or "NA")
    if gene_filter is not None and name not in gene_filter:
        return None

    codon_count = _to_int(trim.get("codon_count"), 0)
    if codon_count <= 0:
        return None

    start_nt0 = _to_int(trim.get("start_nt0"), 0)
    trim_length_nt = _to_int(trim.get("trim_length_nt"), codon_count * 3)
    utr5_codons = _to_int(trim.get("utr5_codons"), 0)
    cds_codons = _to_int(trim.get("cds_codons"), 0)
    utr3_nt = _to_int(trim.get("utr3_nt"), 0)
    from_tts_start = (utr3_nt - trim_length_nt) // 3 + 1

    codon_index = np.arange(codon_count, dtype=np.int32)
    from_tis = codon_index - np.int32(utr5_codons)
    from_tts = np.int32(from_tts_start) + codon_index
    keep = np.ones(codon_count, dtype=bool)
    if tis is not None:
        keep &= from_tis >= int(tis)
    if tts is not None:
        keep &= from_tts <= -int(tts)

    sequence = str(record.get("sequence", "")).upper().encode("ascii", errors="replace")
    target_length = codon_count * 3
    if len(sequence) < target_length:
        sequence = sequence + b" " * (target_length - len(sequence))
    else:
        sequence = sequence[:target_length]
    codon_bytes = np.frombuffer(sequence, dtype=np.uint8, count=codon_count * 3).reshape(codon_count, 3)
    keep &= ~(codon_bytes == ord("N")).any(axis=1)
    codons = np.frombuffer(sequence, dtype="S3", count=codon_count)

    selected = np.flatnonzero(keep).astype(np.int32, copy=False)
    if selected.size == 0:
        return None

    selected_lookup = np.full(codon_count, -1, dtype=np.int32)
    selected_lookup[selected] = np.arange(selected.size, dtype=np.int32)

    selected_region = np.full(selected.size, "3utr", dtype="U4")
    selected_region[selected < utr5_codons] = "5utr"
    selected_region[
        (selected >= utr5_codons) & (selected < utr5_codons + cds_codons)
    ] = "cds"

    return {
        "record": record,
        "name": name,
        "codon_count": codon_count,
        "selected": selected,
        "selected_lookup": selected_lookup,
        "now_nt": (start_nt0 + 1 + selected.astype(np.int64) * 3).astype(np.int64),
        "from_tis": from_tis[selected].astype(np.int32, copy=False),
        "from_tts": from_tts[selected].astype(np.int32, copy=False),
        "region": selected_region,
        "codon": codons[selected].astype("U3"),
    }


def _fill_selected_density(
    target: np.ndarray,
    record: dict[str, Any],
    sample_name: str,
    codon_count: int,
    selected: np.ndarray,
    selected_lookup: np.ndarray,
) -> None:
    """Decode one sample directly into a preallocated ``rows x 3`` target."""
    density = _density_for_sample(record, sample_name)
    encoding = str(density.get("encoding", SPARSE_ENCODING))

    if encoding in {DENSE_ENCODING, "dense"}:
        for frame_id, keys in enumerate((("f0", "frame0"), ("f1", "frame1"), ("f2", "frame2"))):
            values = density.get(keys[0], density.get(keys[1], []))
            if not values:
                continue
            array = np.asarray(values, dtype=np.int64).reshape(-1)
            valid = selected < array.size
            if valid.any():
                target[valid, frame_id] = array[selected[valid]]
        return

    if encoding not in {SPARSE_ENCODING, "sparse"}:
        raise ValueError(
            "Unsupported density encoding '{encoding}' in transcript '{transcript}' "
            "sample '{sample}'.".format(
                encoding=encoding,
                transcript=record.get("transcript_id", "NA"),
                sample=sample_name,
            )
        )

    codon_index = np.asarray(density.get("codon_index", []), dtype=np.int64)
    frame = np.asarray(density.get("frame", []), dtype=np.int64)
    count = np.asarray(density.get("count", []), dtype=np.int64)
    length = min(codon_index.size, frame.size, count.size)
    if length == 0:
        return
    codon_index = codon_index[:length]
    frame = frame[:length]
    count = count[:length]
    valid = (
        (codon_index >= 0)
        & (codon_index < codon_count)
        & (frame >= 0)
        & (frame < 3)
    )
    if not valid.any():
        return
    codon_index = codon_index[valid]
    frame = frame[valid]
    count = count[valid]
    output_index = selected_lookup[codon_index]
    retained = output_index >= 0
    if retained.any():
        np.add.at(target, (output_index[retained], frame[retained]), count[retained])


def _records_to_frame(
    records: Sequence[dict[str, Any]],
    sample_names: Sequence[str],
    gene_filter: set[str] | None = None,
    tis: int | None = None,
    tts: int | None = None,
) -> tuple[pl.DataFrame | None, int]:
    """Build one Polars chunk using one batch-level preallocation."""
    prepared: list[dict[str, Any]] = []
    total_rows = 0
    max_name_length = 1
    for record in records:
        metadata = _prepare_record_metadata(record, gene_filter, tis, tts)
        if metadata is None:
            continue
        prepared.append(metadata)
        rows = int(metadata["selected"].size)
        total_rows += rows
        max_name_length = max(max_name_length, len(metadata["name"]))

    if total_rows == 0:
        return None, 0

    names = np.empty(total_rows, dtype=f"U{max_name_length}")
    now_nt = np.empty(total_rows, dtype=np.int64)
    from_tis = np.empty(total_rows, dtype=np.int32)
    from_tts = np.empty(total_rows, dtype=np.int32)
    region = np.empty(total_rows, dtype="U4")
    codon = np.empty(total_rows, dtype="U3")
    density = np.zeros((total_rows, len(sample_names) * 3), dtype=np.int64)

    offset = 0
    for metadata in prepared:
        rows = int(metadata["selected"].size)
        stop = offset + rows
        sl = slice(offset, stop)
        names[sl] = metadata["name"]
        now_nt[sl] = metadata["now_nt"]
        from_tis[sl] = metadata["from_tis"]
        from_tts[sl] = metadata["from_tts"]
        region[sl] = metadata["region"]
        codon[sl] = metadata["codon"]

        for sample_index, sample in enumerate(sample_names):
            _fill_selected_density(
                target=density[sl, sample_index * 3:(sample_index + 1) * 3],
                record=metadata["record"],
                sample_name=str(sample),
                codon_count=int(metadata["codon_count"]),
                selected=metadata["selected"],
                selected_lookup=metadata["selected_lookup"],
            )
        offset = stop

    columns: dict[str, np.ndarray] = {
        "name": names,
        "now_nt": now_nt,
        "from_tis": from_tis,
        "from_tts": from_tts,
        "region": region,
        "codon": codon,
    }
    for sample_index, sample in enumerate(sample_names):
        columns[f"{sample}_f0"] = density[:, sample_index * 3]
        columns[f"{sample}_f1"] = density[:, sample_index * 3 + 1]
        columns[f"{sample}_f2"] = density[:, sample_index * 3 + 2]
    return pl.DataFrame(columns), total_rows



def read_json_rpf_file(
    rpf_file: str,
    gene: str | None = None,
    tis: int | None = None,
    tts: int | None = None,
    sample_name: str | Sequence[str] | None = None,
    thread: int | None = None,
) -> pl.DataFrame:
    """Read compact JSONL using native sequential batch conversion.

    The ``thread`` argument is retained for backward compatibility but is not
    used. Benchmarks showed that thread-pool conversion was slower because gzip
    decompression and JSON parsing remain sequential, while concurrent NumPy and
    Polars construction adds scheduling and memory-bandwidth overhead.
    """
    records = iter_json_records(rpf_file)
    try:
        first_record = next(records)
    except StopIteration as exc:
        raise ValueError(
            f"No transcript records were found in JSON density file: {rpf_file}"
        ) from exc

    all_sample_names = [str(sample) for sample in first_record["samples"].keys()]
    requested_samples = _normalize_sample_name(sample_name)
    if requested_samples is None:
        selected_samples = all_sample_names
    else:
        missing = sorted(set(requested_samples) - set(all_sample_names))
        if missing:
            raise ValueError(
                "Requested sample(s) not found in JSON density file: {samples}".format(
                    samples=", ".join(missing)
                )
            )
        selected_samples = requested_samples

    gene_filter = _read_gene_filter(gene)
    chunks: list[pl.DataFrame] = []
    batch: list[dict[str, Any]] = []
    record_count = 0
    row_count = 0
    next_progress = PROGRESS_EVERY

    def flush_batch(records_batch: list[dict[str, Any]]) -> None:
        nonlocal row_count, next_progress
        if not records_batch:
            return
        frame, rows = _records_to_frame(
            records_batch,
            selected_samples,
            gene_filter,
            tis,
            tts,
        )
        if frame is not None:
            chunks.append(frame)
        row_count += rows
        if record_count >= next_progress:
            print(
                f"processed records={record_count:,}, retained rows={row_count:,}",
                flush=True,
            )
            while next_progress <= record_count:
                next_progress += PROGRESS_EVERY

    for record in itertools.chain((first_record,), records):
        current_samples = [str(sample) for sample in record["samples"].keys()]
        if current_samples != all_sample_names:
            raise ValueError(
                "Inconsistent sample order in transcript '{transcript}'.".format(
                    transcript=record.get("transcript_id", "NA")
                )
            )

        batch.append(record)
        record_count += 1
        if len(batch) >= JSON_CHUNK_RECORDS:
            flush_batch(batch)
            batch = []

    if batch:
        flush_batch(batch)

    print(
        "Imported JSON RPF density: records={records:,}, rows={rows:,}, "
        "reader=native-json, builder=preallocated.".format(
            records=record_count,
            rows=row_count,
        ),
        flush=True,
    )

    if not chunks:
        columns = {column: [] for column in BASE_COLUMNS}
        for sample in selected_samples:
            for column in _frame_columns(str(sample)):
                columns[column] = []
        return pl.DataFrame(columns)
    if len(chunks) == 1:
        return chunks[0]
    return pl.concat(chunks, how="vertical", rechunk=False)


# -----------------------------------------------------------------------------
# TXT reader
# -----------------------------------------------------------------------------


def read_txt_rpf_file(
    rpf_file: str,
    gene: str | None = None,
    tis: int | None = None,
    tts: int | None = None,
    sample_name: str | Sequence[str] | None = None,
) -> pl.DataFrame:
    """Read legacy codon-level TXT RPF density as a Polars table."""
    raw_rpf = pl.read_csv(rpf_file, has_header=True, separator="\t")

    raw_rpf = raw_rpf.with_columns(pl.col("codon").cast(pl.Utf8).str.to_uppercase())
    raw_rpf = raw_rpf.filter(~pl.col("codon").str.contains("N"))

    if gene:
        gene_filter = _read_gene_filter(gene) or set()
        raw_rpf = raw_rpf.filter(pl.col("name").cast(pl.Utf8).is_in(list(gene_filter)))

    raw_rpf = filter_tis_tts(raw_rpf, tis, tts)

    requested_samples = _normalize_sample_name(sample_name)
    if requested_samples is not None:
        keep_columns = BASE_COLUMNS.copy()
        for sample in requested_samples:
            keep_columns.extend(_frame_columns(sample))
        missing_columns = [column for column in keep_columns if column not in raw_rpf.columns]
        if missing_columns:
            raise ValueError(
                "Requested sample frame column(s) not found in TXT density file: {columns}".format(
                    columns=", ".join(missing_columns)
                )
            )
        raw_rpf = raw_rpf.select(keep_columns)

    return raw_rpf


# -----------------------------------------------------------------------------
# Public compatibility functions
# -----------------------------------------------------------------------------


def read_rpf_file(rpf_file: str) -> pl.DataFrame:
    """Import an RPF density file as a codon-level Polars table.

    Parameters
    ----------
    rpf_file : str
        RPF density file generated by ``rpf_Density`` or ``rpf_Merge``. Both
        current JSONL and legacy TXT formats are supported.

    Returns
    -------
    polars.DataFrame
        Codon-level table with base columns and sample frame columns.
    """
    file_format = _detect_rpf_format(rpf_file)
    if file_format == "json":
        return read_json_rpf_file(rpf_file)
    return read_txt_rpf_file(rpf_file)


def get_frame_rpf(raw_rpf: pl.DataFrame, sample_name: Sequence[str], frame: str) -> pd.DataFrame:
    """Merge all frame density or retrieve one frame as a Pandas table.

    Notes
    -----
    Polars expressions in ``with_columns`` can only reference columns that are
    already present in the dataframe being modified. Therefore this function
    builds the final table directly from the full ``raw_rpf`` dataframe instead
    of first selecting only the six metadata columns.
    """
    frame = str(frame)

    missing_base = [column for column in BASE_COLUMNS if column not in raw_rpf.columns]
    if missing_base:
        raise ValueError(
            "RPF density table is missing required base column(s): {columns}".format(
                columns=", ".join(missing_base)
            )
        )

    select_exprs = [pl.col(column) for column in BASE_COLUMNS]

    if frame == "all":
        for now_sp in sample_name:
            print("Import the density file {file_name}.".format(file_name=now_sp), flush=True)
            f0, f1, f2 = _frame_columns(now_sp)
            missing_frame = [column for column in (f0, f1, f2) if column not in raw_rpf.columns]
            if missing_frame:
                raise ValueError(
                    "RPF density table is missing frame column(s) for sample {sample}: {columns}".format(
                        sample=now_sp,
                        columns=", ".join(missing_frame),
                    )
                )
            select_exprs.append(
                pl.sum_horizontal([pl.col(f0), pl.col(f1), pl.col(f2)]).alias(now_sp)
            )
    elif frame in {"0", "1", "2"}:
        for now_sp in sample_name:
            print("Import the density file {file_name}.".format(file_name=now_sp), flush=True)
            now_sp_index = f"{now_sp}_f{frame}"
            if now_sp_index not in raw_rpf.columns:
                raise ValueError(
                    "RPF density table is missing frame column for sample {sample}: {column}".format(
                        sample=now_sp,
                        column=now_sp_index,
                    )
                )
            select_exprs.append(pl.col(now_sp_index).alias(now_sp))
    else:
        raise ValueError("frame must be one of '0', '1', '2', or 'all'.")

    merged_rpf = raw_rpf.select(select_exprs)
    return merged_rpf.to_pandas()


def set_codon_shift(sites: str) -> int:
    """Set codon shift by E/P/A site."""
    if sites == "E":
        return -1
    if sites == "P":
        return 0
    if sites == "A":
        return 1
    return 0


def shift_site(merged_rpf: pd.DataFrame, sample_name: Sequence[str], shift_num: int) -> pd.DataFrame:
    """Shift codon-level density from P-site to E-site or A-site."""
    if shift_num == 0:
        return merged_rpf

    merged_rpf.loc[:, list(sample_name)] = (
        merged_rpf.groupby("name", sort=False)[list(sample_name)]
        .shift(shift_num)
        .fillna(0)
        .values
    )

    return merged_rpf


def sum_total_rpf(raw_rpf: pl.DataFrame) -> pd.Series:
    """Calculate total RPF count for each sample across all three frames."""
    frame_columns = [column for column in raw_rpf.columns if _is_frame_column(column)]
    if not frame_columns:
        return pd.Series(dtype="int64", name="total_rpf")

    total_rpf_num = raw_rpf.select(frame_columns).sum().to_pandas().T.reset_index()
    total_rpf_num.columns = ["sample_frame", "total_rpf"]
    total_rpf_num["sample"] = total_rpf_num["sample_frame"].map(_sample_from_frame_column)
    total_rpf_num = total_rpf_num.groupby("sample", sort=False)["total_rpf"].sum()

    return total_rpf_num


def high_expression(
    merged_rpf: pd.DataFrame,
    total_rpf_num: pd.Series,
    sample_name: Sequence[str],
    rpf_num: int,
) -> tuple[pd.DataFrame, pd.Index, pd.DataFrame]:
    """Filter high-expression genes using the mean RPF count across samples."""
    gene_rpf_sum = merged_rpf.groupby("name", sort=False)[list(sample_name)].sum()
    high_gene = gene_rpf_sum.loc[gene_rpf_sum.mean(axis=1) >= rpf_num, :].index
    high_rpf = merged_rpf.loc[merged_rpf["name"].isin(high_gene), :]

    return gene_rpf_sum, high_gene, high_rpf


def sum_sample_number(raw_rpf: pl.DataFrame, sample_num: int | None) -> int:
    """Return the number of samples in an RPF table."""
    if sample_num:
        return int(sample_num)

    sample_names = retrieve_sample_name(raw_rpf, None)
    return len(sample_names)


def retrieve_sample_name(
    raw_rpf: pl.DataFrame,
    sample_name: str | Sequence[str] | None,
) -> list[str]:
    """Retrieve sample names from frame density columns."""
    normalized = _normalize_sample_name(sample_name)
    if normalized is not None:
        return normalized

    sample_names = []
    seen = set()
    for column in raw_rpf.columns:
        if not _is_frame_column(column):
            continue
        sample = _sample_from_frame_column(column)
        if sample not in seen:
            sample_names.append(sample)
            seen.add(sample)

    return sample_names


def filter_tis_tts(raw_rpf: pl.DataFrame, tis: int | None, tts: int | None) -> pl.DataFrame:
    """Trim the RPF table by TIS/TTS codon offsets."""
    if tis is not None:
        raw_rpf = raw_rpf.filter(pl.col("from_tis") >= tis)

    if tts is not None:
        raw_rpf = raw_rpf.filter(pl.col("from_tts") <= -tts)

    return raw_rpf


def retrieve_gene_rpf(raw_rpf: pl.DataFrame, gene: str | None) -> pl.DataFrame:
    """Retrieve RPF rows for specific transcript IDs."""
    gene_filter = _read_gene_filter(gene)
    if gene_filter is None:
        return raw_rpf

    return raw_rpf.filter(pl.col("name").cast(pl.Utf8).is_in(list(gene_filter)))


def check_merged_rpf_results(merged_rpf: pd.DataFrame) -> None:
    """Exit if the merged density table is empty."""
    if merged_rpf.empty:
        print("Filtered density table is empty! Please recheck the parameters and data quality.", flush=True)
        sys.exit(1)


def check_high_rpf_results(high_rpf: pd.DataFrame) -> None:
    """Exit if the high-expression density table is empty."""
    if high_rpf.empty:
        print("Filtered density table is empty! Please recheck the parameters and data quality.", flush=True)
        sys.exit(1)


def rpf_to_rpm(raw_rpf: pd.DataFrame | pl.DataFrame, norm: bool):
    """Convert frame density columns to RPM values."""
    if not norm:
        return raw_rpf

    if isinstance(raw_rpf, pl.DataFrame):
        frame_columns = [column for column in raw_rpf.columns if _is_frame_column(column)]
        total_exprs = []
        totals = raw_rpf.select(frame_columns).sum().row(0, named=True)
        for column in frame_columns:
            total = totals.get(column, 0) or 0
            if total > 0:
                total_exprs.append((pl.col(column) * 1_000_000 / total).alias(column))
        return raw_rpf.with_columns(total_exprs)

    frame_columns = [column for column in raw_rpf.columns if _is_frame_column(column)]
    totals = raw_rpf.loc[:, frame_columns].sum(axis=0)
    for column in frame_columns:
        if totals[column] > 0:
            raw_rpf.loc[:, column] = raw_rpf.loc[:, column] * 1_000_000 / totals[column]
    return raw_rpf


@dataclass
class RPFData:
    """Container for codon-level RPF density tables and derived metadata."""

    raw_rpf: pl.DataFrame
    sample_name: list[str]
    sample_num: int
    total_rpf_num: pd.Series
    file_format: str
    source_file: str
    metadata: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_file(
        cls,
        rpf_file: str,
        sample_name: str | Sequence[str] | None = None,
        gene: str | None = None,
        tis: int | None = None,
        tts: int | None = None,
        json_thread: int | None = None,
    ) -> "RPFData":
        """Create an ``RPFData`` object from JSONL or TXT density input."""
        file_format = _detect_rpf_format(rpf_file)

        if file_format == "json":
            raw_rpf = read_json_rpf_file(
                rpf_file=rpf_file,
                gene=gene,
                tis=tis,
                tts=tts,
                sample_name=sample_name,
                thread=json_thread,
            )
        else:
            raw_rpf = read_txt_rpf_file(
                rpf_file=rpf_file,
                gene=gene,
                tis=tis,
                tts=tts,
                sample_name=sample_name,
            )

        samples = retrieve_sample_name(raw_rpf, sample_name)
        totals = sum_total_rpf(raw_rpf)

        return cls(
            raw_rpf=raw_rpf,
            sample_name=samples,
            sample_num=len(samples),
            total_rpf_num=totals,
            file_format=file_format,
            source_file=os.path.abspath(rpf_file),
            metadata={"rows": raw_rpf.height, "columns": raw_rpf.width},
        )

    def get_frame(self, frame: str = "all") -> pd.DataFrame:
        """Return a sample-level codon density table for one or all frames."""
        return get_frame_rpf(self.raw_rpf, self.sample_name, frame)

    def shifted_frame(self, sites: str = "P", frame: str = "all") -> pd.DataFrame:
        """Return frame density shifted to E/P/A site."""
        merged_rpf = self.get_frame(frame=frame)
        shift_num = set_codon_shift(sites)
        return shift_site(merged_rpf, self.sample_name, shift_num)

    def high_expression(
        self,
        rpf_num: int,
        sites: str = "P",
        frame: str = "all",
    ) -> tuple[pd.DataFrame, pd.Index, pd.DataFrame]:
        """Return high-expression transcript summary and table."""
        merged_rpf = self.shifted_frame(sites=sites, frame=frame)
        return high_expression(merged_rpf, self.total_rpf_num, self.sample_name, rpf_num)


def import_rpf(
    rpf_file: str,
    sample_num: int | None,
    sample_name: str | Sequence[str] | None,
    sites: str,
    frame: str,
    gene: str | None,
    rpf_num: int,
    tis: int | None = None,
    tts: int | None = None,
):
    """Import RPF density data using the historical RiboParser return structure.

    Returns
    -------
    tuple
        ``raw_rpf, sample_name, sample_num, merged_rpf, total_rpf_num, gene_rpf_sum, high_gene, high_rpf``.
    """
    # Import and filter the RPF file. JSON input is filtered during expansion to
    # reduce memory use; TXT input is filtered after table import.
    rpf_data = RPFData.from_file(
        rpf_file=rpf_file,
        sample_name=sample_name,
        gene=gene,
        tis=tis,
        tts=tts,
    )

    raw_rpf = rpf_data.raw_rpf
    sample_name = rpf_data.sample_name
    sample_num = int(sample_num) if sample_num else rpf_data.sample_num
    total_rpf_num = rpf_data.total_rpf_num

    # Merge the RPFs of nucleotide frames to codon-level values or retrieve a
    # specific frame.
    merged_rpf = get_frame_rpf(raw_rpf, sample_name, frame)

    # Shift P-site codon density to E-site or A-site when requested.
    shift_num = set_codon_shift(sites)
    merged_rpf = shift_site(merged_rpf, sample_name, shift_num)

    # Filter high-expression genes using the historical mean-count criterion.
    gene_rpf_sum, high_gene, high_rpf = high_expression(
        merged_rpf=merged_rpf,
        total_rpf_num=total_rpf_num,
        sample_name=sample_name,
        rpf_num=rpf_num,
    )

    check_merged_rpf_results(merged_rpf)
    check_high_rpf_results(high_rpf)

    return raw_rpf, sample_name, sample_num, merged_rpf, total_rpf_num, gene_rpf_sum, high_gene, high_rpf


# -----------------------------------------------------------------------------
# Codon annotation helper
# -----------------------------------------------------------------------------


def codon_table():
    """Return codon annotation dictionaries and tables."""
    codon_anno = {
        "AAA": ["Lys", "K"], "AAC": ["Asn", "N"], "AAG": ["Lys", "K"], "AAT": ["Asn", "N"],
        "ACA": ["Thr", "T"], "ACC": ["Thr", "T"], "ACG": ["Thr", "T"], "ACT": ["Thr", "T"],
        "AGA": ["Arg", "R"], "AGC": ["Ser", "S"], "AGG": ["Arg", "R"], "AGT": ["Ser", "S"],
        "ATA": ["Ile", "I"], "ATC": ["Ile", "I"], "ATG": ["Met", "M"], "ATT": ["Ile", "I"],
        "CAA": ["Gln", "Q"], "CAC": ["His", "H"], "CAG": ["Gln", "Q"], "CAT": ["His", "H"],
        "CCA": ["Pro", "P"], "CCC": ["Pro", "P"], "CCG": ["Pro", "P"], "CCT": ["Pro", "P"],
        "CGA": ["Arg", "R"], "CGC": ["Arg", "R"], "CGG": ["Arg", "R"], "CGT": ["Arg", "R"],
        "CTA": ["Leu", "L"], "CTC": ["Leu", "L"], "CTG": ["Leu", "L"], "CTT": ["Leu", "L"],
        "GAA": ["Glu", "E"], "GAC": ["Asp", "D"], "GAG": ["Glu", "E"], "GAT": ["Asp", "D"],
        "GCA": ["Ala", "A"], "GCC": ["Ala", "A"], "GCG": ["Ala", "A"], "GCT": ["Ala", "A"],
        "GGA": ["Gly", "G"], "GGC": ["Gly", "G"], "GGG": ["Gly", "G"], "GGT": ["Gly", "G"],
        "GTA": ["Val", "V"], "GTC": ["Val", "V"], "GTG": ["Val", "V"], "GTT": ["Val", "V"],
        "TAC": ["Tyr", "Y"], "TAT": ["Tyr", "Y"], "TCA": ["Ser", "S"], "TCC": ["Ser", "S"],
        "TCG": ["Ser", "S"], "TCT": ["Ser", "S"], "TGC": ["Cys", "C"], "TGG": ["Trp", "W"],
        "TGT": ["Cys", "C"], "TTA": ["Leu", "L"], "TTC": ["Phe", "F"], "TTG": ["Leu", "L"],
        "TTT": ["Phe", "F"], "TAA": ["Stop", "*"], "TAG": ["Stop", "*"], "TGA": ["Stop", "*"],
    }

    codon_df = pd.DataFrame(codon_anno, index=["AA", "Abbr"]).T.sort_values("Abbr")
    codon_df.index.name = "codon"

    return codon_anno, codon_df
