#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-07-08
# Version: 0.2.8-dev.006
# Function: Merge RPF length distribution tables generated by rpf_Check.
# Input: One or more *_length_distribution.txt files.
# Output: Merged RPF length distribution table.

import argparse
import glob
import os
import sys
from pathlib import Path

import pandas as pd


def merge_length_args_parser():
    """Parse command-line arguments for length distribution merging."""
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description="Merge RPF length distribution files generated by rpf_Check.",
    )

    input_group = parser.add_argument_group("Required arguments")
    input_group.add_argument(
        "-l",
        "--list",
        nargs="+",
        required=True,
        help=(
            "Input length distribution files or shell-style patterns. "
            "Examples: '*_length_distribution.txt' sample1_length_distribution.txt"
        ),
    )
    input_group.add_argument(
        "-o",
        dest="output",
        required=True,
        type=str,
        help="Output prefix.",
    )

    args = parser.parse_args()
    args.length_files = expand_input_files(args.list)

    print("list        :  " + ", ".join(args.length_files), flush=True)
    print("output      :  " + str(args.output), flush=True)

    return args


def expand_input_files(input_items):
    """Expand input files and glob patterns into a sorted unique file list.

    Parameters
    ----------
    input_items : list
        Input file names or shell-style glob patterns.

    Returns
    -------
    list
        Existing length distribution files.

    Workflow
    --------
    1. Expand shell-style glob patterns when they are quoted by the user.
    2. Keep normal file names unchanged.
    3. Remove duplicated paths while preserving sorted order.
    4. Fail early when no valid input file is found.
    """
    matched_files = []

    for item in input_items:
        expanded = glob.glob(item)
        if expanded:
            matched_files.extend(expanded)
        else:
            matched_files.append(item)

    unique_files = []
    seen_files = set()

    for file_name in sorted(matched_files):
        file_path = os.path.abspath(file_name)
        if file_path in seen_files:
            continue
        if not os.path.isfile(file_path):
            raise FileNotFoundError(f"Input length distribution file does not exist: {file_name}")
        unique_files.append(file_name)
        seen_files.add(file_path)

    if not unique_files:
        raise RuntimeError("No length distribution files were found.")

    return unique_files


def normalize_column_name(column_name):
    """Normalize a column name for flexible format detection."""
    return (
        str(column_name)
        .strip()
        .replace("\ufeff", "")
        .replace(" ", "")
        .replace("-", "")
        .replace("_", "")
        .lower()
    )


def infer_sample_name(length_file):
    """Infer sample name from a length distribution file name."""
    base_name = Path(length_file).name

    for suffix in (
        "_length_distribution.txt",
        ".length_distribution.txt",
        "_length_distribution.tsv",
        ".length_distribution.tsv",
    ):
        if base_name.endswith(suffix):
            return base_name[: -len(suffix)]

    if base_name.endswith(".txt") or base_name.endswith(".tsv"):
        return str(Path(base_name).with_suffix(""))

    return base_name


def find_column(column_map, candidate_names):
    """Find the first matching column from normalized candidate names."""
    for candidate in candidate_names:
        candidate_norm = normalize_column_name(candidate)
        if candidate_norm in column_map:
            return column_map[candidate_norm]
    return None


def import_length_file(length_file):
    """Read one length distribution file and return a canonical table.

    Parameters
    ----------
    length_file : str
        Input length distribution file.

    Returns
    -------
    pandas.DataFrame
        Canonical table with Length, Plus_Count, Minus_Count, and Total_Count.

    Workflow
    --------
    1. Read tab-delimited length distribution table.
    2. Detect old format: Length, Plus, Minus.
    3. Detect new format: Length, Plus, Minus, Total.
    4. Convert all count columns to numeric values.
    5. Sum duplicated length rows if present.
    """
    try:
        length_df = pd.read_csv(length_file, sep="\t", comment="#")
    except Exception as error:
        raise RuntimeError(f"Failed to read length distribution file: {length_file}. Error: {error}") from error

    if length_df.empty:
        raise RuntimeError(f"Length distribution file is empty: {length_file}")

    length_df = length_df.dropna(how="all")

    column_map = {
        normalize_column_name(column): column
        for column in length_df.columns
    }

    length_col = find_column(
        column_map,
        ["Length", "Read_Length", "RPF_Length", "RPFs_Length"],
    )
    plus_col = find_column(
        column_map,
        ["Plus", "Plus_Count", "PlusCount", "Forward", "Forward_Count"],
    )
    minus_col = find_column(
        column_map,
        ["Minus", "Minus_Count", "MinusCount", "Reverse", "Reverse_Count"],
    )
    total_col = find_column(
        column_map,
        ["Total", "Total_Count", "TotalCount", "Reads", "Read_Count"],
    )

    if length_col is None or plus_col is None or minus_col is None:
        if length_df.shape[1] >= 3:
            length_col = length_df.columns[0]
            plus_col = length_df.columns[1]
            minus_col = length_df.columns[2]
            total_col = length_df.columns[3] if length_df.shape[1] >= 4 else None
        else:
            raise RuntimeError(
                "Unrecognized length distribution format. "
                f"Expected at least 3 columns, but got {length_df.shape[1]} columns in {length_file}"
            )

    canonical_df = pd.DataFrame()
    canonical_df["Length"] = pd.to_numeric(length_df[length_col], errors="coerce")
    canonical_df["Plus_Count"] = pd.to_numeric(length_df[plus_col], errors="coerce").fillna(0)
    canonical_df["Minus_Count"] = pd.to_numeric(length_df[minus_col], errors="coerce").fillna(0)

    if total_col is not None:
        canonical_df["Total_Count"] = pd.to_numeric(length_df[total_col], errors="coerce")
    else:
        canonical_df["Total_Count"] = canonical_df["Plus_Count"] + canonical_df["Minus_Count"]

    canonical_df["Total_Count"] = canonical_df["Total_Count"].fillna(
        canonical_df["Plus_Count"] + canonical_df["Minus_Count"]
    )

    canonical_df = canonical_df.dropna(subset=["Length"])
    canonical_df["Length"] = canonical_df["Length"].astype(int)

    count_columns = ["Plus_Count", "Minus_Count", "Total_Count"]
    for column in count_columns:
        canonical_df[column] = canonical_df[column].round().astype(int)

    canonical_df = (
        canonical_df
        .groupby("Length", as_index=False, sort=True)[count_columns]
        .sum()
    )

    return canonical_df


def safe_ratio(count_series, denominator):
    """Calculate percentage ratio with zero-denominator protection."""
    if denominator <= 0:
        return pd.Series([0.0] * len(count_series), index=count_series.index)
    return count_series / denominator * 100.0


def process_length_files(length_file_list):
    """Merge length distribution files into one table.

    Parameters
    ----------
    length_file_list : list
        Input length distribution files.

    Returns
    -------
    pandas.DataFrame
        Merged length distribution table.

    Workflow
    --------
    1. Read each length distribution file.
    2. Standardize old and new column formats.
    3. Calculate plus, minus, and total ratios per sample.
    4. Merge all samples into a single long-format table.
    """
    merged_tables = []

    for input_order, length_file in enumerate(length_file_list):
        sample_name = infer_sample_name(length_file)
        length_df = import_length_file(length_file)

        plus_sum = int(length_df["Plus_Count"].sum())
        minus_sum = int(length_df["Minus_Count"].sum())
        total_sum = int(length_df["Total_Count"].sum())

        length_df["Plus_Ratio"] = safe_ratio(length_df["Plus_Count"], plus_sum)
        length_df["Minus_Ratio"] = safe_ratio(length_df["Minus_Count"], minus_sum)
        length_df["Total_Ratio"] = safe_ratio(length_df["Total_Count"], total_sum)
        length_df["Sample"] = sample_name
        length_df["_Input_Order"] = input_order

        merged_tables.append(length_df)

    if not merged_tables:
        raise RuntimeError("No valid length distribution table was loaded.")

    reads_length_df = pd.concat(merged_tables, axis=0, ignore_index=True)

    output_columns = [
        "Sample",
        "Length",
        "Plus_Count",
        "Minus_Count",
        "Total_Count",
        "Plus_Ratio",
        "Minus_Ratio",
        "Total_Ratio",
        "_Input_Order",
    ]
    reads_length_df = reads_length_df.loc[:, output_columns]
    reads_length_df = reads_length_df.sort_values(
        by=["_Input_Order", "Length"],
        ascending=[True, True],
    ).reset_index(drop=True)

    reads_length_df = reads_length_df.drop(columns=["_Input_Order"])

    return reads_length_df


def output_table(reads_length_df, output_prefix):
    """Write merged length distribution table.

    Parameters
    ----------
    reads_length_df : pandas.DataFrame
        Merged length distribution table.
    output_prefix : str
        Output prefix.

    Returns
    -------
    None
        The merged table is written to disk.
    """
    count_columns = ["Length", "Plus_Count", "Minus_Count", "Total_Count"]
    ratio_columns = ["Plus_Ratio", "Minus_Ratio", "Total_Ratio"]

    for column in count_columns:
        reads_length_df[column] = pd.to_numeric(reads_length_df[column], errors="raise").astype(int)

    for column in ratio_columns:
        reads_length_df[column] = pd.to_numeric(reads_length_df[column], errors="raise").round(4)

    output_file = output_prefix + "_length_distribution.txt"
    reads_length_df.to_csv(output_file, sep="\t", index=False)

    print(f"Output file :  {output_file}", flush=True)


def main():
    """Run the length distribution merging workflow."""
    print("Step1: Checking the input arguments.", flush=True)
    args = merge_length_args_parser()

    print("Step2: Import the length distribution files.", flush=True)
    reads_length_df = process_length_files(args.length_files)

    print("Step3: Output the merged length distribution table.", flush=True)
    output_table(reads_length_df, args.output)

    print("All done.", flush=True)


if __name__ == "__main__":
    try:
        main()
    except Exception as error:
        print(f"Error: {error}", file=sys.stderr, flush=True)
        sys.exit(1)
