#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-07-09
# Version: 0.2.7
# Function: Create a sample list for RPF/RNA density files.
# Input: Density file paths or glob patterns.
# Output: A tab-delimited sample list for rpf_Merge.

"""Create sample lists for RiboParser density merging.

This helper script scans RPF/RNA density files and creates a tab-delimited
sample list that can be used by ``rpf_Merge``. It supports both the historical
legacy TXT density files and the compact JSONL density files generated by the
newer ``rpf_Density`` workflow.

Supported input examples
------------------------
- ``*_rpf.txt``
- ``*_rna.txt``
- ``*_rpf.jsonl``
- ``*_rpf.jsonl.gz``
- ``*_rna.jsonl``
- ``*_rna.jsonl.gz``

Output columns
--------------
Name
    Sample name inferred from the file name.
File
    Absolute path of the density file.
Type
    Density type: ``Ribo`` or ``RNA``.
Format
    Density file format: ``json`` or ``txt``.
"""

from __future__ import annotations

import argparse
import glob
import os
import sys
from argparse import Namespace
from collections.abc import Sequence
from pathlib import Path

import pandas as pd


SUPPORTED_SUFFIXES = (
    "_rpf.jsonl.gz",
    "_rpf.jsonl",
    "_rpf.json",
    "_rpf.txt",
    "_rna.jsonl.gz",
    "_rna.jsonl",
    "_rna.json",
    "_rna.txt",
)


def merge_density_args_parser(argv: Sequence[str] | None = None) -> Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Create a sample list for RiboParser density files."
    )

    input_group = parser.add_argument_group("Required arguments")
    input_group.add_argument(
        "-l",
        "--list",
        nargs="+",
        required=True,
        help=(
            "Density files or glob patterns. Examples: '*_rpf.jsonl.gz', "
            "'*_rpf.txt', sample1_rpf.jsonl.gz sample2_rpf.jsonl.gz."
        ),
    )

    parser.add_argument(
        "-o",
        "--output",
        dest="output",
        required=False,
        default=None,
        type=str,
        help="Output file name. Default: RPF.file.list or RNA.file.list.",
    )
    parser.add_argument(
        "--allow-mixed-type",
        dest="allow_mixed_type",
        required=False,
        action="store_true",
        default=False,
        help=(
            "Allow Ribo and RNA density files in the same output list. "
            "Default: %(default)s."
        ),
    )
    parser.add_argument(
        "--allow-mixed-format",
        dest="allow_mixed_format",
        required=False,
        action="store_true",
        default=False,
        help=(
            "Allow JSON and TXT density files in the same output list. "
            "This is usually not recommended for rpf_Merge. Default: %(default)s."
        ),
    )

    args = parser.parse_args(argv)

    for key, value in vars(args).items():
        print(f"{key:<18}: {value}", flush=True)

    return args


def expand_density_inputs(density_patterns: Sequence[str]) -> list[str]:
    """Expand density file paths and glob patterns.

    Parameters
    ----------
    density_patterns : Sequence[str]
        Input files or glob patterns from the command line.

    Returns
    -------
    list[str]
        Unique density file paths sorted by path name.
    """
    density_files: list[str] = []

    for pattern in density_patterns:
        matched_files = glob.glob(pattern)

        if matched_files:
            density_files.extend(matched_files)
        elif os.path.exists(pattern):
            density_files.append(pattern)
        else:
            print(f"Warning: no density file matched: {pattern}", flush=True)

    unique_files = sorted({os.path.abspath(file_path) for file_path in density_files})

    if not unique_files:
        print("Error: no valid density files were found.", flush=True)
        sys.exit(1)

    return unique_files


def infer_sample_name(file_name: str) -> str:
    """Infer sample name from a density file name."""
    sample_name = file_name

    for suffix in SUPPORTED_SUFFIXES:
        if sample_name.endswith(suffix):
            return sample_name[: -len(suffix)]

    # Fallback for uncommon names while preserving backward compatibility.
    for suffix in (".jsonl.gz", ".jsonl", ".json", ".txt"):
        if sample_name.endswith(suffix):
            sample_name = sample_name[: -len(suffix)]
            break

    sample_name = sample_name.replace("_rpf", "").replace("_rna", "")
    return sample_name


def infer_density_type(file_name: str) -> str:
    """Infer whether a density file is Ribo or RNA."""
    if any(
        file_name.endswith(suffix)
        for suffix in ("_rpf.jsonl.gz", "_rpf.jsonl", "_rpf.json", "_rpf.txt")
    ):
        return "Ribo"

    if any(
        file_name.endswith(suffix)
        for suffix in ("_rna.jsonl.gz", "_rna.jsonl", "_rna.json", "_rna.txt")
    ):
        return "RNA"

    print(f"Error: unsupported density file name: {file_name}", flush=True)
    print(
        "Supported suffixes: " + ", ".join(SUPPORTED_SUFFIXES),
        flush=True,
    )
    sys.exit(1)


def infer_density_format(file_name: str) -> str:
    """Infer density storage format from a file name."""
    if file_name.endswith((".jsonl.gz", ".jsonl", ".json")):
        return "json"

    if file_name.endswith(".txt"):
        return "txt"

    print(f"Error: unsupported density file format: {file_name}", flush=True)
    sys.exit(1)


def process_density_files(
    density_patterns: Sequence[str],
    allow_mixed_type: bool = False,
    allow_mixed_format: bool = False,
) -> tuple[list[list[str]], str, str]:
    """Create sample list records from density files.

    Parameters
    ----------
    density_patterns : Sequence[str]
        Input files or glob patterns.
    allow_mixed_type : bool
        Whether to allow Ribo and RNA density files in the same list.
    allow_mixed_format : bool
        Whether to allow JSON and TXT density files in the same list.

    Returns
    -------
    tuple[list[list[str]], str, str]
        Sample-list records, detected density type, and detected file format.
    """
    density_files = expand_density_inputs(density_patterns)
    density_merge: list[list[str]] = []
    density_types: set[str] = set()
    density_formats: set[str] = set()
    sample_names: set[str] = set()

    for density_file in density_files:
        file_name = os.path.basename(density_file)
        file_path_name = os.path.abspath(density_file)

        sample_name = infer_sample_name(file_name)
        density_type = infer_density_type(file_name)
        density_format = infer_density_format(file_name)

        if sample_name in sample_names:
            print(f"Error: duplicated sample name detected: {sample_name}", flush=True)
            print(
                "Please rename the input files or separate the lists before merging.",
                flush=True,
            )
            sys.exit(1)

        sample_names.add(sample_name)
        density_types.add(density_type)
        density_formats.add(density_format)
        density_merge.append([sample_name, file_path_name, density_type, density_format])

    if len(density_types) > 1 and not allow_mixed_type:
        print("Error: mixed Ribo and RNA density files were detected.", flush=True)
        print("Use --allow-mixed-type only if this is intentional.", flush=True)
        sys.exit(1)

    if len(density_formats) > 1 and not allow_mixed_format:
        print("Error: mixed JSON and TXT density files were detected.", flush=True)
        print("This is usually not recommended for rpf_Merge.", flush=True)
        print("Use --allow-mixed-format only if this is intentional.", flush=True)
        sys.exit(1)

    detected_type = next(iter(density_types)) if len(density_types) == 1 else "Mixed"
    detected_format = next(iter(density_formats)) if len(density_formats) == 1 else "mixed"

    return density_merge, detected_type, detected_format


def output_table(
    density_merge: list[list[str]],
    density_type: str,
    density_format: str,
    output_file: str | None,
) -> None:
    """Write the density sample list."""
    if output_file is None:
        if density_type == "Ribo":
            output_file = "RPF.file.list"
        elif density_type == "RNA":
            output_file = "RNA.file.list"
        else:
            output_file = "Density.file.list"

    density_merge_df = pd.DataFrame(
        density_merge,
        columns=["Name", "File", "Type", "Format"],
    )

    density_merge_df.sort_values(by=["Name", "File"], inplace=True)
    density_merge_df.to_csv(output_file, sep="\t", index=False)

    print(f"Density type: {density_type}", flush=True)
    print(f"Density format: {density_format}", flush=True)
    print(f"Density file list written: {output_file}", flush=True)


def main(argv: Sequence[str] | None = None) -> None:
    """Command-line entry point."""
    print("Step1: Checking the input arguments.", flush=True)
    args = merge_density_args_parser(argv)

    print("Step2: List density files.", flush=True)
    density_file_list, density_type, density_format = process_density_files(
        args.list,
        allow_mixed_type=args.allow_mixed_type,
        allow_mixed_format=args.allow_mixed_format,
    )

    print("Step3: Output density file list.", flush=True)
    output_table(density_file_list, density_type, density_format, args.output)

    print("All done.", flush=True)


if __name__ == "__main__":
    main()
