#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-06-12
# Version: 0.2.7
# Function: This script is used to merge the pausing score files.
# Input: Command-line arguments and input files specified by the user.
# Output: Analysis tables, figures, logs, or intermediate files generated by the command.


import pandas as pd
import argparse


def merge_pausing_args_parser():

    parser = argparse.ArgumentParser(description='This script is used to merge the pausing score files')

    # needed arguments
    input_group = parser.add_argument_group('Required arguments')
    input_group.add_argument(
        "-l", "--list", nargs='+', required=True, help="List for pausing score files (e.g., '*sum_codon_pausing_score.txt')."
    )
    input_group.add_argument(
        '-o', dest='output', required=True, type=str, help='prefix of output file name (default: prefix + sum_codon_pausing_score.txt).'
    )

    args = parser.parse_args()
    args_dict = vars(args)
    for k, v in args_dict.items():
        print('{:<12}:  {:<}'.format(k, str(v)), flush=True)

    return args


def import_pausing_files(pausing_list):
    """Retrieve the pausing table.

    Parameters
    ----------
    pausing_list : object
        Input argument used by this function.

    Returns
    -------
    object
        output dataframe contain the pausing.

    Notes
    -----
    Legacy input information:
    - ``list``: pattern for pausing files (e.g., '*sum_codon_pausing_score.txt').

    Workflow
    --------
    1. Retrieve the pausing.
    """

    # make the dataframe
    pausing_df = pd.DataFrame()

    # for each pausing file
    for pausing_file in pausing_list:
        # import the pausing file
        pausing = pd.read_csv(pausing_file, sep='\t', index_col=False)
        pausing.sort_values(by=['Abbr', 'Codon'], ascending=True, inplace=True, ignore_index=True)

        # merge the gene pausing file
        if pausing_df.empty:
            pausing_df = pausing
        else:
            # delete the columns ['AA', 'Abbr.', 'count']
            pausing = pausing.drop(['AA', 'Abbr', 'Count'], axis=1)
            pausing_df = pd.merge(left=pausing_df, right=pausing, how='outer', on='Codon')

    # reorder the pausing columns with 
    # ['codon', 'AA', 'Abbr.', 'count', *_valid_codon, *_rpf_count, *_absolute_total_ps, *_absolute_valid_ps, *_relative_total_ps, *_relative_valid_ps]
    pausing_codon = pausing_df[['Codon', 'AA', 'Abbr', 'Count']]
    pausing_valid_codon = pausing_df.filter(regex='_valid_codon')
    pausing_rpf_count = pausing_df.filter(regex='_rpf_count')
    pausing_total_ps = pausing_df.filter(regex='_absolute_total_ps')
    pausing_valid_ps = pausing_df.filter(regex='_absolute_valid_ps')
    pausing_rel_total_ps = pausing_df.filter(regex='_relative_total_ps')
    pausing_rel_valid_ps = pausing_df.filter(regex='_relative_valid_ps')

    pausing_merge = pd.concat([pausing_codon, pausing_valid_codon, pausing_rpf_count,
                               pausing_total_ps, pausing_valid_ps, pausing_rel_total_ps, pausing_rel_valid_ps], 
                               axis=1)

    return pausing_merge


def output_table(pausing_merge, output_file):
    """Output.

    Parameters
    ----------
    pausing_merge : object
        Input argument used by this function.
    output_file : object
        Input argument used by this function.

    Returns
    -------
    None
        The function updates internal state or writes output files in place.

    Notes
    -----
    Legacy input information:
    - ``result_dict``: nested dict contain the pausing.

    Legacy return information:
    - ``output``: description.

    Workflow
    --------
    1. Convert the dict to dataframe.
    """

    pausing_merge.to_csv(output_file + '_sum_codon_pausing_score.txt', sep='\t', index=False)


def main():

    print('Step1: Checking the input Arguments.', flush=True)
    args = merge_pausing_args_parser()

    print('Step2: import the pausing file.', flush=True)
    pausing_df = import_pausing_files(args.list)

    print('Step3: output the pausing table.', flush=True)
    output_table(pausing_df, args.output)

    print('All done.', flush=True)


if __name__ == '__main__':
    main()
