#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-06-12
# Version: 0.2.7
# Function: This script is used to merge the 3-nt periodicity files.
# Input: Command-line arguments and input files specified by the user.
# Output: Analysis tables, figures, logs, or intermediate files generated by the command.


import os
import pandas as pd
from collections import OrderedDict
import argparse


def merge_period_args_parser():

    parser = argparse.ArgumentParser(description='This script is used to merge the 3-nt periodicity files')

    # needed arguments
    input_group = parser.add_argument_group('Required arguments')
    input_group.add_argument(
        "-l", "--list", nargs='+', required=True, help="List for periodicity files (e.g., '*_periodicity.txt')."
    )
    input_group.add_argument(
        '-o', dest='output', required=True, type=str, help='prefix of output file name (default: prefix + _periodicity.txt).'
    )

    args = parser.parse_args()
    args_dict = vars(args)
    for k, v in args_dict.items():
        print('{:<12}:  {:<}'.format(k, str(v)), flush=True)

    return args


def import_period_files(period_list):
    """Retrieve the periodicity table.

    Parameters
    ----------
    period_list : object
        Input argument used by this function.

    Returns
    -------
    object
        output dataframe contain the 3-nt periodicity.

    Notes
    -----
    Legacy input information:
    - ``list``: pattern for 3-nt periodicity files (e.g., '*_periodicity.txt').

    Workflow
    --------
    1. Retrieve the 3-nt periodicity.
    """

    # make the dataframe
    period_colunms = ['Sample', 'Frame', 'Count', 'Ratio']
    period_df = pd.DataFrame(columns=period_colunms)

    # for each gne file
    for period_file in period_list:
        # import the motif file
        period = pd.read_csv(period_file, sep='\t', index_col=False)

        # merge the gene periodion file
        period_df = pd.concat([period_df, period], axis=0)

    return period_df


def output_table(period_merge, output_file):
    """Output.

    Parameters
    ----------
    period_merge : object
        Input argument used by this function.
    output_file : object
        Input argument used by this function.

    Returns
    -------
    None
        The function updates internal state or writes output files in place.

    Notes
    -----
    Legacy input information:
    - ``result_dict``: nested dict contain the 3-nt periodicity.

    Legacy return information:
    - ``output``: description.

    Workflow
    --------
    1. Convert the dict to dataframe.
    """

    period_merge.to_csv(output_file + '_periodicity.txt', sep='\t', index=False)


def main():

    print('Step1: Checking the input Arguments.', flush=True)
    args = merge_period_args_parser()

    print('Step2: import the 3-nt periodicity file.', flush=True)
    period_df = import_period_files(args.list)

    print('Step3: output the 3-nt periodicity table.', flush=True)
    output_table(period_df, args.output)

    print('All done.', flush=True)


if __name__ == '__main__':
    main()
