#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-06-12
# Version: 0.2.7
# Function: This script is used to statstic the mapped reads from log files.
# Input: Command-line arguments and input files specified by the user.
# Output: Analysis tables, figures, logs, or intermediate files generated by the command.


import os
import matplotlib

matplotlib.use("AGG")

import matplotlib.font_manager as fm
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from collections import OrderedDict
import argparse

def _setup_fonts():
    """Register Arial / Liberation Sans and set them as the default font.

    Arial is preferred. Liberation Sans is metric-compatible with Arial and
    is commonly shipped with Linux distributions, so it is used as the
    fallback when Arial is not installed. DejaVu Sans is the last resort.

    Returns
    -------
    None
    """

    candidates = []
    for path in fm.findSystemFonts(fontext='ttf'):
        base = os.path.basename(path).lower()
        if 'arial' in base or 'liberationsans' in base:
            candidates.append(path)
    # also scan a few common font directories manually
    extra_dirs = [
        '/usr/share/fonts', '/usr/local/share/fonts',
        os.path.expanduser('~/.fonts'), os.path.expanduser('~/.local/share/fonts'),
    ]
    for d in extra_dirs:
        if os.path.isdir(d):
            for root, _, files in os.walk(d):
                for f in files:
                    base = f.lower()
                    if 'arial' in base or 'liberationsans' in base:
                        candidates.append(os.path.join(root, f))

    seen = set()
    for path in candidates:
        path = os.path.abspath(path)
        if path in seen:
            continue
        seen.add(path)
        try:
            fm.fontManager.addfont(path)
        except Exception:
            pass

    plt.rcParams['font.family'] = 'sans-serif'
    plt.rcParams['font.sans-serif'] = ['Arial', 'Liberation Sans', 'Helvetica', 'DejaVu Sans']


_setup_fonts()

def stat_bwt_args_parser():

    parser = argparse.ArgumentParser(description='This script is used to statstic the mapped reads from log files')

    # needed arguments
    input_group = parser.add_argument_group('Required arguments')
    input_group.add_argument(
        "-l", "--list", nargs='+', required=True, help="List for bowtie mapping log files (e.g., '*log')."
    )
    input_group.add_argument(
        '-o', dest='output', required=True, type=str, help='prefix of output file name.'
    )

    # optional arguments
    parser.add_argument(
        "-n", "--name", required=False, default="rRNA,tRNA,ncRNA,mRNA,Genome", 
        help="set the name of each database (default: %(default)s)."
    )

    args = parser.parse_args()
    args_dict = vars(args)
    for k, v in args_dict.items():
        print('{:<12}:  {:<}'.format(k, str(v)), flush=True)

    return args


def process_log_files(log_file_list, database_list=None):
    """
    Retrieve the mapped reads from log files.

    Parameters
    ----------
    log_file_list : list
        List of log file paths.
    database_list : str or None
        Comma-separated database names, e.g. "rRNA,tRNA,ncRNA,mRNA,Genome".

    Returns
    -------
    result_dict : OrderedDict
        Nested dict storing read counts.
    database_list : list
        Parsed database list.
    """

    if database_list is None:
        database_list = ['rRNA', 'tRNA', 'ncRNA', 'mRNA', 'Genome']
    else:
        database_list = database_list.split(',')

    result_dict = OrderedDict()

    for log_file in log_file_list:
        file_prefix = os.path.basename(log_file).split('.')[0]
        result_dict[file_prefix] = OrderedDict()

        mapped_sum = 0
        flag = -1  # index for database_list

        with open(log_file, 'r') as file_in:
            for line in file_in:
                line = line.strip()

                # Total reads (only once)
                if flag == -1 and line.startswith("# reads processed:"):
                    result_dict[file_prefix]['Total'] = int(line.split()[-1])
                    flag = 0

                # Case 1: reported alignments
                elif flag >= 0 and line.startswith("Reported"):
                    count = int(line.split()[-2])
                    result_dict[file_prefix][database_list[flag]] = count
                    mapped_sum += count
                    flag += 1

                # Case 2: no alignments
                elif flag >= 0 and line == "No alignments":
                    result_dict[file_prefix][database_list[flag]] = 0
                    flag += 1

                # Skip summary/stat lines
                elif line.startswith("# reads with") or \
                     line.startswith("# reads that") or \
                     line.startswith("# reads processed:"):
                    continue

                # Ignore empty or unrelated lines
                else:
                    continue

        # Reads not mapped to any listed database
        result_dict[file_prefix]['Others'] = (result_dict[file_prefix]['Total'] - mapped_sum)

    return result_dict, database_list


def output_table(result_dict, database_list, output_file):
    """Output.

    Parameters
    ----------
    result_dict : object
        nested dict contain the mapped reads.
    database_list : object
        Input argument used by this function.
    output_file : object
        Input argument used by this function.

    Returns
    -------
    None
        The function updates internal state or writes output files in place.

    Notes
    -----
    Legacy return information:
    - ``output``: description.

    Workflow
    --------
    1. Convert the dict to dataframe.
    """
    
    mapped_df = pd.DataFrame.from_dict(result_dict, orient='index').fillna(0)
    ratio_df = mapped_df.div(mapped_df['Total'], axis=0) * 100

    mapped_df = mapped_df.drop('Total', axis=1).reset_index().melt(id_vars='index', var_name='Database', value_name='Count')
    ratio_df = ratio_df.drop('Total', axis=1).reset_index().melt(id_vars='index', var_name='Database', value_name='Ratio')

    mapped_df = mapped_df.rename(columns={'index': 'Sample'}).set_index(['Sample', 'Database'])
    ratio_df = ratio_df.rename(columns={'index': 'Sample'}).set_index(['Sample', 'Database'])

    result_df = mapped_df.join(ratio_df, how='outer').reset_index()
    result_df['Ratio'] = result_df['Ratio'].astype('float').round(2)
    
    database_list = database_list + ['Others']
    result_df['Database'] = pd.Categorical(result_df['Database'], categories=database_list, ordered=True)
    result_df = result_df.sort_values(by=['Sample', 'Database'])

    result_df.to_csv(output_file + '_mapping.txt', sep='\t', index=False)


def output_barplot(result_dict, database_list, output_file):
    """Draw stacked bar plots of mapped read counts and ratios.

    Parameters
    ----------
    result_dict : OrderedDict
        Nested dict storing read counts.
    database_list : list
        Database names in mapping order.
    output_file : str
        Prefix of the output figure file.

    Returns
    -------
    None
        The function writes the figure to '<output_file>_mapping_barplot.png'
        and '<output_file>_mapping_barplot.pdf' in place.

    Notes
    -----
    The left subplot shows the raw read count of each database, while the
    right subplot shows the corresponding ratio (%). The ``Paired`` colormap
    is used for the bars. Sample labels are rotated 90 degrees.
    """

    mapped_df = pd.DataFrame.from_dict(result_dict, orient='index').fillna(0)
    ratio_df = mapped_df.div(mapped_df['Total'], axis=0) * 100

    mapped_df = mapped_df.drop('Total', axis=1)
    ratio_df = ratio_df.drop('Total', axis=1)

    database_list = database_list + ['Others']
    # keep the column order consistent with database_list
    mapped_df = mapped_df.reindex(columns=database_list).fillna(0)
    ratio_df = ratio_df.reindex(columns=database_list).fillna(0)

    sample_list = list(mapped_df.index)
    x = np.arange(len(sample_list))

    # Paired colormap (cycle if more than 12 databases)
    paired_cmap = plt.get_cmap('Paired')
    colors = [paired_cmap(i % 12) for i in range(len(database_list))]

    # bar width: slightly wider to tighten the gaps between samples
    bar_width = 0.8
    figure, axes = plt.subplots(
        1, 2,
        figsize=(max(8.0, 1.8 * len(sample_list)), 8),
        dpi=500,
    )

    # left: count
    bottom = np.zeros(len(sample_list))
    for i, db in enumerate(database_list):
        axes[0].bar(
            x, mapped_df[db].to_numpy(), bottom=bottom,
            width=bar_width, label=db, color=colors[i],
            edgecolor='white', linewidth=0.5,
        )
        bottom += mapped_df[db].to_numpy()
    axes[0].set_xticks(x)
    axes[0].set_xticklabels(sample_list, rotation=90, ha='center', size=12)
    axes[0].set_xlabel('Sample', size=14)
    axes[0].set_ylabel('Count', size=14)
    axes[0].set_title('Mapped read count', size=14)

    # right: ratio
    bottom = np.zeros(len(sample_list))
    for i, db in enumerate(database_list):
        axes[1].bar(
            x, ratio_df[db].to_numpy(), bottom=bottom,
            width=bar_width, label=db, color=colors[i],
            edgecolor='white', linewidth=0.5,
        )
        bottom += ratio_df[db].to_numpy()
    axes[1].set_xticks(x)
    axes[1].set_xticklabels(sample_list, rotation=90, ha='center', size=12)
    axes[1].set_xlabel('Sample', size=14)
    axes[1].set_ylabel('Ratio (%)', size=14)
    axes[1].set_title('Mapped read ratio', size=14)

    handles, labels = axes[0].get_legend_handles_labels()
    figure.legend(
        handles, labels,
        loc='upper center', bbox_to_anchor=(0.5, 1.0),
        ncol=min(len(database_list), 6), frameon=False,
    )

    figure.tight_layout(rect=[0, 0, 1, 0.94])
    figure.savefig(output_file + '_mapping_barplot.png', bbox_inches='tight')
    figure.savefig(output_file + '_mapping_barplot.pdf', bbox_inches='tight')
    plt.close(figure)


def main():

    print('Step1: Checking the input Arguments.', flush=True)
    args = stat_bwt_args_parser()

    print('Step2: improt the bowtie log file.', flush=True)
    result_dict, database_list = process_log_files(args.list, args.name)

    print('Step3: output the mapping table.', flush=True)
    output_table(result_dict, database_list, args.output)

    print('Step4: draw the mapping barplot.', flush=True)
    output_barplot(result_dict, database_list, args.output)

    print('All done.', flush=True)


if __name__ == '__main__':
    main()
