#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-07-21
# Version: 0.2.8.18
# Function: Calculate transcript-level RNA-seq read density from BAM alignments.
# Input: Transcript annotation, transcript FASTA, BAM alignment, and offset table.
# Output: RNA-seq density table.

"""Command-line entry point for RNA-seq density calculation."""

from __future__ import annotations

import argparse
from argparse import Namespace
from collections.abc import Sequence

from utils.ribo import RNA
from utils.ribo.ArgsParser import args_print, file_check, now_time


def _build_parser() -> argparse.ArgumentParser:
    """Build the command-line argument parser."""
    parser = argparse.ArgumentParser(
        description="Calculate transcript-level RNA-seq read density."
    )

    required_group = parser.add_argument_group("Required arguments")
    required_group.add_argument(
        "-t",
        "--transcript",
        dest="transcript",
        required=True,
        type=str,
        help="Input transcript annotation file generated by rpf_Reference.",
    )
    required_group.add_argument(
        "-s",
        "--sequence",
        dest="sequence",
        required=True,
        type=str,
        help="Input transcript sequence file in FASTA format.",
    )
    required_group.add_argument(
        "-b",
        "--bam",
        dest="bam",
        required=True,
        type=str,
        help="Input BAM alignment file.",
    )
    required_group.add_argument(
        "-p",
        "--psite",
        dest="psite",
        required=True,
        type=str,
        help="Input RNA-seq offset table.",
    )
    required_group.add_argument(
        "-o",
        "--output",
        dest="output",
        required=True,
        type=str,
        help="Output file prefix.",
    )

    filtering_group = parser.add_argument_group("Read filtering arguments")
    filtering_group.add_argument(
        "-l",
        "--longest",
        dest="longest",
        action="store_true",
        default=False,
        help="Only retain the representative transcript per gene (default: %(default)s).",
    )
    filtering_group.add_argument(
        "-m",
        "--min",
        dest="min",
        default=25,
        type=int,
        help="Minimum read length retained (default: %(default)s nt).",
    )
    filtering_group.add_argument(
        "-M",
        "--max",
        dest="max",
        default=150,
        type=int,
        help="Maximum read length retained (default: %(default)s nt).",
    )
    filtering_group.add_argument(
        "-r",
        "--rolling",
        dest="rolling",
        action="store_true",
        default=False,
        help="Use rolling read assignment (default: %(default)s).",
    )
    filtering_group.add_argument(
        "--pe",
        dest="pair_end",
        action="store_true",
        default=False,
        help="Process paired-end RNA-seq alignments (default: %(default)s).",
    )

    runtime_group = parser.add_argument_group("Runtime arguments")
    runtime_group.add_argument(
        "--thread",
        dest="thread",
        default=1,
        type=int,
        help="Number of worker processes (default: %(default)s).",
    )

    return parser


def _validate_args(args: Namespace) -> None:
    """Validate command-line arguments."""
    file_check(args.transcript, args.sequence, args.bam, args.psite)
    if args.min <= 0:
        raise ValueError("-m must be > 0.")
    if args.max < args.min:
        raise ValueError("-M must be >= -m.")
    if args.thread < 1:
        raise ValueError("--thread must be >= 1.")


def _parse_args(argv: Sequence[str] | None = None) -> Namespace:
    """Parse, validate, and print command-line arguments."""
    parser = _build_parser()
    args = parser.parse_args(argv)
    _validate_args(args)
    args_print(args)
    return args


def _print_step(step: int, message: str) -> None:
    """Print a standardized pipeline step message."""
    print(f"\nStep{step}: {message}", flush=True)


def _run_rna_density_pipeline(args: Namespace) -> None:
    """Run the RNA-seq density workflow."""
    density = RNA.RNA(args)

    _print_step(2, "Import the RNA-seq offset table.")
    density.read_offset()

    _print_step(3, "Import transcript annotation.")
    density.read_transcript()

    _print_step(4, "Import BAM alignments.")
    density.read_bam()

    _print_step(5, "Calculate RNA-seq read density.")
    density.calculate_density()

    _print_step(6, "Format read-density records.")
    density.run_format_reads_with_multi_thread()

    _print_step(7, "Output the RNA-seq density table.")
    density.output_density()


def main(argv: Sequence[str] | None = None) -> None:
    """Command-line entry point for rna_Density."""
    now_time()
    print("\nCalculate transcript-level RNA-seq read density.", flush=True)
    _print_step(1, "Checking the input arguments.")

    args = _parse_args(argv)
    _run_rna_density_pipeline(args)

    print("\nAll done.", flush=True)
    now_time()


if __name__ == "__main__":
    main()
