#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-07-09
# Version: 0.2.8-dev.013
# Function: Summarize RPF BAM/SAM mapping quality and output filtered BAM.
# Input: RiboParser transcript annotation and BAM/SAM alignment file.
# Output: Filtered sorted BAM, BAM index, length distribution, summary JSON, and optional saturation plots.

"""Command-line entry point for rpf_Check."""

from __future__ import annotations

import argparse
from argparse import Namespace
from collections.abc import Sequence


from utils.ribo.Quality import Quality

from utils.ribo.ArgsParser import (
    args_print,
    complete_print,
    file_check,
    now_time,
    step_print,
    title_print,
)


def _build_parser() -> argparse.ArgumentParser:
    """Build the command-line argument parser."""
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description="Summarize RPF BAM/SAM mapping quality and output filtered BAM.",
    )

    input_group = parser.add_argument_group("Required arguments")
    input_group.add_argument(
        "-t",
        dest="transcript",
        required=True,
        type=str,
        help="Input gene/transcript annotation file generated by rpf_Reference.",
    )
    input_group.add_argument(
        "-b",
        dest="bam",
        required=True,
        type=str,
        help="Input BAM/SAM alignment file.",
    )
    input_group.add_argument(
        "-o",
        dest="output",
        required=True,
        type=str,
        help="Output prefix.",
    )

    runtime_group = parser.add_argument_group("Runtime and performance options")
    runtime_group.add_argument(
        "--thread",
        dest="thread",
        required=False,
        type=int,
        default=4,
        help=(
            "Number of parallel worker processes and BAM I/O threads "
            "(default: %(default)s). When this value is greater than 1, "
            "rpf_Check automatically prepares an indexed BAM and uses "
            "multi-process transcript-reference fetching."
        ),
    )

    filter_group = parser.add_argument_group("Read filtering options")
    filter_group.add_argument(
        "-g",
        dest="tag",
        choices=[0, 1],
        type=int,
        required=False,
        default=0,
        help=(
            "Filter reads by mapping uniqueness (default: %(default)s). "
            "[0]: all mapped reads are used; [1]: unique mapped reads are used."
        ),
    )
    filter_group.add_argument(
        "-a",
        dest="align",
        choices=["star", "hisat2", "bowtie2"],
        type=str,
        required=False,
        default="star",
        help=(
            "Aligner used to generate the BAM/SAM file. This option controls "
            "unique-read tag interpretation. (default: %(default)s)."
        ),
    )
    filter_group.add_argument(
        "-r",
        dest="reverse",
        action="store_true",
        required=False,
        default=False,
        help=(
            "Backward-compatible option retained for old commands. The optimized "
            "rpf_Check workflow always retains and reports plus/minus strands separately."
        ),
    )
    filter_group.add_argument(
        "-l",
        dest="longest",
        action="store_true",
        required=False,
        default=False,
        help="Only keep the representative/longest transcript per gene. (default: %(default)s).",
    )
    filter_group.add_argument(
        "-s",
        dest="saturation",
        action="store_true",
        required=False,
        default=False,
        help=(
            "Calculate RPF saturation. (default: %(default)s). This step takes "
            "extra memory, especially when multi-mapping reads are retained."
        ),
    )
    filter_group.add_argument(
        "--secondary",
        dest="secondary",
        action="store_true",
        required=False,
        default=False,
        help="Keep secondary alignments. (default: %(default)s).",
    )
    filter_group.add_argument(
        "--supplementary",
        dest="supplementary",
        action="store_true",
        required=False,
        default=False,
        help="Keep supplementary alignments. (default: %(default)s).",
    )
    filter_group.add_argument(
        "--duplicate",
        dest="duplicate",
        action="store_true",
        required=False,
        default=False,
        help="Keep duplicate alignments. (default: %(default)s).",
    )

    return parser


def _validate_args(args: Namespace) -> None:
    """Validate command-line arguments."""
    file_check(args.transcript, args.bam)


def _parse_args(argv: Sequence[str] | None = None) -> Namespace:
    """Parse, validate, and print command-line arguments."""
    parser = _build_parser()
    args = parser.parse_args(argv)
    _validate_args(args)
    args_print(args)
    return args


def _run_check_pipeline(args: Namespace) -> None:
    """Run the optimized rpf_Check workflow."""
    rpf_quality = Quality(args)

    step_print(2, "Import the transcripts annotation.")
    rpf_quality.read_transcript()

    step_print(3, "Scan mRNA-aligned reads and output filtered BAM.")
    rpf_quality.scan_mrna_reads()

    step_print(4, "Detect the type of sequence profile.")
    if not rpf_quality.profile:
        rpf_quality.detect_seq_type()
    else:
        print(
            "{bam} is specified as {ribo}-seq.".format(
                bam=rpf_quality.sample_file,
                ribo=rpf_quality.profile,
            ),
            flush=True,
        )

    step_print(5, "Summarize the length distribution of reads aligned to mRNA.")
    rpf_quality.write_length_distr()
    rpf_quality.write_summary()

    if args.saturation:
        step_print(6, "Check the RPFs saturation.")
        rpf_quality.rpf_saturation()
        rpf_quality.draw_gene_saturation()
        rpf_quality.draw_rpf_saturation()
        rpf_quality.write_summary()
    else:
        step_print(6, "Do not check the RPFs saturation.")


def main(argv: Sequence[str] | None = None) -> None:
    """Command-line entry point for rpf_Check."""
    now_time()
    title_print('Check the RPFs mapping condition.')

    step_print(1, "Checking the input arguments.")
    args = _parse_args(argv)

    _run_check_pipeline(args)

    complete_print()
    now_time()


if __name__ == "__main__":
    main()
