#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-07-21
# Version: 0.2.8.18
# Function: Calculate the relative RPF density distribution across transcript regions.
# Input: RiboParser transcript annotation and frame-resolved RPF density file.
# Output: RPF density percentage table and summary figures.

"""Command-line entry point for RPF density percentage analysis."""

from __future__ import annotations

import argparse
from argparse import Namespace
from collections.abc import Sequence

from utils.ribo import Percentage
from utils.ribo.ArgsParser import args_print, file_check, now_time


def _build_parser() -> argparse.ArgumentParser:
    """Build the command-line argument parser."""
    parser = argparse.ArgumentParser(
        description="Calculate the relative RPF density distribution."
    )

    required_group = parser.add_argument_group("Required arguments")
    required_group.add_argument(
        "-t",
        dest="transcript",
        required=True,
        type=str,
        help="Input transcript annotation file generated by rpf_Reference.",
    )
    required_group.add_argument(
        "-r",
        dest="rpf",
        required=True,
        type=str,
        help="Input frame-resolved RPF density file.",
    )
    required_group.add_argument(
        "-o",
        dest="output",
        required=False,
        default=None,
        type=str,
        help="Output file prefix. Default: determined from the input filename.",
    )

    calculation_group = parser.add_argument_group("Calculation arguments")
    calculation_group.add_argument(
        "-f",
        dest="frame",
        choices=["0", "1", "2", "all"],
        default="all",
        type=str,
        help="Reading frame used for calculation (default: %(default)s).",
    )
    calculation_group.add_argument(
        "-m",
        dest="min",
        default=50,
        type=int,
        help="Minimum RPF count required for retained transcripts (default: %(default)s).",
    )
    calculation_group.add_argument(
        "-n",
        dest="normal",
        action="store_true",
        default=False,
        help="Normalize RPF counts to RPM (default: %(default)s).",
    )

    return parser


def _validate_args(args: Namespace) -> None:
    """Validate command-line arguments."""
    file_check(args.transcript, args.rpf)
    if args.min < 0:
        raise ValueError("-m must be >= 0.")


def _parse_args(argv: Sequence[str] | None = None) -> Namespace:
    """Parse, validate, and print command-line arguments."""
    parser = _build_parser()
    args = parser.parse_args(argv)
    _validate_args(args)
    args_print(args)
    return args


def _print_step(step: int, message: str) -> None:
    """Print a standardized pipeline step message."""
    print(f"\nStep{step}: {message}", flush=True)


def _run_percentage_pipeline(args: Namespace) -> None:
    """Run the RPF density percentage workflow."""
    percentage = Percentage.Percentage(args)

    _print_step(2, "Import the RPF density file.")
    percentage.read_rpf()

    _print_step(3, "Import transcript annotation.")
    percentage.import_gene()

    _print_step(4, "Calculate the RPF density percentage.")
    percentage.calc_density_percent()

    _print_step(5, "Draw RPF density summary figures.")
    percentage.draw_rpf_histogram()
    percentage.draw_rpf_boxplot()

    _print_step(6, "Output the RPF density percentage table.")
    percentage.output_density_percent()


def main(argv: Sequence[str] | None = None) -> None:
    """Command-line entry point for rpf_Percent."""
    now_time()
    print("\nCalculate the relative RPF density distribution.", flush=True)
    _print_step(1, "Checking the input arguments.")

    args = _parse_args(argv)
    _run_percentage_pipeline(args)

    print("\nAll done.", flush=True)
    now_time()


if __name__ == "__main__":
    main()
