#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-07-21
# Version: 0.2.8.18
# Function: Detect RPF digestion-site nucleotide preferences.
# Input: Transcript annotation, transcript FASTA, and BAM alignment file.
# Output: Digestion-site tables, motif counts, heatmaps, and sequence logos.

"""Command-line entry point for RPF digestion-site analysis."""

from __future__ import annotations

import argparse
from argparse import Namespace
from collections.abc import Sequence

from utils.ribo.ArgsParser import args_print, file_check, now_time


def _build_parser() -> argparse.ArgumentParser:
    """Build the command-line argument parser."""
    parser = argparse.ArgumentParser(
        description="Detect RPF digestion-site nucleotide preferences."
    )

    required_group = parser.add_argument_group("Required arguments")
    required_group.add_argument(
        "-t",
        dest="transcript",
        required=True,
        type=str,
        help="Input transcript annotation file generated by rpf_Reference.",
    )
    required_group.add_argument(
        "-s",
        dest="sequence",
        required=True,
        type=str,
        help="Input transcript sequence file in FASTA format.",
    )
    required_group.add_argument(
        "-b",
        dest="bam",
        required=True,
        type=str,
        help="Input BAM alignment file.",
    )
    required_group.add_argument(
        "-o",
        dest="output",
        required=True,
        type=str,
        help="Output file prefix.",
    )

    filtering_group = parser.add_argument_group("Read filtering arguments")
    filtering_group.add_argument(
        "-l",
        dest="longest",
        action="store_true",
        default=False,
        help="Only retain the transcript with the longest CDS per gene.",
    )
    filtering_group.add_argument(
        "-m",
        dest="min",
        default=20,
        type=int,
        help="Minimum read length retained (default: %(default)s nt).",
    )
    filtering_group.add_argument(
        "-M",
        dest="max",
        default=100,
        type=int,
        help="Maximum read length retained (default: %(default)s nt).",
    )

    calculation_group = parser.add_argument_group("Calculation arguments")
    calculation_group.add_argument(
        "--scale",
        dest="scale",
        action="store_true",
        default=False,
        help="Scale the digestion-site motif matrix (default: %(default)s).",
    )

    runtime_group = parser.add_argument_group("Runtime arguments")
    runtime_group.add_argument(
        "-p",
        "--thread",
        dest="thread",
        default=1,
        type=int,
        help="Number of worker processes for indexed BAM input (default: %(default)s).",
    )

    return parser


def _validate_args(args: Namespace) -> None:
    """Validate command-line arguments."""
    file_check(args.transcript, args.sequence, args.bam)
    if args.min <= 0:
        raise ValueError("-m must be > 0.")
    if args.max < args.min:
        raise ValueError("-M must be >= -m.")
    if args.thread < 1:
        raise ValueError("-p/--thread must be >= 1.")


def _parse_args(argv: Sequence[str] | None = None) -> Namespace:
    """Parse, validate, and print command-line arguments."""
    parser = _build_parser()
    args = parser.parse_args(argv)
    _validate_args(args)
    args_print(args)
    return args


def _print_step(step: int, message: str) -> None:
    """Print a standardized pipeline step message."""
    print(f"\nStep{step}: {message}", flush=True)


def _run_digest_pipeline(args: Namespace) -> None:
    """Run digestion-site detection."""
    from utils.ribo.Digestion import Ribo

    digestion = Ribo(args)

    _print_step(2, "Import transcript annotation.")
    digestion.read_transcript()

    _print_step(3, "Detect RPF digestion sites.")
    digestion.get_digest_sites()

    _print_step(4, "Output digestion-site tables.")
    digestion.output_digest_sites()

    _print_step(5, "Draw digestion-site heatmaps.")
    digestion.digestion_plot()

    _print_step(6, "Output digestion-site motif counts.")
    digestion.output_counts()

    _print_step(7, "Draw digestion-site sequence logos.")
    digestion.seq_logo_plot2()


def main(argv: Sequence[str] | None = None) -> None:
    """Command-line entry point for rpf_Digest."""
    now_time()
    print("\nDetect RPF digestion-site nucleotide preferences.", flush=True)
    _print_step(1, "Checking the input arguments.")

    args = _parse_args(argv)
    _run_digest_pipeline(args)

    print("\nAll done.", flush=True)
    now_time()


if __name__ == "__main__":
    main()
