#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-07-09
# Version: 0.2.8.2
# Function: Fast merge RPF density files generated by rpf_Density.
# Input: Sample list table and per-sample density JSONL or legacy TXT files.
# Output: Merged JSONL, legacy TXT, and summary files.

"""Fast RPF density merger.

This module merges RPF density files across samples. It is optimized for the
compact JSONL files produced by the enhanced ``rpf_Density`` workflow and also
keeps compatibility with legacy codon-level TXT density files.

The JSON fast path performs streaming transcript-order merging: all sample
files are opened together, one transcript record is read from each file, sample
payloads are merged, and the merged record is written immediately. This avoids
building large per-sample dictionaries in memory and is much faster than the
old dataframe/dictionary merge strategy.
"""

from __future__ import annotations

import argparse
import csv
import gzip
import json
import os
import sys
import time
from collections import OrderedDict
from contextlib import ExitStack
from dataclasses import dataclass
from pathlib import Path
from typing import BinaryIO, Dict, Iterable, Iterator, List, Optional, Sequence, TextIO, Tuple

try:
    import orjson  # type: ignore
except ImportError:  # pragma: no cover - optional speed dependency
    orjson = None

try:
    from utils.ribo.ArgsParser import args_print, file_check, now_time
except ImportError:  # pragma: no cover - supports standalone testing
    def now_time() -> None:
        print(time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()), flush=True)

    def args_print(args) -> None:
        for key, value in vars(args).items():
            print(f"{key:<12}:  {value}", flush=True)

    def file_check(*paths: str) -> None:
        for path in paths:
            if not os.path.exists(path):
                raise FileNotFoundError(path)


SPARSE_ENCODING = "sparse_codon_frame"
DENSE_ENCODING = "dense_codon_frame"
BASE_TXT_COLUMNS = ["name", "now_nt", "from_tis", "from_tts", "region", "codon"]
PROGRESS_EVERY = 1000
PROGRESS_RPF_EVERY = 500000
JSON_COMPRESS_LEVEL = 1
ORDER_CHECK = False
KEEP_SOURCE_SAMPLE_NAME = False


JsonDict = Dict[str, object]


@dataclass(frozen=True)
class SampleFile:
    """One sample-density file entry."""

    name: str
    file: str
    data_type: str
    file_format: str


# -----------------------------------------------------------------------------
# Argument parser
# -----------------------------------------------------------------------------


def rpf_merge_args_parser(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Fast merge RPF density files generated by rpf_Density in JSONL or TXT format."
    )

    required_group = parser.add_argument_group("Required arguments")
    required_group.add_argument(
        "-l",
        dest="list",
        required=True,
        type=str,
        help="Sample list table. Required columns: Name and File. Optional columns: Type and Format.",
    )
    required_group.add_argument(
        "-o",
        dest="output",
        required=True,
        type=str,
        help="Output prefix.",
    )

    parser.add_argument(
        "--input-format",
        dest="input_format",
        choices=["auto", "json", "txt"],
        default="auto",
        help="Input density format. Default: %(default)s.",
    )
    parser.add_argument(
        "--output-format",
        dest="output_format",
        choices=["auto", "json", "txt", "both"],
        default="auto",
        help="Output density format. Default: JSON input -> json; TXT input -> txt.",
    )
    parser.add_argument(
        "--density-encoding",
        dest="density_encoding",
        choices=["sparse", "dense"],
        default="sparse",
        help="Density encoding used when converting TXT input to JSON. Default: %(default)s.",
    )
    parser.add_argument(
        "--thread",
        dest="thread",
        type=int,
        default=1,
        help=(
            "Reserved for compatibility. The default streaming merge is usually faster "
            "than worker-based dictionary merge and does not need extra workers."
        ),
    )

    args = parser.parse_args(argv)
    file_check(args.list)
    args.thread = max(1, int(args.thread))
    args_print(args)
    return args


# -----------------------------------------------------------------------------
# Sample list reader
# -----------------------------------------------------------------------------


def _detect_density_format(file_path: str) -> str:
    """Detect density format from file suffix."""
    lowered = file_path.lower()
    if lowered.endswith((".jsonl.gz", ".jsonl", ".json.gz", ".json")):
        return "json"
    if lowered.endswith((".txt", ".txt.gz")):
        return "txt"
    raise ValueError(f"Unsupported density file suffix: {file_path}")


def _detect_density_type(file_path: str) -> str:
    """Infer density type from file name."""
    lowered = os.path.basename(file_path).lower()
    if "_rna" in lowered:
        return "RNA"
    return "Ribo"


def _normalize_format_value(value: str) -> str:
    """Normalize format labels from the sample list."""
    value = value.strip().lower()
    if value in {"json", "jsonl", "jsonl.gz", "json.gz"}:
        return "json"
    if value in {"txt", "text", "legacy"}:
        return "txt"
    if not value:
        return "auto"
    raise ValueError(f"Unsupported Format value: {value}")


def read_sample_list(sample_list: str, forced_format: str = "auto") -> List[SampleFile]:
    """Read sample list and return sample-density file entries."""
    records: List[SampleFile] = []

    with open(sample_list, "r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        if reader.fieldnames is None:
            raise ValueError(f"Empty sample list: {sample_list}")

        fields = [field.strip() for field in reader.fieldnames]
        if "Name" not in fields or "File" not in fields:
            raise ValueError("Sample list must contain at least Name and File columns.")

        for line_no, row in enumerate(reader, start=2):
            sample_name = (row.get("Name") or "").strip()
            file_path = (row.get("File") or "").strip()
            data_type = (row.get("Type") or "").strip() or _detect_density_type(file_path)
            format_value = (row.get("Format") or "").strip()

            if not sample_name:
                raise ValueError(f"Empty sample name at line {line_no}.")
            if not file_path:
                raise ValueError(f"Empty file path at line {line_no}.")
            if not os.path.exists(file_path):
                raise FileNotFoundError(file_path)

            if forced_format != "auto":
                file_format = forced_format
            else:
                file_format = _normalize_format_value(format_value)
                if file_format == "auto":
                    file_format = _detect_density_format(file_path)

            records.append(
                SampleFile(
                    name=sample_name,
                    file=os.path.abspath(file_path),
                    data_type=data_type,
                    file_format=file_format,
                )
            )

    if not records:
        raise ValueError("No density files were found in the sample list.")

    sample_names = [record.name for record in records]
    duplicated = sorted({name for name in sample_names if sample_names.count(name) > 1})
    if duplicated:
        raise ValueError("Duplicated sample names: " + ",".join(duplicated))

    formats = sorted({record.file_format for record in records})
    if len(formats) > 1:
        raise ValueError(
            "Mixed JSON and TXT inputs are not supported in one merge run. "
            "Please merge them separately."
        )

    return records


# -----------------------------------------------------------------------------
# JSON IO helpers
# -----------------------------------------------------------------------------


def _json_loads(line: bytes) -> JsonDict:
    """Load one JSON object from a byte line."""
    if orjson is not None:
        return orjson.loads(line)
    return json.loads(line)


def _json_dumps(record: JsonDict) -> bytes:
    """Dump one JSON object as compact bytes."""
    if orjson is not None:
        return orjson.dumps(record)
    return json.dumps(record, ensure_ascii=False, separators=(",", ":")).encode("utf-8")


def _open_binary_text(path: str) -> BinaryIO:
    """Open plain or gzip JSONL in binary mode."""
    if path.endswith(".gz"):
        return gzip.open(path, "rb")
    return open(path, "rb")


def _open_text(path: str) -> TextIO:
    """Open plain or gzip text table in text mode."""
    if path.endswith(".gz"):
        return gzip.open(path, "rt", encoding="utf-8")
    return open(path, "r", encoding="utf-8")


def _read_next_transcript(handle: BinaryIO) -> Optional[JsonDict]:
    """Read the next transcript record from a JSONL file."""
    for line in handle:
        line = line.strip()
        if not line:
            continue
        record = _json_loads(line)
        if record.get("record_type") != "transcript":
            continue
        return record
    return None


def _record_id(record: JsonDict) -> str:
    """Return transcript identifier for order validation."""
    value = record.get("transcript_id") or record.get("name")
    if value is None:
        raise ValueError("JSON record lacks transcript_id or name.")
    return str(value)


def _base_record_without_samples(record: JsonDict) -> JsonDict:
    """Create the base merged transcript record."""
    base: JsonDict = {}
    for key, value in record.items():
        if key in {"sample", "profile", "density", "samples"}:
            continue
        base[key] = value
    if "record_type" not in base:
        base["record_type"] = "transcript"
    return base


def _sample_payloads_from_json(record: JsonDict, sample_name: str, keep_source_sample_name: bool) -> OrderedDict[str, JsonDict]:
    """Extract sample payloads from a single-sample or merged JSON record."""
    payloads: OrderedDict[str, JsonDict] = OrderedDict()
    samples = record.get("samples")

    if isinstance(samples, dict) and samples:
        if len(samples) == 1 and not keep_source_sample_name:
            payload = next(iter(samples.values()))
            if not isinstance(payload, dict):
                raise ValueError("Invalid JSON samples payload.")
            payloads[sample_name] = payload
            return payloads

        for embedded_name, payload in samples.items():
            if not isinstance(payload, dict):
                raise ValueError("Invalid JSON samples payload.")
            out_name = str(embedded_name) if keep_source_sample_name or len(samples) > 1 else sample_name
            payloads[out_name] = payload
        return payloads

    payload: JsonDict = {
        "profile": record.get("profile", "unknown"),
        "density": record.get("density", {}),
    }
    out_name = str(record.get("sample", sample_name)) if keep_source_sample_name else sample_name
    payloads[out_name] = payload
    return payloads


# -----------------------------------------------------------------------------
# JSON -> JSON/TXT streaming merger
# -----------------------------------------------------------------------------


def _resolve_output_format(input_format: str, output_format: str) -> str:
    """Resolve automatic output format."""
    if output_format != "auto":
        return output_format
    return "json" if input_format == "json" else "txt"


def _check_output(path: str) -> None:
    """Prepare output path for overwrite-style writing."""
    if os.path.isdir(path):
        raise IsADirectoryError(f"Output path is a directory: {path}")


def _legacy_header(sample_names: List[str]) -> List[str]:
    """Build legacy TXT header."""
    header = BASE_TXT_COLUMNS.copy()
    for sample in sample_names:
        header.extend([f"{sample}_f0", f"{sample}_f1", f"{sample}_f2"])
    return header


def _sample_names_from_record(record: JsonDict) -> List[str]:
    """Return sample names from merged JSON record."""
    samples = record.get("samples")
    if isinstance(samples, dict):
        return [str(name) for name in samples.keys()]
    sample = record.get("sample")
    return [str(sample)] if sample is not None else ["sample"]


def _density_for_sample(record: JsonDict, sample_name: str) -> JsonDict:
    """Return density object for one sample from a merged record."""
    samples = record.get("samples")
    if isinstance(samples, dict):
        sample_entry = samples.get(sample_name)
        if isinstance(sample_entry, dict):
            density = sample_entry.get("density")
            if isinstance(density, dict):
                return density
    density = record.get("density")
    return density if isinstance(density, dict) else {}


def _density_to_frames(record: JsonDict, sample_name: str) -> Tuple[List[int], List[int], List[int]]:
    """Convert sparse or dense sample density to dense frame arrays."""
    trim = record.get("trim") if isinstance(record.get("trim"), dict) else {}
    codon_count = int(trim.get("codon_count", 0)) if isinstance(trim, dict) else 0
    density = _density_for_sample(record, sample_name)
    encoding = str(density.get("encoding", SPARSE_ENCODING))

    if encoding == DENSE_ENCODING:
        f0 = [int(x) for x in density.get("f0", [])]
        f1 = [int(x) for x in density.get("f1", [])]
        f2 = [int(x) for x in density.get("f2", [])]
        if len(f0) < codon_count:
            f0.extend([0] * (codon_count - len(f0)))
        if len(f1) < codon_count:
            f1.extend([0] * (codon_count - len(f1)))
        if len(f2) < codon_count:
            f2.extend([0] * (codon_count - len(f2)))
        return f0[:codon_count], f1[:codon_count], f2[:codon_count]

    f0 = [0] * codon_count
    f1 = [0] * codon_count
    f2 = [0] * codon_count
    frames = (f0, f1, f2)

    for codon_index, frame, count in zip(
        density.get("codon_index", []),
        density.get("frame", []),
        density.get("count", []),
    ):
        codon_index = int(codon_index)
        frame = int(frame)
        if 0 <= codon_index < codon_count and frame in (0, 1, 2):
            frames[frame][codon_index] += int(count)

    return f0, f1, f2


def _legacy_rows_from_json_record(record: JsonDict, sample_names: List[str]) -> Iterator[List[object]]:
    """Yield legacy TXT rows from one merged JSON record."""
    trim = record.get("trim") if isinstance(record.get("trim"), dict) else {}
    if not isinstance(trim, dict):
        return

    codon_count = int(trim.get("codon_count", 0))
    start_nt0 = int(trim.get("start_nt0", 0))
    utr5_codons = int(trim.get("utr5_codons", 0))
    cds_codons = int(trim.get("cds_codons", 0))
    utr3_nt = int(trim.get("utr3_nt", 0))
    trim_length_nt = int(trim.get("trim_length_nt", codon_count * 3))
    from_tts_start = (utr3_nt - trim_length_nt) // 3 + 1

    sequence = str(record.get("sequence", ""))
    transcript_name = str(record.get("name") or record.get("transcript_id") or "NA")
    frame_arrays = [_density_to_frames(record, sample_name) for sample_name in sample_names]

    for codon_index in range(codon_count):
        codon = sequence[codon_index * 3 : codon_index * 3 + 3].upper()
        if "N" in codon:
            continue

        if codon_index < utr5_codons:
            region = "5utr"
        elif codon_index < utr5_codons + cds_codons:
            region = "cds"
        else:
            region = "3utr"

        values: List[object] = [
            transcript_name,
            start_nt0 + 1 + codon_index * 3,
            codon_index - utr5_codons,
            from_tts_start + codon_index,
            region,
            codon,
        ]

        for f0, f1, f2 in frame_arrays:
            values.extend([f0[codon_index], f1[codon_index], f2[codon_index]])

        yield values


def merge_json_stream(sample_records: List[SampleFile], output_prefix: str, output_format: str, args: argparse.Namespace) -> Dict[str, str]:
    """Fast streaming merge for compact JSONL density files."""
    output_files: Dict[str, str] = OrderedDict()
    output_json = output_prefix + "_merged.jsonl.gz"
    output_txt = output_prefix + "_merged.txt"

    if output_format in {"json", "both"}:
        _check_output(output_json)
    if output_format in {"txt", "both"}:
        _check_output(output_txt)

    sample_names = [record.name for record in sample_records]
    sample_files = [record.file for record in sample_records]
    start_time = time.time()
    record_count = 0
    txt_row_count = 0

    print(f"Merge {len(sample_records)} JSONL files by streaming transcript order.", flush=True)
    if args.thread > 1:
        print("Streaming merge is enabled; --thread is not used for JSON because it would add synchronization overhead.", flush=True)

    with ExitStack() as stack:
        handles = [stack.enter_context(_open_binary_text(path)) for path in sample_files]
        json_out: Optional[BinaryIO] = None
        txt_out: Optional[TextIO] = None
        txt_writer: Optional[csv.writer] = None

        if output_format in {"json", "both"}:
            json_out = stack.enter_context(gzip.open(output_json, "wb", compresslevel=JSON_COMPRESS_LEVEL))
            output_files["json"] = output_json

        if output_format in {"txt", "both"}:
            txt_out = stack.enter_context(open(output_txt, "w", encoding="utf-8", newline=""))
            txt_writer = csv.writer(txt_out, delimiter="\t", lineterminator="\n")
            txt_writer.writerow(_legacy_header(sample_names))
            output_files["txt"] = output_txt

        while True:
            records = [_read_next_transcript(handle) for handle in handles]

            if all(record is None for record in records):
                break
            if any(record is None for record in records):
                missing = [sample_names[idx] for idx, record in enumerate(records) if record is None]
                raise ValueError("Input JSON files have different transcript counts. Missing: " + ",".join(missing))

            typed_records = [record for record in records if record is not None]
            first_record = typed_records[0]
            first_id = _record_id(first_record)

            if ORDER_CHECK:
                for sample_name, record in zip(sample_names[1:], typed_records[1:]):
                    now_id = _record_id(record)
                    if now_id != first_id:
                        raise ValueError(
                            "Transcript order mismatch. "
                            f"First sample transcript={first_id}; sample={sample_name}; transcript={now_id}."
                        )

            merged_record = _base_record_without_samples(first_record)
            merged_samples: OrderedDict[str, JsonDict] = OrderedDict()

            for sample_name, record in zip(sample_names, typed_records):
                payloads = _sample_payloads_from_json(
                    record=record,
                    sample_name=sample_name,
                    keep_source_sample_name=KEEP_SOURCE_SAMPLE_NAME,
                )
                for out_sample_name, payload in payloads.items():
                    if out_sample_name in merged_samples:
                        raise ValueError(f"Duplicated sample name in merged JSON: {out_sample_name}")
                    merged_samples[out_sample_name] = payload

            merged_record["samples"] = merged_samples

            if json_out is not None:
                json_out.write(_json_dumps(merged_record))
                json_out.write(b"\n")

            if txt_writer is not None:
                for row in _legacy_rows_from_json_record(merged_record, list(merged_samples.keys())):
                    txt_writer.writerow(row)
                    txt_row_count += 1

            record_count += 1
            if PROGRESS_EVERY > 0 and record_count % PROGRESS_EVERY == 0:
                elapsed = max(time.time() - start_time, 1e-6)
                print(f"records={record_count:,}, speed={record_count / elapsed:,.0f} records/s", flush=True)

    elapsed = max(time.time() - start_time, 1e-6)
    print(f"records={record_count:,}, speed={record_count / elapsed:,.0f} records/s", flush=True)
    if txt_row_count:
        print(f"txt_rows={txt_row_count:,}", flush=True)
    return output_files


# -----------------------------------------------------------------------------
# TXT streaming merger
# -----------------------------------------------------------------------------


def _parse_density_triplet(row: List[str]) -> Tuple[str, str, str]:
    """Return the first density triplet from a legacy TXT row."""
    if len(row) < 9:
        raise ValueError("Legacy TXT density row has fewer than 9 columns.")
    return row[6], row[7], row[8]


def _sparse_density_from_arrays(f0: List[int], f1: List[int], f2: List[int]) -> JsonDict:
    """Create sparse density from frame arrays."""
    codon_index: List[int] = []
    frame: List[int] = []
    count: List[int] = []

    for idx, value in enumerate(f0):
        if value != 0:
            codon_index.append(idx)
            frame.append(0)
            count.append(int(value))
    for idx, value in enumerate(f1):
        if value != 0:
            codon_index.append(idx)
            frame.append(1)
            count.append(int(value))
    for idx, value in enumerate(f2):
        if value != 0:
            codon_index.append(idx)
            frame.append(2)
            count.append(int(value))

    return {
        "encoding": SPARSE_ENCODING,
        "index_base": 0,
        "codon_index": codon_index,
        "frame": frame,
        "count": count,
    }


def _dense_density_from_arrays(f0: List[int], f1: List[int], f2: List[int]) -> JsonDict:
    """Create dense density from frame arrays."""
    return {"encoding": DENSE_ENCODING, "index_base": 0, "f0": f0, "f1": f1, "f2": f2}


def _flush_txt_group_to_json(
    json_out: BinaryIO,
    transcript_name: str,
    group_rows: List[List[str]],
    group_values: Dict[str, Tuple[List[int], List[int], List[int]]],
    sample_names: List[str],
    density_encoding: str,
) -> int:
    """Write one transcript group converted from merged TXT rows to JSON."""
    if not group_rows:
        return 0

    codons = [row[5].upper() for row in group_rows]
    regions = [row[4] for row in group_rows]
    codon_count = len(group_rows)
    utr5_codons = sum(1 for region in regions if region == "5utr")
    cds_codons = sum(1 for region in regions if region == "cds")
    utr3_codons = sum(1 for region in regions if region == "3utr")
    start_nt0 = int(group_rows[0][1]) - 1
    sequence = "".join(codons)

    samples: OrderedDict[str, JsonDict] = OrderedDict()
    for sample_name in sample_names:
        f0, f1, f2 = group_values[sample_name]
        if density_encoding == "dense":
            density = _dense_density_from_arrays(f0, f1, f2)
        else:
            density = _sparse_density_from_arrays(f0, f1, f2)
        samples[sample_name] = {"profile": "unknown", "density": density}

    record: JsonDict = {
        "record_type": "transcript",
        "transcript_id": transcript_name,
        "gene_id": transcript_name,
        "name": transcript_name,
        "annotation": {
            "source": "legacy_txt",
            "coordinate_system": None,
            "gene_id": transcript_name,
            "transcript_id": transcript_name,
            "cds_tx_start": utr5_codons * 3,
            "cds_tx_end": (utr5_codons + cds_codons) * 3,
            "utr5_length": utr5_codons * 3,
            "cds_length": cds_codons * 3,
            "utr3_length": utr3_codons * 3,
            "transcript_length": codon_count * 3,
        },
        "genome_mapping": None,
        "trim": {
            "shift5_nt": 0,
            "shift3_nt": 0,
            "start_nt0": start_nt0,
            "end_nt0": start_nt0 + codon_count * 3,
            "trim_length_nt": codon_count * 3,
            "codon_count": codon_count,
            "utr5_nt": utr5_codons * 3,
            "cds_nt": cds_codons * 3,
            "utr3_nt": utr3_codons * 3,
            "utr5_codons": utr5_codons,
            "cds_codons": cds_codons,
            "utr3_codons": utr3_codons,
        },
        "sequence": sequence,
        "samples": samples,
    }
    json_out.write(_json_dumps(record))
    json_out.write(b"\n")
    return 1


def merge_txt_stream(sample_records: List[SampleFile], output_prefix: str, output_format: str, args: argparse.Namespace) -> Dict[str, str]:
    """Fast streaming merge for legacy TXT density files."""
    output_files: Dict[str, str] = OrderedDict()
    output_txt = output_prefix + "_merged.txt"
    output_json = output_prefix + "_merged.jsonl.gz"

    if output_format in {"txt", "both"}:
        _check_output(output_txt)
    if output_format in {"json", "both"}:
        _check_output(output_json)

    sample_names = [record.name for record in sample_records]
    sample_files = [record.file for record in sample_records]
    start_time = time.time()
    row_count = 0
    transcript_count = 0

    print(f"Merge {len(sample_records)} legacy TXT files by streaming row order.", flush=True)
    if args.thread > 1:
        print("Streaming merge is enabled; --thread is not used for TXT because row-order streaming avoids dataframe joins.", flush=True)

    with ExitStack() as stack:
        handles = [stack.enter_context(_open_text(path)) for path in sample_files]
        readers = [csv.reader(handle, delimiter="\t") for handle in handles]
        headers = [next(reader, None) for reader in readers]

        if any(header is None for header in headers):
            raise ValueError("At least one TXT input file is empty.")
        for header in headers:
            if header is None or len(header) < 9:
                raise ValueError("Legacy TXT header has fewer than 9 columns.")

        txt_out: Optional[TextIO] = None
        txt_writer: Optional[csv.writer] = None
        json_out: Optional[BinaryIO] = None

        if output_format in {"txt", "both"}:
            txt_out = stack.enter_context(open(output_txt, "w", encoding="utf-8", newline=""))
            txt_writer = csv.writer(txt_out, delimiter="\t", lineterminator="\n")
            txt_writer.writerow(_legacy_header(sample_names))
            output_files["txt"] = output_txt

        if output_format in {"json", "both"}:
            json_out = stack.enter_context(gzip.open(output_json, "wb", compresslevel=JSON_COMPRESS_LEVEL))
            output_files["json"] = output_json

        current_transcript: Optional[str] = None
        group_rows: List[List[str]] = []
        group_values: Dict[str, Tuple[List[int], List[int], List[int]]] = {
            sample_name: ([], [], []) for sample_name in sample_names
        }

        while True:
            rows = [next(reader, None) for reader in readers]

            if all(row is None for row in rows):
                break
            if any(row is None for row in rows):
                missing = [sample_names[idx] for idx, row in enumerate(rows) if row is None]
                raise ValueError("Input TXT files have different row counts. Missing: " + ",".join(missing))

            typed_rows = [row for row in rows if row is not None]
            first = typed_rows[0]
            base_key = first[0:2]
            base_coord = first[0:6]

            if ORDER_CHECK:
                for sample_name, row in zip(sample_names[1:], typed_rows[1:]):
                    if row[0:2] != base_key:
                        raise ValueError(
                            "TXT row-order mismatch. "
                            f"First={base_key}; sample={sample_name}; now={row[0:2]}."
                        )

            if "N" in first[5].upper():
                continue

            if txt_writer is not None:
                merged_row: List[str] = base_coord.copy()
                for row in typed_rows:
                    merged_row.extend(list(_parse_density_triplet(row)))
                txt_writer.writerow(merged_row)

            if json_out is not None:
                transcript_name = first[0]
                if current_transcript is None:
                    current_transcript = transcript_name
                elif transcript_name != current_transcript:
                    transcript_count += _flush_txt_group_to_json(
                        json_out=json_out,
                        transcript_name=current_transcript,
                        group_rows=group_rows,
                        group_values=group_values,
                        sample_names=sample_names,
                        density_encoding=args.density_encoding,
                    )
                    current_transcript = transcript_name
                    group_rows = []
                    group_values = {sample_name: ([], [], []) for sample_name in sample_names}

                group_rows.append(first)
                for sample_name, row in zip(sample_names, typed_rows):
                    f0_value, f1_value, f2_value = _parse_density_triplet(row)
                    f0, f1, f2 = group_values[sample_name]
                    f0.append(int(float(f0_value)))
                    f1.append(int(float(f1_value)))
                    f2.append(int(float(f2_value)))

            row_count += 1
            if PROGRESS_RPF_EVERY > 0 and row_count % PROGRESS_RPF_EVERY == 0:
                elapsed = max(time.time() - start_time, 1e-6)
                print(f"rows={row_count:,}, speed={row_count / elapsed:,.0f} rows/s", flush=True)

        if json_out is not None and current_transcript is not None:
            transcript_count += _flush_txt_group_to_json(
                json_out=json_out,
                transcript_name=current_transcript,
                group_rows=group_rows,
                group_values=group_values,
                sample_names=sample_names,
                density_encoding=args.density_encoding,
            )

    elapsed = max(time.time() - start_time, 1e-6)
    print(f"rows={row_count:,}, speed={row_count / elapsed:,.0f} rows/s", flush=True)
    if transcript_count:
        print(f"transcripts={transcript_count:,}", flush=True)
    return output_files


# -----------------------------------------------------------------------------
# Summary and dispatcher
# -----------------------------------------------------------------------------


def write_summary(
    output_prefix: str,
    input_format: str,
    output_format: str,
    sample_records: List[SampleFile],
    output_files: Dict[str, str],
    elapsed: float,
) -> str:
    """Write merge summary JSON."""
    output_summary = output_prefix + "_merged.summary.json"
    summary = OrderedDict(
        [
            ("tool", "rpf_Merge"),
            ("version", "0.2.8.2"),
            ("merge_strategy", "streaming_order_merge"),
            ("input_format", input_format),
            ("output_format", output_format),
            ("sample_count", len(sample_records)),
            ("samples", [record.name for record in sample_records]),
            ("input_files", OrderedDict((record.name, record.file) for record in sample_records)),
            ("output_files", output_files),
            ("elapsed_seconds", round(elapsed, 3)),
        ]
    )
    with open(output_summary, "w", encoding="utf-8") as out:
        json.dump(summary, out, ensure_ascii=False, indent=2)
        out.write("\n")
    print(f"Merge summary written: {output_summary}", flush=True)
    return output_summary


def merge_density_files(args: argparse.Namespace) -> None:
    """Merge density files according to input format."""
    start_time = time.time()
    sample_records = read_sample_list(args.list, forced_format=args.input_format)
    input_format = sample_records[0].file_format
    output_format = _resolve_output_format(input_format, args.output_format)

    print(f"Detected input density format: {input_format}", flush=True)
    print(f"Resolved output density format: {output_format}", flush=True)

    if input_format == "json":
        output_files = merge_json_stream(sample_records, args.output, output_format, args)
    elif input_format == "txt":
        output_files = merge_txt_stream(sample_records, args.output, output_format, args)
    else:
        raise ValueError(f"Unsupported input format: {input_format}")

    elapsed = max(time.time() - start_time, 1e-6)
    write_summary(args.output, input_format, output_format, sample_records, output_files, elapsed)


def main(argv: Optional[Sequence[str]] = None) -> None:
    """Command-line entry point."""
    now_time()
    print("\nMerge RPF density files from different samples.", flush=True)
    print("\nStep1: Checking the input arguments.", flush=True)
    args = rpf_merge_args_parser(argv)

    print("\nStep2: Merge density files.", flush=True)
    merge_density_files(args)

    print("\nAll done.", flush=True)
    now_time()


if __name__ == "__main__":
    main()
