#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-07-09
# Version: 0.2.8.3
# Function: This script is used to merge RPF density files.
# Input: Sample list table and per-sample density JSONL or legacy TXT files.
# Output: Merged JSONL, legacy TXT, and summary files.

"""Command-line entry point for rpf_Merge."""

from __future__ import annotations

import argparse
from argparse import Namespace
from collections.abc import Sequence

from utils.ribo import Merge

from utils.ribo.ArgsParser import (
    args_print,
    complete_print,
    file_check,
    now_time,
    step_print,
    title_print,
)


def _build_parser() -> argparse.ArgumentParser:
    """Build the command-line argument parser."""
    parser = argparse.ArgumentParser(
        description="Fast merge RPF density files generated by rpf_Density in JSONL or TXT format."
    )

    required_group = parser.add_argument_group("Required arguments")
    required_group.add_argument(
        "-l",
        "--list",
        dest="list",
        required=True,
        type=str,
        help="Sample list table. Required columns: Name and File. Optional columns: Type and Format.",
    )
    required_group.add_argument(
        "-o",
        "--output",
        dest="output",
        required=True,
        type=str,
        help="Output prefix.",
    )

    file_group = parser.add_argument_group("File arguments")
    file_group.add_argument(
        "-if",
        "--input-format",
        dest="input_format",
        choices=["auto", "json", "txt"],
        default="auto",
        help="Input density format. Default: %(default)s.",
    )
    file_group.add_argument(
        "-of",
        "--output-format",
        dest="output_format",
        choices=["auto", "json", "txt", "both"],
        default="auto",
        help="Output density format. Default: JSON input -> json; TXT input -> txt.",
    )
    file_group.add_argument(
        "-c",
        "--density-encoding",
        dest="density_encoding",
        choices=["sparse", "dense"],
        default="sparse",
        help="Density encoding used when converting TXT input to JSON. Default: %(default)s.",
    )

    runtime_group = parser.add_argument_group("Runtime arguments")
    runtime_group.add_argument(
        "--thread",
        dest="thread",
        type=int,
        default=1,
        help=(
            "Reserved for compatibility. The default streaming merge is usually faster "
            "than worker-based dictionary merge and does not need extra workers."
        ),
    )

    return parser


def _validate_args(args: Namespace) -> None:
    """Validate command-line arguments."""
    file_check(args.list)
    args.thread = max(1, int(args.thread))


def _parse_args(argv: Sequence[str] | None = None) -> Namespace:
    """Parse and validate command-line arguments."""
    parser = _build_parser()
    args = parser.parse_args(argv)
    _validate_args(args)
    args_print(args)
    return args


def _run_merge_pipeline(args: Namespace) -> None:
    """Run the RPF density merge pipeline."""
    merger = Merge.RPFMerge(args)
    merger.run()


def main(argv: Sequence[str] | None = None) -> None:
    """Command-line entry point for rpf_Merge."""
    now_time()
    title_print('Merge RPF density files from different samples.')

    step_print(1, "Checking the input arguments.")
    args = _parse_args(argv)

    step_print(2, "Merge density files.")
    _run_merge_pipeline(args)

    complete_print()
    now_time()


if __name__ == "__main__":
    main()
