#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-07-21
# Version: 0.2.8.18
# Function: Detect P-site offsets using SSCBM followed by RSBM.
# Input: Transcript annotation and BAM/SAM alignment file.
# Output: SSCBM and RSBM offset tables and heatmap figures.

"""Command-line entry point for SSCBM and RSBM P-site offset detection."""

from __future__ import annotations

import argparse
from argparse import Namespace
from collections.abc import Sequence

from utils.ribo.ArgsParser import args_print, file_check, now_time


def _build_parser() -> argparse.ArgumentParser:
    """Build the command-line argument parser."""
    parser = argparse.ArgumentParser(
        description="Detect P-site offsets using SSCBM followed by RSBM."
    )

    required_group = parser.add_argument_group("Required arguments")
    required_group.add_argument(
        "-t",
        dest="transcript",
        required=True,
        type=str,
        help="Input transcript annotation file generated by rpf_Reference.",
    )
    required_group.add_argument(
        "-b",
        dest="bam",
        required=True,
        type=str,
        help="Input BAM or SAM alignment file.",
    )
    required_group.add_argument(
        "-o",
        dest="output",
        required=True,
        type=str,
        help="Output file prefix.",
    )

    offset_group = parser.add_argument_group("Offset detection arguments")
    offset_group.add_argument(
        "-a",
        dest="align",
        choices=["both", "tis", "tts"],
        default="both",
        type=str,
        help="Read-end alignment used for SSCBM detection (default: %(default)s).",
    )
    offset_group.add_argument(
        "-l",
        dest="longest",
        action="store_true",
        default=False,
        help="Only retain the transcript with the longest CDS per gene.",
    )
    offset_group.add_argument(
        "-m",
        dest="min",
        default=27,
        type=int,
        help="Minimum read length retained (default: %(default)s nt).",
    )
    offset_group.add_argument(
        "-M",
        dest="max",
        default=33,
        type=int,
        help="Maximum read length retained (default: %(default)s nt).",
    )
    offset_group.add_argument(
        "-p",
        dest="exp_peak",
        default=30,
        type=int,
        help="Expected RPF peak length (default: %(default)s nt).",
    )
    offset_group.add_argument(
        "-s",
        dest="shift",
        default=2,
        type=int,
        help="P-site offset shift between adjacent read lengths (default: %(default)s nt).",
    )
    offset_group.add_argument(
        "--silence",
        dest="silence",
        action="store_true",
        default=False,
        help="Suppress offset warning messages (default: %(default)s).",
    )

    output_group = parser.add_argument_group("Output arguments")
    output_group.add_argument(
        "-d",
        dest="detail",
        action="store_true",
        default=False,
        help="Output detailed offset information (default: %(default)s).",
    )

    return parser


def _validate_args(args: Namespace) -> None:
    """Validate command-line arguments."""
    file_check(args.transcript, args.bam)
    if args.min <= 0:
        raise ValueError("-m must be > 0.")
    if args.max < args.min:
        raise ValueError("-M must be >= -m.")
    if args.exp_peak <= 0:
        raise ValueError("-p must be > 0.")
    if args.shift <= 0:
        raise ValueError("-s must be > 0.")


def _parse_args(argv: Sequence[str] | None = None) -> Namespace:
    """Parse, validate, and print command-line arguments."""
    parser = _build_parser()
    args = parser.parse_args(argv)
    _validate_args(args)
    args_print(args)
    return args


def _print_step(step: int, message: str) -> None:
    """Print a standardized pipeline step message."""
    print(f"\nStep{step}: {message}", flush=True)


def _run_offset_pipeline(args: Namespace) -> None:
    """Run SSCBM followed by RSBM offset detection."""
    from utils.ribo.Offset import Offset

    offset = Offset(args)

    _print_step(2, "Import transcript annotation.")
    offset.read_transcript()

    _print_step(3, "Import BAM/SAM alignments.")
    offset.get_mrna_reads()

    _print_step(4, "Detect and output SSCBM offsets.")
    offset.get_tis_offset()
    offset.adjust_tis_offset()
    offset.write_tis_offset()
    offset.draw_tis_heatmap()

    _print_step(5, "Detect and output RSBM offsets.")
    offset.get_frame_offset()
    offset.format_frame_offset()
    offset.adjust_frame_offset()
    offset.write_frame_offset()
    offset.draw_frame_heatmap()


def main(argv: Sequence[str] | None = None) -> None:
    """Command-line entry point for rpf_Offset."""
    now_time()
    print("\nDetect P-site offsets using SSCBM and RSBM.", flush=True)
    _print_step(1, "Checking the input arguments.")

    args = _parse_args(argv)
    _run_offset_pipeline(args)

    print("\nAll done.", flush=True)
    now_time()


if __name__ == "__main__":
    main()
