#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-07-08
# Version: 0.2.8-dev.012
# Function: Summarize RPF BAM/SAM mapping quality and output filtered BAM.
# Input: RiboParser transcript annotation and BAM/SAM alignment file.
# Output: Filtered sorted BAM, BAM index, length distribution, summary JSON, and optional saturation plots.

import argparse

from utils.ribo.ArgsParser import args_print, file_check, now_time
from utils.ribo.Quality import Quality


def rpf_bam_check_parser():
    """Parse command-line arguments for rpf_Check."""
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description="Summarize RPF BAM/SAM mapping quality and output filtered BAM.",
    )

    input_group = parser.add_argument_group("Required arguments")
    input_group.add_argument(
        "-t",
        dest="transcript",
        required=True,
        type=str,
        help="Input gene/transcript annotation file generated by rpf_Reference.",
    )
    input_group.add_argument(
        "-b",
        dest="bam",
        required=True,
        type=str,
        help="Input BAM/SAM alignment file.",
    )
    input_group.add_argument(
        "-o",
        dest="output",
        required=True,
        type=str,
        help="Output prefix.",
    )

    runtime_group = parser.add_argument_group("Runtime and performance options")
    runtime_group.add_argument(
        "--thread",
        dest="thread",
        required=False,
        type=int,
        default=4,
        help="""Number of parallel worker processes and BAM I/O threads (default: %(default)s).
When this value is greater than 1, rpf_Check automatically prepares an indexed BAM and uses multi-process transcript-reference fetching.""",
    )
    filter_group = parser.add_argument_group("Read filtering options")
    filter_group.add_argument(
        "-g",
        dest="tag",
        choices=[0, 1],
        type=int,
        required=False,
        default=0,
        help="""Filter reads by mapping uniqueness (default: %(default)s).
[0]: all mapped reads are used;
[1]: unique mapped reads are used.""",
    )
    filter_group.add_argument(
        "-a",
        dest="align",
        choices=["star", "hisat2", "bowtie2"],
        type=str,
        required=False,
        default="star",
        help="""Aligner used to generate the BAM/SAM file.
This option controls unique-read tag interpretation. (default: %(default)s).""",
    )
    filter_group.add_argument(
        "-r",
        dest="reverse",
        action="store_true",
        required=False,
        default=False,
        help="""Backward-compatible option retained for old commands.
The optimized rpf_Check workflow always retains and reports plus/minus strands separately.""",
    )
    filter_group.add_argument(
        "-l",
        dest="longest",
        action="store_true",
        required=False,
        default=False,
        help="Only keep the representative/longest transcript per gene. (default: %(default)s).",
    )
    filter_group.add_argument(
        "-s",
        dest="saturation",
        action="store_true",
        required=False,
        default=False,
        help="""Calculate RPF saturation. (default: %(default)s).
This step takes extra memory, especially when multi-mapping reads are retained.""",
    )
    filter_group.add_argument(
        "--secondary",
        dest="secondary",
        action="store_true",
        required=False,
        default=False,
        help="Keep secondary alignments. (default: %(default)s).",
    )
    filter_group.add_argument(
        "--supplementary",
        dest="supplementary",
        action="store_true",
        required=False,
        default=False,
        help="Keep supplementary alignments. (default: %(default)s).",
    )
    filter_group.add_argument(
        "--duplicate",
        dest="duplicate",
        action="store_true",
        required=False,
        default=False,
        help="Keep duplicate alignments. (default: %(default)s).",
    )

    args = parser.parse_args()
    file_check(args.transcript, args.bam)
    args_print(args)

    return args


def main():
    """Run the optimized rpf_Check workflow."""
    now_time()
    print("\nCheck the RPFs mapping condition.", flush=True)

    print("\nStep1: Checking the input arguments.", flush=True)
    args = rpf_bam_check_parser()

    rpf_quality = Quality(args)

    print("\nStep2: Import the transcripts annotation.", flush=True)
    rpf_quality.read_transcript()

    print("\nStep3: Scan mRNA-aligned reads and output filtered BAM.", flush=True)
    rpf_quality.scan_mrna_reads()

    print("\nStep4: Detect the type of sequence profile.", flush=True)
    if not rpf_quality.profile:
        rpf_quality.detect_seq_type()
    else:
        print(
            "{bam} is specified as {ribo}-seq.".format(
                bam=rpf_quality.sample_file,
                ribo=rpf_quality.profile,
            ),
            flush=True,
        )

    print("\nStep5: Summarize the length distribution of reads aligned to mRNA.", flush=True)
    rpf_quality.write_length_distr()
    rpf_quality.write_summary()

    if args.saturation:
        print("\nStep6: Check the RPFs saturation.", flush=True)
        rpf_quality.rpf_saturation()
        rpf_quality.draw_gene_saturation()
        rpf_quality.draw_rpf_saturation()
        rpf_quality.write_summary()
    else:
        print("\nStep6: Do not check the RPFs saturation.", flush=True)

    print("\nAll done.", flush=True)
    now_time()


if __name__ == "__main__":
    main()
