#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-08-10
# Version: dev002
# Function: Calculate validated CDS, protein, and SeRP peak-group sequence properties.
# Input: Coding-sequence FASTA, optional CAI reference, and optional serp_summary peak classification.
# Output: Sequence QC, codon/protein properties, local peak contexts, group statistics, and figures.

"""Command-line entry point for SeRP sequence-property analysis."""

from __future__ import annotations

import argparse
from argparse import Namespace
from collections.abc import Sequence
from pathlib import Path

from Bio.Data import CodonTable

from utils.ribo.ArgsParser import (
    args_print,
    complete_print,
    file_check,
    now_time,
    result_print,
    step_print,
    title_print,
)
from utils.serp.Properties import SeRPProperties


def _build_parser() -> argparse.ArgumentParser:
    """Build the command-line argument parser."""
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description=(
            "Calculate validated CDS/protein properties and optionally compare "
            "shared versus condition-specific SeRP peak sequence features."
        ),
    )

    required_group = parser.add_argument_group("Required arguments")
    required_group.add_argument(
        "-f",
        "--fasta",
        dest="fasta",
        required=True,
        type=str,
        help="Input coding-sequence FASTA file keyed by transcript ID.",
    )
    required_group.add_argument(
        "-o",
        "--output",
        dest="output",
        required=True,
        type=str,
        help="Output file prefix.",
    )

    peak_group = parser.add_argument_group("SeRP peak-group arguments")
    peak_group.add_argument(
        "-p",
        "--peak-classification",
        dest="peak_classification",
        default=None,
        type=str,
        help=(
            "Optional *.peak_classification.txt generated by serp_summary. When "
            "provided, shared and condition-specific sequence properties are analyzed."
        ),
    )
    peak_group.add_argument(
        "--local-up",
        dest="local_up",
        default=30,
        type=int,
        help="Amino acids extracted upstream of each peak max_site.",
    )
    peak_group.add_argument(
        "--local-down",
        dest="local_down",
        default=10,
        type=int,
        help="Amino acids extracted downstream of each peak max_site.",
    )
    peak_group.add_argument(
        "--require-complete-local",
        dest="require_complete_local",
        action=argparse.BooleanOptionalAction,
        default=True,
        help=(
            "Require every peak-local context to contain the complete requested "
            "upstream/downstream window."
        ),
    )
    peak_group.add_argument(
        "--specific-set",
        dest="specific_set",
        choices=["all", "significant"],
        default="all",
        help=(
            "Condition-specific peak set used for statistics and figures. Tables "
            "always retain both all-specific and significant-specific groups."
        ),
    )
    peak_group.add_argument(
        "--min-group-size",
        dest="min_group_size",
        default=3,
        type=int,
        help="Minimum non-overlapping transcript number per group required for a statistical test.",
    )

    sequence_group = parser.add_argument_group("Sequence arguments")
    sequence_group.add_argument(
        "--genetic-code",
        dest="genetic_code",
        default=1,
        type=int,
        help="NCBI genetic code identifier used for translation and codon annotation.",
    )
    sequence_group.add_argument(
        "--cai-reference",
        dest="cai_reference",
        default=None,
        type=str,
        help=(
            "Reference CDS FASTA used to build the Sharp-Li codon adaptiveness "
            "index. CAI remains NA when this argument is omitted."
        ),
    )
    sequence_group.add_argument(
        "--charge-ph",
        dest="charge_ph",
        default=7.0,
        type=float,
        help="pH used to calculate full-protein net charge and charge density.",
    )

    figure_group = parser.add_argument_group("Figure arguments")
    figure_group.add_argument(
        "--plot",
        dest="plot",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Generate peak-group sequence-property figures when -p is provided.",
    )
    figure_group.add_argument(
        "--output-format",
        dest="output_format",
        choices=["pdf", "png", "both"],
        default="pdf",
        help="Figure output format.",
    )
    figure_group.add_argument(
        "--font-size",
        dest="font_size",
        default=9.0,
        type=float,
        help="Base figure font size.",
    )
    figure_group.add_argument(
        "--dpi",
        dest="dpi",
        default=300,
        type=int,
        help="PNG output resolution.",
    )
    return parser


def _validate_args(args: Namespace) -> None:
    """Validate input files, numeric arguments, and output location."""
    file_check(args.fasta)
    if args.cai_reference is not None:
        file_check(args.cai_reference)
    if args.peak_classification is not None:
        file_check(args.peak_classification)
    if args.genetic_code not in CodonTable.unambiguous_dna_by_id:
        raise ValueError(
            "Unknown NCBI genetic code: {0}".format(args.genetic_code)
        )
    if args.charge_ph <= 0:
        raise ValueError("--charge-ph must be > 0.")
    if args.local_up < 0 or args.local_down < 0:
        raise ValueError("--local-up and --local-down must be >= 0.")
    if args.min_group_size < 2:
        raise ValueError("--min-group-size must be >= 2.")
    if args.font_size <= 0:
        raise ValueError("--font-size must be > 0.")
    if args.dpi < 1:
        raise ValueError("--dpi must be >= 1.")

    output_parent = Path(args.output).expanduser().resolve().parent
    if not output_parent.exists():
        raise FileNotFoundError(
            "Output directory does not exist: {0}".format(output_parent)
        )


def _parse_args(argv: Sequence[str] | None = None) -> Namespace:
    """Parse, validate, and print command-line arguments."""
    parser = _build_parser()
    args = parser.parse_args(argv)
    try:
        _validate_args(args)
    except (ValueError, FileNotFoundError) as error:
        parser.error(str(error))
    args_print(args)
    return args


def _run_sequence_pipeline(args: Namespace) -> SeRPProperties:
    """Run validated full-CDS and full-protein property analysis."""
    workflow = SeRPProperties(args)

    step_print(2, "Read and validate coding sequences.")
    workflow.read_sequences()

    step_print(3, "Build optional CAI reference and calculate codon usage.")
    workflow.build_cai_index()

    step_print(4, "Calculate nucleotide and protein sequence properties.")
    workflow.calculate_properties()

    step_print(5, "Write sequence QC and full-sequence property tables.")
    workflow.write_tables()
    return workflow


def _run_peak_group_pipeline(args: Namespace, sequence_workflow: SeRPProperties):
    """Run shared/specific peak-local extraction and group sequence-property analysis."""
    from utils.serp.PeakProperties import SeRPPeakProperties
    from utils.serp.PropertiesGroup import SeRPPropertyGroups

    peak_workflow = SeRPPeakProperties(args, sequence_workflow)

    step_print(6, "Read serp_summary peak classification and build analysis groups.")
    peak_workflow.read_peak_classification()

    step_print(7, "Extract max-site-centered local sequences and write local properties.")
    peak_workflow.extract_local_sequences()
    peak_workflow.write_tables()

    group_workflow = SeRPPropertyGroups(args, sequence_workflow, peak_workflow)
    step_print(8, "Calculate group codon, amino-acid, position, and statistical summaries.")
    group_workflow.calculate_all()
    group_workflow.write_tables()

    if args.plot:
        step_print(9, "Draw shared and condition-specific sequence-property figures.")
        group_workflow.draw_figures(args)
    return peak_workflow, group_workflow


def main(argv: Sequence[str] | None = None) -> None:
    """Command-line entry point for ``serp_properties``."""
    now_time()
    title_print("Calculate selective ribosome profiling sequence properties.")

    step_print(1, "Checking the input arguments.")
    args = _parse_args(argv)
    sequence_workflow = _run_sequence_pipeline(args)

    results = dict(sequence_workflow.summary_counts())
    if args.peak_classification is not None:
        peak_workflow, group_workflow = _run_peak_group_pipeline(args, sequence_workflow)
        results.update(peak_workflow.result_counts())
        results.update(group_workflow.result_counts())
    result_print(results)

    complete_print()
    now_time()


if __name__ == "__main__":
    main()