#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Author: Rensc
date: 2026-05-23

@Project : smORF
@Script  : smorf_integrate.py

Command-line entry for integrating smORF Ribo-seq evidence tables.
"""

import argparse

from utils.smorf.smorf_riboseq_integrate import run_integration


def get_parser() -> argparse.ArgumentParser:
    """Create command-line parser."""
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description="Integrate long-format smORF Ribo-seq evidence into matrices and ORF-level summary tables.",
    )

    parser.add_argument(
        "-i",
        "--input",
        required=True,
        help="Long-format smORF Ribo-seq evidence table generated by smorf_evidence.py.",
    )

    parser.add_argument(
        "--output-matrix",
        default=None,
        help="Output ORF-by-sample matrix table for frame density and selected sample metrics.",
    )

    parser.add_argument(
        "--output-integrated",
        default=None,
        help="Output integrated ORF-level evidence table.",
    )

    parser.add_argument(
        "--capture-labels",
        default="LowConfidence,MediumConfidence,HighConfidence",
        help="Translation evidence labels used to define captured samples.",
    )

    parser.add_argument(
        "--pass-labels",
        default="MediumConfidence,HighConfidence",
        help="Translation evidence labels used to define reliable/pass samples.",
    )

    parser.add_argument(
        "--excellent-min-samples",
        type=int,
        default=2,
        help="Minimum number of pass samples required to mark an ORF as Excellent.",
    )

    return parser


def main() -> None:
    """Run command-line workflow."""
    parser = get_parser()
    args = parser.parse_args()

    if not args.output_matrix and not args.output_integrated:
        parser.error("At least one of --output-matrix or --output-integrated must be provided.")

    run_integration(args)


if __name__ == "__main__":
    main()
