#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-07-25
# Version: 0.2.8.24-dev.005
# Function: Build gene-level smORF families with indexed parallel clustering.
# Input: ORF message table, source genePred annotation, and optional Kozak PWM.
# Output: Family representatives, member map, removed ORFs, and cluster summary.

"""Command-line entry point for gene-level smORF family clustering."""

from __future__ import annotations

import argparse
from argparse import Namespace
from collections.abc import Sequence

from utils.ribo.ArgsParser import (
    args_print,
    file_check,
    message_print,
    now_time,
    result_print,
    step_print,
    title_print,
    warning_print,
)
from utils.smorf.smorf_cluster_core import SmORFCluster
from utils.smorf.smorf_filter import ORFTable
from utils.smorf.smorf_kozak import BUILTIN_MODELS, KozakModel

DEFAULT_CATEGORIES = (
    "uORF,dORF,lncORF,iORF,same_frame_iORF,emORF,"
    "overlap_uORF,overlap_dORF,other_ORF,"
    "annotated_ORF,annotated_mORF"
)
AUTO_KOZAK_MINIMUM = 100
AUTO_KOZAK_FALLBACK = "plant"


def _build_parser() -> argparse.ArgumentParser:
    """Build the command-line argument parser."""
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=(
            "Filter candidate smORFs, remove transcript-level duplicates, "
            "and cluster strict alternative-start families."
        ),
    )

    required_group = parser.add_argument_group("Required arguments")
    required_group.add_argument(
        "-i",
        "--input",
        dest="input",
        required=True,
        type=str,
        help="Input ORF message table generated by smorf_scanner.",
    )
    required_group.add_argument(
        "-a",
        "--annotation",
        dest="annotation",
        required=True,
        type=str,
        help="Source genePred or genePredExt annotation used by smorf_scanner.",
    )

    output_group = parser.add_argument_group("Output arguments")
    output_group.add_argument(
        "-o",
        "--out-prefix",
        dest="out_prefix",
        default="ORF.cluster",
        type=str,
        help="Output file prefix (default: %(default)s).",
    )

    filter_group = parser.add_argument_group("Basic filtering arguments")
    filter_group.add_argument(
        "-s",
        "--keep-start-codons",
        dest="keep_start_codons",
        default="all",
        type=str,
        help=(
            "Comma-separated retained start codons; 'all' retains every "
            "start codon emitted by smorf_scanner (default: %(default)s)."
        ),
    )
    filter_group.add_argument(
        "-m",
        "--min-aa",
        dest="min_aa",
        default=8,
        type=int,
        help="Minimum peptide length (default: %(default)s aa).",
    )
    filter_group.add_argument(
        "-M",
        "--max-aa",
        dest="max_aa",
        default=10000,
        type=int,
        help="Maximum peptide length (default: %(default)s aa).",
    )
    filter_group.add_argument(
        "-c",
        "--keep-categories",
        dest="keep_categories",
        default=DEFAULT_CATEGORIES,
        type=str,
        help="Comma-separated retained category allowlist.",
    )
    filter_group.add_argument(
        "-r",
        "--remove-categories",
        dest="remove_categories",
        default="antisense_ORF",
        type=str,
        help=(
            "Comma-separated category denylist. same_frame_iORF is retained "
            "for alternative-start clustering (default: %(default)s)."
        ),
    )
    filter_group.add_argument(
        "-A",
        "--keep-antisense",
        dest="keep_antisense",
        action="store_true",
        default=False,
        help="Retain antisense ORFs (default: %(default)s).",
    )
    filter_group.add_argument(
        "--max-ambiguous-codons",
        dest="max_ambiguous_codons",
        default=0,
        type=int,
        help=(
            "Maximum ambiguous codon count when available "
            "(default: %(default)s)."
        ),
    )

    family_group = parser.add_argument_group("Family clustering arguments")
    family_group.add_argument(
        "--start-priority",
        dest="start_priority",
        default="ATG",
        type=str,
        help=(
            "Comma-separated start-codon priority. Unlisted codons share the "
            "lowest priority and are then ranked by ORF length "
            "(default: %(default)s)."
        ),
    )

    kozak_group = parser.add_argument_group("Optional Kozak arguments")
    kozak_group.add_argument(
        "-k",
        "--kozak-model",
        dest="kozak_model",
        choices=["none", "auto", *sorted(BUILTIN_MODELS)],
        default="none",
        type=str,
        help=(
            "Kozak model used for annotation, optional filtering, and family "
            "tie-breaking (default: %(default)s)."
        ),
    )
    kozak_group.add_argument(
        "--kozak-pwm",
        dest="kozak_pwm",
        default=None,
        type=str,
        help="Custom Kozak PWM file; overrides --kozak-model.",
    )
    kozak_group.add_argument(
        "-w",
        "--min-kozak-score",
        dest="min_kozak_score",
        default=0.0,
        type=float,
        help=(
            "Minimum normalized Kozak score. Zero annotates without filtering "
            "(default: %(default)s)."
        ),
    )
    kozak_group.add_argument(
        "--export-kozak-pwm",
        dest="export_kozak_pwm",
        default=None,
        type=str,
        help="Optional output path for the selected PWM.",
    )

    runtime_group = parser.add_argument_group("Runtime arguments")
    runtime_group.add_argument(
        "-t",
        "--thread",
        dest="threads",
        default=0,
        type=int,
        help=(
            "Number of worker processes. Zero uses the SLURM allocation or "
            "available CPUs for large files and one worker for small files "
            "(default: %(default)s)."
        ),
    )

    return parser


def _parse_set(value: str) -> set[str]:
    """Parse comma-separated values."""
    return {item.strip() for item in str(value).split(",") if item.strip()}


def _join_set(values: set[str]) -> str:
    """Return a sorted comma-separated set."""
    return ",".join(sorted(values))


def _normalize_rules(args: Namespace) -> None:
    """Normalize category and start-codon rules in place."""
    retained = _parse_set(args.keep_categories)
    removed = _parse_set(args.remove_categories)
    if args.keep_antisense:
        retained.add("antisense_ORF")
        removed.discard("antisense_ORF")
    conflict = retained.intersection(removed)
    if conflict:
        raise ValueError(
            "Category cannot be both retained and removed: "
            + ", ".join(sorted(conflict))
        )
    args.keep_categories = _join_set(retained)
    args.remove_categories = _join_set(removed)

    if args.keep_start_codons.strip().lower() == "all":
        args.keep_start_codons = ""
    else:
        _validate_codons(
            args.keep_start_codons,
            argument="--keep-start-codons",
        )
    _validate_codons(args.start_priority, argument="--start-priority")


def _validate_codons(value: str, argument: str) -> None:
    """Validate a comma-separated codon list."""
    codons = [
        codon.strip().upper().replace("U", "T")
        for codon in value.split(",")
        if codon.strip()
    ]
    if not codons:
        raise ValueError(f"{argument} cannot be empty.")
    invalid = sorted(
        codon
        for codon in codons
        if len(codon) != 3 or set(codon).difference("ACGT")
    )
    if invalid:
        raise ValueError(
            f"Invalid codon(s) for {argument}: " + ", ".join(invalid)
        )


def _validate_args(args: Namespace) -> None:
    """Validate command-line arguments."""
    file_check(args.input, args.annotation)
    if args.kozak_pwm:
        file_check(args.kozak_pwm)
    if not args.out_prefix:
        raise ValueError("--out-prefix must not be empty.")
    if args.min_aa < 1:
        raise ValueError("--min-aa must be >= 1.")
    if args.max_aa < args.min_aa:
        raise ValueError("--max-aa must be >= --min-aa.")
    if args.max_ambiguous_codons < 0:
        raise ValueError("--max-ambiguous-codons must be >= 0.")
    if args.threads < 0:
        raise ValueError("--thread must be >= 0.")
    if not 0 <= args.min_kozak_score <= 1:
        raise ValueError("--min-kozak-score must be in [0, 1].")
    if (
        args.kozak_model == "none"
        and args.kozak_pwm is None
        and args.min_kozak_score > 0
    ):
        raise ValueError(
            "--min-kozak-score requires an enabled Kozak model."
        )
    _normalize_rules(args)


def _parse_args(argv: Sequence[str] | None = None) -> Namespace:
    """Parse, validate, and print command-line arguments."""
    parser = _build_parser()
    args = parser.parse_args(argv)
    try:
        _validate_args(args)
    except ValueError as error:
        parser.error(str(error))
    args_print(args)
    return args


def _load_kozak_model(args: Namespace) -> KozakModel | None:
    """Load or train the requested Kozak model."""
    if args.kozak_pwm:
        return KozakModel.from_pwm_file(args.kozak_pwm)
    if args.kozak_model == "none":
        return None
    if args.kozak_model in BUILTIN_MODELS:
        return KozakModel.from_builtin(args.kozak_model)

    header = ORFTable.read_header(args.input)
    ORFTable.validate_header(header, require_kozak=True)
    try:
        model = KozakModel.from_annotated_records(
            ORFTable.iter_table(args.input, header),
            minimum_records=AUTO_KOZAK_MINIMUM,
        )
        message_print(
            "Auto Kozak model: annotated contexts "
            f"(n={model.training_count:,})."
        )
        return model
    except ValueError as error:
        warning_print(
            "{error}. Use built-in {fallback} Kozak model.".format(
                error=error,
                fallback=AUTO_KOZAK_FALLBACK,
            )
        )
        return KozakModel.from_builtin(AUTO_KOZAK_FALLBACK)


def _run_cluster_pipeline(args: Namespace) -> None:
    """Run filtering, exact deduplication, and family clustering."""
    step_print(2, "Load annotation and optional Kozak model.")
    kozak_model = _load_kozak_model(args)
    if kozak_model is not None and args.export_kozak_pwm:
        kozak_model.export(args.export_kozak_pwm)

    step_print(3, "Filter ORFs and build gene-level families.")
    clusterer = SmORFCluster(
        annotation=args.annotation,
        keep_start_codons=args.keep_start_codons,
        min_aa=args.min_aa,
        max_aa=args.max_aa,
        keep_categories=args.keep_categories,
        remove_categories=args.remove_categories,
        require_sense=not args.keep_antisense,
        max_ambiguous_codons=args.max_ambiguous_codons,
        kozak_model=kozak_model,
        min_kozak_score=args.min_kozak_score,
        start_priority=args.start_priority,
        threads=args.threads,
    )
    summary = clusterer.cluster_file(
        input_path=args.input,
        output_prefix=args.out_prefix,
    )

    step_print(4, "Report smORF family results.")
    result_print(
        [
            ("Input ORFs", f"{summary.input_orfs:,}"),
            ("Basic-filter passed", f"{summary.basic_passed:,}"),
            ("Basic-filter removed", f"{summary.basic_removed:,}"),
            ("lncORF-mORF removed", f"{summary.lnc_morf_removed:,}"),
            (
                "Exact duplicates collapsed",
                f"{summary.exact_duplicates_collapsed:,}",
            ),
            (
                "Alternative starts collapsed",
                f"{summary.alt_starts_collapsed:,}",
            ),
            ("Output families", f"{summary.family_count:,}"),
            ("Genes processed", f"{summary.genes_processed:,}"),
            ("Effective workers", f"{summary.effective_workers:,}"),
            ("Family table", f"{args.out_prefix}.family.message.txt"),
            ("Member map", f"{args.out_prefix}.family.members.txt"),
            ("Removed table", f"{args.out_prefix}.removed.message.txt"),
            ("Summary", f"{args.out_prefix}.cluster_summary.txt"),
        ]
    )


def main(argv: Sequence[str] | None = None) -> None:
    """Run the smorf_cluster command."""
    now_time()
    title_print("Build gene-level small ORF families.")
    step_print(1, "Checking the input arguments.")
    args = _parse_args(argv)
    _run_cluster_pipeline(args)
    title_print("All done.")
    now_time()


def deprecated_main() -> None:
    """Run the compatibility alias for the former smorf_filter command."""
    warning_print("smorf_filter is deprecated; use smorf_cluster.")
    main()


if __name__ == "__main__":
    main()
