#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-07-21
# Version: 0.2.8.18
# Function: Evaluate smORF translation evidence using Ribo-seq P-site density.
# Input: Filtered smORF table and stranded or unstranded P-site density files.
# Output: Long-format smORF Ribo-seq evidence table.

"""Command-line entry point for smORF Ribo-seq evidence evaluation."""

from __future__ import annotations

import argparse
from argparse import Namespace
from collections.abc import Sequence

from utils.ribo.ArgsParser import args_print, file_check, now_time
from utils.smorf.smorf_riboseq_io import eprint, write_output
from utils.smorf.smorf_riboseq_pipeline import run_riboseq_evidence


_PROGRESS_EVERY = 10000


def _build_parser() -> argparse.ArgumentParser:
    """Build the command-line argument parser."""
    parser = argparse.ArgumentParser(
        description="Evaluate smORF translation evidence using Ribo-seq P-site density."
    )

    required_group = parser.add_argument_group("Required arguments")
    required_group.add_argument(
        "-i",
        "--orf-table",
        dest="orf_table",
        required=True,
        type=str,
        help="Filtered smORF table generated by smorf_filter.",
    )
    required_group.add_argument(
        "-o",
        "--output",
        dest="output",
        required=True,
        type=str,
        help="Output evidence table in TSV format.",
    )

    density_group = parser.add_argument_group("Density input arguments")
    density_group.add_argument(
        "-a",
        "--genepred",
        dest="genepred",
        default=None,
        type=str,
        help="Optional genePred file used for ORF exon blocks.",
    )
    density_group.add_argument(
        "-z",
        "--chrom-sizes",
        dest="chrom_sizes",
        default=None,
        type=str,
        help="Optional chromosome-size table.",
    )
    density_group.add_argument(
        "-l",
        "--density-list",
        dest="density_list",
        default=None,
        type=str,
        help="Density list with sample, strand, path, and optional format columns.",
    )
    density_group.add_argument(
        "-p",
        "--density-plus",
        dest="density_plus",
        default=None,
        type=str,
        help="Plus-strand P-site density file.",
    )
    density_group.add_argument(
        "-n",
        "--density-minus",
        dest="density_minus",
        default=None,
        type=str,
        help="Minus-strand P-site density file.",
    )
    density_group.add_argument(
        "-d",
        "--density",
        dest="density",
        default=None,
        type=str,
        help="Unstranded P-site density file.",
    )
    density_group.add_argument(
        "-s",
        "--sample",
        dest="sample",
        default="sample1",
        type=str,
        help="Sample name used for direct density input.",
    )
    density_group.add_argument(
        "-f",
        "--density-format",
        dest="density_format",
        choices=["auto", "wig", "bedgraph"],
        default="auto",
        type=str,
        help="Density file format.",
    )
    density_group.add_argument(
        "-c",
        "--coord-mode",
        dest="coord_mode",
        choices=["0based-half-open", "1based-closed"],
        default="0based-half-open",
        type=str,
        help="Coordinate mode for ORF and genePred-like records.",
    )

    evidence_group = parser.add_argument_group("Evidence scoring arguments")
    evidence_group.add_argument(
        "-r",
        "--post-stop-codons",
        dest="post_stop_codons",
        default=10,
        type=int,
        help="Post-stop codons used to calculate release signal.",
    )
    evidence_group.add_argument(
        "-P",
        "--pseudocount",
        dest="pseudocount",
        default=0.1,
        type=float,
        help="Pseudocount used for ratio calculation.",
    )
    evidence_group.add_argument(
        "-R",
        "--min-rpf-sum",
        dest="min_rpf_sum",
        default=3.0,
        type=float,
        help="Minimum ORF-level RPF sum.",
    )
    evidence_group.add_argument(
        "-C",
        "--min-covered-codon",
        dest="min_covered_codon",
        default=2,
        type=int,
        help="Minimum covered-codon count.",
    )
    evidence_group.add_argument(
        "-v",
        "--min-coverage-ratio",
        dest="min_coverage_ratio",
        default=0.10,
        type=float,
        help="Minimum nucleotide-level coverage ratio.",
    )
    evidence_group.add_argument(
        "--strong-periodicity",
        dest="strong_periodicity",
        default=0.70,
        type=float,
        help="Frame-0 ratio threshold for strong periodicity.",
    )
    evidence_group.add_argument(
        "--moderate-periodicity",
        dest="moderate_periodicity",
        default=0.55,
        type=float,
        help="Frame-0 ratio threshold for moderate periodicity.",
    )
    evidence_group.add_argument(
        "--strong-start-pause",
        dest="strong_start_pause",
        default=1.50,
        type=float,
        help="Start-pausing ratio threshold for strong signal.",
    )
    evidence_group.add_argument(
        "--moderate-start-pause",
        dest="moderate_start_pause",
        default=1.20,
        type=float,
        help="Start-pausing ratio threshold for moderate signal.",
    )
    evidence_group.add_argument(
        "--strong-stop-pause",
        dest="strong_stop_pause",
        default=1.50,
        type=float,
        help="Pre-stop pausing threshold for strong signal.",
    )
    evidence_group.add_argument(
        "--moderate-stop-pause",
        dest="moderate_stop_pause",
        default=1.20,
        type=float,
        help="Pre-stop pausing threshold for moderate signal.",
    )
    evidence_group.add_argument(
        "--strong-release",
        dest="strong_release",
        default=3.0,
        type=float,
        help="Release-ratio threshold for strong signal.",
    )
    evidence_group.add_argument(
        "--moderate-release",
        dest="moderate_release",
        default=1.5,
        type=float,
        help="Release-ratio threshold for moderate signal.",
    )

    shape_group = parser.add_argument_group("Coverage shape arguments")
    shape_group.add_argument(
        "--uniform-coverage-ratio",
        dest="uniform_coverage_ratio",
        default=0.40,
        type=float,
        help="Coverage-ratio threshold for Uniform shape.",
    )
    shape_group.add_argument(
        "--uniform-gini",
        dest="uniform_gini",
        default=0.50,
        type=float,
        help="Gini threshold for Uniform shape.",
    )
    shape_group.add_argument(
        "--uniform-max-to-mean",
        dest="uniform_max_to_mean",
        default=5.0,
        type=float,
        help="Max-to-mean threshold for Uniform shape.",
    )
    shape_group.add_argument(
        "--skewed-max-to-mean",
        dest="skewed_max_to_mean",
        default=10.0,
        type=float,
        help="Max-to-mean threshold for Skewed shape.",
    )
    shape_group.add_argument(
        "--skewed-top-fraction",
        dest="skewed_top_fraction",
        default=0.70,
        type=float,
        help="Top-density fraction threshold for Skewed shape.",
    )
    shape_group.add_argument(
        "--disperse-coverage-ratio",
        dest="disperse_coverage_ratio",
        default=0.20,
        type=float,
        help="Coverage-ratio threshold for Disperse shape.",
    )

    output_group = parser.add_argument_group("Output arguments")
    output_group.add_argument(
        "-N",
        "--keep-no-evidence",
        dest="keep_no_evidence",
        action="store_true",
        default=False,
        help="Retain ORFs without detected RPF evidence.",
    )

    return parser


def _validate_args(args: Namespace) -> None:
    """Validate command-line arguments."""
    direct_stranded = args.density_plus is not None and args.density_minus is not None
    if not any((args.density_list, args.density, direct_stranded)):
        raise ValueError(
            "Provide --density-list, --density, or both "
            "--density-plus and --density-minus."
        )
    if (args.density_plus is None) != (args.density_minus is None):
        raise ValueError(
            "--density-plus and --density-minus must be provided together."
        )

    files = [args.orf_table]
    for file_name in (
        args.genepred,
        args.chrom_sizes,
        args.density_list,
        args.density_plus,
        args.density_minus,
        args.density,
    ):
        if file_name:
            files.append(file_name)
    file_check(*files)

    if args.post_stop_codons < 0:
        raise ValueError("--post-stop-codons must be >= 0.")
    if args.pseudocount < 0:
        raise ValueError("--pseudocount must be >= 0.")
    if args.min_rpf_sum < 0:
        raise ValueError("--min-rpf-sum must be >= 0.")
    if args.min_covered_codon < 0:
        raise ValueError("--min-covered-codon must be >= 0.")

    ratio_names = (
        "min_coverage_ratio",
        "strong_periodicity",
        "moderate_periodicity",
        "uniform_coverage_ratio",
        "uniform_gini",
        "skewed_top_fraction",
        "disperse_coverage_ratio",
    )
    for name in ratio_names:
        value = getattr(args, name)
        if not 0 <= value <= 1:
            raise ValueError(f"--{name.replace('_', '-')} must be in [0, 1].")


def _parse_args(argv: Sequence[str] | None = None) -> Namespace:
    """Parse, validate, and print command-line arguments."""
    parser = _build_parser()
    args = parser.parse_args(argv)
    args.progress_every = _PROGRESS_EVERY
    _validate_args(args)
    args_print(args)
    return args


def _print_step(step: int, message: str) -> None:
    """Print a standardized pipeline step message."""
    print(f"\nStep{step}: {message}", flush=True)


def _run_evidence_pipeline(args: Namespace) -> None:
    """Run smORF Ribo-seq evidence evaluation."""
    _print_step(2, "Evaluate Ribo-seq evidence for candidate smORFs.")
    output_table = run_riboseq_evidence(args)

    _print_step(3, "Output the smORF evidence table.")
    eprint(f"[smORFEvidence] Writing output: {args.output}")
    write_output(output_table, args.output)
    eprint("[smORFEvidence] Done.")


def main(argv: Sequence[str] | None = None) -> None:
    """Command-line entry point for smorf_evidence."""
    now_time()
    print("\nEvaluate smORF translation evidence.", flush=True)
    _print_step(1, "Checking the input arguments.")

    args = _parse_args(argv)
    _run_evidence_pipeline(args)

    print("\nAll done.", flush=True)
    now_time()


if __name__ == "__main__":
    main()
