#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-07-22
# Version: 0.2.8.18
# Function: Filter candidate smORFs using structural QC and optional Kozak context.
# Input: ORF message table and optional custom Kozak PWM.
# Output: Passed, removed, all-record, summary, and optional PWM files.

"""Command-line entry point for lightweight smORF filtering."""

from __future__ import annotations

import argparse
from argparse import Namespace
from collections.abc import Sequence
from pathlib import Path

from utils.ribo.ArgsParser import (
    args_print,
    file_check,
    now_time,
    message_print,
    result_print,
    warning_print,
    step_print,
    title_print,
)
from utils.smorf.smorf_filter import ORFFilter, ORFTable
from utils.smorf.smorf_kozak import BUILTIN_MODELS, KozakModel


DEFAULT_CATEGORIES = (
    "uORF,dORF,lncORF,iORF,emORF,overlap_uORF,"
    "overlap_dORF,other_ORF,annotated_ORF,annotated_mORF"
)
AUTO_KOZAK_MINIMUM = 100
AUTO_KOZAK_FALLBACK = "plant"


def _build_parser() -> argparse.ArgumentParser:
    """Build the command-line argument parser.

    Returns:
        Configured argument parser.
    """
    parser = argparse.ArgumentParser(
        description=(
            "Filter candidate smORFs using metadata, structural quality "
            "control, and optional Kozak context."
        )
    )

    required_group = parser.add_argument_group("Required arguments")
    required_group.add_argument(
        "-i",
        "--input",
        dest="input",
        required=True,
        type=str,
        help="Input ORF.message.txt generated by smorf_scanner.",
    )

    filter_group = parser.add_argument_group("Basic filtering arguments")
    filter_group.add_argument(
        "-o",
        "--out-prefix",
        dest="out_prefix",
        default="ORF.filtered",
        type=str,
        help="Output file prefix (default: %(default)s).",
    )
    filter_group.add_argument(
        "-s",
        "--keep-start-codons",
        dest="keep_start_codons",
        default="ATG,CTG,GTG,TTG",
        type=str,
        help="Comma-separated retained start codons (default: %(default)s).",
    )
    filter_group.add_argument(
        "-m",
        "--min-aa",
        dest="min_aa",
        default=8,
        type=int,
        help="Minimum peptide length (default: %(default)s aa).",
    )
    filter_group.add_argument(
        "-M",
        "--max-aa",
        dest="max_aa",
        default=10000,
        type=int,
        help="Maximum peptide length (default: %(default)s aa).",
    )
    filter_group.add_argument(
        "-c",
        "--keep-categories",
        dest="keep_categories",
        default=DEFAULT_CATEGORIES,
        type=str,
        help="Comma-separated category allowlist.",
    )
    filter_group.add_argument(
        "-r",
        "--remove-categories",
        dest="remove_categories",
        default="same_frame_iORF,antisense_ORF",
        type=str,
        help="Comma-separated category denylist.",
    )
    filter_group.add_argument(
        "-A",
        "--keep-antisense",
        dest="keep_antisense",
        action="store_true",
        default=False,
        help="Retain antisense ORFs (default: %(default)s).",
    )
    filter_group.add_argument(
        "-S",
        "--keep-secondary",
        dest="keep_secondary",
        action="store_true",
        default=False,
        help="Retain secondary overlapping ORFs (default: %(default)s).",
    )
    filter_group.add_argument(
        "-P",
        "--keep-partial",
        dest="keep_partial",
        action="store_true",
        default=False,
        help="Retain 3-prime partial ORFs (default: %(default)s).",
    )
    filter_group.add_argument(
        "--max-ambiguous-codons",
        dest="max_ambiguous_codons",
        default=0,
        type=int,
        help=(
            "Maximum ambiguous codon count when the field is available "
            "(default: %(default)s)."
        ),
    )

    kozak_group = parser.add_argument_group("Optional Kozak arguments")
    kozak_group.add_argument(
        "-k",
        "--kozak-model",
        dest="kozak_model",
        choices=["none", "auto", *sorted(BUILTIN_MODELS)],
        default="auto",
        type=str,
        help=(
            "Kozak model: none, auto, or a built-in species model "
            "(default: %(default)s)."
        ),
    )
    kozak_group.add_argument(
        "--kozak-pwm",
        dest="kozak_pwm",
        default=None,
        type=str,
        help="Custom PWM file. Overrides --kozak-model.",
    )
    kozak_group.add_argument(
        "-w",
        "--min-kozak-score",
        dest="min_kozak_score",
        default=0.0,
        type=float,
        help=(
            "Minimum Kozak score. Zero annotates without filtering "
            "(default: %(default)s)."
        ),
    )
    kozak_group.add_argument(
        "--export-kozak-pwm",
        dest="export_kozak_pwm",
        default=None,
        type=str,
        help="Optional output path for the selected PWM.",
    )

    return parser


def _parse_set(value: str) -> set[str]:
    """Parse comma-separated values."""
    return {
        item.strip()
        for item in str(value).split(",")
        if item.strip()
    }


def _join_set(values: set[str]) -> str:
    """Return a sorted comma-separated set."""
    return ",".join(sorted(values))


def _normalize_category_rules(args: Namespace) -> None:
    """Apply explicit keep flags to category rules.

    Args:
        args: Parsed arguments modified in place.
    """
    retained = _parse_set(args.keep_categories)
    removed = _parse_set(args.remove_categories)

    if args.keep_antisense:
        retained.add("antisense_ORF")
        removed.discard("antisense_ORF")

    conflict = retained.intersection(removed)
    if conflict:
        raise ValueError(
            "Category cannot be both retained and removed: "
            + ", ".join(sorted(conflict))
        )

    args.keep_categories = _join_set(retained)
    args.remove_categories = _join_set(removed)


def _validate_start_codons(value: str) -> None:
    """Validate retained start codons.

    Args:
        value: Comma-separated codons.

    Raises:
        ValueError: If codons are absent or invalid.
    """
    codons = {
        codon.strip().upper().replace("U", "T")
        for codon in value.split(",")
        if codon.strip()
    }
    if not codons:
        raise ValueError("--keep-start-codons cannot be empty.")

    invalid = sorted(
        codon
        for codon in codons
        if len(codon) != 3 or set(codon).difference("ACGT")
    )
    if invalid:
        raise ValueError(
            "Invalid retained start codon(s): "
            + ", ".join(invalid)
        )


def _validate_args(args: Namespace) -> None:
    """Validate command-line arguments.

    Args:
        args: Parsed command-line arguments.

    Raises:
        ValueError: If an argument is invalid.
    """
    file_check(args.input)
    if args.kozak_pwm:
        file_check(args.kozak_pwm)

    if not args.out_prefix:
        raise ValueError("--out-prefix must not be empty.")
    if args.min_aa < 1:
        raise ValueError("--min-aa must be >= 1.")
    if args.max_aa < args.min_aa:
        raise ValueError("--max-aa must be >= --min-aa.")
    if args.max_ambiguous_codons < 0:
        raise ValueError("--max-ambiguous-codons must be >= 0.")
    if not 0 <= args.min_kozak_score <= 1:
        raise ValueError("--min-kozak-score must be in [0, 1].")
    if (
        args.kozak_model == "none"
        and args.kozak_pwm is None
        and args.min_kozak_score > 0
    ):
        raise ValueError(
            "--min-kozak-score requires an enabled Kozak model."
        )

    _validate_start_codons(args.keep_start_codons)
    _normalize_category_rules(args)


def _parse_args(
    argv: Sequence[str] | None = None,
) -> Namespace:
    """Parse, validate, and print command-line arguments.

    Args:
        argv: Optional argument sequence for tests.

    Returns:
        Validated command-line arguments.
    """
    parser = _build_parser()
    args = parser.parse_args(argv)

    try:
        _validate_args(args)
    except ValueError as error:
        parser.error(str(error))

    args_print(args)
    return args




def _load_kozak_model(args: Namespace) -> KozakModel | None:
    """Load the requested Kozak model.

    Args:
        args: Validated command-line arguments.

    Returns:
        Kozak model or ``None``.
    """
    if args.kozak_pwm:
        return KozakModel.from_pwm_file(args.kozak_pwm)

    if args.kozak_model == "none":
        return None

    if args.kozak_model in BUILTIN_MODELS:
        return KozakModel.from_builtin(args.kozak_model)

    header = ORFTable.read_header(args.input)
    ORFTable.validate_header(header, require_kozak=True)
    try:
        model = KozakModel.from_annotated_records(
            ORFTable.iter_table(args.input, header),
            minimum_records=AUTO_KOZAK_MINIMUM,
        )
        message_print(
            "Auto Kozak model: annotated contexts "
            f"(n={model.training_count:,})."
        )
        return model
    except ValueError as error:
        warning_print(
            "{error}. Use built-in {fallback} Kozak model.".format(
                error=error,
                fallback=AUTO_KOZAK_FALLBACK,
            )
        )
        return KozakModel.from_builtin(AUTO_KOZAK_FALLBACK)


def _run_filter_pipeline(args: Namespace) -> None:
    """Run structural and optional Kozak filtering.

    Args:
        args: Validated arguments.
    """
    step_print(2, "Load the optional Kozak model.")
    kozak_model = _load_kozak_model(args)
    if kozak_model is not None and args.export_kozak_pwm:
        kozak_model.export(args.export_kozak_pwm)

    step_print(3, "Validate and filter ORF records.")
    orf_filter = ORFFilter(
        keep_start_codons=args.keep_start_codons,
        min_aa=args.min_aa,
        max_aa=args.max_aa,
        keep_categories=args.keep_categories,
        remove_categories=args.remove_categories,
        require_sense=not args.keep_antisense,
        require_primary=not args.keep_secondary,
        require_complete=not args.keep_partial,
        max_ambiguous_codons=args.max_ambiguous_codons,
        kozak_model=kozak_model,
        min_kozak_score=args.min_kozak_score,
    )
    summary = orf_filter.filter_file(
        input_path=args.input,
        output_prefix=args.out_prefix,
    )

    step_print(4, "Report filtering results.")
    result_print(
        [
            ("Total ORFs", f"{summary.total:,}"),
            ("Passed ORFs", f"{summary.passed:,}"),
            ("Removed ORFs", f"{summary.removed:,}"),
            (
                "Kozak model",
                "none" if kozak_model is None else kozak_model.name,
            ),
            (
                "Output summary",
                f"{args.out_prefix}.filter_summary.txt",
            ),
        ]
    )


def main(argv: Sequence[str] | None = None) -> None:
    """Run the smorf_filter command.

    Args:
        argv: Optional argument sequence for tests.
    """
    now_time()
    title_print("Filter candidate small open reading frames.")
    step_print(1, "Checking the input arguments.")

    args = _parse_args(argv)
    _run_filter_pipeline(args)

    title_print("All done.")
    now_time()


if __name__ == "__main__":
    main()
