#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Author: Rensc
date: 2026-05-23

@Project : smORF
@Script  : smorf_evidence.py

Entry script for smORF Ribo-seq evidence analysis.
"""


import argparse
import os
import sys


# Add the project root directory to Python import path.
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(CURRENT_DIR)

if PROJECT_DIR not in sys.path:
    sys.path.insert(0, PROJECT_DIR)

from utils.ribo.ArgsParser import args_print, file_check, now_time
from utils.smorf.smorf_riboseq_io import eprint, write_output
from utils.smorf.smorf_riboseq_pipeline import run_riboseq_evidence


def get_parser() -> argparse.ArgumentParser:
    """
    Create command-line argument parser.
    """

    parser = argparse.ArgumentParser(
        description="This script is used to evaluate smORF translation evidence using Ribo-seq P-site density."
    )

    input_group = parser.add_argument_group('Required arguments')
    input_group.add_argument('-i', '--orf-table', dest="orf_table", required=True, type=str,
                             help="the filtered smORF table generated by smorf_filter.")
    input_group.add_argument('-o', '--output', dest="output", required=True, type=str,
                             help="the output evidence table in TSV format.")

    parser.add_argument('-a', '--genepred', dest="genepred", required=False, type=str, default=None,
                        help="the optional genePred file used for ORF exon blocks. (default: %(default)s).")
    parser.add_argument('-z', '--chrom-sizes', dest="chrom_sizes", required=False, type=str, default=None,
                        help="the optional two-column chromosome size file. (default: infer from density files).")

    parser.add_argument('-l', '--density-list', dest="density_list", required=False, type=str, default=None,
                        help="the density file list with columns: sample, strand, path and optional format. (default: %(default)s).")
    parser.add_argument('-p', '--density-plus', dest="density_plus", required=False, type=str, default=None,
                        help="the plus-strand P-site density file. (default: %(default)s).")
    parser.add_argument('-n', '--density-minus', dest="density_minus", required=False, type=str, default=None,
                        help="the minus-strand P-site density file. (default: %(default)s).")
    parser.add_argument('-d', '--density', dest="density", required=False, type=str, default=None,
                        help="the unstranded P-site density file. (default: %(default)s).")
    parser.add_argument('-s', '--sample', dest="sample", required=False, type=str, default="sample1",
                        help="the sample name used for direct density input. (default: %(default)s).")
    parser.add_argument('-f', '--density-format', dest="density_format", required=False, type=str,
                        choices=["auto", "wig", "bedgraph"], default="auto",
                        help="the density file format. (default: %(default)s).")
    parser.add_argument('-c', '--coord-mode', dest="coord_mode", required=False, type=str,
                        choices=["0based-half-open", "1based-closed"], default="0based-half-open",
                        help="the coordinate mode for ORF table and genePred-like blocks. (default: %(default)s).")

    parser.add_argument('-r', '--post-stop-codons', dest="post_stop_codons", required=False, type=int, default=10,
                        help="the number of codons after stop codon used for release signal. (default: %(default)s).")
    parser.add_argument('-P', '--pseudocount', dest="pseudocount", required=False, type=float, default=0.1,
                        help="the pseudocount used for ratio calculation. (default: %(default)s).")

    parser.add_argument('-R', '--min-rpf-sum', dest="min_rpf_sum", required=False, type=float, default=3.0,
                        help="the minimum ORF-level RPF sum required for evidence scoring. (default: %(default)s).")
    parser.add_argument('-C', '--min-covered-codon', dest="min_covered_codon", required=False, type=int, default=2,
                        help="the minimum covered codon count required for evidence scoring. (default: %(default)s).")
    parser.add_argument('-v', '--min-coverage-ratio', dest="min_coverage_ratio", required=False, type=float, default=0.10,
                        help="the minimum nucleotide-level coverage ratio required for evidence scoring. (default: %(default)s).")

    parser.add_argument('--strong-periodicity', dest="strong_periodicity", required=False, type=float, default=0.70,
                        help="the frame-0 ratio threshold for strong periodicity. (default: %(default)s).")
    parser.add_argument('--moderate-periodicity', dest="moderate_periodicity", required=False, type=float, default=0.55,
                        help="the frame-0 ratio threshold for moderate periodicity. (default: %(default)s).")
    parser.add_argument('--strong-start-pause', dest="strong_start_pause", required=False, type=float, default=1.50,
                        help="the start pausing ratio threshold for strong signal. (default: %(default)s).")
    parser.add_argument('--moderate-start-pause', dest="moderate_start_pause", required=False, type=float, default=1.20,
                        help="the start pausing ratio threshold for moderate signal. (default: %(default)s).")
    parser.add_argument('--strong-stop-pause', dest="strong_stop_pause", required=False, type=float, default=1.50,
                        help="the pre-stop pausing ratio threshold for strong signal. (default: %(default)s).")
    parser.add_argument('--moderate-stop-pause', dest="moderate_stop_pause", required=False, type=float, default=1.20,
                        help="the pre-stop pausing ratio threshold for moderate signal. (default: %(default)s).")
    parser.add_argument('--strong-release', dest="strong_release", required=False, type=float, default=3.0,
                        help="the release ratio threshold for strong signal. (default: %(default)s).")
    parser.add_argument('--moderate-release', dest="moderate_release", required=False, type=float, default=1.5,
                        help="the release ratio threshold for moderate signal. (default: %(default)s).")

    parser.add_argument('--uniform-coverage-ratio', dest="uniform_coverage_ratio", required=False, type=float, default=0.40,
                        help="the coverage ratio threshold for Uniform shape. (default: %(default)s).")
    parser.add_argument('--uniform-gini', dest="uniform_gini", required=False, type=float, default=0.50,
                        help="the Gini threshold for Uniform shape. (default: %(default)s).")
    parser.add_argument('--uniform-max-to-mean', dest="uniform_max_to_mean", required=False, type=float, default=5.0,
                        help="the max-to-mean threshold for Uniform shape. (default: %(default)s).")
    parser.add_argument('--skewed-max-to-mean', dest="skewed_max_to_mean", required=False, type=float, default=10.0,
                        help="the max-to-mean threshold for Skewed shape. (default: %(default)s).")
    parser.add_argument('--skewed-top-fraction', dest="skewed_top_fraction", required=False, type=float, default=0.70,
                        help="the top 10 percent density fraction threshold for Skewed shape. (default: %(default)s).")
    parser.add_argument('--disperse-coverage-ratio', dest="disperse_coverage_ratio", required=False, type=float, default=0.20,
                        help="the coverage ratio threshold below which coverage is Disperse. (default: %(default)s).")
    parser.add_argument('-E', '--progress-every', dest="progress_every", required=False, type=int, default=10000,
                        help="print progress every N ORFs per chromosome. (default: %(default)s).")
    parser.add_argument('-N', '--keep-no-evidence', dest="keep_no_evidence", action="store_true", required=False, default=False,
                        help="keep ORFs with no RPF evidence in output. (default: %(default)s).")

    return parser


def main() -> None:
    """Run command-line workflow."""
    parser = get_parser()
    args = parser.parse_args()

    now_time()

    print('\nEvaluate smORF translation evidence.', flush=True)
    print('\nStep1: Checking the input Arguments.', flush=True)

    if args.density_list is None and args.density is None and (args.density_plus is None or args.density_minus is None):
        parser.error("Please provide --density-list, --density, or both --density-plus and --density-minus.")

    check_files = [args.orf_table]
    for file_name in [args.genepred, args.chrom_sizes, args.density_list, args.density_plus, args.density_minus, args.density]:
        if file_name is not None:
            check_files.append(file_name)
    file_check(*check_files)
    args_print(args)

    print('\nStep2: Evaluate Ribo-seq evidence for smORFs.', flush=True)
    output_table = run_riboseq_evidence(args)

    eprint(f"[smORFEvidence] Writing output: {args.output}")
    write_output(output_table, args.output)
    eprint("[smORFEvidence] Done.")

    print('\nAll done.', flush=True)
    now_time()


if __name__ == "__main__":
    main()
