#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-07-21
# Version: 0.2.8.18
# Function: Filter candidate smORFs and evaluate Kozak sequence context.
# Input: Candidate ORF message table and optional Kozak PWM or sequence model.
# Output: Passed, removed, and complete ORF tables with Kozak scores.

"""Command-line entry point for candidate smORF filtering."""

from __future__ import annotations

import argparse
from argparse import Namespace
from collections.abc import Sequence

from utils.ribo.ArgsParser import args_print, file_check, now_time
from utils.smorf.smorf_filter import ORFFilter
from utils.smorf.smorf_kozak import (
    BUILTIN_KOZAK_CONSENSUS,
    BUILTIN_KOZAK_PWMS,
    KozakPWM,
)


def _build_parser() -> argparse.ArgumentParser:
    """Build the command-line argument parser."""
    parser = argparse.ArgumentParser(
        description="Filter candidate smORFs and evaluate Kozak context."
    )

    required_group = parser.add_argument_group("Required arguments")
    required_group.add_argument(
        "-i",
        "--input",
        dest="input",
        default=None,
        type=str,
        help="Input ORF.message.txt generated by smorf_scanner.",
    )

    filtering_group = parser.add_argument_group("ORF filtering arguments")
    filtering_group.add_argument(
        "-o",
        "--out-prefix",
        dest="out_prefix",
        default="ORF.filtered",
        type=str,
        help="Output file prefix (default: %(default)s).",
    )
    filtering_group.add_argument(
        "-s",
        "--keep-start-codons",
        dest="keep_start_codons",
        default="ATG,CTG,GTG,TTG",
        type=str,
        help="Comma-separated retained start codons (default: %(default)s).",
    )
    filtering_group.add_argument(
        "-m",
        "--min-aa",
        dest="min_aa",
        default=8,
        type=int,
        help="Minimum peptide length (default: %(default)s aa).",
    )
    filtering_group.add_argument(
        "-M",
        "--max-aa",
        dest="max_aa",
        default=10000,
        type=int,
        help="Maximum peptide length (default: %(default)s aa).",
    )
    filtering_group.add_argument(
        "-c",
        "--keep-categories",
        dest="keep_categories",
        default=(
            "uORF,dORF,lncORF,iORF,emORF,overlap_uORF,"
            "overlap_dORF,other_ORF,annotated_ORF"
        ),
        type=str,
        help="Comma-separated ORF categories retained before filtering.",
    )
    filtering_group.add_argument(
        "-r",
        "--remove-categories",
        dest="remove_categories",
        default="same_frame_iORF,antisense_ORF",
        type=str,
        help="Comma-separated ORF categories removed before filtering.",
    )
    filtering_group.add_argument(
        "-A",
        "--keep-antisense",
        dest="keep_antisense",
        action="store_true",
        default=False,
        help="Retain antisense ORFs (default: %(default)s).",
    )
    filtering_group.add_argument(
        "-S",
        "--keep-secondary",
        dest="keep_secondary",
        action="store_true",
        default=False,
        help="Retain secondary overlapping ORFs (default: %(default)s).",
    )
    filtering_group.add_argument(
        "-P",
        "--keep-partial",
        dest="keep_partial",
        action="store_true",
        default=False,
        help="Retain incomplete ORFs (default: %(default)s).",
    )

    kozak_group = parser.add_argument_group("Kozak model arguments")
    kozak_group.add_argument(
        "-k",
        "--kozak-mode",
        dest="kozak_mode",
        choices=["none", "annotated", "builtin", "pwm", "sequence"],
        default="annotated",
        type=str,
        help="Kozak model source (default: %(default)s).",
    )
    kozak_group.add_argument(
        "-b",
        "--builtin-kozak",
        dest="builtin_kozak",
        choices=sorted(BUILTIN_KOZAK_PWMS),
        default="plant",
        type=str,
        help="Built-in Kozak model used in builtin mode.",
    )
    kozak_group.add_argument(
        "-p",
        "--kozak-pwm",
        dest="kozak_pwm",
        default=None,
        type=str,
        help="Custom Kozak PWM file used in pwm mode.",
    )
    kozak_group.add_argument(
        "-q",
        "--kozak-seq",
        dest="kozak_seq",
        default=None,
        type=str,
        help="Aligned Kozak sequence file used in sequence mode.",
    )
    kozak_group.add_argument(
        "-C",
        "--annotated-categories",
        dest="annotated_categories",
        default="annotated_ORF",
        type=str,
        help="ORF categories used to build the annotated Kozak PWM.",
    )
    kozak_group.add_argument(
        "-n",
        "--min-annotated-kozak",
        dest="min_annotated_kozak",
        default=100,
        type=int,
        help="Minimum annotated Kozak sequences used to build a PWM.",
    )
    kozak_group.add_argument(
        "-B",
        "--fallback-builtin-kozak",
        dest="fallback_builtin_kozak",
        choices=sorted(BUILTIN_KOZAK_PWMS),
        default="plant",
        type=str,
        help="Fallback built-in Kozak model.",
    )
    kozak_group.add_argument(
        "-F",
        "--no-kozak-fallback",
        dest="no_kozak_fallback",
        action="store_true",
        default=False,
        help="Disable fallback when annotated PWM construction fails.",
    )
    kozak_group.add_argument(
        "-w",
        "--min-kozak-pwm-score",
        dest="min_kozak_pwm_score",
        default=0.0,
        type=float,
        help="Minimum normalized Kozak PWM score.",
    )
    kozak_group.add_argument(
        "-e",
        "--export-kozak-pwm",
        dest="export_kozak_pwm",
        default=None,
        type=str,
        help="Optional output path for the loaded or constructed PWM.",
    )
    kozak_group.add_argument(
        "-L",
        "--list-builtin-kozak",
        dest="list_builtin_kozak",
        action="store_true",
        default=False,
        help="List built-in Kozak models and exit.",
    )

    return parser


def _validate_args(args: Namespace) -> None:
    """Validate command-line arguments."""
    if args.list_builtin_kozak:
        return
    if args.input is None:
        raise ValueError(
            "the following arguments are required: -i/--input"
        )
    if args.kozak_mode == "pwm" and args.kozak_pwm is None:
        raise ValueError("--kozak-pwm is required in pwm mode.")
    if args.kozak_mode == "sequence" and args.kozak_seq is None:
        raise ValueError("--kozak-seq is required in sequence mode.")

    files = [args.input]
    if args.kozak_pwm:
        files.append(args.kozak_pwm)
    if args.kozak_seq:
        files.append(args.kozak_seq)
    file_check(*files)

    if args.min_aa < 1:
        raise ValueError("--min-aa must be >= 1.")
    if args.max_aa < args.min_aa:
        raise ValueError("--max-aa must be >= --min-aa.")
    if args.min_annotated_kozak < 1:
        raise ValueError("--min-annotated-kozak must be >= 1.")


def _parse_args(argv: Sequence[str] | None = None) -> Namespace:
    """Parse, validate, and print command-line arguments."""
    parser = _build_parser()
    args = parser.parse_args(argv)

    try:
        _validate_args(args)
    except ValueError as error:
        parser.error(str(error))

    args_print(args)
    return args


def _print_step(step: int, message: str) -> None:
    """Print a standardized pipeline step message."""
    print(f"\nStep{step}: {message}", flush=True)


def _print_builtin_kozak_models() -> None:
    """Print available built-in Kozak models."""
    print("name\tconsensus\tlength")
    for name in sorted(BUILTIN_KOZAK_PWMS):
        pwm = BUILTIN_KOZAK_PWMS[name]
        consensus = BUILTIN_KOZAK_CONSENSUS.get(name, "NA")
        print(f"{name}\t{consensus}\t{len(pwm)}")


def _load_kozak_pwm(args: Namespace, records: list[dict]) -> KozakPWM | None:
    """Load or construct the requested Kozak PWM."""
    if args.kozak_mode == "none":
        return None
    if args.kozak_mode == "builtin":
        return KozakPWM.from_builtin(args.builtin_kozak)
    if args.kozak_mode == "pwm":
        return KozakPWM.from_pwm_file(
            args.kozak_pwm,
            name="custom_pwm",
        )
    if args.kozak_mode == "sequence":
        sequences: list[str] = []
        with open(args.kozak_seq, "r", encoding="utf-8") as handle:
            for line in handle:
                sequence = line.strip()
                if sequence and not sequence.startswith(">"):
                    sequences.append(sequence)
        return KozakPWM.from_sequences(
            sequences=sequences,
            name="custom_sequence_pwm",
        )
    if args.kozak_mode == "annotated":
        try:
            return KozakPWM.from_annotated_orf_records(
                records=records,
                annotated_categories=args.annotated_categories,
                min_sequences=args.min_annotated_kozak,
                name="annotated_ORF_pwm",
            )
        except ValueError as error:
            if args.no_kozak_fallback:
                raise
            print(
                "[smORFFilter] Warning: "
                f"{error}. Fallback to built-in Kozak PWM: "
                f"{args.fallback_builtin_kozak}",
                flush=True,
            )
            return KozakPWM.from_builtin(args.fallback_builtin_kozak)
    return None


def _run_filter_pipeline(args: Namespace) -> None:
    """Run candidate smORF filtering."""
    if args.list_builtin_kozak:
        _print_step(2, "List built-in Kozak PWM models.")
        _print_builtin_kozak_models()
        return

    _print_step(2, "Import candidate ORF records.")
    header, records = ORFFilter.read_table(args.input)

    _print_step(3, "Load or construct the Kozak PWM.")
    kozak_pwm = _load_kozak_pwm(args, records)
    if kozak_pwm is not None and args.export_kozak_pwm:
        kozak_pwm.export_pwm(args.export_kozak_pwm)

    _print_step(4, "Filter candidate ORF records.")
    orf_filter = ORFFilter(
        keep_start_codons=args.keep_start_codons,
        min_aa=args.min_aa,
        max_aa=args.max_aa,
        min_kozak_pwm_score=args.min_kozak_pwm_score,
        kozak_pwm=kozak_pwm,
        keep_categories=args.keep_categories,
        remove_categories=args.remove_categories,
        require_sense=not args.keep_antisense,
        require_primary=not args.keep_secondary,
        require_complete=not args.keep_partial,
    )
    header = orf_filter.add_kozak_pwm_fields(header, records)
    passed, removed = orf_filter.filter_records(records)

    _print_step(5, "Output filtered ORF tables.")
    passed_path = f"{args.out_prefix}.passed.message.txt"
    removed_path = f"{args.out_prefix}.removed.message.txt"
    all_path = f"{args.out_prefix}.all.message.txt"

    ORFFilter.write_table(passed_path, header, passed)
    ORFFilter.write_table(removed_path, header, removed)
    ORFFilter.write_table(all_path, header, records)

    print(f"[smORFFilter] Total ORFs: {len(records):,}", flush=True)
    print(f"[smORFFilter] Passed ORFs: {len(passed):,}", flush=True)
    print(f"[smORFFilter] Removed ORFs: {len(removed):,}", flush=True)
    if kozak_pwm is not None:
        print(f"[smORFFilter] Kozak PWM name: {kozak_pwm.name}", flush=True)
        print(f"[smORFFilter] Kozak PWM source: {kozak_pwm.source}", flush=True)
        print(f"[smORFFilter] Kozak consensus: {kozak_pwm.consensus}", flush=True)
    print(f"[smORFFilter] Output passed file: {passed_path}", flush=True)


def main(argv: Sequence[str] | None = None) -> None:
    """Command-line entry point for smorf_filter."""
    now_time()
    print("\nFilter candidate small open reading frames.", flush=True)
    _print_step(1, "Checking the input arguments.")

    args = _parse_args(argv)
    _run_filter_pipeline(args)

    print("\nAll done.", flush=True)
    now_time()


if __name__ == "__main__":
    main()
