#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-08-01
# Version: dev003
# Function: Quantify reliable smORF P-site density across Ribo-seq samples.
# Input: Reliable smORF genePred and a sample/strand density design table.
# Output: Wide smORF-by-sample raw P-site density count matrix.

"""Command-line entry point for reliable smORF density quantification."""

from __future__ import annotations

import argparse
from argparse import Namespace
from collections.abc import Sequence

from utils.ribo.ArgsParser import (
    args_print,
    file_check,
    now_time,
    result_print,
    step_print,
    title_print,
)
from utils.smorf.quant import run_smorf_quant


def _build_parser() -> argparse.ArgumentParser:
    """Build the production command-line parser."""
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=(
            "Quantify reliable smORFs from genomic P-site WIG/bedGraph "
            "density tracks. Counts are reported in smORF genePred order."
        ),
    )
    parser.add_argument(
        "--version",
        action="version",
        version="smorf_quant dev003 (2026-08-01)",
    )

    required = parser.add_argument_group("Required arguments")
    required.add_argument(
        "-g",
        "--genepred",
        dest="genepred",
        required=True,
        type=str,
        help=(
            "Reliable smORF genePred generated by smorf_evidence. Column 1 "
            "must contain unique ORF IDs."
        ),
    )
    required.add_argument(
        "-l",
        "--density-list",
        dest="density_list",
        required=True,
        type=str,
        help=(
            "Tab-delimited density design containing sample/name, strand, "
            "and path/file/density columns."
        ),
    )
    required.add_argument(
        "-o",
        "--output",
        dest="output",
        required=True,
        type=str,
        help=("Output prefix. The count matrix is written as <prefix>.density_quant.txt."),
    )

    quantification = parser.add_argument_group("Quantification arguments")
    quantification.add_argument(
        "-f",
        "--frame",
        dest="frame",
        choices=("all", "0", "1", "2"),
        default="all",
        type=str,
        help=(
            "P-site frame retained relative to each spliced smORF. 'all' "
            "matches the evidence rpf_sum definition (default: %(default)s)."
        ),
    )
    quantification.add_argument(
        "--include-stop",
        dest="include_stop",
        action="store_true",
        default=False,
        help=(
            "Include a complete terminal stop codon in quantification. By "
            "default, the terminal stop is excluded (default: %(default)s)."
        ),
    )

    runtime = parser.add_argument_group("Runtime arguments")
    runtime.add_argument(
        "-t",
        "--thread",
        dest="threads",
        default=1,
        type=int,
        help=(
            "Number of samples quantified concurrently. Each density track "
            "is parsed once (default: %(default)s)."
        ),
    )
    return parser


def _validate_args(args: Namespace) -> None:
    """Validate command-line arguments."""
    file_check(args.genepred, args.density_list)
    if args.threads < 1:
        raise ValueError("--thread must be >= 1.")
    if not str(args.output).strip():
        raise ValueError("--output cannot be empty.")


def _parse_args(argv: Sequence[str] | None = None) -> Namespace:
    """Parse, validate, and print command-line arguments."""
    parser = _build_parser()
    args = parser.parse_args(argv)
    try:
        _validate_args(args)
    except ValueError as error:
        parser.error(str(error))
    args_print(args)
    return args


def main(argv: Sequence[str] | None = None) -> None:
    """Run smORF P-site density quantification."""
    now_time()
    title_print("Quantify reliable smORF Ribo-seq density.")

    step_print(1, "Checking the input arguments.")
    args = _parse_args(argv)

    step_print(2, "Quantify smORF density across samples.")
    result = run_smorf_quant(args)

    step_print(3, "Report smORF quantification outputs.")
    result_print(
        [
            ("Reliable smORFs", f"{result.orf_count:,}"),
            ("Biological samples", f"{result.sample_count:,}"),
            ("Effective workers", result.effective_workers),
            ("Quantified frame", result.frame),
            ("Include stop", result.include_stop),
            ("Density quant", result.output),
        ]
    )

    title_print("All done.")
    now_time()


if __name__ == "__main__":
    main()
