#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-06-12
# Version: 0.2.7
# Function: This script is used to integrate smORF Ribo-seq evidence tables.
# Input: Command-line arguments and input files specified by the user.
# Output: Analysis tables, figures, logs, or intermediate files generated by the command.


import argparse
import os
import sys


# Add the project root directory to Python import path.
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(CURRENT_DIR)

if PROJECT_DIR not in sys.path:
    sys.path.insert(0, PROJECT_DIR)

from utils.ribo.ArgsParser import args_print, file_check, now_time
from utils.smorf.smorf_riboseq_integrate import run_integration


def get_parser() -> argparse.ArgumentParser:
    """
    Create command-line parser.
    """

    parser = argparse.ArgumentParser(
        description="This script is used to integrate smORF Ribo-seq evidence tables."
    )

    input_group = parser.add_argument_group('Required arguments')
    input_group.add_argument('-i', '--input', dest="input", required=True, type=str,
                             help="the long-format smORF Ribo-seq evidence table generated by smorf_evidence.")

    parser.add_argument('-m', '--output-matrix', dest="output_matrix", required=False, type=str, default=None,
                        help="the output ORF-by-sample matrix table. (default: %(default)s).")
    parser.add_argument('-o', '--output-integrated', dest="output_integrated", required=False, type=str, default=None,
                        help="the output integrated ORF-level evidence table. (default: %(default)s).")
    parser.add_argument('-c', '--capture-labels', dest="capture_labels", required=False, type=str,
                        default="LowConfidence,MediumConfidence,HighConfidence",
                        help="translation evidence labels used to define captured samples. (default: %(default)s).")
    parser.add_argument('-p', '--pass-labels', dest="pass_labels", required=False, type=str,
                        default="MediumConfidence,HighConfidence",
                        help="translation evidence labels used to define reliable samples. (default: %(default)s).")
    parser.add_argument('-n', '--excellent-min-samples', dest="excellent_min_samples", required=False, type=int, default=2,
                        help="the minimum number of reliable samples required to mark an ORF as Excellent. (default: %(default)s).")

    return parser


def main() -> None:
    """Run command-line workflow."""
    parser = get_parser()
    args = parser.parse_args()

    now_time()

    print('\nIntegrate smORF Ribo-seq evidence tables.', flush=True)
    print('\nStep1: Checking the input Arguments.', flush=True)

    if not args.output_matrix and not args.output_integrated:
        parser.error("At least one of --output-matrix or --output-integrated must be provided.")

    file_check(args.input)
    args_print(args)

    print('\nStep2: Integrate smORF evidence across samples.', flush=True)
    run_integration(args)

    print('\nAll done.', flush=True)
    now_time()


if __name__ == "__main__":
    main()
