#!/usr/bin/env python3
# Author: Rensc
# date: 2026-05-22

"""
Command-line interface for ORF filtering.

Default Kozak mode:
    annotated

This means the script builds a species-specific Kozak PWM from annotated_ORF
records in ORF.message.txt and then scores all ORFs using this PWM.
"""

import argparse
import os
import sys


CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(CURRENT_DIR)

if PROJECT_DIR not in sys.path:
    sys.path.insert(0, PROJECT_DIR)

from utils.ribo.ArgsParser import args_print, file_check, now_time
from utils.smorf.smorf_filter import ORFFilter
from utils.smorf.smorf_kozak import (
    KozakPWM,
    BUILTIN_KOZAK_PWMS,
    BUILTIN_KOZAK_CONSENSUS,
)


def parse_args():
    """
    Parse command-line arguments.
    """

    parser = argparse.ArgumentParser(
        description="This script is used to filter smORFs and evaluate Kozak context."
    )

    input_group = parser.add_argument_group('Required arguments')
    input_group.add_argument('-i', '--input', dest="input", required=False, type=str, default=None,
                             help="the input ORF.message.txt file generated by smorf_scanner.")

    parser.add_argument('-o', '--out-prefix', dest="out_prefix", required=False, type=str, default="ORF.filtered",
                        help="the prefix of output files. (default: %(default)s).")
    parser.add_argument('-s', '--keep-start-codons', dest="keep_start_codons", required=False, type=str,
                        default="ATG,CTG,GTG,TTG",
                        help="comma-separated start codons retained in the output. (default: %(default)s).")
    parser.add_argument('-m', '--min-aa', dest="min_aa", required=False, type=int, default=8,
                        help="the minimum ORF peptide length to keep. (default: %(default)s aa).")
    parser.add_argument('-M', '--max-aa', dest="max_aa", required=False, type=int, default=10000,
                        help="the maximum ORF peptide length to keep. (default: %(default)s aa).")
    parser.add_argument('-c', '--keep-categories', dest="keep_categories", required=False, type=str,
                        default="uORF,dORF,lncORF,iORF,emORF,overlap_uORF,overlap_dORF,other_ORF,annotated_ORF",
                        help="comma-separated ORF categories retained before filtering. (default: %(default)s).")
    parser.add_argument('-r', '--remove-categories', dest="remove_categories", required=False, type=str,
                        default="same_frame_iORF,antisense_ORF",
                        help="comma-separated ORF categories removed before filtering. (default: %(default)s).")
    parser.add_argument('-A', '--keep-antisense', dest="keep_antisense", action="store_true", required=False, default=False,
                        help="keep antisense ORFs. (default: %(default)s).")
    parser.add_argument('-S', '--keep-secondary', dest="keep_secondary", action="store_true", required=False, default=False,
                        help="keep secondary or lower-priority overlapping ORFs. (default: %(default)s).")
    parser.add_argument('-P', '--keep-partial', dest="keep_partial", action="store_true", required=False, default=False,
                        help="keep incomplete ORFs without a complete start-stop structure. (default: %(default)s).")

    parser.add_argument('-k', '--kozak-mode', dest="kozak_mode", required=False, type=str,
                        choices=["none", "annotated", "builtin", "pwm", "sequence"], default="annotated",
                        help="specify the Kozak model source. (default: %(default)s).")
    parser.add_argument('-b', '--builtin-kozak', dest="builtin_kozak", required=False, type=str,
                        choices=sorted(BUILTIN_KOZAK_PWMS.keys()), default="plant",
                        help="the built-in Kozak PWM used when --kozak-mode builtin. (default: %(default)s).")
    parser.add_argument('-p', '--kozak-pwm', dest="kozak_pwm", required=False, type=str, default=None,
                        help="the custom Kozak PWM matrix file used when --kozak-mode pwm. (default: %(default)s).")
    parser.add_argument('-q', '--kozak-seq', dest="kozak_seq", required=False, type=str, default=None,
                        help="the aligned Kozak sequence file used when --kozak-mode sequence. (default: %(default)s).")
    parser.add_argument('-C', '--annotated-categories', dest="annotated_categories", required=False, type=str,
                        default="annotated_ORF",
                        help="ORF categories used to build annotated ORF Kozak PWM. (default: %(default)s).")
    parser.add_argument('-n', '--min-annotated-kozak', dest="min_annotated_kozak", required=False, type=int, default=100,
                        help="the minimum annotated ORF Kozak sequences required to build PWM. (default: %(default)s).")
    parser.add_argument('-B', '--fallback-builtin-kozak', dest="fallback_builtin_kozak", required=False, type=str,
                        choices=sorted(BUILTIN_KOZAK_PWMS.keys()), default="plant",
                        help="fallback built-in Kozak PWM if annotated PWM construction fails. (default: %(default)s).")
    parser.add_argument('-F', '--no-kozak-fallback', dest="no_kozak_fallback", action="store_true", required=False, default=False,
                        help="disable fallback to built-in PWM if annotated PWM construction fails. (default: %(default)s).")
    parser.add_argument('-w', '--min-kozak-pwm-score', dest="min_kozak_pwm_score", required=False, type=float, default=0.0,
                        help="the minimum normalized Kozak PWM score to keep. (default: %(default)s).")
    parser.add_argument('-e', '--export-kozak-pwm', dest="export_kozak_pwm", required=False, type=str, default=None,
                        help="export the loaded or constructed Kozak PWM to this file. (default: %(default)s).")
    parser.add_argument('-L', '--list-builtin-kozak', dest="list_builtin_kozak", action="store_true", required=False, default=False,
                        help="list built-in Kozak PWM models and exit. (default: %(default)s).")

    args = parser.parse_args()

    if args.list_builtin_kozak:
        return args

    if args.input is None:
        parser.error("-i/--input is required unless --list-builtin-kozak is used.")

    if args.kozak_mode == "pwm" and args.kozak_pwm is None:
        parser.error("--kozak-pwm is required when --kozak-mode pwm.")

    if args.kozak_mode == "sequence" and args.kozak_seq is None:
        parser.error("--kozak-seq is required when --kozak-mode sequence.")

    return args


def print_builtin_kozak_models():
    """
    Print available built-in Kozak models.
    """

    print("name\tconsensus\tlength")

    for name in sorted(BUILTIN_KOZAK_PWMS.keys()):
        pwm = BUILTIN_KOZAK_PWMS[name]
        consensus = BUILTIN_KOZAK_CONSENSUS.get(name, "NA")
        print("{}\t{}\t{}".format(name, consensus, len(pwm)))


def load_kozak_pwm(args, records):
    """
    Load or build Kozak PWM.
    """

    if args.kozak_mode == "none":
        return None

    if args.kozak_mode == "builtin":
        return KozakPWM.from_builtin(args.builtin_kozak)

    if args.kozak_mode == "pwm":
        if args.kozak_pwm is None:
            raise ValueError("--kozak-pwm is required when --kozak-mode pwm")

        return KozakPWM.from_pwm_file(
            args.kozak_pwm,
            name="custom_pwm",
        )

    if args.kozak_mode == "sequence":
        if args.kozak_seq is None:
            raise ValueError("--kozak-seq is required when --kozak-mode sequence")

        sequences = []

        with open(args.kozak_seq, "r") as handle:
            for line in handle:
                line = line.strip()

                if not line or line.startswith(">"):
                    continue

                sequences.append(line)

        return KozakPWM.from_sequences(
            sequences=sequences,
            name="custom_sequence_pwm",
        )

    if args.kozak_mode == "annotated":
        try:
            return KozakPWM.from_annotated_orf_records(
                records=records,
                annotated_categories=args.annotated_categories,
                min_sequences=args.min_annotated_kozak,
                name="annotated_ORF_pwm",
            )
        except ValueError as error:
            if args.no_kozak_fallback:
                raise error

            print(
                "[smORFFilter] Warning: {}. Fallback to built-in Kozak PWM: {}".format(
                    error,
                    args.fallback_builtin_kozak,
                ),
                flush=True,
            )

            return KozakPWM.from_builtin(args.fallback_builtin_kozak)

    return None


def main():
    """
    Run ORF filtering.
    """

    args = parse_args()

    now_time()

    print('\nFilter smORF records.', flush=True)
    print('\nStep1: Checking the input Arguments.', flush=True)

    if args.list_builtin_kozak:
        print('\nStep2: List built-in Kozak PWM models.', flush=True)
        print_builtin_kozak_models()
        print('\nAll done.', flush=True)
        now_time()
        return

    check_files = [args.input]
    if args.kozak_pwm is not None:
        check_files.append(args.kozak_pwm)
    if args.kozak_seq is not None:
        check_files.append(args.kozak_seq)
    file_check(*check_files)
    args_print(args)

    print('\nStep2: Reading ORF records', flush=True)
    header, records = ORFFilter.read_table(args.input)

    print('\nStep3: Loading Kozak PWM', flush=True)
    kozak_pwm = load_kozak_pwm(args, records)

    if kozak_pwm is not None and args.export_kozak_pwm is not None:
        kozak_pwm.export_pwm(args.export_kozak_pwm)

    print('\nStep4: Filtering ORF records', flush=True)
    orf_filter = ORFFilter(
        keep_start_codons=args.keep_start_codons,
        min_aa=args.min_aa,
        max_aa=args.max_aa,
        min_kozak_pwm_score=args.min_kozak_pwm_score,
        kozak_pwm=kozak_pwm,
        keep_categories=args.keep_categories,
        remove_categories=args.remove_categories,
        require_sense=not args.keep_antisense,
        require_primary=not args.keep_secondary,
        require_complete=not args.keep_partial,
    )

    
    header = orf_filter.add_kozak_pwm_fields(header, records)

    passed, removed = orf_filter.filter_records(records)

    print('\nStep5: Format the output', flush=True)
    passed_path = "{}.passed.message.txt".format(args.out_prefix)
    removed_path = "{}.removed.message.txt".format(args.out_prefix)
    all_path = "{}.all.message.txt".format(args.out_prefix)

    print('\nStep6: Writing output files', flush=True)
    ORFFilter.write_table(passed_path, header, passed)
    ORFFilter.write_table(removed_path, header, removed)
    ORFFilter.write_table(all_path, header, records)

    print("[smORFFilter] Total ORFs: {}".format(len(records)), flush=True)
    print("[smORFFilter] Passed ORFs: {}".format(len(passed)), flush=True)
    print("[smORFFilter] Removed ORFs: {}".format(len(removed)), flush=True)

    if kozak_pwm is not None:
        print("[smORFFilter] Kozak PWM name: {}".format(kozak_pwm.name), flush=True)
        print("[smORFFilter] Kozak PWM source: {}".format(kozak_pwm.source), flush=True)
        print("[smORFFilter] Kozak consensus: {}".format(kozak_pwm.consensus), flush=True)

    print("[smORFFilter] Output passed file: {}".format(passed_path), flush=True)

    print('\nAll done.', flush=True)
    now_time()


if __name__ == "__main__":
    main()
