#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-07-22
# Version: 0.2.8.18
# Function: Evaluate smORF translation evidence from Ribo-seq P-site density.
# Input: Filtered smORF table and one or more density tracks.
# Output: Separate sample-level evidence and summary files for every sample.

"""Command-line entry point for smORF Ribo-seq evidence analysis."""

from __future__ import annotations

import argparse
from argparse import Namespace
from collections.abc import Sequence

from utils.ribo.ArgsParser import (
    args_print,
    file_check,
    now_time,
    result_print,
    step_print,
    title_print,
)
from utils.smorf.smorf_riboseq_pipeline import run_riboseq_evidence


def _build_parser() -> argparse.ArgumentParser:
    """Build the command-line argument parser.

    Returns:
        Configured argument parser.
    """
    parser = argparse.ArgumentParser(
        description=(
            "Evaluate smORF translation evidence using Ribo-seq P-site "
            "density and write one result set per sample."
        )
    )

    required_group = parser.add_argument_group("Required arguments")
    required_group.add_argument(
        "-i",
        "--orf-table",
        dest="orf_table",
        required=True,
        type=str,
        help="Filtered smORF message table generated by smorf_filter.",
    )
    required_group.add_argument(
        "-o",
        "--output",
        dest="output",
        required=True,
        type=str,
        help=(
            "Output template in TSV or TSV.GZ format. The density-list "
            "sample name is inserted before the suffix."
        ),
    )

    density_group = parser.add_argument_group("P-site density arguments")
    density_group.add_argument(
        "-l",
        "--density-list",
        dest="density_list",
        default=None,
        type=str,
        help=(
            "Density list with sample and path columns; strand and format "
            "are optional."
        ),
    )
    density_group.add_argument(
        "-d",
        "--density",
        dest="density",
        action="append",
        default=None,
        type=str,
        help=(
            "Direct density file. Repeat for plus/minus files. Strand is "
            "inferred from plus/minus in the file name; otherwise the file "
            "is treated as unstranded."
        ),
    )
    density_group.add_argument(
        "-s",
        "--sample",
        dest="sample",
        default="sample1",
        type=str,
        help="Sample name for direct density input (default: %(default)s).",
    )
    density_group.add_argument(
        "-f",
        "--density-format",
        dest="density_format",
        choices=["auto", "wig", "bedgraph"],
        default="auto",
        type=str,
        help="Direct density-file format (default: %(default)s).",
    )

    annotation_group = parser.add_argument_group("Annotation arguments")
    annotation_group.add_argument(
        "-a",
        "--genepred",
        dest="genepred",
        default=None,
        type=str,
        help=(
            "Optional original transcript genePred used by smorf_scanner "
            "-a. Do not use the scanner ORF genePred output."
        ),
    )
    annotation_group.add_argument(
        "-c",
        "--coord-mode",
        dest="coord_mode",
        choices=["0based-half-open", "1based-closed"],
        default="0based-half-open",
        type=str,
        help="ORF and genePred coordinate convention (default: %(default)s).",
    )
    annotation_group.add_argument(
        "-r",
        "--post-stop-codons",
        dest="post_stop_codons",
        default=10,
        type=int,
        help=(
            "Transcript-spliced codons after the stop used for release "
            "analysis (default: %(default)s)."
        ),
    )

    evidence_group = parser.add_argument_group("Evidence arguments")
    evidence_group.add_argument(
        "--evidence-mode",
        dest="evidence_mode",
        choices=["sensitive", "balanced", "strict"],
        default="balanced",
        type=str,
        help="Evidence-threshold preset (default: %(default)s).",
    )
    evidence_group.add_argument(
        "-R",
        "--min-rpf-sum",
        dest="min_rpf_sum",
        default=None,
        type=float,
        help="Override the preset minimum coding-region P-site sum.",
    )
    evidence_group.add_argument(
        "-C",
        "--min-covered-codon",
        dest="min_covered_codon",
        default=None,
        type=int,
        help="Override the preset minimum covered codon count.",
    )
    evidence_group.add_argument(
        "-v",
        "--min-codon-coverage",
        "--min-coverage-ratio",
        dest="min_codon_coverage",
        default=None,
        type=float,
        help="Override the preset covered-codon fraction.",
    )
    evidence_group.add_argument(
        "--moderate-periodicity",
        dest="moderate_periodicity",
        default=None,
        type=float,
        help="Override the moderate frame-0 ratio.",
    )
    evidence_group.add_argument(
        "--strong-periodicity",
        dest="strong_periodicity",
        default=None,
        type=float,
        help="Override the strong frame-0 ratio.",
    )
    evidence_group.add_argument(
        "--min-evidence",
        dest="min_evidence",
        choices=["all", "low", "medium", "high"],
        default="all",
        type=str,
        help=(
            "Minimum evidence written to each sample table. Each summary "
            "always includes all ORFs (default: %(default)s)."
        ),
    )

    runtime_group = parser.add_argument_group("Runtime arguments")
    runtime_group.add_argument(
        "-t",
        "--threads",
        dest="threads",
        default=1,
        type=int,
        help=(
            "Parallel sample processes. Each sample is written independently "
            "(default: %(default)s)."
        ),
    )

    # Hidden compatibility aliases from the previous interface.
    parser.add_argument(
        "-p",
        "--density-plus",
        dest="density_plus",
        default=None,
        type=str,
        help=argparse.SUPPRESS,
    )
    parser.add_argument(
        "-n",
        "--density-minus",
        dest="density_minus",
        default=None,
        type=str,
        help=argparse.SUPPRESS,
    )
    parser.add_argument(
        "-z",
        "--chrom-sizes",
        dest="chrom_sizes",
        default=None,
        type=str,
        help=argparse.SUPPRESS,
    )
    parser.add_argument(
        "-N",
        "--keep-no-evidence",
        dest="keep_no_evidence",
        action="store_true",
        default=True,
        help=argparse.SUPPRESS,
    )

    return parser


def _validate_args(args: Namespace) -> None:
    """Validate command-line arguments.

    Args:
        args: Parsed arguments.

    Raises:
        ValueError: If input combinations or thresholds are invalid.
    """
    files = [args.orf_table]
    if args.density_list is not None:
        files.append(args.density_list)
    for path in (
        *(args.density or []),
        args.density_plus,
        args.density_minus,
        args.genepred,
        args.chrom_sizes,
    ):
        if path is not None:
            files.append(path)
    file_check(*files)

    has_list = args.density_list is not None
    has_direct = bool(
        args.density
        or args.density_plus
        or args.density_minus
    )
    if has_list and has_direct:
        raise ValueError(
            "--density-list cannot be mixed with direct --density files."
        )
    if not has_list and not has_direct:
        raise ValueError(
            "Provide --density-list or at least one --density file."
        )

    if not args.sample.strip():
        raise ValueError("--sample must not be empty.")
    if args.post_stop_codons < 0:
        raise ValueError("--post-stop-codons must be >= 0.")
    if args.threads < 1:
        raise ValueError("--threads must be >= 1.")
    if args.min_rpf_sum is not None and args.min_rpf_sum < 0:
        raise ValueError("--min-rpf-sum must be >= 0.")
    if (
        args.min_covered_codon is not None
        and args.min_covered_codon < 1
    ):
        raise ValueError("--min-covered-codon must be >= 1.")
    if (
        args.min_codon_coverage is not None
        and not 0 <= args.min_codon_coverage <= 1
    ):
        raise ValueError("--min-codon-coverage must be in [0, 1].")

    for name in ("moderate_periodicity", "strong_periodicity"):
        value = getattr(args, name)
        if value is not None and not 0 <= value <= 1:
            raise ValueError(
                f"--{name.replace('_', '-')} must be in [0, 1]."
            )
    if (
        args.moderate_periodicity is not None
        and args.strong_periodicity is not None
        and args.moderate_periodicity > args.strong_periodicity
    ):
        raise ValueError(
            "--moderate-periodicity must be <= --strong-periodicity."
        )


def _parse_args(
    argv: Sequence[str] | None = None,
) -> Namespace:
    """Parse, validate, and print arguments.

    Args:
        argv: Optional argument sequence for tests.

    Returns:
        Validated arguments.
    """
    parser = _build_parser()
    args = parser.parse_args(argv)

    try:
        _validate_args(args)
    except ValueError as error:
        parser.error(str(error))

    hidden_fields = {
        "density_plus",
        "density_minus",
        "chrom_sizes",
        "keep_no_evidence",
    }
    display_args = Namespace(
        **{
            name: value
            for name, value in vars(args).items()
            if name not in hidden_fields
        }
    )
    args_print(display_args)
    return args




def _run_evidence_pipeline(args: Namespace) -> None:
    """Run the evidence workflow.

    Args:
        args: Validated arguments.
    """
    result = run_riboseq_evidence(args)

    step_print(3, "Report sample-specific evidence outputs.")
    result_print(
        [
            ("Parallel workers", result.threads),
            ("Output samples", f"{len(result.samples):,}"),
        ]
    )
    for sample_result in result.samples:
        print(flush=True)
        result_print(
            [
                ("Sample", sample_result.sample),
                ("Evidence file", sample_result.output),
                ("Written rows", f"{sample_result.written_rows:,}"),
            ]
        )


def main(argv: Sequence[str] | None = None) -> None:
    """Run the smorf_evidence command.

    Args:
        argv: Optional argument sequence for tests.
    """
    now_time()
    title_print("Evaluate smORF translation evidence.")
    step_print(1, "Checking the input arguments.")

    args = _parse_args(argv)

    step_print(2, "Evaluate Ribo-seq evidence for smORFs.")
    _run_evidence_pipeline(args)

    title_print("All done.")
    now_time()


if __name__ == "__main__":
    main()
