#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-06-12
# Version: 0.2.7
# Function: This script is used to convert the ribotish result to genepred format.
# Input: Command-line arguments and input files specified by the user.
# Output: Analysis tables, figures, logs, or intermediate files generated by the command.


import pandas as pd
# import polars as pl
# import numpy as np
from collections import OrderedDict
# from Bio import SeqIO
import argparse

def get_args_parser():

    parser = argparse.ArgumentParser(description='This script is used to convert the ribotish result to genepred format.')

    # needed arguments
    input_group = parser.add_argument_group('Required arguments')
    input_group.add_argument(
        '-i', dest='input', required=True, type=str, help='input file name.'
    )
    input_group.add_argument(
        '-o', dest='output', required=True, type=str, help='prefix of output genepred file name.'
    )

    # optional arguments
    parser.add_argument(
        '-t', dest='type', required=False, type=str, choices=['all', 'smorf', 'annotated'], default='all', 
        help='select the ORF class. (default: %(default)s)'
    )
    parser.add_argument(
        '-p', dest='pvalue', required=False, type=float, default=0.05, help='threshold of the ribo pvalue. (default: %(default)s)'
    )
    parser.add_argument(
        '-l', dest='length', required=False, type=int, default=8, help='length of the amino acids. (default: %(default)s)'
    )
    parser.add_argument(
        '-c', dest='clean', required=False, action='store_true', default=False, help='drop all the fuzzy ORFs. (default: %(default)s)'
    )
    args = parser.parse_args()

    args_dict = vars(args)
    for k, v in args_dict.items():
        print('{:<12}:  {:<}'.format(k, str(v)), flush=True)

    return args


def filter_the_pvalue(ribotish, args):
    """Filter the pvalue and length of ORFs.

    Parameters
    ----------
    ribotish : object
        the ribotish result.
    args : object
        Input argument used by this function.

    Returns
    -------
    object
        filtered pvalue and length of ribotish results.

    Workflow
    --------
    1. Filter the pvalue.
    2. Filter the length of ORFs.
    """
    
    # filter the pvalue
    ribotish = ribotish.loc[ribotish['RiboPvalue'] <= args.pvalue, :]
    ribotish = ribotish.loc[ribotish['AALen'] >= args.length, :]

    return  ribotish


def filter_the_orf_class(ribotish, args):
    """Filter the ORFs with different orf class.

    Parameters
    ----------
    ribotish : object
        filtered pvalue and length of ribotish results.
    args : object
        Input argument used by this function.

    Returns
    -------
    object
        ribotish results.

    Workflow
    --------
    1. Filter the smORF and annotated genes.
    """
    
    # replace the ['5UTR', '3UTR', 'Novel'] string in the part of TisType to ['uORF', 'dORF', 'Novel']
    ribotish['TisType'] = ribotish['TisType'].str.replace("5'UTR", 'uORF')
    ribotish['TisType'] = ribotish['TisType'].str.replace("3'UTR", 'dORF')

    # clean the TisType
    if args.clean:
        # remove the TisType contain the string 'Known'
        ribotish = ribotish.loc[~ribotish['TisType'].str.contains('Known'), :]

        # remove the TisType contain the string 'CDSFrameOverlap'
        ribotish = ribotish.loc[~ribotish['TisType'].str.contains('CDSFrameOverlap'), :]
        
    else:
        pass

    # filter the smORF and annotated genes
    if args.type == 'smorf':
        # filter the TisType contain the string 5'UTR/3'UTR/Novel
        ribotish = ribotish.loc[ribotish['TisType'].str.contains("uORF|dORF|Novel"), :]

    elif args.type == 'annotated':
        # filter the TisType contain the string Annotated
        ribotish = ribotish.loc[ribotish['TisType'].str.contains("Annotated|Extended|Internal|Truncated"), :]

    else:
        pass

    return ribotish


def unique_the_orf(ribotish):
    """Unique the ORFs with the same gene-blocks.

    Parameters
    ----------
    ribotish : object
        filtered ribotish results.

    Returns
    -------
    object
        unique ribotish results.

    Workflow
    --------
    1. Sort the ORFs with genome position and length of amino acids.
    2. Drop the ORFs with the same gene-blocks.
    """
    
    ribotish = ribotish.sort_values(by=['GenomePos', 'AALen'], ascending=[True, False])

    ribotish = ribotish.drop_duplicates(subset=['TisType', 'Blocks'], keep='first')

    return ribotish


def input_the_ribotish(args):
    """Filter the pvalue and length of ORFs.

    Parameters
    ----------
    args : object
        Packed arguments used by this function.

    Returns
    -------
    object
        the ribotish result.

    Notes
    -----
    Legacy input information:
    - ``args``: input arguments.

    Workflow
    --------
    1. Input the ribotish result.
    2. Drop the fuzzy ORFs.
    3. Filter the pvalue and length of ORFs.
    4. Filter the ORFs with different orf class.
    5. Unique the ORFs with the same blocks.
    6. Output the ribotish result.
    """

    ribotish = pd.read_csv(args.input, sep='\t', header=0, names=None)

    ribotish = filter_the_pvalue(ribotish, args)

    ribotish = filter_the_orf_class(ribotish, args)

    ribotish = unique_the_orf(ribotish)

    return ribotish


def retrieve_aa(ribotish, args):
    """Retrieve the amino acid of the ORFs.

    Parameters
    ----------
    ribotish : object
        filtered ribotish results.
    args : object
        Input argument used by this function.

    Returns
    -------
    None
        The function updates internal state or writes output files in place.

    Notes
    -----
    Legacy return information:
    - ``aa_sequence``: the amino acid sequence of the ORFs.

    Workflow
    --------
    1. Retrieve the amino acid sequence.
    2. Format the amino acid sequence to fasta format.
    3. Output the amino acid sequence.
    """

    with open(args.output + '.aa', 'w') as aa_output:
        for index, row in ribotish.iterrows():

            aa_name = row['TisType'] + '_' + row['Gid'] + '_' + row['Tid'] + '_' + row['GenomePos'] + ' ' + row['Blocks']
            aa_seq = row['AASeq'][:-1]

            aa_output.writelines('>' + aa_name + '\n')
            aa_output.writelines(aa_seq + '\n')
    

def retrieve_cds(ribotish, args):
    """Retrieve the amino acid of the ORFs.

    Parameters
    ----------
    ribotish : object
        filtered ribotish results.
    args : object
        Input argument used by this function.

    Returns
    -------
    None
        The function updates internal state or writes output files in place.

    Notes
    -----
    Legacy return information:
    - ``aa_sequence``: the amino acid sequence of the ORFs.

    Workflow
    --------
    1. Retrieve the cds sequence.
    2. Format the cds sequence to fasta format.
    3. Output the cds sequence.
    """

    with open(args.output + '.cds', 'w') as cds_output:
        for index, row in ribotish.iterrows():
            aa_name = row['Gid'] + '_' + row['Tid'] + ' ' + row['GenomePos'] + ' ' + row['TisType'] + ' ' + row['Blocks']
            aa_seq = row['Seq']

            cds_output.writelines('>' + aa_name + '\n')
            cds_output.writelines(aa_seq + '\n')


def get_cds_frame(strand, gene_blocks):
    """Get the cds frame.

    Parameters
    ----------
    strand : object
        gene strand.
    gene_blocks : object
        gene blocks.

    Returns
    -------
    object
        frame of cds.

    Workflow
    --------
    1. Check the different strand.
    2. Get the list of gene blocks.
    3. Calculate the length of cds.
    4. Calculate the frame of cds.
    - @notes    : genepred --> cds length = txEnd - txStart.
    - gtf --> cds length = txEnd - txStart + 1.
    - bed --> cds length = txEnd - txStart.
    """

    if strand == '+':
        orf_length = 0

        for index, block in enumerate(gene_blocks):
            t_start, t_end = block.split('-')

            if index == 0:
                cds_frame = [0]
                exonStarts = [int(t_start)]
                exonEnds = [int(t_end)]

                continue

            exonStarts.append(int(t_start))
            exonEnds.append(int(t_end))
            cds_len = int(t_end) - int(t_start)
            
            orf_length += cds_len
            frame = orf_length % 3

            cds_frame = cds_frame + [frame]

    elif strand == '-':
        orf_length = 0
        
        exonEnds = []

        for index, block in enumerate(gene_blocks):
            t_start, t_end = block.split('-')

            if index == 0:
                cds_frame = [0]
                exonStarts = [int(t_start)]
                exonEnds = [int(t_end)]

                continue

            exonStarts = [int(t_start)] + exonStarts
            exonEnds = [int(t_end)] + exonEnds
            cds_len = int(t_end) - int(t_start)
            
            orf_length += cds_len
            frame = orf_length % 3

            cds_frame = [frame] + cds_frame

    else:
        pass
    
    cds_frame = ','.join([str(item) for item in cds_frame]) + ','
    exonStarts = ','.join([str(item) for item in exonStarts]) + ','
    exonEnds = ','.join([str(item) for item in exonEnds]) + ','

    return cds_frame, exonStarts, exonEnds


def retrieve_blocks(ribotish, args):
    """Format the gene blocks to genepred.

    Parameters
    ----------
    ribotish : object
        filtered ribotish results.
    args : object
        Input argument used by this function.

    Returns
    -------
    None
        The function updates internal state or writes output files in place.

    Notes
    -----
    Legacy return information:
    - ``gene``: blocks --> formatted gene-blocks.

    Workflow
    --------
    1. Retrieve the gene-blocks.
    2. Format the gene-blocks.
    3. Output the gene-blocks file.
    """
    
    with open(args.output + '.genepred', 'w') as genepred_output:

        for index, row in ribotish.iterrows():
            # gene names
            name = row['TisType'] + '_' + row['Gid'] + '_' + row['Tid']
            chrom = row['GenomePos'].split(':')[0]
            # source = 'ribotish'
            # type = 'CDS'

            # gene position
            strand = row['GenomePos'].split(':')[-1]

            gene_blocks = row['Blocks'].split(',')
            exonCount = len(gene_blocks)

            exonStarts_list = [item.split('-')[0] for item in gene_blocks]
            exonEnds_list = [item.split('-')[-1] for item in gene_blocks]

            txStart = exonStarts_list[0]
            txEnd = exonEnds_list[-1]
            cdsStart = txStart
            cdsEnd = txEnd

            exonStarts = ','.join(exonStarts_list) + ','
            exonEnds = ','.join(exonEnds_list) + ','

            # output the gene-blocks
            # gene_blocks = [name, chrom, strand, txStart, txEnd, cdsStart, cdsEnd, exonCount, exonStarts, exonEnds, score, name2, cdsStartStat, cdsEndStat, IstringexonFrames]
            gene_blocks = [name, chrom, strand, txStart, txEnd, cdsStart, cdsEnd, exonCount, exonStarts, exonEnds]

            genepred_output.writelines('\t'.join([str(item) for item in gene_blocks]) + '\n')


def main():
    print('Convert ribotish results to genepred format.', flush=True)
    args = get_args_parser()

    print('Step1: input the ribotish.', flush=True)
    record = input_the_ribotish(args)

    print('Step2: output the cds file.', flush=True)
    retrieve_aa(record, args)

    print('Step3: output the amino acid file.', flush=True)
    retrieve_cds(record, args)

    print('Step4: output the genepred file.', flush=True)
    retrieve_blocks(record, args)

    print('Done.', flush=True)


if __name__ == '__main__':
    main()
