#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Author: Rensc
# Date: 2026-06-12
# Version: 0.2.7
# Function: Convert legacy RiboParser docstrings to NumPy-style docstrings.
# Input: Command-line arguments and input files specified by the user.
# Output: Analysis tables, figures, logs, or intermediate files generated by the command.


"""Convert legacy RiboParser docstrings to NumPy-style docstrings.

The converter rewrites only the first docstring inside functions, methods, or
classes when that docstring contains the legacy RiboParser message tag. It does
not modify function logic, signatures, imports, or inline comments.
"""

from __future__ import annotations

import argparse
import ast
import re
import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

LEGACY_MESSAGE_TAG = "@" + "Message"
LEGACY_TAGS = tuple("@" + tag for tag in ("Message", "Input", "Return", "Flow"))
SKIP_DIRS = {".git", "build", "dist", "RiboParser.egg-info", "__pycache__"}


@dataclass
class LegacyDocstring:
    """Parsed legacy RiboParser docstring sections."""

    message: list[str]
    inputs: list[str]
    returns: list[str]
    flow: list[str]


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser(
        description="Convert legacy RiboParser docstrings to NumPy-style docstrings."
    )
    parser.add_argument(
        "paths",
        nargs="*",
        default=["utils", "scripts", "one_step"],
        help="Python files or directories to scan. Default: utils scripts one_step.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Only report files that would be modified.",
    )
    return parser.parse_args()


def iter_python_files(paths: Iterable[str]) -> Iterable[Path]:
    """Yield Python files from input files or directories."""

    for raw_path in paths:
        path = Path(raw_path)
        if not path.exists():
            continue
        if path.is_file() and path.suffix == ".py":
            yield path
        elif path.is_dir():
            for py_file in path.rglob("*.py"):
                if not SKIP_DIRS.intersection(py_file.parts):
                    yield py_file


def parse_legacy_docstring(docstring: str) -> LegacyDocstring:
    """Parse legacy RiboParser tag sections."""

    sections = {"message": [], "input": [], "return": [], "flow": []}
    current: str | None = None
    pattern = re.compile(r"^@(Message|Input|Return|Flow)\s*:?(.*)$", re.IGNORECASE)

    for raw_line in docstring.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        match = pattern.match(line)
        if match:
            current = match.group(1).lower()
            content = match.group(2).strip()
            if content.startswith(":"):
                content = content[1:].strip()
            if content:
                sections[current].append(content)
        elif current is not None:
            sections[current].append(line)

    return LegacyDocstring(
        message=sections["message"],
        inputs=sections["input"],
        returns=sections["return"],
        flow=sections["flow"],
    )


def clean_sentence(text: str, fallback: str) -> str:
    """Normalize a short docstring summary."""

    text = re.sub(r"\s+", " ", text).strip() or fallback
    text = re.sub(r"^function\s+for\s+", "", text, flags=re.IGNORECASE)
    text = re.sub(r"^function\s+used\s+to\s+", "", text, flags=re.IGNORECASE)
    text = re.sub(r"^used\s+to\s+", "", text, flags=re.IGNORECASE)
    text = text.strip()
    text = text[0].upper() + text[1:] if text else fallback
    if text[-1] not in ".!?":
        text += "."
    return text


def parse_item(line: str) -> tuple[str | None, str]:
    """Parse a legacy ``name --> description`` item."""

    line = line.strip().rstrip(".")
    if not line:
        return None, ""
    match = re.match(
        r"^([A-Za-z_][\w\.]*)(?:\s*\([^)]*\))?\s*(?:-->|:|-{1,2})\s*(.+)$",
        line,
    )
    if match:
        return match.group(1), match.group(2).strip()
    return None, line


def normalize_items(lines: list[str]) -> list[tuple[str | None, str]]:
    """Normalize legacy section lines into name-description pairs."""

    items: list[tuple[str | None, str]] = []
    for line in lines:
        name, desc = parse_item(line)
        if desc:
            items.append((name, desc))
    return items


def annotation_to_string(annotation: ast.expr | None) -> str:
    """Return a readable annotation string."""

    if annotation is None:
        return "object"
    try:
        return ast.unparse(annotation)
    except Exception:
        return "object"


def default_flags(args: ast.arguments) -> dict[str, bool]:
    """Return whether each argument has a default value."""

    flags: dict[str, bool] = {}
    positional = list(args.posonlyargs) + list(args.args)
    default_offset = len(positional) - len(args.defaults)
    for index, arg in enumerate(positional):
        flags[arg.arg] = index >= default_offset
    for arg, default in zip(args.kwonlyargs, args.kw_defaults):
        flags[arg.arg] = default is not None
    return flags


def function_arguments(node: ast.FunctionDef | ast.AsyncFunctionDef) -> list[tuple[str, str, bool]]:
    """Return argument names, types, and optional flags."""

    flags = default_flags(node.args)
    output: list[tuple[str, str, bool]] = []
    all_args = list(node.args.posonlyargs) + list(node.args.args) + list(node.args.kwonlyargs)
    for arg in all_args:
        if arg.arg in {"self", "cls"}:
            continue
        output.append((arg.arg, annotation_to_string(arg.annotation), flags.get(arg.arg, False)))
    if node.args.vararg is not None:
        output.append((node.args.vararg.arg, "tuple", False))
    if node.args.kwarg is not None:
        output.append((node.args.kwarg.arg, "dict", False))
    return output


def has_value_return(node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    """Return whether a function contains a non-empty return statement."""

    return any(isinstance(child, ast.Return) and child.value is not None for child in ast.walk(node))


def return_type(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    """Infer a conservative return type string."""

    if node.returns is not None:
        return annotation_to_string(node.returns)
    return "object" if has_value_return(node) else "None"


def make_description(text: str) -> str:
    """Normalize a field description."""

    text = re.sub(r"\s+", " ", text.strip())
    if not text:
        text = "Description is not specified"
    if text[-1] not in ".!?":
        text += "."
    return text


def wrap_append(lines: list[str], text: str, indent: str, width: int = 88) -> None:
    """Append wrapped text with indentation."""

    for part in textwrap.wrap(text, width=max(40, width - len(indent))) or [""]:
        lines.append(f"{indent}{part}")


def flow_to_workflow(lines: list[str]) -> list[str]:
    """Convert legacy flow lines into numbered workflow steps."""

    output: list[str] = []
    for line in lines:
        text = line.strip().rstrip(".")
        if not text:
            continue
        text = re.sub(r"^step\s*(\d+)\s*(?:-->|:|-)?\s*", r"\1. ", text, flags=re.IGNORECASE)
        if re.match(r"^\d+\.\s+", text):
            number, desc = text.split(".", 1)
            desc = desc.strip()
            desc = desc[0].upper() + desc[1:] if desc else desc
            text = f"{number}. {desc}."
        else:
            text = f"- {text}."
        output.append(text)
    return output


def build_docstring(
    node: ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef,
    legacy: LegacyDocstring,
    base_indent: str,
) -> list[str]:
    """Build a NumPy-style replacement docstring."""

    summary = clean_sentence(" ".join(legacy.message), fallback=f"Document {node.name}.")
    lines = [f'{base_indent}"""{summary}']
    input_items = normalize_items(legacy.inputs)
    return_items = normalize_items(legacy.returns)
    input_map = {name: desc for name, desc in input_items if name}
    unmatched_inputs = [(name, desc) for name, desc in input_items if not name]

    if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
        args = function_arguments(node)
        if args:
            lines.extend(["", f"{base_indent}Parameters", f"{base_indent}----------"])
            if len(args) == 1 and args[0][0] == "args" and input_items:
                lines.append(f"{base_indent}args : {args[0][1]}")
                lines.append(f"{base_indent}    Packed arguments used by this function.")
            else:
                for arg_name, arg_type, optional in args:
                    suffix = ", optional" if optional else ""
                    desc = input_map.pop(arg_name, "Input argument used by this function")
                    lines.append(f"{base_indent}{arg_name} : {arg_type}{suffix}")
                    wrap_append(lines, make_description(desc), base_indent + "    ")

        ret_type = return_type(node)
        ret_desc = " ".join(desc for _, desc in return_items).strip()
        legacy_return_notes: list[tuple[str | None, str]] = []
        if ret_type != "None" or ret_desc:
            lines.extend(["", f"{base_indent}Returns", f"{base_indent}-------", f"{base_indent}{ret_type}"])
            if ret_type == "None":
                lines.append(f"{base_indent}    The function updates internal state or writes output files in place.")
                legacy_return_notes = return_items
            elif ret_desc:
                wrap_append(lines, make_description(ret_desc), base_indent + "    ")
            else:
                lines.append(f"{base_indent}    Function result.")
    else:
        legacy_return_notes = return_items

    remaining_inputs = [(name, desc) for name, desc in input_map.items()] + unmatched_inputs
    if remaining_inputs or legacy_return_notes:
        lines.extend(["", f"{base_indent}Notes", f"{base_indent}-----"])
        if remaining_inputs:
            lines.append(f"{base_indent}Legacy input information:")
            for name, desc in remaining_inputs:
                if name:
                    wrap_append(lines, f"- ``{name}``: {make_description(desc)}", base_indent)
                else:
                    wrap_append(lines, f"- {make_description(desc)}", base_indent)
        if legacy_return_notes:
            if remaining_inputs:
                lines.append("")
            lines.append(f"{base_indent}Legacy return information:")
            for name, desc in legacy_return_notes:
                if name:
                    wrap_append(lines, f"- ``{name}``: {make_description(desc)}", base_indent)
                else:
                    wrap_append(lines, f"- {make_description(desc)}", base_indent)

    workflow = flow_to_workflow(legacy.flow)
    if workflow:
        lines.extend(["", f"{base_indent}Workflow", f"{base_indent}--------"])
        for step in workflow:
            wrap_append(lines, step, base_indent)

    lines.append(f'{base_indent}"""')
    return lines


def convert_file(path: Path, check: bool = False) -> bool:
    """Convert legacy docstrings in one Python file."""

    text = path.read_text()
    if not any(tag in text for tag in LEGACY_TAGS):
        return False
    tree = ast.parse(text)
    lines = text.splitlines()
    replacements: list[tuple[int, int, list[str]]] = []

    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)) or not node.body:
            continue
        first = node.body[0]
        if not (
            isinstance(first, ast.Expr)
            and isinstance(first.value, ast.Constant)
            and isinstance(first.value.value, str)
            and LEGACY_MESSAGE_TAG in first.value.value
        ):
            continue
        legacy = parse_legacy_docstring(first.value.value)
        if not legacy.message:
            continue
        base_indent = re.match(r"^\s*", lines[first.lineno - 1]).group(0)
        replacements.append((first.lineno - 1, first.end_lineno, build_docstring(node, legacy, base_indent)))

    if not replacements:
        return False
    for start, end, replacement in sorted(replacements, reverse=True):
        lines[start:end] = replacement
    new_text = "\n".join(lines) + ("\n" if text.endswith("\n") else "")
    if new_text == text:
        return False
    if not check:
        path.write_text(new_text)
    return True


def main() -> None:
    """Run the docstring converter."""

    args = parse_args()
    changed: list[Path] = []
    for path in iter_python_files(args.paths):
        try:
            if convert_file(path, check=args.check):
                changed.append(path)
        except SyntaxError as exc:
            print(f"[skip] {path}: {exc}")
    action = "would update" if args.check else "updated"
    for path in changed:
        print(f"[{action}] {path}")
    print(f"Total files {action}: {len(changed)}")


if __name__ == "__main__":
    main()
